### ISSUE TITLE
examples/getting-started: Inconsistent use of ipv6 option

### ISSUE THREAD

**Issue by qingyunha** [cilium/cilium#10396]
Vagrantfile disabled ipv6.
https://github.com/cilium/cilium/blob/220604167c3f8795980ecdee8a7b022a43b7b9d5/examples/getting-started/Vagrantfile#L7

But the document says create ipv6 network.
https://github.com/cilium/cilium/blob/master/Documentation/gettingstarted/docker.rst#step-5-create-a-docker-network-of-type-cilium

Failed:
```
level=info msg="Cilium Docker plugin ready" subsys=cilium-docker-driver
level=info msg="Listening for events from Docker" file-path=/run/docker/plugins/cilium.sock subsys=cilium-docker
2020/02/29 14:10:16 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc000090140)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0xb63060, 0x12cf580)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cilium/cilium/plugins/cilium-docker/driver.(*driver).getPoolResponse(...)
	/go/src/github.com/cilium/cilium/plugins/cilium-docker/driver/ipam.go:69
github.com/cilium/cilium/plugins/cilium-docker/driver.(*driver).requestPool(0xc000558000, 0xd4c5e0, 0xc000558460, 0xc00053d700)
	/go/src/github.com/cilium/cilium/plugins/cilium-docker/driver/ipam.go:85 +0x30c
net/http.HandlerFunc.ServeHTTP(0xc000555110, 0xd4c5e0, 0xc000558460, 0xc00053d700)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/cilium/cilium/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001926c0, 0xd4c5e0, 0xc000558460, 0xc00053d500)
	/go/src/github.com/cilium/cilium/vendor/github.com/gorilla/mux/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc000552f70, 0xd4c5e0, 0xc000558460, 0xc00053d500)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000090140, 0xd4e520, 0xc000398100)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
level=error msg="Sending error" code=400 fields.msg="Could not decode JSON encode payload" subsys=cilium-docker-driver
```

**Comment by aanm** [comment]
@qingyunha can you try with `docker network create --driver cilium --ipam-driver cilium cilium-net` to see if it works as well?

**Comment by qingyunha** [comment]
Yes, it works.
