### ISSUE TITLE
Potential locking issue on master with `cilium debuginfo`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10599]
I don't have a specific repro environment for this, but I observed the following output from the daemon's `debuginfo` API in a testsuite failure on master (v1.8 dev cycle):

...

#### BPF Policy Get 576

```
goroutine 1 [running]:
goroutine 1 runtime/debug.Stack(0xbf94320bd9c840b2, 0x10da8070, 0x31e0ee0)
goroutine 1    /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc000453988)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:97 +0xc3
goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).Open(0xc0004538c0, 0x0, 0x0)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:506 +0x156
goroutine 1 github.com/cilium/cilium/pkg/maps/policymap.Open(0xc000125dd0, 0x2a, 0xc00, 0xc0003ef8e0, 0x13)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/policymap/policymap.go:284 +0x4f
goroutine 1 github.com/cilium/cilium/cilium/cmd.dumpMap(0xc000125dd0, 0x2a)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:95 +0x5d
goroutine 1 github.com/cilium/cilium/cilium/cmd.listMap(0xc0004c3da0, 0x1, 0x2)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:91 +0x73
goroutine 1 github.com/cilium/cilium/cilium/cmd.glob..func14(0x31be2a0, 0xc0004c3da0, 0x1, 0x2)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:55 +0xa0
goroutine 1 github.com/spf13/cobra.(*Command).execute(0x31be2a0, 0xc0004c3d60, 0x2, 0x2, 0x31be2a0, 0xc0004c3d60)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:830 +0x29d
goroutine 1 github.com/spf13/cobra.(*Command).ExecuteC(0x31bf420, 0x4442fa, 0x312c8c0, 0xc000000180)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
goroutine 1 github.com/spf13/cobra.(*Command).Execute(...)
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:864
goroutine 1 github.com/cilium/cilium/cilium/cmd.Execute()
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/root.go:47 +0x31
goroutine 1 main.main()
goroutine 1    /home/vagrant/go/src/github.com/cilium/cilium/cilium/main.go:22 +0x20
DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   BYTES   PACKETS
Egress      583        ANY          NONE         1080    10
Egress      3630       ANY          NONE         0       0

```

...

It's surprising to see a stacktrace in the debuginfo output here, is this related to any recent map locking changes?

**Comment by aanm** [comment]
@joestringer this seems to be expected since we enable the deadlock detection when running with debug mode https://github.com/cilium/cilium/blob/47059b4b098d6f788b039adb772864b3250c5d0c/pkg/lock/lock_debug.go#L95-L100
