### ISSUE TITLE
CI: Travis failed on arm64: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#10678]
CI failure Link:
https://travis-ci.com/github/cilium/cilium/jobs/301427159#L4800

failed on arm64 build, but passed on amd64 build.
```
=== RUN   Test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x220 pc=0x11b0f78]

goroutine 101 [running]:
github.com/cilium/cilium/pkg/ipam.(*Node).getPreAllocate(...)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:184
github.com/cilium/cilium/pkg/ipam.(*Node).recalculateLocked(0x4000161080)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:308 +0x150
github.com/cilium/cilium/pkg/ipam.(*NodeManager).resyncNode(0x4000281960, 0x18f7d40, 0x400005a1c0, 0x4000161080, 0x40006a2180, 0xbf96702e542db63f, 0x211f09a8, 0x27d0640)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:317 +0xb0
github.com/cilium/cilium/pkg/ipam.(*NodeManager).Resync.func1(0x4000281960, 0x18f7d40, 0x400005a1c0, 0xbf96702e542db63f, 0x211f09a8, 0x27d0640, 0x4000218b40, 0x4000161080, 0x40006a2180)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:363 +0x7c
created by github.com/cilium/cilium/pkg/ipam.(*NodeManager).Resync
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:362 +0x1c8
FAIL	github.com/cilium/cilium/pkg/ipam	0.590s
FAIL
Makefile:146: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
```

**Comment by joestringer** [comment]
This is still (rarely) hit on v1.7 branch despite the fix https://github.com/cilium/cilium/pull/9893 having been merged.

**Comment by joestringer** [comment]
Seen also on AMD64 test runs.
