### ISSUE TITLE
segfault in isXfrmPolicyCilium

### ISSUE THREAD

**Issue by clamchowder** [cilium/cilium#10679]
## Bug report

**General Information**

- Cilium version (run `cilium version`):  
Cilium CNI plugin 1.7.0 adeaf8c04 2020-02-18T21:41:10+01:00 go version go1.13.8 linux/amd64
- Kernel version (run `uname -a`):
5.0.0-1014-azure #14~18.04.1-Ubuntu SMP Fri Aug 2 17:17:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
kubernetes initialized with kubeadm init --pod-network-cidr=172.20.0.0/16
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)
sysdump fails with:

```
ERROR Error: Command 'kubectl logs cilium-z997k --container=cilium-agent --timestamps=true --since=30m --limit-bytes=1048576 -n kube-system > ./cilium-sysdump-20200324-044304/cilium-z997k-20200324-044338.log' returned non-zero exit status 1. Could not collect log file: cilium-z997k-20200324-044338
DEBUG no previous pod logs to gather for pod/container cilium-wghh9/cilium-agent
DEBUG no previous pod logs to gather for pod/container cilium-m67s2/cilium-agent
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "cilium-sysdump.zip/__main__.py", line 124, in <module>
  File "cilium-sysdump.zip/sysdumpcollector.py", line 461, in collect
  File "cilium-sysdump.zip/sysdumpcollector.py", line 106, in collect_logs
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'containerStatuses'
```

**How to reproduce the issue**

1. Created a cluster with kubeadm init --pod-network-cidr=172.20.0.0/16
2. Joined a couple nodes w/join command from above
3. kubectl create -f original_cilium.yaml
[original_cilium.yaml.txt](https://github.com/cilium/cilium/files/4373259/original_cilium.yaml.txt)

4. check cilium pods on nodes when they fail to start, and see error:
```
level=info msg="Blacklisting local route as no-alloc" route=192.168.1.0/24 subsys=ipam
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1c853df]

goroutine 1 [running]:
github.com/cilium/cilium/pkg/datapath/linux/ipsec.isXfrmPolicyCilium(...)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/ipsec_linux.go:367
github.com/cilium/cilium/pkg/datapath/linux/ipsec.DeleteXfrm()
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/ipsec_linux.go:393 +0x10f
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeConfigurationChanged(0xc00035cf00, 0x5dc, 0x5aa, 0x5dc, 0x1, 0x3f928b0, 0x0, 0x0, 0x10001000001, 0x3f928b0, ...)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1102 +0x69a
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).Reinitialize(0xc0002aa000, 0x274cbc0, 0xc0000d4780, 0x2764c00, 0xc0004f6d80, 0x5dc, 0x7f5af398b878, 0xc00025e460, 0x26edf40, 0xc000a6c5f0, ...)
        /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:284 +0xf55
main.(*Daemon).init(0xc0004f6d80, 0x286029bd5, 0x3a49920)
        /go/src/github.com/cilium/cilium/daemon/daemon.go:202 +0x7c6
main.NewDaemon(0x274cb40, 0xc000378540, 0x278fe20, 0xc00025e460, 0x276a540, 0xc0004c7e20, 0x278fe20, 0xc00025e460)
        /go/src/github.com/cilium/cilium/daemon/daemon.go:491 +0x1a62
main.runDaemon()
        /go/src/github.com/cilium/cilium/daemon/daemon_main.go:1181 +0x350
main.glob..func1(0x3a27040, 0xc0003e6090, 0x0, 0x1)
        /go/src/github.com/cilium/cilium/daemon/daemon_main.go:101 +0x7b
github.com/spf13/cobra.(*Command).execute(0x3a27040, 0xc00010c030, 0x1, 0x1, 0x3a27040, 0xc00010c030)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x3a27040, 0xc000694000, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:864
main.daemonMain()
        /go/src/github.com/cilium/cilium/daemon/daemon_main.go:129 +0x184
main.main()
        /go/src/github.com/cilium/cilium/daemon/main.go:18 +0x20
```
I was able to run Cilium after making a change to isXfrmPolicyCilium, in ipsec_linux.go:
```
func isXfrmPolicyCilium(policy netlink.XfrmPolicy) bool {
        if (policy.Mark == nil || (uintptr(unsafe.Pointer(policy.Mark)) < 0x1000)) {
                return false
        }
```
but that feels like a hack, so advice on a proper fix would be appreciated

**Comment by brb** [comment]
@clamchowder have you tried running with https://github.com/cilium/cilium/releases/tag/v1.7.1 which fixes some xfrm-related segfaults?

**Comment by clamchowder** [comment]
I tried v1.7.1 and don't see the segfault problem. Thanks!
