### ISSUE TITLE
CI: concurrent map read and map write in ipmasq tests

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11289]
```
coverage: 2.1% of statements in ./...
ok  	github.com/cilium/cilium/pkg/ipcache/fake	0.063s	coverage: 2.1% of statements in ./...
=== RUN   Test
fatal error: concurrent map read and map write
goroutine 33 [running]:
runtime.throw(0xc67924, 0x21)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/panic.go:1116 +0x72 fp=0xc000574bb0 sp=0xc000574b80 pc=0x4370d2
runtime.mapaccess2_faststr(0xb78a00, 0xc00009e810, 0xc00003a320, 0xa, 0xc000574fb8, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/map_faststr.go:116 +0x47c fp=0xc000574c20 sp=0xc000574bb0 pc=0x4155bc
github.com/cilium/cilium/pkg/ipmasq.(*ipMasqMapMock).Update(0xc0001241c0, 0xc00003a2bc, 0x4, 0x4, 0xc00003a2b8, 0x4, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq_test.go:42 +0x6a fp=0xc000574c88 sp=0xc000574c20 pc=0xabc63a
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Update(0xc00009e870, 0x22cf4b36, 0xc630b7c75d)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:118 +0x324 fp=0xc0005750d8 sp=0xc000574c88 pc=0xabb8a4
github.com/cilium/cilium/pkg/ipmasq.start.func1(0xd71440, 0xc00014ea80, 0x12c7560, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:102 +0x30 fp=0xc000575100 sp=0xc0005750d8 pc=0xabdb50
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc0001c7300)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa88 fp=0xc000575fd8 sp=0xc000575100 pc=0xa53ec8
runtime.goexit()
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000575fe0 sp=0xc000575fd8 pc=0x469241
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb69
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000360d80, 0xc50ee1, 0x4, 0xc8a708, 0x491a76)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1043 +0x37e
testing.runTests.func1(0xc000360c60)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1284 +0x78
testing.tRunner(0xc000360c60, 0xc0004f5dd8)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0xdc
testing.runTests(0xc0004fbf00, 0x12ae940, 0x1, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1282 +0x2a7
testing.(*M).Run(0xc0002b8880, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1199 +0x15f
main.main()
	_testmain.go:878 +0x1d4
goroutine 22 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x12c7920)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:411 +0xd6
goroutine 23 [select]:
io.(*pipe).Read(0xc0000889c0, 0xc000562000, 0x1000, 0x1000, 0xb34ba0, 0x1, 0xc000562000)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc0001240e8, 0xc000562000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc000073f38, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/bufio/scan.go:213 +0xa4
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001a90a0, 0xc0001240e8, 0xc0004fcef0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:53 +0xc3
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:45 +0x1a5
goroutine 24 [select]:
io.(*pipe).Read(0xc000088a20, 0xc000341000, 0x1000, 0x1000, 0xb34ba0, 0x1, 0xc000341000)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc0001240f8, 0xc000341000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc000071f38, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/bufio/scan.go:213 +0xa4
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001a90a0, 0xc0001240f8, 0xc0004fcf10)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:53 +0xc3
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:45 +0x1a5
goroutine 25 [select]:
io.(*pipe).Read(0xc000088a80, 0xc000563000, 0x1000, 0x1000, 0xb34ba0, 0x1, 0xc000563000)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc000124108, 0xc000563000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc000074f38, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/bufio/scan.go:213 +0xa4
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001a90a0, 0xc000124108, 0xc0004fcf30)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:53 +0xc3
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:45 +0x1a5
goroutine 26 [select]:
io.(*pipe).Read(0xc000088ae0, 0xc000564000, 0x1000, 0x1000, 0xb34ba0, 0x1, 0xc000564000)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc000124118, 0xc000564000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc000075f38, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/bufio/scan.go:213 +0xa4
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001a90a0, 0xc000124118, 0xc0004fcf50)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:53 +0xc3
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:45 +0x1a5
goroutine 29 [chan receive]:
gopkg.in/check%2ev1.(*suiteRunner).runTest(...)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:819
gopkg.in/check%2ev1.(*suiteRunner).run(0xc0002b8980, 0xc0004fbea0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:624 +0x11d
gopkg.in/check%2ev1.Run(0xbaafa0, 0xc0004fbea0, 0xc000062f18, 0xd0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x4d
gopkg.in/check%2ev1.RunAll(0xc0005fff18, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x96
gopkg.in/check%2ev1.TestingT(0xc000360d80)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x395
github.com/cilium/cilium/pkg/ipmasq.Test(0xc000360d80)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq_test.go:33 +0x2b
testing.tRunner(0xc000360d80, 0xc8a708)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/testing/testing.go:1042 +0x357
goroutine 30 [select]:
gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc0004f8240)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:470 +0xc4
created by gopkg.in/check%2ev1.(*resultTracker).start
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:450 +0x3f
goroutine 31 [sleep]:
time.Sleep(0x11e1a300)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/time.go:188 +0xba
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqTestSuite).TestRestore(0xc0004fbea0, 0xc0005921e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq_test.go:136 +0x34f
reflect.Value.call(0xbaafa0, 0xc0004fbea0, 0xa13, 0xc50dd5, 0x4, 0xc00006ef08, 0x1, 0x1, 0x12f4480, 0xc00006ee48, ...)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0xbaafa0, 0xc0004fbea0, 0xa13, 0xc00006ef08, 0x1, 0x1, 0xc0005922d0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/reflect/value.go:321 +0xb4
gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc0005921e0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0x628
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc0002b8980, 0xc0005921e0, 0xc00000e060)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0x98
created by gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:672 +0x1fb
goroutine 34 [select]:
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc0001c7400)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/controller/controller.go:262 +0x1c7
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb69
FAIL	github.com/cilium/cilium/pkg/ipmasq	0.072s
FAIL
Makefile:145: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.

```

**Comment by brb** [comment]
Did you catch this with the golang race detector?

**Comment by pchaigno** [comment]
I hit this one just by running `make unit-tests`.

**Comment by ungureanuvladvictor** [comment]
Happened again via https://travis-ci.com/github/cilium/cilium/jobs/327432313.

**Comment by brb** [comment]
Fix is coming soon.
