### ISSUE TITLE
CI: Travis: panic: close of closed channel in (*IPMasqAgent).Start

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11373]
Seen in PR #11368 posted 3 hours ago:
https://travis-ci.com/github/cilium/cilium/jobs/328758821

```
=== RUN   Test
panic: close of closed channel
goroutine 27 [running]:
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start.func1(0xc000032af0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:146 +0x368
created by github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:124 +0x3cb
FAIL	github.com/cilium/cilium/pkg/ipmasq	0.350s
FAIL
Makefile:151: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

I'm not sure whether this is with or without PR https://github.com/cilium/cilium/pull/11317

**Comment by brb** [comment]
> I'm not sure whether this is with or without PR #11317

It's. I'm looking into it.
