### ISSUE TITLE
CI: test-gke pipeline broken

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#11928]
All tests fail due to:
```
01:45:45 STEP: Checking if deployment is ready
01:45:46 STEP: Kubernetes DNS is not ready yet: unable to retrieve deployment kube-system/coredns: Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error from server (NotFound): deployments.extensions "coredns" not found
	 

FAIL: Kubernetes DNS did not become ready in time
```

Oddly enough, I don't get this error when I'm running ginkgo against a private GKE cluster.

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/1669/

**Comment by jrajahalme** [comment]
kubedns container in kube-dns POD times out waiting for the API server to initialize `endpoint services`:
```
2020-06-05T01:46:06.983776409Z I0605 01:46:06.983511       1 dns.go:219] Waiting for [endpoints services] to be initialized from apiserver...
2020-06-05T01:46:07.483786216Z I0605 01:46:07.483554       1 dns.go:219] Waiting for [endpoints services] to be initialized from apiserver...
2020-06-05T01:46:07.983818037Z I0605 01:46:07.983539       1 dns.go:219] Waiting for [endpoints services] to be initialized from apiserver...
2020-06-05T01:46:08.484472302Z F0605 01:46:08.483525       1 dns.go:209] Timeout waiting for initialization
```

**Comment by jrajahalme** [comment]
Someone else had similar problem: https://github.com/kontena/pharos-cluster/issues/1082

**Comment by jrajahalme** [comment]
The Ginkgo test suite works on GKE when run on a private cluster:
```
$ cd test
$ gke/delete-terminating-namespaces.sh
$ CNI_INTEGRATION=gke K8S_VERSION=1.14 ~/go/bin/ginkgo -v --focus="K8s" -noColor -- -cilium.provision=false -cilium.kubeconfig=`echo ~/.kube/config` -cilium.image="docker.io/cilium/cilium:latest" -cilium.operator-image="docker.io/cilium/operator-generic:latest"  -cilium.hubble-relay-image="docker.io/cilium/hubble-relay:latest" -cilium.passCLIEnvironment=true
...
Ran 63 of 395 Specs in 5249.800 seconds
SUCCESS! -- 63 Passed | 0 Failed | 0 Pending | 332 Skipped
PASS

Ginkgo ran 1 suite in 1h27m47.422761282s
Test Suite Passed
```

**Comment by jrajahalme** [comment]
In addition to the kube-dns POD timing out (as shown above), the kube-dns sidecar container panics:
```
2020-06-17T07:15:42.180350696Z W0617 07:15:42.180094       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:32962->127.0.0.1:53: read: connection refused
2020-06-17T07:15:47.183745453Z panic: counter cannot decrease in value
2020-06-17T07:15:47.183792616Z 
2020-06-17T07:15:47.183844674Z goroutine 1 [running]:
2020-06-17T07:15:47.183852712Z k8s.io/dns/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc000349540, 0xc060e00000000000)
2020-06-17T07:15:47.183858012Z 	/go/src/k8s.io/dns/vendor/github.com/prometheus/client_golang/prometheus/counter.go:71 +0xa3
2020-06-17T07:15:47.183862266Z k8s.io/dns/pkg/sidecar.exportMetrics(0xc000246218)
2020-06-17T07:15:47.183865805Z 	/go/src/k8s.io/dns/pkg/sidecar/server.go:86 +0x1b0
2020-06-17T07:15:47.183869386Z k8s.io/dns/pkg/sidecar.(*server).runMetrics(0xc0002202a0, 0xc00056f3b0)
2020-06-17T07:15:47.18387292Z 	/go/src/k8s.io/dns/pkg/sidecar/server.go:68 +0x1b4
2020-06-17T07:15:47.18387658Z k8s.io/dns/pkg/sidecar.(*server).Run(0xc0002202a0, 0xc00056f3b0)
2020-06-17T07:15:47.18388001Z 	/go/src/k8s.io/dns/pkg/sidecar/server.go:53 +0x233
2020-06-17T07:15:47.183883463Z main.main()
2020-06-17T07:15:47.183886871Z 	/go/src/k8s.io/dns/cmd/sidecar/main.go:56 +0x1dc
```
(this could happen as the POD is restarted, though?)

**Comment by jrajahalme** [comment]
describe pods for the failing kube-dns PODS:
```
00:16:02  07:16:02 STEP: Kubernetes DNS is not ready yet: unable to retrieve deployment kube-system/coredns: Exitcode: 1 
00:16:02  Stdout:
00:16:02   	 
00:16:02  Stderr:
00:16:02   	 Error from server (NotFound): deployments.extensions "coredns" not found
00:16:02  	 
00:16:02  
00:16:07  07:16:06 STEP: Checking if deployment is ready
00:16:07  07:16:07 STEP: cmd: kubectl describe pods -n kube-system -l k8s-app=kube-dns
00:16:07  Exitcode: 0 
00:16:07  Stdout:
00:16:07   	 Name:                 kube-dns-5995c95f64-7lnpc
00:16:07  	 Namespace:            kube-system
00:16:07  	 Priority:             2000000000
00:16:07  	 Priority Class Name:  system-cluster-critical
00:16:07  	 Node:                 gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q/10.128.0.37
00:16:07  	 Start Time:           Wed, 17 Jun 2020 07:11:03 +0000
00:16:07  	 Labels:               k8s-app=kube-dns
00:16:07  	                       pod-template-hash=5995c95f64
00:16:07  	 Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
00:16:07  	                       seccomp.security.alpha.kubernetes.io/pod: docker/default
00:16:07  	 Status:               Running
00:16:07  	 IP:                   10.24.115.41
00:16:07  	 IPs:                  <none>
00:16:07  	 Controlled By:        ReplicaSet/kube-dns-5995c95f64
00:16:07  	 Containers:
00:16:07  	   kubedns:
00:16:07  	     Container ID:  docker://8e08bab22fd2dde660551a0debb7d759e31048f0dac667c8ecd5b8a198ee298a
00:16:07  	     Image:         k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-kube-dns-amd64@sha256:a13c60e2a9d49f965095a1e003388926f3f2a6189ed4aecb1541f114c955f8ec
00:16:07  	     Ports:         10053/UDP, 10053/TCP, 10055/TCP
00:16:07  	     Host Ports:    0/UDP, 0/TCP, 0/TCP
00:16:07  	     Args:
00:16:07  	       --domain=cluster.local.
00:16:07  	       --dns-port=10053
00:16:07  	       --config-dir=/kube-dns-config
00:16:07  	       --v=2
00:16:07  	     State:          Waiting
00:16:07  	       Reason:       CrashLoopBackOff
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    255
00:16:07  	       Started:      Wed, 17 Jun 2020 07:14:52 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:52 +0000
00:16:07  	     Ready:          False
00:16:07  	     Restart Count:  3
00:16:07  	     Limits:
00:16:07  	       memory:  170Mi
00:16:07  	     Requests:
00:16:07  	       cpu:      100m
00:16:07  	       memory:   70Mi
00:16:07  	     Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
00:16:07  	     Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
00:16:07  	     Environment:
00:16:07  	       PROMETHEUS_PORT:  10055
00:16:07  	     Mounts:
00:16:07  	       /kube-dns-config from kube-dns-config (rw)
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	   dnsmasq:
00:16:07  	     Container ID:  docker://25b7ecf401a92b833e54e9a207285173d758781a35a526e3b1f2e2259d2acd74
00:16:07  	     Image:         k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:0a70a8a9ae8cfe752021de84f13b3ecd109d9b5fbe3f1541c52fcd1d4c2c0b45
00:16:07  	     Ports:         53/UDP, 53/TCP
00:16:07  	     Host Ports:    0/UDP, 0/TCP
00:16:07  	     Args:
00:16:07  	       -v=2
00:16:07  	       -logtostderr
00:16:07  	       -configDir=/etc/k8s/dns/dnsmasq-nanny
00:16:07  	       -restartDnsmasq=true
00:16:07  	       --
00:16:07  	       -k
00:16:07  	       --cache-size=1000
00:16:07  	       --no-negcache
00:16:07  	       --log-facility=-
00:16:07  	       --server=/cluster.local/127.0.0.1#10053
00:16:07  	       --server=/in-addr.arpa/127.0.0.1#10053
00:16:07  	       --server=/ip6.arpa/127.0.0.1#10053
00:16:07  	     State:          Running
00:16:07  	       Started:      Wed, 17 Jun 2020 07:15:33 +0000
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    137
00:16:07  	       Started:      Wed, 17 Jun 2020 07:13:23 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:33 +0000
00:16:07  	     Ready:          True
00:16:07  	     Restart Count:  2
00:16:07  	     Requests:
00:16:07  	       cpu:        150m
00:16:07  	       memory:     20Mi
00:16:07  	     Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
00:16:07  	     Environment:  <none>
00:16:07  	     Mounts:
00:16:07  	       /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	   sidecar:
00:16:07  	     Container ID:  docker://a79181d1dafc0f9e4acec2bab4ee2e155b20b5d7c74d44930e144b08a85ef4b7
00:16:07  	     Image:         k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-sidecar-amd64@sha256:e55cbd5361a86bf0a01bfeaca2e958e15571f1e741356eab83bb444a13020d4c
00:16:07  	     Port:          10054/TCP
00:16:07  	     Host Port:     0/TCP
00:16:07  	     Args:
00:16:07  	       --v=2
00:16:07  	       --logtostderr
00:16:07  	       --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV
00:16:07  	       --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV
00:16:07  	     State:          Running
00:16:07  	       Started:      Wed, 17 Jun 2020 07:15:53 +0000
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    2
00:16:07  	       Started:      Wed, 17 Jun 2020 07:13:28 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:38 +0000
00:16:07  	     Ready:          True
00:16:07  	     Restart Count:  2
00:16:07  	     Requests:
00:16:07  	       cpu:        10m
00:16:07  	       memory:     20Mi
00:16:07  	     Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
00:16:07  	     Environment:  <none>
00:16:07  	     Mounts:
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	   prometheus-to-sd:
00:16:07  	     Container ID:  docker://c98e722300336a8ac21f5fba0048e9775d153dfeff6de77c33f4c0026d528439
00:16:07  	     Image:         k8s.gcr.io/prometheus-to-sd:v0.4.2
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/prometheus-to-sd@sha256:aca8ef83a7fae83f1f8583e978dd4d1ff655b9f2ca0a76bda5edce6d8965bdf2
00:16:07  	     Port:          <none>
00:16:07  	     Host Port:     <none>
00:16:07  	     Command:
00:16:07  	       /monitor
00:16:07  	       --source=kubedns:http://localhost:10054?whitelisted=probe_kubedns_latency_ms,probe_kubedns_errors,dnsmasq_misses,dnsmasq_hits
00:16:07  	       --stackdriver-prefix=container.googleapis.com/internal/addons
00:16:07  	       --api-override=https://monitoring.googleapis.com/
00:16:07  	       --pod-id=$(POD_NAME)
00:16:07  	       --namespace-id=$(POD_NAMESPACE)
00:16:07  	       --v=2
00:16:07  	     State:          Waiting
00:16:07  	       Reason:       CrashLoopBackOff
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    255
00:16:07  	       Started:      Wed, 17 Jun 2020 07:14:52 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:14:59 +0000
00:16:07  	     Ready:          False
00:16:07  	     Restart Count:  5
00:16:07  	     Environment:
00:16:07  	       POD_NAME:       kube-dns-5995c95f64-7lnpc (v1:metadata.name)
00:16:07  	       POD_NAMESPACE:  kube-system (v1:metadata.namespace)
00:16:07  	     Mounts:
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	 Conditions:
00:16:07  	   Type              Status
00:16:07  	   Initialized       True 
00:16:07  	   Ready             False 
00:16:07  	   ContainersReady   False 
00:16:07  	   PodScheduled      True 
00:16:07  	 Volumes:
00:16:07  	   kube-dns-config:
00:16:07  	     Type:      ConfigMap (a volume populated by a ConfigMap)
00:16:07  	     Name:      kube-dns
00:16:07  	     Optional:  true
00:16:07  	   kube-dns-token-q2bjn:
00:16:07  	     Type:        Secret (a volume populated by a Secret)
00:16:07  	     SecretName:  kube-dns-token-q2bjn
00:16:07  	     Optional:    false
00:16:07  	 QoS Class:       Burstable
00:16:07  	 Node-Selectors:  <none>
00:16:07  	 Tolerations:     CriticalAddonsOnly
00:16:07  	                  components.gke.io/gke-managed-components
00:16:07  	                  node.kubernetes.io/not-ready:NoExecute for 300s
00:16:07  	                  node.kubernetes.io/unreachable:NoExecute for 300s
00:16:07  	 Events:
00:16:07  	   Type     Reason     Age                    From                                                  Message
00:16:07  	   ----     ------     ----                   ----                                                  -------
00:16:07  	   Normal   Scheduled  5m4s                   default-scheduler                                     Successfully assigned kube-system/kube-dns-5995c95f64-7lnpc to gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q
00:16:07  	   Normal   Pulling    5m1s                   kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4"
00:16:07  	   Normal   Pulled     5m                     kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4"
00:16:07  	   Normal   Created    4m59s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container kubedns
00:16:07  	   Normal   Started    4m59s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container kubedns
00:16:07  	   Normal   Pulling    4m59s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4"
00:16:07  	   Normal   Pulled     4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4"
00:16:07  	   Normal   Created    4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container dnsmasq
00:16:07  	   Normal   Started    4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container dnsmasq
00:16:07  	   Normal   Pulling    4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4"
00:16:07  	   Normal   Pulling    4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
00:16:07  	   Normal   Created    4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container sidecar
00:16:07  	   Normal   Started    4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container sidecar
00:16:07  	   Normal   Pulled     4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4"
00:16:07  	   Normal   Pulled     4m55s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
00:16:07  	   Normal   Started    4m47s (x2 over 4m55s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container prometheus-to-sd
00:16:07  	   Warning  BackOff    4m39s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Back-off restarting failed container
00:16:07  	   Warning  Unhealthy  4m29s (x3 over 4m49s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Readiness probe failed: Get http://10.24.115.41:8081/readiness: dial tcp 10.24.115.41:8081: connect: connection refused
00:16:07  	   Normal   Created    4m26s (x3 over 4m55s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container prometheus-to-sd
00:16:07  	   Normal   Pulled     4m26s (x2 over 4m47s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Container image "k8s.gcr.io/prometheus-to-sd:v0.4.2" already present on machine
00:16:07  	 
00:16:07  	 
00:16:07  	 Name:                 kube-dns-5995c95f64-8zlh5
00:16:07  	 Namespace:            kube-system
00:16:07  	 Priority:             2000000000
00:16:07  	 Priority Class Name:  system-cluster-critical
00:16:07  	 Node:                 gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q/10.128.0.37
00:16:07  	 Start Time:           Wed, 17 Jun 2020 07:11:03 +0000
00:16:07  	 Labels:               k8s-app=kube-dns
00:16:07  	                       pod-template-hash=5995c95f64
00:16:07  	 Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
00:16:07  	                       seccomp.security.alpha.kubernetes.io/pod: docker/default
00:16:07  	 Status:               Running
00:16:07  	 IP:                   10.24.115.38
00:16:07  	 IPs:                  <none>
00:16:07  	 Controlled By:        ReplicaSet/kube-dns-5995c95f64
00:16:07  	 Containers:
00:16:07  	   kubedns:
00:16:07  	     Container ID:  docker://8e0bf2769312b9a93fcd737e5513c446100dd3408ae8b6b890379d9d3b221a0c
00:16:07  	     Image:         k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-kube-dns-amd64@sha256:a13c60e2a9d49f965095a1e003388926f3f2a6189ed4aecb1541f114c955f8ec
00:16:07  	     Ports:         10053/UDP, 10053/TCP, 10055/TCP
00:16:07  	     Host Ports:    0/UDP, 0/TCP, 0/TCP
00:16:07  	     Args:
00:16:07  	       --domain=cluster.local.
00:16:07  	       --dns-port=10053
00:16:07  	       --config-dir=/kube-dns-config
00:16:07  	       --v=2
00:16:07  	     State:          Waiting
00:16:07  	       Reason:       CrashLoopBackOff
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    255
00:16:07  	       Started:      Wed, 17 Jun 2020 07:14:55 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:55 +0000
00:16:07  	     Ready:          False
00:16:07  	     Restart Count:  3
00:16:07  	     Limits:
00:16:07  	       memory:  170Mi
00:16:07  	     Requests:
00:16:07  	       cpu:      100m
00:16:07  	       memory:   70Mi
00:16:07  	     Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
00:16:07  	     Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
00:16:07  	     Environment:
00:16:07  	       PROMETHEUS_PORT:  10055
00:16:07  	     Mounts:
00:16:07  	       /kube-dns-config from kube-dns-config (rw)
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	   dnsmasq:
00:16:07  	     Container ID:  docker://dc727c2f3d2f1032361fc42ebd3cc6c6be5064cf07acaf744d1bd8c29072c68f
00:16:07  	     Image:         k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:0a70a8a9ae8cfe752021de84f13b3ecd109d9b5fbe3f1541c52fcd1d4c2c0b45
00:16:07  	     Ports:         53/UDP, 53/TCP
00:16:07  	     Host Ports:    0/UDP, 0/TCP
00:16:07  	     Args:
00:16:07  	       -v=2
00:16:07  	       -logtostderr
00:16:07  	       -configDir=/etc/k8s/dns/dnsmasq-nanny
00:16:07  	       -restartDnsmasq=true
00:16:07  	       --
00:16:07  	       -k
00:16:07  	       --cache-size=1000
00:16:07  	       --no-negcache
00:16:07  	       --log-facility=-
00:16:07  	       --server=/cluster.local/127.0.0.1#10053
00:16:07  	       --server=/in-addr.arpa/127.0.0.1#10053
00:16:07  	       --server=/ip6.arpa/127.0.0.1#10053
00:16:07  	     State:          Running
00:16:07  	       Started:      Wed, 17 Jun 2020 07:15:42 +0000
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    137
00:16:07  	       Started:      Wed, 17 Jun 2020 07:13:22 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:41 +0000
00:16:07  	     Ready:          True
00:16:07  	     Restart Count:  2
00:16:07  	     Requests:
00:16:07  	       cpu:        150m
00:16:07  	       memory:     20Mi
00:16:07  	     Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
00:16:07  	     Environment:  <none>
00:16:07  	     Mounts:
00:16:07  	       /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	   sidecar:
00:16:07  	     Container ID:  docker://ad53c4650d4e5a39aa30d6fec132de99740aae736e5660b9873e14d0dd94ee68
00:16:07  	     Image:         k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-sidecar-amd64@sha256:e55cbd5361a86bf0a01bfeaca2e958e15571f1e741356eab83bb444a13020d4c
00:16:07  	     Port:          10054/TCP
00:16:07  	     Host Port:     0/TCP
00:16:07  	     Args:
00:16:07  	       --v=2
00:16:07  	       --logtostderr
00:16:07  	       --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV
00:16:07  	       --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV
00:16:07  	     State:          Waiting
00:16:07  	       Reason:       CrashLoopBackOff
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    2
00:16:07  	       Started:      Wed, 17 Jun 2020 07:13:27 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:47 +0000
00:16:07  	     Ready:          False
00:16:07  	     Restart Count:  1
00:16:07  	     Requests:
00:16:07  	       cpu:        10m
00:16:07  	       memory:     20Mi
00:16:07  	     Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
00:16:07  	     Environment:  <none>
00:16:07  	     Mounts:
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	   prometheus-to-sd:
00:16:07  	     Container ID:  docker://f70f3f903cb47a8d9de541a4b222c0ab126bb241e32db22783dea52b253c2e06
00:16:07  	     Image:         k8s.gcr.io/prometheus-to-sd:v0.4.2
00:16:07  	     Image ID:      docker-pullable://k8s.gcr.io/prometheus-to-sd@sha256:aca8ef83a7fae83f1f8583e978dd4d1ff655b9f2ca0a76bda5edce6d8965bdf2
00:16:07  	     Port:          <none>
00:16:07  	     Host Port:     <none>
00:16:07  	     Command:
00:16:07  	       /monitor
00:16:07  	       --source=kubedns:http://localhost:10054?whitelisted=probe_kubedns_latency_ms,probe_kubedns_errors,dnsmasq_misses,dnsmasq_hits
00:16:07  	       --stackdriver-prefix=container.googleapis.com/internal/addons
00:16:07  	       --api-override=https://monitoring.googleapis.com/
00:16:07  	       --pod-id=$(POD_NAME)
00:16:07  	       --namespace-id=$(POD_NAMESPACE)
00:16:07  	       --v=2
00:16:07  	     State:          Waiting
00:16:07  	       Reason:       CrashLoopBackOff
00:16:07  	     Last State:     Terminated
00:16:07  	       Reason:       Error
00:16:07  	       Exit Code:    255
00:16:07  	       Started:      Wed, 17 Jun 2020 07:14:55 +0000
00:16:07  	       Finished:     Wed, 17 Jun 2020 07:15:02 +0000
00:16:07  	     Ready:          False
00:16:07  	     Restart Count:  5
00:16:07  	     Environment:
00:16:07  	       POD_NAME:       kube-dns-5995c95f64-8zlh5 (v1:metadata.name)
00:16:07  	       POD_NAMESPACE:  kube-system (v1:metadata.namespace)
00:16:07  	     Mounts:
00:16:07  	       /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-q2bjn (ro)
00:16:07  	 Conditions:
00:16:07  	   Type              Status
00:16:07  	   Initialized       True 
00:16:07  	   Ready             False 
00:16:07  	   ContainersReady   False 
00:16:07  	   PodScheduled      True 
00:16:07  	 Volumes:
00:16:07  	   kube-dns-config:
00:16:07  	     Type:      ConfigMap (a volume populated by a ConfigMap)
00:16:07  	     Name:      kube-dns
00:16:07  	     Optional:  true
00:16:07  	   kube-dns-token-q2bjn:
00:16:07  	     Type:        Secret (a volume populated by a Secret)
00:16:07  	     SecretName:  kube-dns-token-q2bjn
00:16:07  	     Optional:    false
00:16:07  	 QoS Class:       Burstable
00:16:07  	 Node-Selectors:  <none>
00:16:07  	 Tolerations:     CriticalAddonsOnly
00:16:07  	                  components.gke.io/gke-managed-components
00:16:07  	                  node.kubernetes.io/not-ready:NoExecute for 300s
00:16:07  	                  node.kubernetes.io/unreachable:NoExecute for 300s
00:16:07  	 Events:
00:16:07  	   Type     Reason     Age                    From                                                  Message
00:16:07  	   ----     ------     ----                   ----                                                  -------
00:16:07  	   Normal   Scheduled  5m4s                   default-scheduler                                     Successfully assigned kube-system/kube-dns-5995c95f64-8zlh5 to gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q
00:16:07  	   Normal   Pulling    5m1s                   kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4"
00:16:07  	   Normal   Pulled     5m                     kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4"
00:16:07  	   Normal   Created    4m59s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container kubedns
00:16:07  	   Normal   Started    4m59s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container kubedns
00:16:07  	   Normal   Pulling    4m59s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4"
00:16:07  	   Normal   Pulled     4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4"
00:16:07  	   Normal   Created    4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container dnsmasq
00:16:07  	   Normal   Started    4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container dnsmasq
00:16:07  	   Normal   Pulling    4m58s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4"
00:16:07  	   Normal   Pulling    4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Pulling image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
00:16:07  	   Normal   Created    4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container sidecar
00:16:07  	   Normal   Started    4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container sidecar
00:16:07  	   Normal   Pulled     4m56s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4"
00:16:07  	   Normal   Pulled     4m55s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
00:16:07  	   Normal   Started    4m47s (x2 over 4m55s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Started container prometheus-to-sd
00:16:07  	   Warning  BackOff    4m39s                  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Back-off restarting failed container
00:16:07  	   Warning  Unhealthy  4m26s (x3 over 4m46s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Readiness probe failed: Get http://10.24.115.38:8081/readiness: dial tcp 10.24.115.38:8081: connect: connection refused
00:16:07  	   Normal   Created    4m25s (x3 over 4m55s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Created container prometheus-to-sd
00:16:07  	   Normal   Pulled     4m25s (x2 over 4m47s)  kubelet, gke-cilium-ci-12-cilium-ci-12-0f5b54d9-m44q  Container image "k8s.gcr.io/prometheus-to-sd:v0.4.2" already present on machine
00:16:07  	 
00:16:07  Stderr:
00:16:07   	 
00:16:07  
00:16:07  FAIL: Kubernetes DNS did not become ready in time
```
