### ISSUE TITLE
1.8-rc3 crashloop with ipv6 enabled

### ISSUE THREAD

**Issue by jedsalazar** [cilium/cilium#12188]
## Bug report

On a fresh install of 1.8-rc3 with ipv6 enabled, cilium-agents goes into a crashloop. logs provide some warnings and then a fatal message about failing to determine IPv6 for the host interface

```
level=fatal msg="Failed to initialize NodePort addrs" error="Failed to determine IPv6 of enp0s8 for NodePort" subsys=daemon
```

Deployed with `helm template cilium/cilium --version 1.8.0-rc3 --namespace=kube-system --set global.ipv4.enabled=true --set global.ipv6.enabled=true > cilium-1.8-rc3.yaml`

Some additional level=warning messages precede the fatal log are included below

```
level=warning msg="Device with a default route cannot be found for BPF NodePort device detection" error="Default route not found for family 10" subsys=daemon
level=info msg="Using auto-derived devices for BPF node port" devices="[enp0s8]" directRoutingDevice=enp0s8 subsys=daemon
level=warning msg="Session affinity for host reachable services needs kernel 5.7.0 or newer to work properly when accessed from inside cluster: the same service endpoint will be selected from all network namespaces on the host." subsys=daemon
```

**General Information**

- Cilium version (run `cilium version`)
 1.8-rc3
- Kernel version (run `uname -a`) 
Linux agent1 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
v1.18.4+k3s1 
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Deploy 1.8-rc3 with IPv6 enabled

**Comment by Rolinh** [comment]
I could reproduce with a cluster created with `kind` (see instructions [here](https://docs.cilium.io/en/latest/gettingstarted/kind/)) and the following `helm` install command:
```
$ helm install cilium ./cilium --set global.tag=v1.8 --namespace kube-system --set global.nodeinit.enabled=true --set global.kubeProxyReplacement=partial --set global.hostServices.enabled=false --set global.externalIPs.enabled=true --set global.nodePort.enabled=true --set global.hostPort.enabled=true --set global.pullPolicy=IfNotPresent --set config.ipam=kubernetes --set global.ipv6.enabled=true --set global.ipv4.enabled=false
```
This results in a `panic` in the cilium pod:
```
evel=info msg="Addressing information:" subsys=daemon
level=info msg="  Cluster-Name: default" subsys=daemon
level=info msg="  Cluster-ID: 0" subsys=daemon
level=info msg="  Local node-name: kind-worker2" subsys=daemon
level=info msg="  Node-IPv6: fc00:f853:ccd:e793::2" subsys=daemon
level=info msg="  IPv6 allocation prefix: fd00:10:244:0:2::/80" subsys=daemon
level=info msg="  IPv6 router address: fd00:10:244:0:2::b2ca" subsys=daemon
level=info msg="  Local IPv6 addresses:" subsys=daemon
level=info msg="  - fc00:f853:ccd:e793::2" subsys=daemon
level=info msg="  External-Node IPv4: <nil>" subsys=daemon
level=info msg="  Internal-Node IPv4: <nil>" subsys=daemon
level=info msg="Annotating k8s node" subsys=daemon v4CiliumHostIP.IPv4="<nil>" v4Prefix="<nil>" v4healthIP.IPv4="<nil>" v6CiliumHostIP.IPv6="fd00:10:244:0:2::b2ca" v6Prefix="fd00:10:244:0:2::/80" v6healthIP.IPv6="fd00:10:244:0:2::b8b1"
level=info msg="Adding local node to cluster" subsys=nodediscovery
level=info msg="Successfully created CiliumNode resource" subsys=nodediscovery
level=info msg="Initializing identity allocator" subsys=identity-cache
level=info msg="Cluster-ID is not specified, skipping ClusterMesh initialization" subsys=daemon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b17ec7]

goroutine 1 [running]:
github.com/cilium/cilium/pkg/datapath/linux/config.(*HeaderfileWriter).WriteNodeConfig(0x40bc480, 0x27c2b20, 0xc0004f0398, 0xc000bb2508, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/config/config.go:344 +0x31d7
github.com/cilium/cilium/daemon/cmd.(*Daemon).createNodeConfigHeaderfile(0xc000bcc000, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/daemon/cmd/datapath.go:70 +0x3d6
github.com/cilium/cilium/daemon/cmd.(*Daemon).init(0xc000bcc000, 0x3b67800, 0x3b54770)
        /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:204 +0x673
github.com/cilium/cilium/daemon/cmd.NewDaemon(0x281f540, 0xc00047fac0, 0x2855fe0, 0xc00037c4d0, 0x2838e00, 0xc000436fe0, 0x2855fe0, 0xc00037c4d0)
        /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:570 +0x19b4
github.com/cilium/cilium/daemon/cmd.runDaemon()
        /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1254 +0x36f
github.com/cilium/cilium/daemon/cmd.glob..func1(0x3b40e80, 0xc00040c150, 0x0, 0x1)
        /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:118 +0x8d
github.com/spf13/cobra.(*Command).execute(0x3b40e80, 0xc00018c010, 0x1, 0x1, 0x3b40e80, 0xc00018c010)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x3b40e80, 0xc000212d20, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:887
github.com/cilium/cilium/daemon/cmd.Execute()
        /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:149 +0x15e
main.main()
        /go/src/github.com/cilium/cilium/daemon/main.go:22 +0x20
```

**Comment by aanm** [comment]
@jedsalazar can you work around it with `--enable-bpf-masquerade=false`?

**Comment by jedsalazar** [comment]
@aanm I get the same error when I deploy with helm `--set config.bpfMasquerade=false`

**Comment by jedsalazar** [comment]
Some additional details from my environment. I disabled BPF-masquerading and received the same `level=fatal msg="Failed to initialize NodePort addrs" error="Failed to determine IPv6 of enp0s8 for NodePort" subsys=daemon` error. 

```
> egrep -R 'masquerade|ipv6' .
./quick-install.yaml:  enable-ipv6: "true"
./quick-install.yaml:  masquerade: "true"
./quick-install.yaml:  enable-bpf-masquerade: "false"
./quick-install.yaml:  k8s-require-ipv6-pod-cidr: "false"

k get po -n kube-system -l k8s-app=cilium
NAME           READY   STATUS             RESTARTS   AGE
cilium-4w59j   0/1     CrashLoopBackOff   2          45s
cilium-w6m67   0/1     Error              2          45s
```

The node only has ipv6 link-local addresses

```
$ ip -6 a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::ac:8aff:fe16:fb20/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::a00:27ff:fee7:3208/64 scope link
       valid_lft forever preferred_lft forever
4: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::48af:a9ff:fe2a:af9a/64 scope link
       valid_lft forever preferred_lft forever
5: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::941f:35ff:fe14:b6a3/64 scope link
       valid_lft forever preferred_lft forever
6: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1000
    inet6 fe80::3484:16ff:fe20:2f5e/64 scope link
       valid_lft forever preferred_lft forever
10: lxc1abe3277b3ff@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::94c9:43ff:fefb:5bc0/64 scope link
       valid_lft forever preferred_lft forever
```

Let me know if there's any other info I can provide. Thanks!

**Comment by borkmann** [comment]
Your env has only link scope v6 address, I think if you change to global scope, it should work then, or alternatively disable v6 in Cilium?

**Comment by borkmann** [comment]
Discussed with @brb offline that we'll do the following in the agent: i) in case of kube-proxy-free=probe we'll fallback to partial mode, that is ClusterIP handling via bpf_lxc and enablement of socket LB, ii) in case of kube-proxy-free=strict we bail out due to invalid user config (aka v6 w/ link-local addresses (LLA) only). We can revisit after 1.8.0 whether we want to just transparently use the LLA for v6 case, but needs more evaluation first.
