### ISSUE TITLE
CI: K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath: provided port is already allocated

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#13071]
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
cannot install connectivity-check
Expected command: kubectl apply --force=false -f /home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/examples/kubernetes/connectivity-check/connectivity-check-proxy.yaml 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 deployment.apps/echo-c created
	 deployment.apps/echo-c-host created
	 deployment.apps/pod-to-a-intra-node-proxy-egress-policy created
	 deployment.apps/pod-to-a-multi-node-proxy-egress-policy created
	 deployment.apps/pod-to-c-intra-node-proxy-ingress-policy created
	 deployment.apps/pod-to-c-multi-node-proxy-ingress-policy created
	 deployment.apps/pod-to-c-intra-node-proxy-to-proxy-policy created
	 deployment.apps/pod-to-c-multi-node-proxy-to-proxy-policy created
	 service/echo-c created
	 service/echo-c-headless created
	 service/echo-c-host-headless created
	 ciliumnetworkpolicy.cilium.io/pod-to-a-intra-node-proxy-egress-policy created
	 ciliumnetworkpolicy.cilium.io/pod-to-a-multi-node-proxy-egress-policy created
	 ciliumnetworkpolicy.cilium.io/pod-to-c-intra-node-proxy-to-proxy-policy created
	 ciliumnetworkpolicy.cilium.io/pod-to-c-multi-node-proxy-to-proxy-policy created
	 ciliumnetworkpolicy.cilium.io/echo-c created
	 deployment.apps/echo-a created
	 service/echo-a created
	 deployment.apps/echo-b created
	 deployment.apps/echo-b-host created
	 service/echo-b-host-headless created
	 
Stderr:
 	 The Service "echo-b" is invalid: spec.ports[0].nodePort: Invalid value: 31313: provided port is already allocated
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/k8sT/Policies.go:1495
```

After investigating this, it turns out that there's a chance that Services that are created in the test suite could conflict with each other's `nodePort`. In some cases, we don't explicitly set the `nodePort` and leave it up to K8s to allocate a port between the range of `30000` and `32768`. In other cases, we do explicitly set the `nodePort`. In this test failure, we had a Service created first and was allocated a random port of `31313`, and later we deploy a Service with a set port to `31313`, causing the conflict.

The reason the conflict occured in the first place is because of a failure to clean up, which we don't have logs for, as it happened in a different block and didn't trigger an error, which we usually ignore. We only retrieve output when an error occurs in a specific block [`It()`, etc]).

I posted on the [#testing channel](https://cilium.slack.com/archives/C7PE7V806/p1599156174009900) about different approaches and I will quote the post here, in case the Slack link expires.

> I've come across a test failure that failed because two different Services conflicted on their `nodePort`. From what I can tell, a NodePort Service was allocated to port 31313 in the test suite, and then later in the test suite, a totally different NodePort Service was created, setting 31313 as the explicit NodePort. This obviously created a conflict and spit out a msg like:
> 
>  	> The Service "echo-b" is invalid: spec.ports[0].nodePort: Invalid value: 31313: provided port is already allocated
> 
> The first Service should have been deleted, but it clearly was not cleaned up, and there are no logs to explain why. We ignore errors when cleaning up to prevent the test suite from halting for "minor" reasons, but it does allow us to get into these situations, where we've potentially polluted the next test.Specifically for Services, I see two approaches to prevent this in the future:
> 
>    1) Explicitly set the nodePort for every Service we create, so that we don't get bitten by the random allocation between 30000 - 32767.
>    2) Where we set the nodePort explicitly, choose a port from outside the range (30000 - 32767), to avoid conflicts with random allocation within that range.

> Actually I just realized that this happened in the same parent Context block, and has nested Contexts within it.Essentially it looks like:
> 
> ```
> Context A {
>   BeforeAll() { Created Service with randomly allocated port 31313 }
>   AfterAll()  { Cleaned up resources, but failed on Service above } ...
>   Context B {
>     BeforeAll() { Created Service with explicit port 31313; conflict }
>     AfterAll() { 
>       Fails to clean up because above Service wasn't created
>     }
>   }
> }
> ```

Unfortunately, trying to dig into why the clean up failed would be moot, because we don't retrieve output from succeeding runs, so we still wouldn't have the reason of why it failed to clean up in the first place. We only have Context B's output (we actually only have the It() block within it). So that leaves us with the two aforementioned approaches above.

Found during https://github.com/cilium/cilium/pull/13053

**Comment by christarazi** [comment]
Following the discussion on Slack (link above), @joestringer pointed out this could be a bug in Cilium where we fail to delete / clean up the Service, even though the delete may have succeeded from the K8s perspective. 

Adding `needs-triage`.

**Comment by joestringer** [comment]
When I look at the original commandline output again, it seems to be `kubectl` reporting this failure, which means it should actually be that there are conflicting k8s objects installed when attempting to configure this new YAML. This suggests that it's actually just kubectl service cleanup from previous test that is not performed properly (ie test-code bug), rather than an agent bug.

**Comment by christarazi** [comment]
> When I look at the original commandline output again, it seems to be `kubectl` reporting this failure, which means it should actually be that there are conflicting k8s objects installed when attempting to configure this new YAML. This suggests that it's actually just kubectl service cleanup from previous test that is not performed properly (ie test-code bug), rather than an agent bug.

Ah, thanks for catching that. It slipped my mind that we were seeing the failure from `kubectl`. So then this reinstates that the solution lies between the two approaches originally listed. @aanm also pointed out that we can't choose a NodePort outside the NodePort range, leaving us with only approach (1) from above.

Removing `needs/triage`.

**Comment by fristonio** [comment]
I also came across this when working with cilium connectivity-checks. This seems to be an issue in Kubernetes itself where the allocation of nodePort is done from the local cache which can be out of sync from the etcd data. See https://github.com/kubernetes/kubernetes/issues/85894 for more context.

I was even able to reproduce it using connectivity checks from a simple script[1]. At this point, there doesn't seem to be a proper solution for this. The way I fixed it for my use case is by retrying during `connectivity-check.yaml` apply until it succeeds or a timeout is reached.

What I am not sure of exactly is if the above error is due to this out of sync behavior or due to the port collision as mentioned in the issue description. My assumption here is that since the issue was fixed in the latest releases and we only see these errors in GKE/net-next this might not be due to port collision.

[1] - The script will fail with an error similar to that mentioned in the issue description.
```
#!/bin/bash

set -e

URL="https://raw.githubusercontent.com/cilium/cilium/v1.9.0/examples/kubernetes/connectivity-check/connectivity-check.yaml"
NAMESPACE="temp-namespace"

kubectl create namespace "${NAMESPACE}" || true

function echo_sep() {
    echo "---------------------------------------"
}

for i in {1..10}
do
    echo "LOOP COUNT : ${i}"
    echo "[*] List services in the namepsace before apply"
    kubectl get svc -n "${NAMESPACE}"

    echo_sep

    echo "[*] Applying connectivity check in the namespace"
    kubectl apply -n "${NAMESPACE}" -f "${URL}"

    echo_sep

    echo "[*] Listing services in the namespace after apply"
    kubectl get svc -n "${NAMESPACE}"

    echo_sep

    echo "[*] Deleting connectivity check in the namespace"
    kubectl delete --wait -n "${NAMESPACE}" -f "${URL}"

    echo_sep

    echo "[*] Listing services in the namespace after delete"
    kubectl get svc -n "${NAMESPACE}"

    echo_sep
done
```

**Comment by christarazi** [comment]
@fristonio It looks like the issue linked has been fixed and was included in K8s 1.19. Are you saying that you still experience this flake with this test when running net-next and 1.19 (I realize that's not a setup that we have).

**Comment by jrajahalme** [comment]
Hit this in CI with Kernel 4.9 and K8s 1.20: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/533/testReport/junit/Suite-k8s-1/20/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/

**Comment by ungureanuvladvictor** [comment]
Hit this one via https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/5174/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/. Code changes were via https://github.com/cilium/cilium/pull/15759 which are unrelated.

**Comment by pchaigno** [comment]
Do we know who allocates the port? If it's the kernel, we could use the same trick as in https://github.com/cilium/cilium/pull/15988, to at least alleviate the problem until all our CI is testing K8s >=1.19.

**Comment by christarazi** [comment]
@pchaigno Yes it appears so. I can take this up and use an even-numbered port.

**Comment by pchaigno** [comment]
Hit again in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/616/testReport/junit/Suite-k8s-1/21/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/, this time with the new even-numbered port:
```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
cannot install connectivity-check
Expected command: kubectl apply --force=false -f /home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/examples/kubernetes/connectivity-check/connectivity-check-proxy.yaml 
To succeed, but it failed:
[...] 
Stderr:
 	 The Service "echo-b" is invalid: spec.ports[0].nodePort: Invalid value: 31414: provided port is already allocated
```

The sysdump doesn't reveal any process holding that port :thinking: Could be that the process released the port between the test failure and the sysdump capture. I'm reopening so we can track this properly and see if another fix is necessary.

**Comment by borkmann** [comment]
Hit in #18779:
```
2022-03-28T17:28:12.226792259Z 
2022-03-28T17:28:12.227448548Z   \{^_^}/ hi!
2022-03-28T17:28:12.227459255Z 
2022-03-28T17:28:12.227491452Z   Loading /default.json
2022-03-28T17:28:12.233540108Z   Done
2022-03-28T17:28:12.238630566Z 
2022-03-28T17:28:12.238679750Z   Resources
2022-03-28T17:28:12.238686068Z   http://:41002/private
2022-03-28T17:28:12.238772007Z   http://:41002/public
2022-03-28T17:28:12.238778630Z 
2022-03-28T17:28:12.238781174Z   Home
2022-03-28T17:28:12.238783454Z   http://:41002
2022-03-28T17:28:12.238785736Z 
2022-03-28T17:28:12.239035451Z   Type s + enter at any time to create a snapshot of the database
2022-03-28T17:28:12.239894213Z   Watching...
2022-03-28T17:28:12.239905751Z 
2022-03-28T17:28:12.242164441Z Some error occurred Error: listen EADDRINUSE: address already in use :::41002
2022-03-28T17:28:12.242177948Z     at Server.setupListenHandle [as _listen2] (node:net:1306:16)
2022-03-28T17:28:12.242180849Z     at listenInCluster (node:net:1354:12)
2022-03-28T17:28:12.242183145Z     at Server.listen (node:net:1441:7)
2022-03-28T17:28:12.242185392Z     at Function.listen (/usr/local/lib/node_modules/json-server/node_modules/express/lib/application.js:618:24)
2022-03-28T17:28:12.242188820Z     at /usr/local/lib/node_modules/json-server/lib/cli/run.js:135:20 {
2022-03-28T17:28:12.242191141Z   code: 'EADDRINUSE',
2022-03-28T17:28:12.242193372Z   errno: -98,
2022-03-28T17:28:12.242195628Z   syscall: 'listen',
2022-03-28T17:28:12.242197834Z   address: '::',
2022-03-28T17:28:12.242200063Z   port: 41002
2022-03-28T17:28:12.242202250Z }
```

**Comment by aditighag** [comment]
Hit in - https://github.com/cilium/cilium/pull/21054.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/827/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/

**Comment by pchaigno** [comment]
I believe the same issue is still happening but now with a different output: https://github.com/cilium/cilium/issues/22749.

**Comment by aspsk** [comment]
Hit this with
```
The Service "echo-b" is invalid: spec.ports[0].nodePort: Invalid value: 31414: provided port is already allocated
```

[logs_1317838.zip](https://github.com/cilium/cilium/files/11155853/logs_1317838.zip)

**Comment by christarazi** [comment]
JFYI, this flake is a bit unfortunate because we don't have control over the nodeport range which can conflict with the port range used by Cilium's proxy. We moved to even-numbered port numbers to reduce the likelihood but there's still a chance we get unlucky.

**Comment by qmonnet** [comment]
[Hit](https://github.com/cilium/cilium/actions/runs/5835968448/job/15828613805) on https://github.com/cilium/cilium/pull/27466.

**Comment by pippolo84** [comment]
[Hit](https://github.com/cilium/cilium/actions/runs/6119358971/job/16609328540) on [#26836](https://github.com/cilium/cilium/pull/26836).
Sysdump:  [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/12560294/cilium-sysdumps.zip)

**Comment by chancez** [comment]
Hit on https://github.com/cilium/cilium/pull/34229

Sysdumps: 
[cilium-sysdumps.zip](https://github.com/user-attachments/files/16603368/cilium-sysdumps.zip)

**Comment by chancez** [comment]
What about instead of hard-coding the port, we should simply create the nodePort, let k8s do the allocation, and then retrieve the port that it generated.

**Comment by tamilmani1989** [comment]
Hitting this issue: https://github.com/cilium/cilium/actions/runs/16916616986/job/47932038023#step:19:1413 
PR: https://github.com/cilium/cilium/pull/37568

**Comment by ajmmm** [comment]
Also hitting this issue: https://github.com/cilium/cilium/actions/runs/16969148459/job/48101199087


PR: https://github.com/cilium/cilium/pull/41153

**Comment by joestringer** [comment]
It appears from the breadcrumbs on this issue that we haven't hit this issue for several months, but just recently we've hit the issue a few times. Could it be that something changed recently in the tree to make this failure more likely again?

**Comment by joestringer** [comment]
> What about instead of hard-coding the port, we should simply create the nodePort, let k8s do the allocation, and then retrieve the port that it generated.

That seems like a reasonable proposal to me.

**Comment by joestringer** [comment]
Closing in favor of https://github.com/cilium/cilium/issues/44164
