### ISSUE TITLE
panic: runtime error with enable-health-check-nodeport: "false" and kube-proxy-replacement: probe

### ISSUE THREAD

**Issue by gandalfmagic** [cilium/cilium#13300]
## Bug report

**General Information**

- Cilium version `v1.8.3`
- Kernel version `Linux test-node6 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux`
- Kubernetes `v1.18.9`

**How to reproduce the issue**

Hello, I got this error:

```
level=info msg="Enabling k8s event listener" subsys=k8s-watcher
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Waiting until all pre-existing resources related to policy have been received" subsys=k8s-watcher
level=info msg="Initializing node addressing" subsys=daemon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1d3aa37]

goroutine 61 [running]:
github.com/cilium/cilium/pkg/service.(*Service).UpsertService(0xc0001a67e0, 0xc0006f9980, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/service/service.go:289 +0xdf7
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addK8sSVCs(0xc00091c160, 0xc000dafb50, 0xc, 0xc000dafb60, 0xc, 0x0, 0xc000605580, 0xc000d98098, 0x0, 0x2)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:810 +0x46a
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler.func1(0x0, 0xc000dafb50, 0xc, 0xc000dafb60, 0xc, 0xc000605580, 0x0, 0xc000d98098, 0xc0006abce0)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:502 +0xa4e
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler(0xc00091c160)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:545 +0x95
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).RunK8sServiceHandler
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:550 +0x3f
```

My config:

```
  auto-direct-node-routes: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.0.0.0/8
  cluster-pool-ipv4-mask-size: "24"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-metrics: "true"
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  etcd-config: |-
    ---
    endpoints:
      - https://...
      - https://...
      - https://...
    ca-file: "/etc/cilium/certs/ca_cert.crt"
    key-file: "/etc/cilium/certs/key.pem"
    cert-file: "/etc/cilium/certs/cert.crt"
  identity-allocation-mode: kvstore
  install-iptables-rules: "true"
  ipam: cluster-pool
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: probe
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config"}'
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: vxlan
  wait-bpf-mount: "false"
```

**Comment by aanm** [comment]
@gandalfmagic thank you for filling the GH issue, this is already fixed on master and it's going to be fixed once we release 1.8.4 which will happen in the following days.

The PR that fixed this https://github.com/cilium/cilium/pull/13190
