### ISSUE TITLE
stacktrace while running cilium bpf command

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#13456]
## Bug report

**General Information**

- Cilium version: 1.8.90 `43e6a4aedd88a0916bc6f38aad29c3ed9e254b68`
- Kernel version: `5.9.0-rc6+` 

**How to reproduce the issue**

1. `NFS=1 NETNEXT=1 NWORKERS=1 K8S=1  ./contrib/vagrant/start.sh`
2. `vagrant ssh k8s1+ -- 'sudo cilium bpf ct list global > /dev/null'`

Output appears to be OK, but there is also a stack trace on stderr that indicates that something is wrong:
```
goroutine 1 [running]:
goroutine 1 runtime/debug.Stack(0xbfd7d2a2d5ac0174, 0x4e1ec34, 0x31cca40)
goroutine 1     /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc00056e078)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:68 +0xc5
goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).Open(0xc00056e000, 0x0, 0x0)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:525 +0x9f
goroutine 1 github.com/cilium/cilium/cilium/cmd.dumpCt(0xc000387900, 0x4, 0x4, 0xc0009e3d40, 0x1, 0x1)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_ct_list.go:67 +0x782
goroutine 1 github.com/cilium/cilium/cilium/cmd.glob..func3(0x319d2e0, 0xc0004e7f90, 0x1, 0x1)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_ct_list.go:43 +0x15e
goroutine 1 github.com/spf13/cobra.(*Command).execute(0x319d2e0, 0xc0004e7f60, 0x1, 0x1, 0x319d2e0, 0xc0004e7f60)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
goroutine 1 github.com/spf13/cobra.(*Command).ExecuteC(0x31aa4e0, 0x445dca, 0x31039c0, 0xc000068778)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:950 +0x375
goroutine 1 github.com/spf13/cobra.(*Command).Execute(...)
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:887
goroutine 1 github.com/cilium/cilium/cilium/cmd.Execute()
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/root.go:47 +0x31
goroutine 1 main.main()
goroutine 1     /home/vagrant/go/src/github.com/cilium/cilium/cilium/main.go:22 +0x25
```
edit: added last line

**Comment by aanm** [comment]
@kkourt what's the full output of that stacktrace?

**Comment by kkourt** [comment]
> @kkourt what's the full output of that stacktrace?

Sorry forgot to add the last line  of stderr which I added now. Not sure if you meant that or the stdout as well. Let me know if it was the latter and I will add that as well.

**Comment by aanm** [comment]
@kkourt that's likely caused by https://github.com/cilium/cilium/blob/47059b4b098d6f788b039adb772864b3250c5d0c/pkg/lock/lock_debug.go#L106-L135

which happens if cilium is compiled with the that `lockdebug`.

**Comment by kkourt** [comment]
I see. Thanks @aanm. Closing the issue.
