### ISSUE TITLE
Panic when going through LRP gsg

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#13736]
on step "If you see an error like “request blocked by whitelist-route-regexp” while running requests to the metadata server, then you may need to whitelist the metadata requests by passing the below argument to the kiam-agent Deamonset." I misconfigured kiam and caused it to crash. this somehow triggered Cilium to crash.

logs from failing pods are here:
[panic.log](https://github.com/cilium/cilium/files/5431668/panic.log)
[panic2.log](https://github.com/cilium/cilium/files/5431669/panic2.log)

Based on cursory look at panic stack trace, this was directly caused by crash of kiam pods, which are AFAIU, a policy backend?

Panic stack trace:
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 226 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2250fa0, 0x3a62f30)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x2250fa0, 0x3a62f30)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).notifyPolicyBackendDelete(0xc000a0ec30, 0xc000acb900, 0xc000d547e0)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:442 +0x316
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).deletePolicyBackends(0xc000a0ec30, 0xc000acb900, 0xc000b74770, 0x10, 0xc000b74780, 0x7)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:417 +0x1c5
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePodLocked(0xc000a0ec30, 0xc001228ea0, 0x3a90001)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:266 +0x3af
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePod(0xc000a0ec30, 0xc001228ea0, 0xc001660000)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:285 +0x8e
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).updateK8sPodV1(0xc000661380, 0xc000e6d200, 0xc001228ea0, 0x2739120, 0xc001bf3c00)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:287 +0x402
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).createPodController.func2(0x25a30e0, 0xc000e6d200, 0x25a30e0, 0xc001228ea0)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:88 +0x11f
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:234
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x2283f00, 0xc00025c520, 0x1, 0xc00025c520)
	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:114 +0x31c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000acadc0, 0xc000ab7a80, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x229
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00018f050)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000af8f90)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001bf3f90, 0x29436a0, 0xc0008c9140, 0xc000481d01, 0xc000c7fc80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000af8f90, 0x3b9aca00, 0x0, 0xc000356401, 0xc000c7fc80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc00018f050, 0xc000c7fc80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x2ce
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).podsInit.func1
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:129 +0x36c
```

**Comment by aditighag** [comment]
Looking into it...
