### ISSUE TITLE
tests: consul watcher does not report event

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1388]
The following consul test failure can be observed by running:
```
go test -ldflags "-X "github.com/cilium/cilium/pkg/kvstore".backend=consul" -check.v -test.v -count=100
```

The respective test has been disabled for now but needs to be re-enabled once this has been fixed.

```
20:11:40 ==> cilium-master-build-PR-1384-3: ?   	github.com/cilium/cilium/common/ipam	[no test files]
20:11:40 ==> cilium-master-build-PR-1384-3: ?   	github.com/cilium/cilium/common/plugins	[no test files]
20:11:40 ==> cilium-master-build-PR-1384-3: ?   	github.com/cilium/cilium/common/types	[no test files]
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=info msg="Consul client ready" 
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=info msg="Using consul as key-value store" 
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=debug msg="Starting watcher testWatcher2 list=true..." 
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=debug msg="Stopped watcher testWatcher2" 
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=info msg="Consul client ready" 
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=info msg="Using consul as key-value store" 
20:12:15 ==> cilium-master-build-PR-1384-3: time="2017-08-25T13:11:44-07:00" level=debug msg="Starting watcher testWatcher1 list=false..." 
20:12:15 ==> cilium-master-build-PR-1384-3: panic: test timed out after 30s
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 147 [running]:
20:12:15 ==> cilium-master-build-PR-1384-3: testing.startAlarm.func1()
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:1023 +0xf9
20:12:15 ==> cilium-master-build-PR-1384-3: created by time.goFunc
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/time/sleep.go:170 +0x44
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 1 [chan receive]:
20:12:15 ==> cilium-master-build-PR-1384-3: testing.(*T).Run(0xc4204ead00, 0x1c6b8d2, 0x4, 0x1d0a358, 0xc420577c90)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:698 +0x2f4
20:12:15 ==> cilium-master-build-PR-1384-3: testing.runTests.func1(0xc4204ead00)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:882 +0x67
20:12:15 ==> cilium-master-build-PR-1384-3: testing.tRunner(0xc4204ead00, 0xc420577d50)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:657 +0x96
20:12:15 ==> cilium-master-build-PR-1384-3: testing.runTests(0xc420194420, 0x2a32bc0, 0x1, 0x1, 0xc420577e40)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:888 +0x2c1
20:12:15 ==> cilium-master-build-PR-1384-3: testing.(*M).Run(0xc420577f20, 0xc420577e90)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:822 +0xfc
20:12:15 ==> cilium-master-build-PR-1384-3: main.main()
20:12:15 ==> cilium-master-build-PR-1384-3: 	github.com/cilium/cilium/daemon/_test/_testmain.go:120 +0x1fa
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 17 [syscall, locked to thread]:
20:12:15 ==> cilium-master-build-PR-1384-3: runtime.goexit()
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 20 [chan receive]:
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2ae2240)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/golang/glog/glog.go:882 +0x7a
20:12:15 ==> cilium-master-build-PR-1384-3: created by github.com/cilium/cilium/vendor/github.com/golang/glog.init.1
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/golang/glog/glog.go:410 +0x21d
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 22 [sleep]:
20:12:15 ==> cilium-master-build-PR-1384-3: time.Sleep(0x45d964b800)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/runtime/time.go:59 +0xf9
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/pkg/kvstore.init.1.func1()
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/keepalive.go:65 +0x55
20:12:15 ==> cilium-master-build-PR-1384-3: created by github.com/cilium/cilium/pkg/kvstore.init.1
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/keepalive.go:67 +0x35
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 23 [syscall]:
20:12:15 ==> cilium-master-build-PR-1384-3: os/signal.signal_recv(0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
20:12:15 ==> cilium-master-build-PR-1384-3: os/signal.loop()
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
20:12:15 ==> cilium-master-build-PR-1384-3: created by os/signal.init.1
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 24 [chan receive]:
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*suiteRunner).runTest(0xc4203c5080, 0xc4200eeee0, 0xc420017e00)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:810 +0x61
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*suiteRunner).run(0xc4203c5080, 0x2b02980)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:615 +0xf4
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.Run(0x1a71560, 0x2b02980, 0xc420434fc0, 0x1b96cc0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x4d
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.RunAll(0xc420434fc0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0xed
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.TestingT(0xc4204eadd0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x3f7
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/daemon.Test(0xc4204eadd0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_test.go:29 +0x2b
20:12:15 ==> cilium-master-build-PR-1384-3: testing.tRunner(0xc4204eadd0, 0x1d0a358)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:657 +0x96
20:12:15 ==> cilium-master-build-PR-1384-3: created by testing.(*T).Run
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/testing/testing.go:697 +0x2ca
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 25 [select]:
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc4200b4fc0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:461 +0x443
20:12:15 ==> cilium-master-build-PR-1384-3: created by github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*resultTracker).start
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:441 +0x3f
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 98 [select]:
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/pkg/kvstore.expectEvent(0xc4203ea1e0, 0xc4203da2c0, 0x0, 0x1c713e2, 0x8, 0xc4202eee80, 0x4, 0x8)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/events_tests.go:42 +0x4e3
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/pkg/kvstore.(*KvstoreSuite).TestWatch(0x2b02980, 0xc4203ea1e0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/events_tests.go:68 +0x2de
20:12:15 ==> cilium-master-build-PR-1384-3: reflect.Value.call(0x1a71560, 0x2b02980, 0xa13, 0x1c6b62e, 0x4, 0xc42003af70, 0x1, 0x1, 0x2b044e0, 0x1c39400, ...)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/reflect/value.go:434 +0x91f
20:12:15 ==> cilium-master-build-PR-1384-3: reflect.Value.Call(0x1a71560, 0x2b02980, 0xa13, 0xc420023f70, 0x1, 0x1, 0xc4203ea2d0, 0xc420023f07, 0xc4203f96c0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/reflect/value.go:302 +0xa4
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc4203ea1e0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:772 +0x643
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc4203c5080, 0xc4203ea1e0, 0xc4203bfd40)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:666 +0x7c
20:12:15 ==> cilium-master-build-PR-1384-3: created by github.com/cilium/cilium/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:667 +0x230
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 92 [select]:
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*persistConn).roundTrip(0xc420415e60, 0xc420401c80, 0x0, 0x0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:1898 +0x974
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*Transport).RoundTrip(0xc4203ea3c0, 0xc42031c700, 0xc4203ea3c0, 0x0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:391 +0x74c
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.send(0xc42031c700, 0x2a4ce00, 0xc4203ea3c0, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc4200726d8, 0x411c58)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/client.go:249 +0x162
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*Client).send(0xc42001a300, 0xc42031c700, 0x0, 0x0, 0x0, 0xc4200726d8, 0x0, 0x1, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/client.go:173 +0x108
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*Client).Do(0xc42001a300, 0xc42031c700, 0x2ae1d80, 0x0, 0x20)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/client.go:595 +0x254
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*Client).doRequest(0xc4203a4c60, 0xc42028e320, 0xc4205bbaa0, 0xc4201bfd98, 0xb, 0xc42028e320)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/api.go:368 +0xbc
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*KV).getInternal(0xc4205bbc70, 0x1c6bb6e, 0x4, 0xc42001bb30, 0xc4205bbd88, 0xc420054a20, 0xc420401b20, 0x0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/kv.go:104 +0x238
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*KV).List(0xc4205bbc70, 0x1c6bb6e, 0x4, 0xc4205bbd88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/kv.go:59 +0x151
20:12:15 ==> cilium-master-build-PR-1384-3: github.com/cilium/cilium/pkg/kvstore.(*ConsulClient).Watch.func1(0xc420072590, 0xc4203da2c0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/consul.go:390 +0x10c
20:12:15 ==> cilium-master-build-PR-1384-3: created by github.com/cilium/cilium/pkg/kvstore.(*ConsulClient).Watch
20:12:15 ==> cilium-master-build-PR-1384-3: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/kvstore/consul.go:459 +0x52
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 145 [IO wait]:
20:12:15 ==> cilium-master-build-PR-1384-3: net.runtime_pollWait(0x7fc455f76f80, 0x72, 0x3)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/runtime/netpoll.go:164 +0x59
20:12:15 ==> cilium-master-build-PR-1384-3: net.(*pollDesc).wait(0xc420122308, 0x72, 0x2a50800, 0x2a41cf8)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
20:12:15 ==> cilium-master-build-PR-1384-3: net.(*pollDesc).waitRead(0xc420122308, 0xc4205e6000, 0x1000)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
20:12:15 ==> cilium-master-build-PR-1384-3: net.(*netFD).Read(0xc4201222a0, 0xc4205e6000, 0x1000, 0x1000, 0x0, 0x2a50800, 0x2a41cf8)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
20:12:15 ==> cilium-master-build-PR-1384-3: net.(*conn).Read(0xc4200726e0, 0xc4205e6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/net.go:181 +0x70
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*persistConn).Read(0xc420415e60, 0xc4205e6000, 0x1000, 0x1000, 0x1c736c5, 0xc42047a050, 0xc4205d6b80)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:1316 +0x14b
20:12:15 ==> cilium-master-build-PR-1384-3: bufio.(*Reader).fill(0xc4202b1020)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/bufio/bufio.go:97 +0x117
20:12:15 ==> cilium-master-build-PR-1384-3: bufio.(*Reader).Peek(0xc4202b1020, 0x1, 0xc4202b11a0, 0xc420371c80, 0x1bdce80, 0x0, 0x0)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/bufio/bufio.go:129 +0x67
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*persistConn).readLoop(0xc420415e60)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:1474 +0x196
20:12:15 ==> cilium-master-build-PR-1384-3: created by net/http.(*Transport).dialConn
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:1117 +0xa35
20:12:15 ==> cilium-master-build-PR-1384-3: 
20:12:15 ==> cilium-master-build-PR-1384-3: goroutine 146 [select]:
20:12:15 ==> cilium-master-build-PR-1384-3: net/http.(*persistConn).writeLoop(0xc420415e60)
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:1704 +0x43a
20:12:15 ==> cilium-master-build-PR-1384-3: created by net/http.(*Transport).dialConn
20:12:15 ==> cilium-master-build-PR-1384-3: 	/usr/local/go/src/net/http/transport.go:1118 +0xa5a
20:12:15 ==> cilium-master-build-PR-1384-3: FAIL	github.com/cilium/cilium/daemon	30.078s
20:12:15 ==> cilium-master-build-PR-1384-3: Makefile:43: recipe for target 'tests-consul' failed
20:12:15 ==> cilium-master-build-PR-1384-3: make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
20:12:15 ==> cilium-master-build-PR-1384-3: make: *** [tests-consul] Error 1
20:12:15 The SSH command responded with a non-zero exit status. Vagrant
20:12:15 assumes that this means the command failed. The output for this command
20:12:15 should be in the log above. Please read the output to determine what
20:12:15 went wrong.
```

**Comment by tgraf** [comment]
Issue does not occur in local test runs.

**Comment by tgraf** [comment]
This can be reproduced with:
```
go test -ldflags "-X "github.com/cilium/cilium/pkg/kvstore".backend=consul" -check.v -test.v -count=100
```

It only occurs with consul, it never occurs with etcd.

**Comment by ianvernon** [comment]
@tgraf can this be closed? ```pkg/kvstore/events_tests.go``` doesn't exist anymore in the Cilium repository.
