### ISSUE TITLE
Cilium operators crashing during migration from tunnelled to non-tunnelled (EKS)

### ISSUE THREAD

**Issue by lachlanmunro** [cilium/cilium#13887]
# Bug report

We are looking to move some clusters away from tunneled (vxlan) on EKS, entirely due to issues around webhooks. This is not expected to be a smooth operation so a test cluster was moved, downtime is expected.

During the "migration" the operators seemed to get stuck in a crash loop that required a complete purge of Cilium's CRD's to escape.

I don't have a clean set of reproducible steps, things were tried to right the system, I'm not sure which bits broke it. The below is a best guess from the test. The result was a pair of cilium operators chain crashing through panic:
```
level=info msg="Discovered new CiliumNode custom resource" name=ip-192-168-125-196.eu-west-2.compute.internal subsys=ipam
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 693 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f5e260, 0x3b094f0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1f5e260, 0x3b094f0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs.func1(0xc000d591a0, 0x13, 0xc000d58e80, 0x15, 0x271ede0, 0xc000e68460, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:466 +0xe8
github.com/cilium/cilium/pkg/ipam/types.foreachInterface(0xc000d591a0, 0x13, 0xc000d8b9b0, 0xc000803188, 0x40c6e6, 0xc000f40ba0)
        /go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:364 +0x12b
github.com/cilium/cilium/pkg/ipam/types.(*InstanceMap).ForeachInterface(0xc000992ee0, 0x0, 0x0, 0xc000803188, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:391 +0x22f
github.com/cilium/cilium/pkg/aws/eni.(*InstancesManager).ForeachInstance(0xc0002d1680, 0x0, 0x0, 0xc000803188)
        /go/src/github.com/cilium/cilium/pkg/aws/eni/instances.go:209 +0x86
github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs(0xc000f32800, 0x275ee60, 0xc000116008, 0xc000221650, 0x10, 0xc000f47d60, 0x5555555555555555)
        /go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:458 +0xf0
github.com/cilium/cilium/pkg/ipam.(*Node).recalculate(0xc0002c63c0)
        /go/src/github.com/cilium/cilium/pkg/ipam/node.go:358 +0xb6
github.com/cilium/cilium/pkg/ipam.(*Node).UpdatedResource(0xc0002c63c0, 0xc000f4a000, 0x0)
        /go/src/github.com/cilium/cilium/pkg/ipam/node.go:334 +0x98
github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func1(0xc0000dee00, 0xc000803b60, 0xc000ec6b68, 0xc000f4a000)
        /go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:263 +0x5c
github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update(0xc0000dee00, 0xc000f4a000, 0xc000f4a001)
        /go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:321 +0x183
github.com/cilium/cilium/pkg/ipam.(*NodeManager).Create(0xc0000dee00, 0xc000f4a000, 0xc000f4a000)
        /go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:251 +0x35
main.startSynchronizingCiliumNodes.func1(0x22b2ca0, 0xc000f4a000)
        /go/src/github.com/cilium/cilium/operator/cilium_node.go:53 +0x71
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:218
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1fa53e0, 0xc000f44540, 0x1, 0xc000f44540)
        /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:118 +0x252
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0007800b0, 0xc000e4d2c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:492 +0x235
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00097c500)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:173 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00010df90)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000803f90, 0x2709900, 0xc00098d7a0, 0xc000cd3201, 0xc0000da360)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00010df90, 0x3b9aca00, 0x0, 0xc000344701, 0xc0000da360)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc00097c500, 0xc0000da360)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:144 +0x2a0
created by main.startSynchronizingCiliumNodes
        /go/src/github.com/cilium/cilium/operator/cilium_node.go:87 +0x3dc
level=error msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=error msg="goroutine 693 [running]:" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f5e260, 0x3b094f0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82" subsys=klog
level=error msg="panic(0x1f5e260, 0x3b094f0)" subsys=klog
level=error msg="\t/usr/local/go/src/runtime/panic.go:969 +0x166" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs.func1(0xc000d591a0, 0x13, 0xc000d58e80, 0x15, 0x271ede0, 0xc000e68460, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:466 +0xe8" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam/types.foreachInterface(0xc000d591a0, 0x13, 0xc000d8b9b0, 0xc000803188, 0x40c6e6, 0xc000f40ba0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:364 +0x12b" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam/types.(*InstanceMap).ForeachInterface(0xc000992ee0, 0x0, 0x0, 0xc000803188, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:391 +0x22f" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/aws/eni.(*InstancesManager).ForeachInstance(0xc0002d1680, 0x0, 0x0, 0xc000803188)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/instances.go:209 +0x86" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs(0xc000f32800, 0x275ee60, 0xc000116008, 0xc000221650, 0x10, 0xc000f47d60, 0x5555555555555555)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:458 +0xf0" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam.(*Node).recalculate(0xc0002c63c0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node.go:358 +0xb6" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam.(*Node).UpdatedResource(0xc0002c63c0, 0xc000f4a000, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node.go:334 +0x98" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func1(0xc0000dee00, 0xc000803b60, 0xc000ec6b68, 0xc000f4a000)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:263 +0x5c" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update(0xc0000dee00, 0xc000f4a000, 0xc000f4a001)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:321 +0x183" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Create(0xc0000dee00, 0xc000f4a000, 0xc000f4a000)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:251 +0x35" subsys=klog
level=error msg="main.startSynchronizingCiliumNodes.func1(0x22b2ca0, 0xc000f4a000)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/operator/cilium_node.go:53 +0x71" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:218" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1fa53e0, 0xc000f44540, 0x1, 0xc000f44540)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:118 +0x252" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0007800b0, 0xc000e4d2c0, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:492 +0x235" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00097c500)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:173 +0x40" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00010df90)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000803f90, 0x2709900, 0xc00098d7a0, 0xc000cd3201, 0xc0000da360)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00010df90, 0x3b9aca00, 0x0, 0xc000344701, 0xc0000da360)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.Until(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).Run(0xc00097c500, 0xc0000da360)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:144 +0x2a0" subsys=klog
level=error msg="created by main.startSynchronizingCiliumNodes" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/operator/cilium_node.go:87 +0x3dc" subsys=klog
level=warning msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=warning msg="goroutine 693 [running]:" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f5e260, 0x3b094f0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82" subsys=klog
level=warning msg="panic(0x1f5e260, 0x3b094f0)" subsys=klog
level=warning msg="\t/usr/local/go/src/runtime/panic.go:969 +0x166" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs.func1(0xc000d591a0, 0x13, 0xc000d58e80, 0x15, 0x271ede0, 0xc000e68460, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:466 +0xe8" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam/types.foreachInterface(0xc000d591a0, 0x13, 0xc000d8b9b0, 0xc000803188, 0x40c6e6, 0xc000f40ba0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:364 +0x12b" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam/types.(*InstanceMap).ForeachInterface(0xc000992ee0, 0x0, 0x0, 0xc000803188, 0x0, 0x0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:391 +0x22f" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/aws/eni.(*InstancesManager).ForeachInstance(0xc0002d1680, 0x0, 0x0, 0xc000803188)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/instances.go:209 +0x86" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs(0xc000f32800, 0x275ee60, 0xc000116008, 0xc000221650, 0x10, 0xc000f47d60, 0x5555555555555555)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:458 +0xf0" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam.(*Node).recalculate(0xc0002c63c0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node.go:358 +0xb6" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam.(*Node).UpdatedResource(0xc0002c63c0, 0xc000f4a000, 0x0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node.go:334 +0x98" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func1(0xc0000dee00, 0xc000803b60, 0xc000ec6b68, 0xc000f4a000)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:263 +0x5c" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update(0xc0000dee00, 0xc000f4a000, 0xc000f4a001)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:321 +0x183" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Create(0xc0000dee00, 0xc000f4a000, 0xc000f4a000)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:251 +0x35" subsys=klog
level=warning msg="main.startSynchronizingCiliumNodes.func1(0x22b2ca0, 0xc000f4a000)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/operator/cilium_node.go:53 +0x71" subsys=klog
level=warning msg="k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:218" subsys=klog
level=warning msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1fa53e0, 0xc000f44540, 0x1, 0xc000f44540)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:118 +0x252" subsys=klog
level=warning msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0007800b0, 0xc000e4d2c0, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:492 +0x235" subsys=klog
level=warning msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00097c500)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:173 +0x40" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00010df90)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000803f90, 0x2709900, 0xc00098d7a0, 0xc000cd3201, 0xc0000da360)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00010df90, 0x3b9aca00, 0x0, 0xc000344701, 0xc0000da360)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/wait.Until(...)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90" subsys=klog
level=warning msg="k8s.io/client-go/tools/cache.(*controller).Run(0xc00097c500, 0xc0000da360)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:144 +0x2a0" subsys=klog
level=warning msg="created by main.startSynchronizingCiliumNodes" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/operator/cilium_node.go:87 +0x3dc" subsys=klog
level=info msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=info msg="goroutine 693 [running]:" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f5e260, 0x3b094f0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82" subsys=klog
level=info msg="panic(0x1f5e260, 0x3b094f0)" subsys=klog
level=info msg="\t/usr/local/go/src/runtime/panic.go:969 +0x166" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs.func1(0xc000d591a0, 0x13, 0xc000d58e80, 0x15, 0x271ede0, 0xc000e68460, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:466 +0xe8" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam/types.foreachInterface(0xc000d591a0, 0x13, 0xc000d8b9b0, 0xc000803188, 0x40c6e6, 0xc000f40ba0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:364 +0x12b" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam/types.(*InstanceMap).ForeachInterface(0xc000992ee0, 0x0, 0x0, 0xc000803188, 0x0, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:391 +0x22f" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/aws/eni.(*InstancesManager).ForeachInstance(0xc0002d1680, 0x0, 0x0, 0xc000803188)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/instances.go:209 +0x86" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/aws/eni.(*Node).ResyncInterfacesAndIPs(0xc000f32800, 0x275ee60, 0xc000116008, 0xc000221650, 0x10, 0xc000f47d60, 0x5555555555555555)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:458 +0xf0" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam.(*Node).recalculate(0xc0002c63c0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node.go:358 +0xb6" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam.(*Node).UpdatedResource(0xc0002c63c0, 0xc000f4a000, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node.go:334 +0x98" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func1(0xc0000dee00, 0xc000803b60, 0xc000ec6b68, 0xc000f4a000)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:263 +0x5c" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update(0xc0000dee00, 0xc000f4a000, 0xc000f4a001)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:321 +0x183" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/ipam.(*NodeManager).Create(0xc0000dee00, 0xc000f4a000, 0xc000f4a000)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:251 +0x35" subsys=klog
level=info msg="main.startSynchronizingCiliumNodes.func1(0x22b2ca0, 0xc000f4a000)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/operator/cilium_node.go:53 +0x71" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:218" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1fa53e0, 0xc000f44540, 0x1, 0xc000f44540)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:118 +0x252" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0007800b0, 0xc000e4d2c0, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:492 +0x235" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00097c500)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:173 +0x40" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00010df90)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000803f90, 0x2709900, 0xc00098d7a0, 0xc000cd3201, 0xc0000da360)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00010df90, 0x3b9aca00, 0x0, 0xc000344701, 0xc0000da360)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.Until(...)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.(*controller).Run(0xc00097c500, 0xc0000da360)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:144 +0x2a0" subsys=klog
level=info msg="created by main.startSynchronizingCiliumNodes" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/operator/cilium_node.go:87 +0x3dc" subsys=klog
level=fatal msg="Panic in Kubernetes runtime handler" subsys=k8s
```

**General Information**

- Cilium version: `1.8.5`
- Kernel version: `1.17.11-20201007 eks linux AMI` (nodegroup is AWS managed)
- Orchestration system version in use: `kubernetes 1.17`
- Link to relevant artifacts: [config.zip](https://github.com/cilium/cilium/files/5484836/config.zip)
- Generate and upload a system zip: `last step was a complete purge, this would be useless`

**How to reproduce the issue**

1. Bring up an eks cluster at version 1.17 with eks the `cluster.yaml`
2. Deploy Cilium through helm at version 1.8.5 with `cilium-helm.yaml` (something like `helm install cilium/cilum --version 1.8.5 --namespace kube-system -f cilium-helm.yaml`
3. Change the networking from vxlan with `helm upgrade cilium cilium/cilium --version 1.8.5 --namespace kube-system --set global.eni=true --set config.ipam=eni --set global.egressMasqueradeInterfaces=eth0 --set global.tunnel=disabled --set global.nodeinit.enabled=true`

**Comment by ti-mo** [comment]
Looks like this hasn't been picked up in a few years, and affected a version of Cilium that's no longer supported. We don't seem to have gotten any other similar reports. Closing for now, but feel free to reopen if still relevant.
