### ISSUE TITLE
Cannot build cilium sphinx-rtd-theme on readthedocs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13963]
Readthedocs builds of the documentation have begun failing today with the following error:

```
Collecting git+git://github.com/cilium/sphinx_rtd_theme.git@v0.7 (from -r Documentation/requirements.txt (line 23))
  Cloning git://github.com/cilium/sphinx_rtd_theme.git (to revision v0.7) to /tmp/pip-req-build-b3bwrps1
Requirement already satisfied: alabaster==0.7.12 in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from -r Documentation/requirements.txt (line 1)) (0.7.12)
Collecting Babel==2.6.0
  Downloading Babel-2.6.0-py2.py3-none-any.whl (8.1 MB)
Collecting certifi==2018.10.15
  Downloading certifi-2018.10.15-py2.py3-none-any.whl (146 kB)
Requirement already satisfied: chardet==3.0.4 in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from -r Documentation/requirements.txt (line 4)) (3.0.4)
Collecting docutils==0.14
  Downloading docutils-0.14-py3-none-any.whl (543 kB)
Collecting idna==2.7
  Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting imagesize==1.1.0
  Downloading imagesize-1.1.0-py2.py3-none-any.whl (4.4 kB)
Collecting Jinja2==2.10.1
  Downloading Jinja2-2.10.1-py2.py3-none-any.whl (124 kB)
Collecting jsonschema==2.6.0
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: MarkupSafe==1.1.1 in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from -r Documentation/requirements.txt (line 10)) (1.1.1)
Collecting pyenchant==2.0.0
  Downloading pyenchant-2.0.0.tar.gz (64 kB)
Collecting Pygments==2.4.2
  Downloading Pygments-2.4.2-py2.py3-none-any.whl (883 kB)
Collecting pytz==2018.7
  Downloading pytz-2018.7-py2.py3-none-any.whl (506 kB)
Collecting PyYAML==5.3.1
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting recommonmark==0.4.0
  Downloading recommonmark-0.4.0-py2.py3-none-any.whl (9.4 kB)
Collecting requests==2.20.0
  Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting semver==2.9.0
  Downloading semver-2.9.0-py2.py3-none-any.whl (9.1 kB)
Requirement already satisfied: six==1.15.0 in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from -r Documentation/requirements.txt (line 18)) (1.15.0)
Collecting snowballstemmer==1.2.1
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64 kB)
Collecting Sphinx==1.8.1
  Downloading Sphinx-1.8.1-py2.py3-none-any.whl (3.1 MB)
Collecting sphinx-autobuild==0.7.1
  Downloading sphinx-autobuild-0.7.1.tar.gz (14 kB)
Collecting sphinxcontrib-httpdomain==1.7.0
  Downloading sphinxcontrib_httpdomain-1.7.0-py2.py3-none-any.whl (18 kB)
Collecting sphinxcontrib-openapi==0.3.2
  Downloading sphinxcontrib-openapi-0.3.2.tar.gz (10 kB)
Collecting sphinxcontrib-spelling==4.2.1
  Downloading sphinxcontrib_spelling-4.2.1-py3-none-any.whl (14 kB)
Collecting sphinxcontrib-websupport==1.1.0
  Downloading sphinxcontrib_websupport-1.1.0-py2.py3-none-any.whl (26 kB)
Collecting sphinx-rtd-theme==0.2.4
  Downloading sphinx_rtd_theme-0.2.4-py2.py3-none-any.whl (1.4 MB)
Collecting sphinx-tabs==1.1.13
  Downloading sphinx-tabs-1.1.13.tar.gz (21 kB)
Collecting sphinx-version-warning==1.1.2
  Downloading sphinx_version_warning-1.1.2-py3-none-any.whl (13 kB)
Collecting typing==3.6.6
  Downloading typing-3.6.6-py3-none-any.whl (25 kB)
Collecting urllib3==1.24.2
  Downloading urllib3-1.24.2-py2.py3-none-any.whl (131 kB)
Collecting yamllint==1.22.0
  Downloading yamllint-1.22.0-py2.py3-none-any.whl (58 kB)
Collecting commonmark<=0.5.4
  Downloading CommonMark-0.5.4.tar.gz (120 kB)
Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from Sphinx==1.8.1->-r Documentation/requirements.txt (line 20)) (41.0.1)
Requirement already satisfied: packaging in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from Sphinx==1.8.1->-r Documentation/requirements.txt (line 20)) (20.4)
Collecting watchdog>=0.7.1
  Downloading watchdog-0.10.3.tar.gz (94 kB)
Collecting argh>=0.24.1
  Downloading argh-0.26.2-py2.py3-none-any.whl (30 kB)
Collecting pathtools>=0.1.2
  Downloading pathtools-0.1.2.tar.gz (11 kB)
Collecting tornado>=3.2
  Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)
Collecting port_for==0.3.1
  Downloading port-for-0.3.1.tar.gz (18 kB)
Collecting livereload>=2.3.0
  Downloading livereload-2.6.3.tar.gz (25 kB)
Collecting pathspec>=0.5.3
  Downloading pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages (from packaging->Sphinx==1.8.1->-r Documentation/requirements.txt (line 20)) (2.4.7)
Building wheels for collected packages: pyenchant, PyYAML, sphinx-autobuild, sphinxcontrib-openapi, sphinx-tabs, sphinx-rtd-theme-cilium, commonmark, watchdog, pathtools, port-for, livereload
  Building wheel for pyenchant (setup.py): started
  Building wheel for pyenchant (setup.py): finished with status 'done'
  Created wheel for pyenchant: filename=pyenchant-2.0.0-py2.py3.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp33.pp35-none-any.whl size=71148 sha256=a430504a11b7bf50efe69966d9e17563588adc78887898d4a0f8571b6ef9de38
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/b3/a1/1f/9f401bb462dc2815fad237aa51b7fc9c6ea68760a468a5113f
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=44619 sha256=ec3e4a4fa780f517444ab1d3dd9db9f4140ba377befff50428753493c1763c96
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
  Building wheel for sphinx-autobuild (setup.py): started
  Building wheel for sphinx-autobuild (setup.py): finished with status 'done'
  Created wheel for sphinx-autobuild: filename=sphinx_autobuild-0.7.1-py3-none-any.whl size=10075 sha256=eb335a4d3d1bdcb1b50ecb24955a2364e38f0d81a81d73e773612fc7c9001f3d
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/b5/33/11/03f2a5fbd63cd60617cbb411d619008e8e4e0100aa3b21ecda
  Building wheel for sphinxcontrib-openapi (setup.py): started
  Building wheel for sphinxcontrib-openapi (setup.py): finished with status 'done'
  Created wheel for sphinxcontrib-openapi: filename=sphinxcontrib_openapi-0.3.2-py3-none-any.whl size=6565 sha256=ddf5de84f01ee0fff262239e6c44a85f3c8d7664595b3fcabca07497e2b3f243
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/75/3d/dc/68075e4895dcf2b109f4f6d588024cad1b0bbe85a9ae3c07c4
  Building wheel for sphinx-tabs (setup.py): started
  Building wheel for sphinx-tabs (setup.py): finished with status 'done'
  Created wheel for sphinx-tabs: filename=sphinx_tabs-1.1.13-py3-none-any.whl size=26306 sha256=f5b9a6625a6886cbeae6d5c2eb3af82a064c588f992e56e0164d7b3a2f794257
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/9c/53/06/e584108f8fb84128891d1ca2dda5e1188b8c1c8302da3625b2
  Building wheel for sphinx-rtd-theme-cilium (setup.py): started
  Building wheel for sphinx-rtd-theme-cilium (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b3bwrps1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b3bwrps1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8dkmdv19
       cwd: /tmp/pip-req-build-b3bwrps1/
  Complete output (56 lines):
  running bdist_wheel
  running build
  running build_py
  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  npm WARN deprecated har-validator@5.1.5: this library is no longer supported
  npm ERR! Linux 5.4.0-1031-azure
  npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
  npm ERR! node v8.10.0
  npm ERR! npm  v3.5.2
  npm ERR! code EMISSINGARG
  
  npm ERR! typeerror Error: Missing required argument #1
  npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
  npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
  npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
  npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
  npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
  npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
  npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
  npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
  npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
  npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
  npm ERR! typeerror This is an error with npm itself. Please report this error at:
  npm ERR! typeerror     <http://github.com/npm/npm/issues>
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /tmp/pip-req-build-b3bwrps1/npm-debug.log
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-b3bwrps1/setup.py", line 146, in <module>
      'Topic :: Software Development :: Documentation',
    File "/home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-b3bwrps1/setup.py", line 22, in run
      subprocess.run(['npm', 'install'], check=True)
    File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for sphinx-rtd-theme-cilium
  Running setup.py clean for sphinx-rtd-theme-cilium
  Building wheel for commonmark (setup.py): started
  Building wheel for commonmark (setup.py): finished with status 'done'
  Created wheel for commonmark: filename=CommonMark-0.5.4-py3-none-any.whl size=30752 sha256=318f4f58af081889cfe1986351c7bd4e26c7626bd80c6cd0684f6f78f9a3d9c5
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/d5/28/c7/ce1ffdf847bcfcfa332299c572b26819dc38383180bb5b9072
  Building wheel for watchdog (setup.py): started
  Building wheel for watchdog (setup.py): finished with status 'done'
  Created wheel for watchdog: filename=watchdog-0.10.3-py3-none-any.whl size=73868 sha256=57f79401275a1f8b1275b960e68be5b8824612109264ef378faf9a0299898b2a
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/27/21/35/9d1e531f9de5335147dbef07e9cc99d312525ba128a93d1225
  Building wheel for pathtools (setup.py): started
  Building wheel for pathtools (setup.py): finished with status 'done'
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8785 sha256=2a694cbccc110102596479f50a34fa9db0dd05c12a4c7721ff4ee2373d4251eb
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
  Building wheel for port-for (setup.py): started
  Building wheel for port-for (setup.py): finished with status 'done'
  Created wheel for port-for: filename=port_for-0.3.1-py3-none-any.whl size=19606 sha256=eab7094fef12945551af7658b23e267d6fb5f1731d1e52c285097d786658e6d4
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/a0/3a/de/2fee22649fd79d152f8726b86b9dec6fd35924e71d8e4c2bf2
  Building wheel for livereload (setup.py): started
  Building wheel for livereload (setup.py): finished with status 'done'
  Created wheel for livereload: filename=livereload-2.6.3-py2.py3-none-any.whl size=24713 sha256=71199c242ec1c92b12c8423a5f56f5328a8c499c593f64cb8b3a761f07e2dfce
  Stored in directory: /tmp/pip-ephem-wheel-cache-anh_xbzt/wheels/d4/f2/03/55f37093eb8cb0c89d7efb206f792dba55cd5bd67b1c5b1ce1
Successfully built pyenchant PyYAML sphinx-autobuild sphinxcontrib-openapi sphinx-tabs commonmark watchdog pathtools port-for livereload
Failed to build sphinx-rtd-theme-cilium
Installing collected packages: pytz, Babel, certifi, docutils, idna, imagesize, Jinja2, jsonschema, pyenchant, Pygments, PyYAML, commonmark, recommonmark, urllib3, requests, semver, snowballstemmer, sphinxcontrib-websupport, Sphinx, pathtools, watchdog, argh, tornado, port-for, livereload, sphinx-autobuild, sphinxcontrib-httpdomain, sphinxcontrib-openapi, sphinxcontrib-spelling, sphinx-rtd-theme, sphinx-tabs, sphinx-version-warning, typing, pathspec, yamllint, sphinx-rtd-theme-cilium
  Attempting uninstall: pytz
    Found existing installation: pytz 2020.4
    Uninstalling pytz-2020.4:
      Successfully uninstalled pytz-2020.4
  Attempting uninstall: Babel
    Found existing installation: Babel 2.8.0
    Uninstalling Babel-2.8.0:
      Successfully uninstalled Babel-2.8.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.11.8
    Uninstalling certifi-2020.11.8:
      Successfully uninstalled certifi-2020.11.8
  Attempting uninstall: docutils
    Found existing installation: docutils 0.16
    Uninstalling docutils-0.16:
      Successfully uninstalled docutils-0.16
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: imagesize
    Found existing installation: imagesize 1.2.0
    Uninstalling imagesize-1.2.0:
      Successfully uninstalled imagesize-1.2.0
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 2.11.2
    Uninstalling Jinja2-2.11.2:
      Successfully uninstalled Jinja2-2.11.2
  Attempting uninstall: Pygments
    Found existing installation: Pygments 2.7.2
    Uninstalling Pygments-2.7.2:
      Successfully uninstalled Pygments-2.7.2
  Attempting uninstall: commonmark
    Found existing installation: commonmark 0.8.1
    Uninstalling commonmark-0.8.1:
      Successfully uninstalled commonmark-0.8.1
  Attempting uninstall: recommonmark
    Found existing installation: recommonmark 0.5.0
    Uninstalling recommonmark-0.5.0:
      Successfully uninstalled recommonmark-0.5.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.11
    Uninstalling urllib3-1.25.11:
      Successfully uninstalled urllib3-1.25.11
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
  Attempting uninstall: snowballstemmer
    Found existing installation: snowballstemmer 2.0.0
    Uninstalling snowballstemmer-2.0.0:
      Successfully uninstalled snowballstemmer-2.0.0
  Attempting uninstall: sphinxcontrib-websupport
    Found existing installation: sphinxcontrib-websupport 1.2.4
    Uninstalling sphinxcontrib-websupport-1.2.4:
      Successfully uninstalled sphinxcontrib-websupport-1.2.4
  Attempting uninstall: Sphinx
    Found existing installation: Sphinx 1.8.5
    Uninstalling Sphinx-1.8.5:
      Successfully uninstalled Sphinx-1.8.5
  Attempting uninstall: sphinx-rtd-theme
    Found existing installation: sphinx-rtd-theme 0.4.3
    Uninstalling sphinx-rtd-theme-0.4.3:
      Successfully uninstalled sphinx-rtd-theme-0.4.3
    Running setup.py install for sphinx-rtd-theme-cilium: started
    Running setup.py install for sphinx-rtd-theme-cilium: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b3bwrps1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b3bwrps1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2zb0ks_/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/include/site/python3.7/sphinx-rtd-theme-cilium
         cwd: /tmp/pip-req-build-b3bwrps1/
    Complete output (58 lines):
    running install
    running build
    running build_py
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm ERR! Linux 5.4.0-1031-azure
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v8.10.0
    npm ERR! npm  v3.5.2
    npm ERR! code EMISSINGARG
    
    npm ERR! typeerror Error: Missing required argument #1
    npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
    npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
    npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
    npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
    npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
    npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
    npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
    npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
    npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
    npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
    npm ERR! typeerror This is an error with npm itself. Please report this error at:
    npm ERR! typeerror     <http://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/pip-req-build-b3bwrps1/npm-debug.log
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-b3bwrps1/setup.py", line 146, in <module>
        'Topic :: Software Development :: Documentation',
      File "/home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-b3bwrps1/setup.py", line 22, in run
        subprocess.run(['npm', 'install'], check=True)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b3bwrps1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b3bwrps1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r2zb0ks_/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/cilium/envs/latest/include/site/python3.7/sphinx-rtd-theme-cilium Check the logs for full command output.
Command time: 56s Return: 1
```

**Comment by fristonio** [comment]
It seems like we are hitting this - https://github.com/npm/cli/issues/681
I am not really sure in which docker build this is failing though. Maybe we can try by updating npm version in the image?

**Comment by fristonio** [comment]
Fixed in https://github.com/cilium/sphinx_rtd_theme/pull/13

**Comment by edgarriba** [comment]
this error still happens to me - I fixed with @frisso patch but would be great to see that working in sphinx_rtd_theme` master. Is there any reason or workaround from readthedocs side to fix that ?

**Comment by joestringer** [comment]
@edgarriba as per the description inside the patch, it seems like at least at the time of solving this issue in `cilium/sphinx_rtd_theme`, readthedocs only provided a very old version of npm which triggered the issue; as far as I can tell when this occurred, they had also started locking down security inside their environments more tightly to prevent installing npm in directories on the host. You're welcome to propose a similar change to the upstream sphinx_rtd_theme repository or see whether RTD are planning to bump the OS versions / NPM versions available on their workers.
