### ISSUE TITLE
cilium config segfaults

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1429]
`cilium config` seems to segfault.

Observed in:
https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-1425/1/execution/node/28/log/?consoleFull

```
18:44:06 ==> cilium-master-build-PR-1425-1: + cilium config
18:44:06 ==> cilium-master-build-PR-1425-1: Conntrack                Enabled
18:44:06 ==> cilium-master-build-PR-1425-1: ConntrackAccounting      Enabled
18:44:06 ==> cilium-master-build-PR-1425-1: ConntrackLocal           Disabled
18:44:06 ==> cilium-master-build-PR-1425-1: Debug                    Enabled
18:44:06 ==> cilium-master-build-PR-1425-1: DropNotification         Enabled
18:44:06 ==> cilium-master-build-PR-1425-1: PolicyTracing            Disabled
18:44:06 ==> cilium-master-build-PR-1425-1: k8s-configuration        
18:44:06 ==> cilium-master-build-PR-1425-1: k8s-endpoint             
18:44:06 ==> cilium-master-build-PR-1425-1: PolicyEnforcement        default
18:44:06 ==> cilium-master-build-PR-1425-1: panic: runtime error: invalid memory address or nil pointer dereference
18:44:06 ==> cilium-master-build-PR-1425-1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1557ef9]
18:44:06 ==> cilium-master-build-PR-1425-1: 
18:44:06 ==> cilium-master-build-PR-1425-1: goroutine 1 [running]:
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.configDaemon(0x252d960, 0x2af4e08, 0x0, 0x0)
18:44:06 ==> cilium-master-build-PR-1425-1: 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/config.go:90 +0x8c9
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.glob..func8(0x252d960, 0x2af4e08, 0x0, 0x0)
18:44:06 ==> cilium-master-build-PR-1425-1: 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/config.go:46 +0x1d1
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x252d960, 0x2af4e08, 0x0, 0x0, 0x252d960, 0x2af4e08)
18:44:06 ==> cilium-master-build-PR-1425-1: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x231
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x252bdc0, 0xc420060058, 0x0, 0x1)
18:44:06 ==> cilium-master-build-PR-1425-1: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x339
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x252bdc0, 0x16d8340, 0xc4215a7e60)
18:44:06 ==> cilium-master-build-PR-1425-1: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.Execute()
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/root.go:68 +0x31
18:44:06 ==> cilium-master-build-PR-1425-1: main.main()
18:44:06 ==> cilium-master-build-PR-1425-1: 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/main.go:20 +0x20
18:44:06 ==> cilium-master-build-PR-1425-1: eval ${CFG_CMD}
18:44:06 ==> cilium-master-build-PR-1425-1: ++ eval cilium config '|' grep PolicyEnforcement '|' awk ''\''{print' '$2}'\'''
18:44:06 ==> cilium-master-build-PR-1425-1: cilium config | grep PolicyEnforcement | awk '{print $2}'
18:44:06 ==> cilium-master-build-PR-1425-1: +++ cilium config
18:44:06 ==> cilium-master-build-PR-1425-1: +++ grep PolicyEnforcement
18:44:06 ==> cilium-master-build-PR-1425-1: +++ awk '{print $2}'
18:44:06 ==> cilium-master-build-PR-1425-1: panic: 
18:44:06 ==> cilium-master-build-PR-1425-1: runtime error: invalid memory address or nil pointer dereference
18:44:06 ==> cilium-master-build-PR-1425-1: [signal 
18:44:06 ==> cilium-master-build-PR-1425-1: SIGSEGV: segmentation violation
18:44:06 ==> cilium-master-build-PR-1425-1:  code=
18:44:06 ==> cilium-master-build-PR-1425-1: 0x1
18:44:06 ==> cilium-master-build-PR-1425-1:  addr=
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1:  pc=
18:44:06 ==> cilium-master-build-PR-1425-1: 0x1557ef9
18:44:06 ==> cilium-master-build-PR-1425-1: ]
18:44:06 ==> cilium-master-build-PR-1425-1: goroutine 
18:44:06 ==> cilium-master-build-PR-1425-1: 1
18:44:06 ==> cilium-master-build-PR-1425-1:  [
18:44:06 ==> cilium-master-build-PR-1425-1: running
18:44:06 ==> cilium-master-build-PR-1425-1: ]:
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.configDaemon
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/config.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 90
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x8c9
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.glob..func8
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/config.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 46
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x1d1
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 648
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x231
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: 0x252bdc0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0xc420060058
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x1
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 735
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x339
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: 0x252bdc0
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0x16d8340
18:44:06 ==> cilium-master-build-PR-1425-1: , 
18:44:06 ==> cilium-master-build-PR-1425-1: 0xc4215a9e60
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 693
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x2b
18:44:06 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.Execute
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/root.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 68
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x31
18:44:06 ==> cilium-master-build-PR-1425-1: main.main
18:44:06 ==> cilium-master-build-PR-1425-1: (
18:44:06 ==> cilium-master-build-PR-1425-1: )
18:44:06 ==> cilium-master-build-PR-1425-1: 	
18:44:06 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/main.go
18:44:06 ==> cilium-master-build-PR-1425-1: :
18:44:06 ==> cilium-master-build-PR-1425-1: 20
18:44:06 ==> cilium-master-build-PR-1425-1:  +
18:44:06 ==> cilium-master-build-PR-1425-1: 0x20
18:44:06 ==> cilium-master-build-PR-1425-1: + POLICY_ENFORCED=default
18:44:06 ==> cilium-master-build-PR-1425-1: + for line in '$POLICY_ENFORCED'
18:44:06 ==> cilium-master-build-PR-1425-1: + [[ default != \d\e\f\a\u\l\t ]]
18:44:06 ==> cilium-master-build-PR-1425-1: + echo '------ setting cilium agent PolicyEnforcement=always'
18:44:06 ==> cilium-master-build-PR-1425-1: ------ setting cilium agent PolicyEnforcement=always
18:44:06 ==> cilium-master-build-PR-1425-1: + cilium config PolicyEnforcement=always
18:44:08 ==> cilium-master-build-PR-1425-1: ------ checking if cilium daemon has policy enforcement enabled ------
18:44:08 ==> cilium-master-build-PR-1425-1: + check_config_policy_enabled
18:44:08 ==> cilium-master-build-PR-1425-1: + echo '------ checking if cilium daemon has policy enforcement enabled ------'
18:44:08 ==> cilium-master-build-PR-1425-1: + cilium config
18:44:08 ==> cilium-master-build-PR-1425-1: Conntrack                Enabled
18:44:08 ==> cilium-master-build-PR-1425-1: ConntrackAccounting      Enabled
18:44:08 ==> cilium-master-build-PR-1425-1: ConntrackLocal           Disabled
18:44:08 ==> cilium-master-build-PR-1425-1: Debug                    Enabled
18:44:08 ==> cilium-master-build-PR-1425-1: DropNotification         Enabled
18:44:08 ==> cilium-master-build-PR-1425-1: PolicyTracing            Disabled
18:44:08 ==> cilium-master-build-PR-1425-1: k8s-configuration        
18:44:08 ==> cilium-master-build-PR-1425-1: k8s-endpoint             
18:44:08 ==> cilium-master-build-PR-1425-1: PolicyEnforcement        always
18:44:08 ==> cilium-master-build-PR-1425-1: panic: 
18:44:08 ==> cilium-master-build-PR-1425-1: runtime error: invalid memory address or nil pointer dereference
18:44:08 ==> cilium-master-build-PR-1425-1: [signal 
18:44:08 ==> cilium-master-build-PR-1425-1: SIGSEGV: segmentation violation
18:44:08 ==> cilium-master-build-PR-1425-1:  code=
18:44:08 ==> cilium-master-build-PR-1425-1: 0x1
18:44:08 ==> cilium-master-build-PR-1425-1:  addr=
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1:  pc=
18:44:08 ==> cilium-master-build-PR-1425-1: 0x1557ef9
18:44:08 ==> cilium-master-build-PR-1425-1: ]
18:44:08 ==> cilium-master-build-PR-1425-1: goroutine 
18:44:08 ==> cilium-master-build-PR-1425-1: 1
18:44:08 ==> cilium-master-build-PR-1425-1:  [
18:44:08 ==> cilium-master-build-PR-1425-1: running
18:44:08 ==> cilium-master-build-PR-1425-1: ]:
18:44:08 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.configDaemon
18:44:08 ==> cilium-master-build-PR-1425-1: (
18:44:08 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1: )
18:44:08 ==> cilium-master-build-PR-1425-1: 	
18:44:08 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/config.go
18:44:08 ==> cilium-master-build-PR-1425-1: :
18:44:08 ==> cilium-master-build-PR-1425-1: 90
18:44:08 ==> cilium-master-build-PR-1425-1:  +
18:44:08 ==> cilium-master-build-PR-1425-1: 0x8c9
18:44:08 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/cilium/cmd.glob..func8
18:44:08 ==> cilium-master-build-PR-1425-1: (
18:44:08 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1: )
18:44:08 ==> cilium-master-build-PR-1425-1: 	
18:44:08 ==> cilium-master-build-PR-1425-1: /home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/config.go
18:44:08 ==> cilium-master-build-PR-1425-1: :
18:44:08 ==> cilium-master-build-PR-1425-1: 46
18:44:08 ==> cilium-master-build-PR-1425-1:  +
18:44:08 ==> cilium-master-build-PR-1425-1: 0x1d1
18:44:08 ==> cilium-master-build-PR-1425-1: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute
18:44:08 ==> cilium-master-build-PR-1425-1: (
18:44:08 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x0
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x252d960
18:44:08 ==> cilium-master-build-PR-1425-1: , 
18:44:08 ==> cilium-master-build-PR-1425-1: 0x2af4e08
18:44:08 ==> cilium-master-build-PR-1425-1: )
18:44:08 ==> cilium-master-build-PR-1425-1: 
```

**Comment by aalemayhu** [comment]
Hmm, I thought I had fixed it by setting a default value. One quick fix is to do a null check[0] but probably better to make `.State()` return a default value when `nm.state` is nil.

[0]:
```
diff --git a/cilium/cmd/config.go b/cilium/cmd/config.go                                                  
index f373fbe79da4..84c28bcb7a68 100644              
--- a/cilium/cmd/config.go                           
+++ b/cilium/cmd/config.go                           
@@ -87,7 +87,9 @@ func configDaemon(cmd *cobra.Command, opts []string) {                                  
                fmt.Printf("%-24s %s\n", "k8s-configuration", resp.K8sConfiguration)                      
                fmt.Printf("%-24s %s\n", "k8s-endpoint", resp.K8sEndpoint)                                
                fmt.Printf("%-24s %s\n", "PolicyEnforcement", resp.PolicyEnforcement)                     
-               fmt.Printf("%-24s %d\n", "MonitorNumPages", resp.NodeMonitor.Npages)                      
+               if resp.NodeMonitor != nil {         
+                       fmt.Printf("%-24s %d\n", "MonitorNumPages", resp.NodeMonitor.Npages)              
+               }                                    
                return                               
        }  
```

**Comment by tgraf** [comment]
> Hmm, I thought I had fixed it by setting a default value. One quick fix is to do a null check[0] but probably better to make .State() return a default value when nm.state is nil.

Given that `NodeMonitor` is a pointer. We should always check for non `nil` before accessing it.

```
type DaemonConfigurationResponse struct {
...
        // Status of the node monitor
        NodeMonitor *MonitorStatus `json:"nodeMonitor,omitempty"`
```
