### ISSUE TITLE
Cilium Operator panics when creating a CCNP with large list of CIDR for egress deny

### ISSUE THREAD

**Issue by ipochi** [cilium/cilium#14373]
## Bug report

**General Information**

- Cilium version (run `cilium version`) - v1.9.0
- Kernel version (run `uname -a`) - 5.9.11
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) Kubernetes v1.19.4
- Link to relevant artifacts (policies, deployments scripts, ...)

How to reproduce the issue:

1. Create a CCNP with 50000 CIDR entries for egress deny (i.e two polices one to allow all and other having a specific list of CIDRs to deny).
2. Apply policies. Policies get created, but Cilium operator crashes and goes into `CrashLoopBackOff`.

Error log:

```
level=info msg="Skipped reading configuration file" reason="Config File \"cilium-operators\" Not Found in \"[/]\"" subsys=config
level=info msg="  --cilium-endpoint-gc-interval='1m0s'" subsys=cilium-operator-generic
level=info msg="  --cluster-id='0'" subsys=cilium-operator-generic
level=info msg="  --cluster-name='default'" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv4-cidr='10.0.0.0/8'" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv4-mask-size='24'" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv6-cidr=''" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv6-mask-size='112'" subsys=cilium-operator-generic
level=info msg="  --cmdref=''" subsys=cilium-operator-generic
level=info msg="  --cnp-node-status-gc-interval='2m0s'" subsys=cilium-operator-generic
level=info msg="  --cnp-status-update-interval='1s'" subsys=cilium-operator-generic
level=info msg="  --config=''" subsys=cilium-operator-generic
level=info msg="  --config-dir='/tmp/cilium/config-map'" subsys=cilium-operator-generic
level=info msg="  --crd-wait-timeout='5m0s'" subsys=cilium-operator-generic
level=info msg="  --debug='false'" subsys=cilium-operator-generic
level=info msg="  --disable-cnp-status-updates='false'" subsys=cilium-operator-generic
level=info msg="  --disable-endpoint-crd='false'" subsys=cilium-operator-generic
level=info msg="  --enable-ipv4='true'" subsys=cilium-operator-generic
level=info msg="  --enable-ipv6='false'" subsys=cilium-operator-generic
level=info msg="  --enable-k8s-api-discovery='false'" subsys=cilium-operator-generic
level=info msg="  --enable-k8s-endpoint-slice='true'" subsys=cilium-operator-generic
level=info msg="  --enable-k8s-event-handover='false'" subsys=cilium-operator-generic
level=info msg="  --enable-metrics='false'" subsys=cilium-operator-generic
level=info msg="  --identity-allocation-mode='crd'" subsys=cilium-operator-generic
level=info msg="  --identity-gc-interval='15m0s'" subsys=cilium-operator-generic
level=info msg="  --identity-gc-rate-interval='1m0s'" subsys=cilium-operator-generic
level=info msg="  --identity-gc-rate-limit='2500'" subsys=cilium-operator-generic
level=info msg="  --identity-heartbeat-timeout='30m0s'" subsys=cilium-operator-generic
level=info msg="  --ipam='cluster-pool'" subsys=cilium-operator-generic
level=info msg="  --k8s-api-server=''" subsys=cilium-operator-generic
level=info msg="  --k8s-heartbeat-timeout='30s'" subsys=cilium-operator-generic
level=info msg="  --k8s-kubeconfig-path=''" subsys=cilium-operator-generic
level=info msg="  --k8s-namespace='kube-system'" subsys=cilium-operator-generic
level=info msg="  --k8s-service-proxy-name=''" subsys=cilium-operator-generic
level=info msg="  --kvstore=''" subsys=cilium-operator-generic
level=info msg="  --kvstore-opt='map[]'" subsys=cilium-operator-generic
level=info msg="  --leader-election-lease-duration='15s'" subsys=cilium-operator-generic
level=info msg="  --leader-election-renew-deadline='10s'" subsys=cilium-operator-generic
level=info msg="  --leader-election-retry-period='2s'" subsys=cilium-operator-generic
level=info msg="  --limit-ipam-api-burst='4'" subsys=cilium-operator-generic
level=info msg="  --limit-ipam-api-qps='20'" subsys=cilium-operator-generic
level=info msg="  --log-driver=''" subsys=cilium-operator-generic
level=info msg="  --log-opt='map[]'" subsys=cilium-operator-generic
level=info msg="  --nodes-gc-interval='2m0s'" subsys=cilium-operator-generic
level=info msg="  --operator-api-serve-addr='127.0.0.1:9234'" subsys=cilium-operator-generic
level=info msg="  --operator-prometheus-serve-addr=':6942'" subsys=cilium-operator-generic
level=info msg="  --parallel-alloc-workers='50'" subsys=cilium-operator-generic
level=info msg="  --subnet-ids-filter=''" subsys=cilium-operator-generic
level=info msg="  --subnet-tags-filter='[]'" subsys=cilium-operator-generic
level=info msg="  --synchronize-k8s-nodes='true'" subsys=cilium-operator-generic
level=info msg="  --synchronize-k8s-services='true'" subsys=cilium-operator-generic
level=info msg="  --unmanaged-pod-watcher-interval='15'" subsys=cilium-operator-generic
level=info msg="  --version='false'" subsys=cilium-operator-generic
level=info msg="Cilium Operator 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64" subsys=cilium-operator-generic
level=info msg="Starting apiserver on address 127.0.0.1:9234" subsys=cilium-operator-generic
level=info msg="Establishing connection to apiserver" host="https://10.3.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumNode/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumExternalWorkload/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumIdentity/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumLocalRedirectPolicy/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumEndpoint/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumExternalWorkload/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumIdentity/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNode/v2 subsys=k8s
level=info msg="Throttling request took 1.079692543s, request: GET:https://10.3.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/ciliumlocalredirectpolicies.cilium.io" subsys=klog
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumLocalRedirectPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumEndpoint/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="attempting to acquire leader lease  kube-system/cilium-operator-resource-lock..." subsys=klog
level=info msg="successfully acquired lease kube-system/cilium-operator-resource-lock" subsys=klog
level=info msg="Leading the operator HA deployment" subsys=cilium-operator-generic
level=info msg="Initializing IPAM" mode=cluster-pool subsys=cilium-operator-generic
level=info msg="Starting ClusterPool IP allocator" ipv4CIDRs="[10.0.0.0/8]" ipv6CIDRs="[]" subsys=ipam-allocator-clusterpool
level=info msg="Starting to synchronize CiliumNode custom resources..." subsys=cilium-operator-generic
level=info msg="Starting to garbage collect stale CiliumEndpoint custom resources..." subsys=cilium-operator-generic
level=info msg="Starting CRD identity garbage collector with 15m0s interval..." subsys=cilium-operator-generic
level=info msg="Starting CNP derivative handler..." subsys=cilium-operator-generic
level=info msg="Starting CCNP derivative handler..." subsys=cilium-operator-generic
level=info msg="Initialization complete" subsys=cilium-operator-generic
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 502 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c991a0, 0x2f5c350)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1c991a0, 0x2f5c350)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cilium/cilium/pkg/k8s.ConvertToCCNP(0x1f0afc0, 0xc000ff2500, 0x18, 0x1c2c360)
	/go/src/github.com/cilium/cilium/pkg/k8s/factory_functions.go:486 +0xfa
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1cbb580, 0xc000be2640, 0x1, 0xc000be2640)
	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:99 +0x466
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0002e7ea0, 0xc0002093c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x229
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00099dc20)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000635f90)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000185f90, 0x2199480, 0xc0008b9890, 0xc000057201, 0xc0000fc3c0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000635f90, 0x3b9aca00, 0x0, 0xc00150a701, 0xc0000fc3c0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc00099dc20, 0xc0000fc3c0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x2ce
created by main.enableCCNPWatcher
	/go/src/github.com/cilium/cilium/operator/ccnp_event.go:139 +0x45a
level=error msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=error msg="goroutine 502 [running]:" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c991a0, 0x2f5c350)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89" subsys=klog
level=error msg="panic(0x1c991a0, 0x2f5c350)" subsys=klog
level=error msg="\t/usr/local/go/src/runtime/panic.go:969 +0x1b9" subsys=klog
level=warning msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=warning msg="goroutine 502 [running]:" subsys=klog
level=warning msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c991a0, 0x2f5c350)" subsys=klog
level=warning msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6" subsys=klog
level=info msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=info msg="goroutine 502 [running]:" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1c991a0, 0x2f5c350)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89" subsys=klog
level=info msg="panic(0x1c991a0, 0x2f5c350)" subsys=klog
level=info msg="\t/usr/local/go/src/runtime/panic.go:969 +0x1b9" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/k8s.ConvertToCCNP(0x1f0afc0, 0xc000ff2500, 0x18, 0x1c2c360)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/factory_functions.go:486 +0xfa" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1cbb580, 0xc000be2640, 0x1, 0xc000be2640)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:99 +0x466" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0002e7ea0, 0xc0002093c0, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x229" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00099dc20)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x42" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000635f90)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000185f90, 0x2199480, 0xc0008b9890, 0xc000057201, 0xc0000fc3c0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000635f90, 0x3b9aca00, 0x0, 0xc00150a701, 0xc0000fc3c0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98" subsys=klog
level=info msg="k8s.io/apimachinery/pkg/util/wait.Until(...)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90" subsys=klog
level=info msg="k8s.io/client-go/tools/cache.(*controller).Run(0xc00099dc20, 0xc0000fc3c0)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x2ce" subsys=klog
level=info msg="created by main.enableCCNPWatcher" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/operator/ccnp_event.go:139 +0x45a" subsys=klog
level=fatal msg="Panic in Kubernetes runtime handler" subsys=k8s
level=warning msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
```

**Comment by aanm** [comment]
@ipochi do you have the CCNP as well?
