### ISSUE TITLE
CI: Segfault in helpers.(*Kubectl).GetAllPods

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14796]
We've hit a segfault in our ginkgo code in v1.9:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3943/execution/node/158/log/

```
11:11:21  11:11:11 STEP: Running BeforeAll block for EntireTestsuite K8sHubbleTest
11:11:21  11:11:12 STEP: Ensuring the namespace kube-system exists
11:12:18  FAIL: Cannot connect to k8s cluster, output:
11:12:18  
11:12:18  11:12:12 STEP: Running JustAfterEach block for EntireTestsuite K8sHubbleTest
11:12:18  ===================== TEST FAILED =====================
11:12:18  11:12:12 STEP: Running AfterFailed block for EntireTestsuite K8sHubbleTest
11:12:18  panic: runtime error: invalid memory address or nil pointer dereference
11:12:18  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1999394]
11:12:18  
11:12:18  goroutine 60 [running]:
11:12:18  github.com/cilium/cilium/test/helpers.(*Kubectl).GetAllPods(0x0, 0x234d680, 0xc000afc1e0, 0xc0005caecf, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
11:12:18  	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:966 +0x194
11:12:18  github.com/cilium/cilium/test/helpers.(*Kubectl).GeneratePodLogGatheringCommands(0x0, 0x234d680, 0xc000afc1e0, 0xc0005cbcc0)
11:12:18  	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:3583 +0x9c
11:12:18  github.com/cilium/cilium/test/helpers.(*Kubectl).GatherLogs(0x0, 0x234d680, 0xc000afc1e0)
11:12:18  	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:3547 +0x9ca
11:12:18  github.com/cilium/cilium/test/helpers.(*Kubectl).CiliumReport.func1(0xc00011cc50, 0x0, 0x234d680, 0xc000afc1e0)
11:12:18  	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:3165 +0x6b
11:12:18  created by github.com/cilium/cilium/test/helpers.(*Kubectl).CiliumReport
11:12:18  	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:3163 +0x125
```

**Comment by pchaigno** [comment]
There's not enough information to fix. I should have attached the sysdump.
