### ISSUE TITLE
lbmap: Segfault when disabling IPv6 after adding IPv6 services

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15000]
I was running `K8sService` test suite on the latest master, and then when an unrelated test case failed (I was holding the env), I disabled the IPv6 support by setting `enable-ipv6: false` via `ks edit cm cilium-config`. Afterwards, I restarted cilium pods and they failed to come up due to the following:
```
level=debug msg="Kubernetes service definition changed" action=service-updated endpoints= k8sNamespace=default k8sSvcName=test-nodeport-local-k8s2-ipv6 old-service=nil service="frontend:fd03::bb4/ports=[tftp http]/selector=map[zgroup:test-k8s2]" subsys=k8s-watcher
level=debug msg="Upserting service" backends="[]" loadBalancerSourceRanges="[]" serviceIP="{fd03::bb4 {TCP 10080} 0}" serviceName=test-nodeport-local-k8s2-ipv6 serviceNamespace=default sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Local svcType=ClusterIP
level=debug msg="Resolving service" l3n4Addr="{IP:fd03::bb4 L4Addr:{Protocol:TCP Port:10080} Scope:0}" subsys=service
level=debug msg="Acquired service ID" backends="[]" loadBalancerSourceRanges="[]" serviceID=33 serviceIP="{fd03::bb4 {TCP 10080} 0}" serviceName=test-nodeport-local-k8s2-ipv6 serviceNamespace=default sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcHealthCheckNodePort=0 svcTrafficPolicy=Local svcType=ClusterIP
level=debug msg="Deleting backends from session affinity match" backends="[]" serviceID=33 subsys=service
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cd5900]

goroutine 147 [running]:
github.com/cilium/cilium/pkg/bpf.(*Map).OpenOrCreate(0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:464 +0x40
github.com/cilium/cilium/pkg/maps/lbmap.updateRevNatLocked(0x2b1b5a0, 0xc000b365fc, 0x2b07380, 0xc000ae7e80, 0xc000b365f0, 0x1)
        /go/src/github.com/cilium/cilium/pkg/maps/lbmap/lbmap.go:331 +0x68
github.com/cilium/cilium/pkg/maps/lbmap.(*LBBPFMap).UpsertService(0xc0009f5040, 0xc000b3a1e0, 0x0, 0xc000b47470)
        /go/src/github.com/cilium/cilium/pkg/maps/lbmap/lbmap.go:130 +0x5b7
github.com/cilium/cilium/pkg/service.(*Service).upsertServiceIntoLBMaps(0xc00065a280, 0xc00066b420, 0x421e500, 0x0, 0x421e540, 0x0, 0x0, 0x421e540, 0x0, 0x0, ...)
        /go/src/github.com/cilium/cilium/pkg/service/service.go:749 +0x3de
github.com/cilium/cilium/pkg/service.(*Service).UpsertService(0xc00065a280, 0xc000661a40, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/service/service.go:324 +0xc85
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addK8sSVCs(0xc000974480, 0xc0009a34c0, 0x1d, 0xc0009b2a96, 0x7, 0x0, 0xc000b22f30, 0xc00012be48, 0x10, 0x7ffff7fb9108)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:743 +0x47b
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler.func1(0x0, 0xc0009a34c0, 0x1d, 0xc0009b2a96, 0x7, 0xc000b22f30, 0x0, 0xc00012be48, 0xc0009b0390)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:447 +0xbc7
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler(0xc000974480)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:490 +0x95
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).RunK8sServiceHandler
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:495 +0x3f
```

Previously, the test cases provisioned the IPv6 services.

**Comment by pchaigno** [comment]
That same segfault is blocking https://github.com/cilium/cilium/pull/14543. I'll try to have a look in the afternoon.

**Comment by pchaigno** [comment]
This bug seems to have been introduced by https://github.com/cilium/cilium/pull/14607 and therefore probably affects v1.9.4 as well.

**Comment by pchaigno** [comment]
@brb @fristonio Should we return early in `upsertServiceIntoLBMaps` if we detect it's an IPv6 service but IPv6 is disabled (or the other way around)? https://github.com/cilium/cilium/blob/2b9485df05ec24fe051684ce992a82dabd0b9e56/pkg/service/service.go#L666
The problem here is that we panic when we try to add the backend for the IPv6 service while IPv6 is disabled.

**Comment by brb** [comment]
> This bug seems to have been introduced by #14607 and therefore probably affects v1.9.4 as well.

/cc @christarazi 

> Should we return early in upsertServiceIntoLBMaps

Makes sense, just that I'd return even earlier to avoid wasting resources for unnecessary steps - https://github.com/cilium/cilium/blob/2b9485df05ec24fe051684ce992a82dabd0b9e56/pkg/service/service.go#L248.
