### ISSUE TITLE
CI: Travis: Hubble Relay TestPeerManager close of closed channel

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#15442]
## CI failure

Seems to be a flake:

```
== RUN   TestPeerManager/empty_pool
panic: close of closed channel

goroutine 12 [running]:
github.com/cilium/cilium/pkg/hubble/relay/pool.TestPeerManager.func1.1.1.1()
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager_test.go:63 +0x2d
sync.(*Once).doSlow(0xc0002c0f90, 0xc000413da8)
	/home/travis/.gimme/versions/go1.16.2.linux.amd64/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/home/travis/.gimme/versions/go1.16.2.linux.amd64/src/sync/once.go:59
github.com/cilium/cilium/pkg/hubble/relay/pool.TestPeerManager.func1.1.1(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager_test.go:63 +0x85
github.com/cilium/cilium/pkg/hubble/testutils.(*FakePeerNotifyClient).Recv(0xc00056c240, 0xc000102de0, 0xc0002b2200, 0xc0000c1e00)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/testutils/fake.go:127 +0x3c
github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).watchNotifications(0xc0002b9860)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:125 +0x7b6
github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).Start.func1(0xc0002b9860)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:74 +0x5a
created by github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).Start
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:72 +0x67
FAIL	github.com/cilium/cilium/pkg/hubble/relay/pool	0.043s
FAIL
make: *** [Makefile:211: unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

https://travis-ci.com/github/cilium/cilium/jobs/493007418

**Comment by christarazi** [comment]
Seen again in https://github.com/cilium/cilium/pull/15441

**Comment by gandro** [comment]
Hit again in https://github.com/cilium/cilium/pull/16521

```
=== RUN   TestPeerManager/empty_pool
=== RUN   TestPeerManager/1_peer_without_IP_address
=== RUN   TestPeerManager/1_unreachable_peer
=== RUN   TestPeerManager/1_reachable_peer
=== RUN   TestPeerManager/1_peer_is_deleted

panic: close of closed channel

goroutine 41 [running]:

github.com/cilium/cilium/pkg/hubble/relay/pool.TestPeerManager.func7.1.1(0x40000619e0, 0x0, 0x4000061900)

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager_test.go:255 +0x88

github.com/cilium/cilium/pkg/hubble/testutils.(*FakePeerNotifyClient).Recv(0x40003e1d60, 0x40000619e0, 0x4000413f00, 0x1)

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/testutils/fake.go:160 +0x6c

github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).watchNotifications(0x40003e4dc0)

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:125 +0x72c

github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).Start.func1(0x40003e4dc0)

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:74 +0x70

created by github.com/cilium/cilium/pkg/hubble/relay/pool.(*PeerManager).Start

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/hubble/relay/pool/manager.go:72 +0x74

FAIL	github.com/cilium/cilium/pkg/hubble/relay/pool	1.037s

FAIL

make: *** [Makefile:209: unit-tests] Error 1

The command "./.travis/build.sh" exited with 2.
```

**Comment by christarazi** [comment]
Seen again in https://github.com/cilium/cilium/pull/16524

**Comment by gandro** [comment]
With the new regime, https://github.com/cilium/cilium/pull/16635  is blocked on this.
