### ISSUE TITLE
Index out of range when handling /healthz v1.9.X on kubernetes 1.18

### ISSUE THREAD

**Issue by oblazek** [cilium/cilium#15701]
## Bug report

**General Information**

Getting following crash when handling /healthz when running cilium version higher than 1.8.X (tested 1.9.3, 1.9.5):
```
level=debug msg="Handling request for /healthz" subsys=health-server
panic: runtime error: index out of range [18] with length 16

goroutine 6485 [running]:
github.com/cilium/arping.FD_SET(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/arping/arping_linux.go:36
github.com/cilium/arping.(*requester).receive(0xc00e3b6640, 0x3b9aca00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/arping/arping_linux.go:41 +0x50f
github.com/cilium/arping.ping.func1(0xc00e3f846c, 0x4, 0x4, 0x2b39b80, 0xc001d96900, 0xc00e3f849c, 0x4, 0x4, 0xc00e3b6640, 0x1040608000001, ...)
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/arping/arping.go:135 +0x3db
created by github.com/cilium/arping.ping
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/arping/arping.go:122 +0x1d8
```

- Cilium version (run `cilium version`)
```
$ kubectl exec -it cilium-cpzzs -- cilium version
Client: 1.9.3 ae8661f14 2021-01-22T18:34:11+01:00 go version go1.15.6 linux/amd64
Daemon: 1.9.3 ae8661f14 2021-01-22T18:34:11+01:00 go version go1.15.6 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux tt-lab13.ko.iszn.cz 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cilium config
```
auto-direct-node-routes: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "1"
  cluster-name: tt-k8st2-ko
  cluster-pool-ipv4-cidr: 10.247.144.0/20
  cluster-pool-ipv4-mask-size: "27"
  clustermesh-config: /var/lib/cilium/conf/clusters
  custom-cni-conf: "false"
  debug: "true"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "false"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-reachable-services: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-local-redirect-policy: "false"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  etcd-config: |-
    ---
    endpoints:
      - https://tt-lab9.ko.iszn.cz:2479
      - https://tt-lab10.ko.iszn.cz:2479
      - https://tt-lab11.ko.iszn.cz:2479
    trusted-ca-file: '/var/lib/etcd-secrets/etcd-client-ca.crt'
    key-file: '/var/lib/etcd-secrets/etcd-client.key'
    cert-file: '/var/lib/etcd-secrets/etcd-client.crt'
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: kvstore
  ipam: cluster-pool
  k8s-require-ipv4-pod-cidr: "false"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config"}'
  masquerade: "false"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  native-routing-cidr: 10.247.0.0/16
  node-port-bind-protection: "true"
  node-port-range: 8000,12000
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  proxy-prometheus-port: "9095"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
  wait-bpf-mount: "false"
  ```

**Comment by oblazek** [comment]
all works well when using cilium e.g. v1.8.8

**Comment by errordeveloper** [comment]
@brb sounds like we maybe able to close this one? @oblazek would you mind testing either 1.10.0 or 1.9.7?

**Comment by oblazek** [comment]
> @brb sounds like we maybe able to close this one? @oblazek would you mind testing either 1.10.0 or 1.9.7?
Will do! thanks

**Comment by oblazek** [comment]
Both v1.9.7 and v1.10.0 seems to work great. Closing :)

**Comment by errordeveloper** [comment]
Glad to hear that, thanks you for reporting and checking.
