### ISSUE TITLE
Cilium without kube-proxy panics on prometheus metrics

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15865]
```
level=error msg="Error while inserting service in LB map" error="Unable to update service entry 100.70.56.241:43558 => 7676 (21256) [FLAGS: 0x0]: Unable to update element for map with file descriptor 15: argument list too long" k8sNamespace=podinfo-190 k8sSvcName=podinfo-20 subsys=k8s-watcher
level=error msg="Error while inserting service in LB map" error="Unable to update service entry 100.70.56.241:3879 => 7682 (21512) [FLAGS: 0x0]: Unable to update element for map with file descriptor 15: argument list too long" k8sNamespace=podinfo-190 k8sSvcName=podinfo-20 subsys=k8s-watcher
panic: inconsistent label cardinality: expected 4 label values but got 3 in []string{"lb4_services_v2", "update", "fail"}
goroutine 400 [running]:
github.com/prometheus/client_golang/prometheus.(*CounterVec).WithLabelValues(0xc0005239b0, 0xc005f3ed20, 0x3, 0x3, 0x2ad5ce0, 0xc005ef69c0)
	/go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/counter.go:248 +0xda
github.com/cilium/cilium/pkg/bpf.(*Map).resolveErrors(0xc000ea9180, 0x2b3cc60, 0xc005f195c0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:1073 +0xda2
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc005632000)
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa77
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb50
```

Cilium 1.9.4 w/ 400 nodes and 30k pods.

**Comment by aanm** [comment]
Fixed by #15866
