### ISSUE TITLE
localRedirectPolicy: pointing to a non-existent service crashes the agent

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#16204]
## Bug report

When attempting to configure a `CiliumLocalRedirectPolicy`, if the **spec.redirectFrontend.serviceMatcher** does not resolve to a service, it seems to cause the cilium agents to crash:

```yaml
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: infra-node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
    - name: udp-53
      port: "53"
      protocol: UDP
    - name: tcp-53
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: coredns-coredns
```

```shell
~$ k -n kube-system get svc/coredns-coredns
Error from server (NotFound): services "coredns-coredns" not found
```

```json
Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 252 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d0ecc0, 0x40000397e0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x84
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x7c
panic(0x1d0ecc0, 0x40000397e0)
	/usr/local/go/src/runtime/panic.go:969 +0x15c
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfigWithSinglePort(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:640 +0x654
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfig(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:620 +0x9c
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).getAndUpsertPolicySvcConfig(0x4000ccc620, 0x4000b70320)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:398 +0x238
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).AddRedirectPolicy(0x4000ccc620, 0x4000039480, 0x14, 0x40003f0220, 0xb, 0x4000ad4b70, 0x24, 0x2, 0x1, 0x39c8da8, ...)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:176 +0x540
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumLocalRedirectPolicy(0x4000dd8300, 0x4001086900, 0x4001086900, 0x0)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:91 +0x498
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit.func1(0x1e68ee0, 0x4001086900)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:44 +0xbc
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:227
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1b562c0, 0x4000964ba0, 0x1, 0x4000964ba0)
	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x1c8
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x4000b70820, 0x4000ee2180, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x1d4
k8s.io/client-go/tools/cache.(*controller).processLoop(0x4000b78630)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4001003f88)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x64
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000fa5f88, 0x22a00a0, 0x4000f9a420, 0x4000e5fe01, 0x4000212480)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x74
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4001003f88, 0x3b9aca00, 0x0, 0x4000763c01, 0x4000212480)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0x4000b78630, 0x4000212480)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x258
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:75 +0x2ac
{"level":"error","msg":"Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)","subsys":"klog"}
{"level":"error","msg":"goroutine 252 [running]:","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d0ecc0, 0x40000397e0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x84","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x7c","subsys":"klog"}
{"level":"error","msg":"panic(0x1d0ecc0, 0x40000397e0)","subsys":"klog"}
{"level":"error","msg":"\t/usr/local/go/src/runtime/panic.go:969 +0x15c","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfigWithSinglePort(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:640 +0x654","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfig(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:620 +0x9c","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).getAndUpsertPolicySvcConfig(0x4000ccc620, 0x4000b70320)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:398 +0x238","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).AddRedirectPolicy(0x4000ccc620, 0x4000039480, 0x14, 0x40003f0220, 0xb, 0x4000ad4b70, 0x24, 0x2, 0x1, 0x39c8da8, ...)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:176 +0x540","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumLocalRedirectPolicy(0x4000dd8300, 0x4001086900, 0x4001086900, 0x0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:91 +0x498","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit.func1(0x1e68ee0, 0x4001086900)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:44 +0xbc","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:227","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1b562c0, 0x4000964ba0, 0x1, 0x4000964ba0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x1c8","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x4000b70820, 0x4000ee2180, 0x0, 0x0, 0x0, 0x0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x1d4","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.(*controller).processLoop(0x4000b78630)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x3c","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4001003f88)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x64","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000fa5f88, 0x22a00a0, 0x4000f9a420, 0x4000e5fe01, 0x4000212480)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x74","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4001003f88, 0x3b9aca00, 0x0, 0x4000763c01, 0x4000212480)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.Until(...)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.(*controller).Run(0x4000b78630, 0x4000212480)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x258","subsys":"klog"}
{"level":"error","msg":"created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:75 +0x2ac","subsys":"klog"}
{"level":"warning","msg":"Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)","subsys":"klog"}
{"level":"warning","msg":"goroutine 252 [running]:","subsys":"klog"}
{"level":"warning","msg":"k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d0ecc0, 0x40000397e0)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x84","subsys":"klog"}
{"level":"warning","msg":"k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x7c","subsys":"klog"}
{"level":"warning","msg":"panic(0x1d0ecc0, 0x40000397e0)","subsys":"klog"}
{"level":"warning","msg":"\t/usr/local/go/src/runtime/panic.go:969 +0x15c","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfigWithSinglePort(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:640 +0x654","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfig(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:620 +0x9c","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).getAndUpsertPolicySvcConfig(0x4000ccc620, 0x4000b70320)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:398 +0x238","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).AddRedirectPolicy(0x4000ccc620, 0x4000039480, 0x14, 0x40003f0220, 0xb, 0x4000ad4b70, 0x24, 0x2, 0x1, 0x39c8da8, ...)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:176 +0x540","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumLocalRedirectPolicy(0x4000dd8300, 0x4001086900, 0x4001086900, 0x0)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:91 +0x498","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit.func1(0x1e68ee0, 0x4001086900)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:44 +0xbc","subsys":"klog"}
{"level":"warning","msg":"k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:227","subsys":"klog"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1b562c0, 0x4000964ba0, 0x1, 0x4000964ba0)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x1c8","subsys":"klog"}
{"level":"warning","msg":"k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x4000b70820, 0x4000ee2180, 0x0, 0x0, 0x0, 0x0)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x1d4","subsys":"klog"}
{"level":"warning","msg":"k8s.io/client-go/tools/cache.(*controller).processLoop(0x4000b78630)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x3c","subsys":"klog"}
{"level":"warning","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4001003f88)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x64","subsys":"klog"}
{"level":"warning","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000fa5f88, 0x22a00a0, 0x4000f9a420, 0x4000e5fe01, 0x4000212480)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x74","subsys":"klog"}
{"level":"warning","msg":"k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4001003f88, 0x3b9aca00, 0x0, 0x4000763c01, 0x4000212480)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88","subsys":"klog"}
{"level":"warning","msg":"k8s.io/apimachinery/pkg/util/wait.Until(...)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90","subsys":"klog"}
{"level":"warning","msg":"k8s.io/client-go/tools/cache.(*controller).Run(0x4000b78630, 0x4000212480)","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x258","subsys":"klog"}
{"level":"warning","msg":"created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit","subsys":"klog"}
{"level":"warning","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:75 +0x2ac","subsys":"klog"}
{"level":"info","msg":"Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)","subsys":"klog"}
{"level":"info","msg":"goroutine 252 [running]:","subsys":"klog"}
{"level":"info","msg":"k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d0ecc0, 0x40000397e0)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x84","subsys":"klog"}
{"level":"info","msg":"k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x7c","subsys":"klog"}
{"level":"info","msg":"panic(0x1d0ecc0, 0x40000397e0)","subsys":"klog"}
{"level":"info","msg":"\t/usr/local/go/src/runtime/panic.go:969 +0x15c","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfigWithSinglePort(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:640 +0x654","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfig(0x4000ccc620, 0x4000b70320, 0x40007908f0, 0x1, 0x1)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:620 +0x9c","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).getAndUpsertPolicySvcConfig(0x4000ccc620, 0x4000b70320)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:398 +0x238","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).AddRedirectPolicy(0x4000ccc620, 0x4000039480, 0x14, 0x40003f0220, 0xb, 0x4000ad4b70, 0x24, 0x2, 0x1, 0x39c8da8, ...)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:176 +0x540","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumLocalRedirectPolicy(0x4000dd8300, 0x4001086900, 0x4001086900, 0x0)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:91 +0x498","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit.func1(0x1e68ee0, 0x4001086900)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:44 +0xbc","subsys":"klog"}
{"level":"info","msg":"k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:227","subsys":"klog"}
{"level":"info","msg":"github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x1b562c0, 0x4000964ba0, 0x1, 0x4000964ba0)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x1c8","subsys":"klog"}
{"level":"info","msg":"k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x4000b70820, 0x4000ee2180, 0x0, 0x0, 0x0, 0x0)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x1d4","subsys":"klog"}
{"level":"info","msg":"k8s.io/client-go/tools/cache.(*controller).processLoop(0x4000b78630)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x3c","subsys":"klog"}
{"level":"info","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4001003f88)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x64","subsys":"klog"}
{"level":"info","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000fa5f88, 0x22a00a0, 0x4000f9a420, 0x4000e5fe01, 0x4000212480)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x74","subsys":"klog"}
{"level":"info","msg":"k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4001003f88, 0x3b9aca00, 0x0, 0x4000763c01, 0x4000212480)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88","subsys":"klog"}
{"level":"info","msg":"k8s.io/apimachinery/pkg/util/wait.Until(...)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90","subsys":"klog"}
{"level":"info","msg":"k8s.io/client-go/tools/cache.(*controller).Run(0x4000b78630, 0x4000212480)","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x258","subsys":"klog"}
{"level":"info","msg":"created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumLocalRedirectPolicyInit","subsys":"klog"}
{"level":"info","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_local_redirect_policy.go:75 +0x2ac","subsys":"klog"}
{"level":"fatal","msg":"Panic in Kubernetes runtime handler","subsys":"k8s"}
```

Creating the service solved the issue right away in my case.

**General Information**

- Cilium version, I tested **v1.9.4** & **v1.10.0-rc2**
- Kernel version: **5.4**
- Orchestration system version in use: **1.19.8-EKS**

**How to reproduce the issue**

1. Create a CiliumLocalRedirectPolicy pointing to a non-existent Kubernetes service

**Comment by aditighag** [comment]
@mvisonneau Thanks for reporting the issue. Just to confirm, if you correct the policy config, things work as expected?

**Comment by mvisonneau** [comment]
yes absolutely, getting the service configured correctly sorts the issue out right away  :+1:
