### ISSUE TITLE
CI: Step "Create AKS cluster" fails on "internal error"

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#17260]
> Create AKS cluster

```
Run # Create group
{
  "id": "/subscriptions/986ec55c-1e77-4e2e-9ca5-dcbb34c7a110/resourceGroups/cilium-cilium-1164807480",
  "location": "westeurope",
  "managedBy": null,
  "name": "cilium-cilium-1164807480",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "owner": "17236",
    "usage": "cilium-cilium"
  },
  "type": "Microsoft.Resources/resourceGroups"
}
WARNING: SSH key files '/home/runner/.ssh/id_rsa' and '/home/runner/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
ERROR: (ReconcileStandardLoadBalancerError) AKS encountered an internal error while attempting the requested Creating operation. AKS will continuously retry the requested operation until successful or a retry timeout is hit. Check back to see if the operation requires resubmission. Correlation ID: 74bd51e9-1041-421e-8dce-82393fd2eb04, Operation ID: f96e1f74-b43f-45a3-9477-200a33283e9f, Timestamp: 2021-08-25T01:38:44Z.
Error: Process completed with exit code 1.
```
https://github.com/cilium/cilium/runs/3417299715?check_suite_focus=true
```
Warning: No files were found with the provided path: cilium-sysdump-out.zip. No artifacts will be uploaded.
```
Azure CLI info:
```
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.0.72
{
  "environmentName": "AzureCloud",
  "homeTenantId": "625cda75-62dd-470e-a554-7313877ff03c",
  "id": "986ec55c-1e77-4e2e-9ca5-dcbb34c7a110",
  "isDefault": true,
  "managedByTenants": [],
  "name": "cilium-pr",
  "state": "Enabled",
  "tenantId": "625cda75-62dd-470e-a554-7313877ff03c",
  "user": {
    "name": "21fb6226-da3b-4ce8-bdbd-66085996e48b",
    "type": "servicePrincipal"
  }
}

az script ran successfully.
cleaning up container...
MICROSOFT_AZURE_CLI_1629855466166_CONTAINER
```

**Comment by joestringer** [comment]
Post-test information gathering also lists this:

```
DEBUG Fetching nodes to determine cluster size...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "cilium-sysdump.zip/__main__.py", line 168, in <module>
  File "cilium-sysdump.zip/utils.py", line 292, in get_nodes
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by nbusseneau** [comment]
This is a pure AKS-side issue, can be reproduced by trying to create clusters manually :/

**Comment by nbusseneau** [comment]
I think I may have fixed the issue by unregistering and re-registering the Kubernetes resource provider on our subscription. This is nuts.

**Comment by pchaigno** [comment]
@joestringer I believe https://github.com/cilium/cilium-sysdump/pull/124 fixed this error.

**Comment by nbusseneau** [comment]
So apparently, they made some change to how the standard load balancers creates its internal resources, and this conflicts with our resource tagging policies. If exempt the sub from applying the policy, it works. If I remove exemption, it stops working again.

This is madness.

**Comment by nbusseneau** [comment]
I have added policy exemptions as a workaround until this issue is fixed or we find another way to implement tag policies and have them work with the standard load balancer SKU. AKS testing should now be working again.

I will try to recreate a minimal subscription + policy example and report the bug to AKS.

**Comment by pchaigno** [comment]
@nbusseneau Is this issue still relevant?

**Comment by nbusseneau** [comment]
AKS never answered, and I've never tried to re-enable the tag policies. The tag policies are less relevant now that we have Cloud Custodian, let's just close this.
