### ISSUE TITLE
Cilium agent keep crash after enable LRP with error "Panic in Kubernetes runtime handler"

### ISSUE THREAD

**Issue by judexzhu** [cilium/cilium#17754]
## Bug report

**General Information**

- Cilium version (run `cilium version`)  1.10.5 tested on 1.10.4 also
- Kernel version (run `uname -a`) 5.10.75-flatcar
- Orchestration system version in use (e.g. `kubectl version`, ...) v1.20.11
- Link to relevant artifacts (policies, deployments scripts, ...) https://docs.cilium.io/en/v1.10/gettingstarted/local-redirect-policy/#local-redirect-policy
- Generate and upload a sysdump:

  - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
  - Run `cilium sysdump` command:

    ```
    cilium sysdump
    ```

**How to reproduce the issue**

1. Enable LRP in cilium-config by setting "enable-local-redirect-policy: 'true'"
2. Rollout restart cilium daemonset
3. Apply LRP https://raw.githubusercontent.com/cilium/cilium/v1.10/examples/kubernetes-local-redirect/backend-pod.yaml
4. confirm with "cilium lrp list"
```
LRP namespace   LRP name       FrontendType                Matching Service
kube-system     nodelocaldns   clusterIP + all svc ports   kube-system/kube-dns
                |              10.217.0.10:53/UDP -> 10.216.13.54:53(kube-system/node-local-dns-vsbg8),
                |              10.217.0.10:53/TCP -> 10.216.13.54:53(kube-system/node-local-dns-vsbg8),
                |              10.217.0.10:9153/TCP ->
```
5. kill the cilium pod and let it recreated 
6.  the pod keep crashing with error logs
```
level=error msg="Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)" subsys=klog
level=error msg="goroutine 277 [running]:" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.logPanic(0x28dd920, 0xc000b11128)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86" subsys=klog
level=error msg="panic(0x28dd920, 0xc000b11128)" subsys=klog
level=error msg="\t/usr/local/go/src/runtime/panic.go:965 +0x1b9" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfigWithSinglePort(0xc00013fb20, 0xc001642460, 0xc001acd308, 0x1, 0x1)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:666 +0x929" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).processConfig(0xc00013fb20, 0xc001642460, 0xc001acd308, 0x1, 0x1)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:646 +0xae" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePodLocked(0xc00013fb20, 0xc0012baac0, 0xc001ac0100)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:306 +0x265" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnAddPod(0xc00013fb20, 0xc0012baac0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:270 +0x113" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addK8sPodV1(0xc0007f4380, 0xc0012baac0, 0x20, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:236 +0x7e7" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).createPodController.func1(0x2a6d920, 0xc0012baac0)" subsys=klog
level=fatal msg="Panic in Kubernetes runtime handler" subsys=k8s
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:94 +0x165" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:231" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x26c89a0, 0xc0006c8150, 0x1, 0xc0006c8150)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x262" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0005bd720, 0xc000b00240, 0x0, 0x0, 0x0, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:544 +0x322" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0000306c0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:183 +0x42" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006d4f90)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001acdf90, 0x2ea4de0, 0xc000a3ca20, 0xc000440101, 0xc000f90300)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006d4f90, 0x3b9aca00, 0x0, 0xc000fbc101, 0xc000f90300)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.Until(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).Run(0xc0000306c0, 0xc000f90300)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:154 +0x2e5" subsys=klog
level=error msg="created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).podsInit.func1" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:148 +0x37a" subsys=klog
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/etcd-config/etcd.config endpoints="[https://172.16.172.102:2379 https://172.16.172.105:2379 https://172.16.172.101:2379 https://172.16.172.104:2379 https://172.16.172.103:2379]" etcdEndpoint="https://172.16.172.102:2379" subsys=kvstore version=3.4.14
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/etcd-config/etcd.config endpoints="[https://172.16.172.102:2379 https://172.16.172.105:2379 https://172.16.172.101:2379 https://172.16.172.104:2379 https://172.16.172.103:2379]" etcdEndpoint="https://172.16.172.105:2379" subsys=kvstore version=3.4.14
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/etcd-config/etcd.config endpoints="[https://172.16.172.102:2379 https://172.16.172.105:2379 https://172.16.172.101:2379 https://172.16.172.104:2379 https://172.16.172.103:2379]" etcdEndpoint="https://172.16.172.101:2379" subsys=kvstore version=3.4.14
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/etcd-config/etcd.config endpoints="[https://172.16.172.102:2379 https://172.16.172.105:2379 https://172.16.172.101:2379 https://172.16.172.104:2379 https://172.16.172.103:2379]" etcdEndpoint="https://172.16.172.104:2379" subsys=kvstore version=3.4.14
level=error msg="Error while inserting service in LB map" error="local-redirect service exists for frontend {{10.217.0.10 {UDP 53} 0} 0}, skip update for svc kube-dns" k8sNamespace=kube-system k8sSvcName=kube-dns subsys=k8s-watcher
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/etcd-config/etcd.config endpoints="[https://172.16.172.102:2379 https://172.16.172.105:2379 https://172.16.172.101:2379 https://172.16.172.104:2379 https://172.16.172.103:2379]" etcdEndpoint="https://172.16.172.103:2379" subsys=kvstore version=3.4.14
level=info msg="Connected to key-value store, stopping CiliumEndpoint watcher" subsys=k8s-watcher
level=info msg="Connected to key-value store, stopping CiliumNode watcher" subsys=k8s-watcher
```
![image](https://user-images.githubusercontent.com/17834225/139747988-297b4fac-a4f6-40f3-b781-e64e43669ab4.png)

this issue was occured at 1.10.4, then I tried to upgrade my cilium to 1.10.5. same result

Cilium sysdump
[cilium-sysdump-20211101-220902.zip](https://github.com/cilium/cilium/files/7456415/cilium-sysdump-20211101-220902.zip)

**Comment by pchaigno** [comment]
Note: v1.10.4 has https://github.com/cilium/cilium/pull/16216, so this isn't another case of https://github.com/cilium/cilium/issues/16204.

cc @aditighag

**Comment by aditighag** [comment]
@judexzhu We've shipped some fixes in recent releases. Could you try with the latest version, and report back if the issue still persists? Thanks!

**Comment by judexzhu** [comment]
@aditighag I follow the https://docs.cilium.io/en/v1.11/gettingstarted/local-redirect-policy/#local-redirect-policy
and found no error now. 
Close the issue. Thank you for help.

**Comment by aditighag** [comment]
> @aditighag I follow the https://docs.cilium.io/en/v1.11/gettingstarted/local-redirect-policy/#local-redirect-policy and found no error now. Close the issue. Thank you for help.

Thanks for the follow-up!
