### ISSUE TITLE
CI: Travis fatal error: concurrent map iteration and map write in github.com/cilium/cilium/pkg/bgp/speaker

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#18832]
## CI failure

- Hit on #18813
- Travis logs: https://app.travis-ci.com/github/cilium/cilium/jobs/559929791#L13212
- Travis logs (saved to GitHub): [log.txt](https://github.com/cilium/cilium/files/8087580/log.txt)
- Arch: arm64

```
=== RUN   TestSpeakerOnDeleteService
level=info msg="processing new event." component=MetalLBSpeaker.run subsys=bgp-speaker
fatal error: concurrent map iteration and map write

goroutine 35 [running]:
runtime.throw({0x17492b0, 0x26})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/runtime/panic.go:1198 +0x54 fp=0x400068f2d0 sp=0x400068f2a0 pc=0x495e4
runtime.mapiternext(0x40001201e0)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/runtime/map.go:858 +0x540 fp=0x400068f350 sp=0x400068f2d0 pc=0x20dc0
runtime.mapiterinit(0x153dac0, 0x400023ab70, 0x40001201e0)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/runtime/map.go:848 +0x294 fp=0x400068f380 sp=0x400068f350 pc=0x20854
reflect.mapiterinit(0x153dac0, 0x400023ab70)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/runtime/map.go:1340 +0x4c fp=0x400068f3b0 sp=0x400068f380 pc=0x78ffc
reflect.(*MapIter).Next(0x4000098000)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/reflect/value.go:1626 +0x5c fp=0x400068f3e0 sp=0x400068f3b0 pc=0xe991c
internal/fmtsort.Sort({0x153dac0, 0x400023ab70, 0x15})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/internal/fmtsort/sort.go:63 +0x14c fp=0x400068f4a0 sp=0x400068f3e0 pc=0xf432c
fmt.(*pp).printValue(0x4000320000, {0x153dac0, 0x400023ab70, 0x15}, 0x76, 0x0)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/fmt/print.go:769 +0x3e0 fp=0x400068f680 sp=0x400068f4a0 pc=0xfbe90
fmt.(*pp).printArg(0x4000320000, {0x153dac0, 0x400023ab70}, 0x76)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/fmt/print.go:712 +0x8dc fp=0x400068f720 sp=0x400068f680 pc=0xfba3c
fmt.(*pp).doPrintf(0x4000320000, {0x17442a2, 0x23}, {0x400068fd88, 0x1, 0x1})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/fmt/print.go:1026 +0x204 fp=0x400068f810 sp=0x400068f720 pc=0xfe3b4
fmt.Sprintf({0x17442a2, 0x23}, {0x400068fd88, 0x1, 0x1})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/fmt/print.go:219 +0x54 fp=0x400068f870 sp=0x400068f810 pc=0xf8424
testing.(*common).Fatalf(0x40001ffa00, {0x17442a2, 0x23}, {0x400068fd88, 0x1, 0x1})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:829 +0x48 fp=0x400068f8c0 sp=0x400068f870 pc=0x123158
github.com/cilium/cilium/pkg/bgp/speaker.TestSpeakerOnDeleteService(0x40001ffa00)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/speaker_test.go:212 +0x918 fp=0x400068ff70 sp=0x400068f8c0 pc=0x134ac88
testing.tRunner(0x40001ffa00, 0x17f7048)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1259 +0xf8 fp=0x400068ffc0 sp=0x400068ff70 pc=0x124ae8
runtime.goexit()
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/runtime/asm_arm64.s:1133 +0x4 fp=0x400068ffc0 sp=0x400068ffc0 pc=0x7f064
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1306 +0x350

goroutine 1 [chan receive]:
testing.(*T).Run(0x40001fe820, {0x17338af, 0x1a}, 0x17f7048)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1307 +0x36c
testing.runTests.func1(0x40001fe820)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1598 +0x80
testing.tRunner(0x40001fe820, 0x400059dce8)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1259 +0xf8
testing.runTests(0x4000133b48, {0x28bc920, 0x6, 0x6}, {0xc07b5ece6a7a2a8a, 0x8bb405a8da, 0x28e3900})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1596 +0x3f8
testing.(*M).Run(0x40000b5900)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/testing/testing.go:1504 +0x510
main.main()
	_testmain.go:1949 +0x238

goroutine 9 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x28e3c20)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/v2/klog.go:1181 +0x70
created by k8s.io/klog/v2.init.0
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/v2/klog.go:420 +0x14c

goroutine 27 [select]:
io.(*pipe).Read(0x40000a5980, {0x400030a000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:57 +0x8c
io.(*PipeReader).Read(0x40000109e8, {0x400030a000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:134 +0x44
bufio.(*Scanner).Scan(0x400008bf38)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/bufio/scan.go:215 +0x948
github.com/sirupsen/logrus.(*Entry).writerScanner(0x40000f0150, 0x40000109e8, 0x400024d340)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:59 +0x88
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:51 +0x42c

goroutine 28 [select]:
io.(*pipe).Read(0x40000a59e0, {0x400030b000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:57 +0x8c
io.(*PipeReader).Read(0x40000109f8, {0x400030b000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:134 +0x44
bufio.(*Scanner).Scan(0x400008ef38)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/bufio/scan.go:215 +0x948
github.com/sirupsen/logrus.(*Entry).writerScanner(0x40000f0150, 0x40000109f8, 0x400024d380)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:59 +0x88
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:51 +0x42c

goroutine 29 [select]:
io.(*pipe).Read(0x40000a5a40, {0x400030c000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:57 +0x8c
io.(*PipeReader).Read(0x4000010a08, {0x400030c000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:134 +0x44
bufio.(*Scanner).Scan(0x400008ff38)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/bufio/scan.go:215 +0x948
github.com/sirupsen/logrus.(*Entry).writerScanner(0x40000f0150, 0x4000010a08, 0x400024d3c0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:59 +0x88
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:51 +0x42c

goroutine 30 [select]:
io.(*pipe).Read(0x40000a5aa0, {0x400030d000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:57 +0x8c
io.(*PipeReader).Read(0x4000010a18, {0x400030d000, 0x1000, 0x1000})
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/io/pipe.go:134 +0x44
bufio.(*Scanner).Scan(0x400008df38)
	/home/travis/.gimme/versions/go1.17.6.linux.arm64/src/bufio/scan.go:215 +0x948
github.com/sirupsen/logrus.(*Entry).writerScanner(0x40000f0150, 0x4000010a18, 0x400024d400)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:59 +0x88
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/writer.go:51 +0x42c

goroutine 36 [runnable]:
k8s.io/client-go/util/workqueue.(*Type).Done(0x40000a5560, {0x15efba0, 0x400004f4a0})
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:180 +0x22c
github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).run(0x40000a55c0, {0x199d028, 0x40000a5500})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/events.go:127 +0x150
created by github.com/cilium/cilium/pkg/bgp/speaker.TestSpeakerOnDeleteService
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/speaker_test.go:174 +0x390
FAIL	github.com/cilium/cilium/pkg/bgp/speaker	0.031s
FAIL
make: *** [Makefile:203: integration-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

Cc @ldelossa (BGP)

**Comment by ldelossa** [comment]
Should be fixed by: https://github.com/cilium/cilium/pull/18884

The read of the map at: `/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/speaker_test.go:212 +0x918 fp=0x400068ff70 sp=0x400068f8c0 pc=0x134ac88`

has been removed all together.

**Comment by ldelossa** [comment]
Closing, linked pull merged
