### ISSUE TITLE
Panic in `cilium bpf policy get`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#19119]
Found on master, v1.12 development cycle.

Found on PR #18864, CI run: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1537/testReport/junit/(root)/Suite-runtime/RuntimeConntrackInVethModeTest_Conntrack_related_configuration_options_for_endpoints/

Test: `Suite-runtime.RuntimeConntrackInVethModeTest Conntrack-related configuration options for endpoints`
Archive: [e804e2ff_RuntimeConntrackInVethModeTest_Conntrack-related_configuration_options_for_endpoints.zip](https://github.com/cilium/cilium/files/8234637/e804e2ff_RuntimeConntrackInVethModeTest_Conntrack-related_configuration_options_for_endpoints.zip)

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
The result of "curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 [http://[f00d::a0f:0:0:f43a]:80](http://[f00d::a0f:0:0:f43a]/) -w \"time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'\"" from container "curl" to httpd2 does not match
Expected
    <bool>: true
to be false
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/runtime/connectivity.go:282
```

...

Here's the actual panic:
```
 	 goroutine 1 [running]:
	 goroutine 1 runtime/debug.Stack()
	 goroutine 1 	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
	 goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc0006da3d8)
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:58 +0x92
	 goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).Open(0xc0006da360)
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:544 +0x95
	 goroutine 1 github.com/cilium/cilium/pkg/maps/policymap.Open({0xc00062b290, 0x4d5f25})
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/policymap/policymap.go:419 +0x2e
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.dumpMap({0xc00062b290, 0xc000134008})
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:85 +0x47
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.listAllMaps()
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:68 +0x185
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.glob..func23(0x3ba5ee0, {0xc0002aa930, 0x0, 0x1})
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:41 +0x4b
	 goroutine 1 github.com/spf13/cobra.(*Command).execute(0x3ba5ee0, {0xc0002aa920, 0x1, 0x1})
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
	 goroutine 1 github.com/spf13/cobra.(*Command).ExecuteC(0x3ba77e0)
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
	 goroutine 1 github.com/spf13/cobra.(*Command).Execute(...)
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:902
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.Execute()
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/root.go:36 +0x25
	 goroutine 1 main.main()
	 goroutine 1 	/home/vagrant/go/src/github.com/cilium/cilium/cilium/main.go:16 +0x17
```

This doesn't seem likely to be relevant to the PR at all, and is likely just a bug in certain conditions for the in-pod `cilium` CLI binary.

**Comment by joestringer** [comment]
One more relevant observation from the test failure, one of the cilium pods was still restoring / regenerating endpoints. This likely failed during Cilium startup / while endpoints were being regenerated. Possibly, bpf policy maps disappeared underneath the CLI while it was attempting to use them.

```
cmd: sudo cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                     
	 415        Disabled           Disabled          5085       container:id.httpd_deny       f00d::a0f:0:0:f43a   10.15.60.130    regenerating            
	                                                            container:id.service1                                                                      
	 592        Disabled           Disabled          4          reserved:health               f00d::a0f:0:0:c02d   10.15.209.198   waiting-to-regenerate   
	 743        Disabled           Disabled          2243       container:id.client           f00d::a0f:0:0:22e3   10.15.3.86      restoring               
	 995        Disabled           Disabled          55488      container:id.httpd            f00d::a0f:0:0:e2b4   10.15.63.56     regenerating            
	                                                            container:id.service1                                                                      
	 1208       Disabled           Disabled          1          reserved:host                                                      ready                   
	 1416       Disabled           Disabled          26003      container:id.server           f00d::a0f:0:0:9b29   10.15.147.41    regenerating            
	 2042       Disabled           Disabled          24664      container:id.curl             f00d::a0f:0:0:c6c    10.15.173.123   regenerating            
	 2370       Disabled           Disabled          35214      container:id.curl2            f00d::a0f:0:0:4d9a   10.15.158.213   restoring               
	 
```

**Comment by joestringer** [comment]
Looking back over the output, I'm not sure that the stack trace is actually pointing out a panic. I think that this is just the "long lock" detection code that tries to figure out when a lock is held longer than expected, so it happened to print the stack trace. The actual panic is listed in #19124.
