### ISSUE TITLE
Cilium v1.10.8 panics when using `io.cilium.proxy-visibility` annotation with wireguard

### ISSUE THREAD

**Issue by anthonyhaussman** [cilium/cilium#19140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

Using Cilium last `v1.10` version installed via Kops `1.23.0`, when scaling via `cluster-autoscaler` for more nodes, some Cilium happened to `CrashloopBackOff` when the number of nodes increased.

Log output is available below with the sysdump.

If more information is needed, I stay available,

### Cilium Version

`v1.10.8`

### Kernel Version

`5.10.102-99.473.amzn2.x86_64`

### Kubernetes Version

`v1.23.4`

### Sysdump

https://gofile.io/d/1ym57M

### Relevant log output

```shell
level=info msg="Reusing existing global key" key="k8s:app.kubernetes.io/instance=pastrami;k8s:app.kubernetes.io/managed-by=spinnaker;k8s:app.kubernetes.io/name=pastrami;k8s:date=1582559798;k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=prod-us;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=prod-us;k8s:service=pastrami;k8s:tags.datadoghq.com/version=2.790.0;" subsys=allocator
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2015 identity=33730 identityLabels="k8s:app.kubernetes.io/instance=pastrami,k8s:app.kubernetes.io/managed-by=spinnaker,k8s:app.kubernetes.io/name=pastrami,k8s:date=1582559798,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=prod-us,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=prod-us,k8s:service=pastrami,k8s:tags.datadoghq.com/version=2.790.0" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2015 identity=33730 ipv4= ipv6= k8sPodName=/ subsys=endpoint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2221207]

goroutine 1261 [running]:
github.com/cilium/cilium/pkg/proxy.(*Proxy).CreateOrUpdateRedirect(0x0, 0x2f1f4c0, 0xc001076a20, 0xc001d5bb60, 0x12, 0x2f514d0, 0xc000549200, 0xc001d3f940, 0xc000560000, 0x0, ...)
	/go/src/github.com/cilium/cilium/pkg/proxy/proxy.go:399 +0x87
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addVisibilityRedirects(0xc000549200, 0xc001fc2d00, 0xc00105f230, 0xc001d3f940, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:400 +0x442
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).addNewRedirects(0xc000549200, 0xc001d3f940, 0xc00105f230, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:498 +0x388
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc000549200, 0xc0001ce000, 0xc000f97a00, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:862 +0x1047
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc000549200, 0xc0001ce000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:612 +0x1b4
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc000549200, 0xc0001ce000, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:416 +0x84d
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc001af5ea0, 0xc0009b0d80)
	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:65 +0x49c
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:256 +0x16b
sync.(*Once).doSlow(0xc0009b06d8, 0xc000e01fb8)
	/usr/local/go/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0xc0009b06c0)
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:244 +0x65
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:240 +0x65
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyhaussman** [comment]
I think I have found the problem :confounded: 
One of the deployment resources that I have backuped had this annotation:
```
      annotations:
        io.cilium.proxy-visibility: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>,<Ingress/80/TCP/HTTP>"
```

This annotation is used for Layer 7 Protocol Visibility which is not supported with WireGuard Transparent Encryption.
After deleting the annotation, everything works perfectly. :ok_hand: 

I close the issue.

**Comment by chancez** [comment]
Let's keep this open as Cilium should not panic, even when misconfigured. Ideally it either logs an error and exits, or just ignores the invalid config option.
