### ISSUE TITLE
Cilium can panic when stopping

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#19204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium panicked when stopped. While otherwise harmless this causes noise in the logs and wastes time checking them out. 

### Cilium Version

master

### Kernel Version

N/A

### Kubernetes Version

N/A

### Relevant log output

```shell
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Deleted filtered entries from map" count=13 file-path=/sys/fs/bpf/tc/globals/cilium_ct4_global subsys=ct-gc
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any4_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Deleted filtered entries from map" count=2 file-path=/sys/fs/bpf/tc/globals/cilium_ct_any4_global subsys=ct-gc
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct6_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Deleted filtered entries from map" count=13 file-path=/sys/fs/bpf/tc/globals/cilium_ct6_global subsys=ct-gc
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any6_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Deleted filtered entries from map" count=2 file-path=/sys/fs/bpf/tc/globals/cilium_ct_any6_global subsys=ct-gc
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any6_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct6_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any4_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_global subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_03116 subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_03116 subsys=bpf
Mar 20 19:05:13 runtime cilium-agent[33599]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 20 19:05:13 runtime cilium-agent[33599]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cdcf7b]
Mar 20 19:05:13 runtime cilium-agent[33599]: goroutine 1229 [running]:
Mar 20 19:05:13 runtime cilium-agent[33599]: github.com/cilium/cilium/pkg/maps/ctmap.doGC4(0xc001d907e0, 0xc000ac3fa8)
Mar 20 19:05:13 runtime cilium-agent[33599]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:429 +0xbb
Mar 20 19:05:13 runtime cilium-agent[33599]: github.com/cilium/cilium/pkg/maps/ctmap.doGC(0x0, 0x2705b20)
Mar 20 19:05:13 runtime cilium-agent[33599]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:532 +0xf1
Mar 20 19:05:13 runtime cilium-agent[33599]: github.com/cilium/cilium/pkg/maps/ctmap.GC(0xc001d907e0, 0xc000ac3fa8)
Mar 20 19:05:13 runtime cilium-agent[33599]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:552 +0x6c
Mar 20 19:05:13 runtime cilium-agent[33599]: github.com/cilium/cilium/pkg/maps/ctmap/gc.runGC(0xc00696e700, 0x1, 0x1, 0x0, 0x1)
Mar 20 19:05:13 runtime cilium-agent[33599]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:189 +0x58a
Mar 20 19:05:13 runtime cilium-agent[33599]: github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable.func1()
Mar 20 19:05:13 runtime cilium-agent[33599]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:97 +0x609
Mar 20 19:05:13 runtime cilium-agent[33599]: created by github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable
Mar 20 19:05:13 runtime cilium-agent[33599]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:40 +0x1e5
Mar 20 19:05:13 runtime systemd[1]: cilium.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 20 19:05:13 runtime cilium-agent[79559]: error while listening: http: Server closed
Mar 20 19:05:13 runtime systemd[1]: cilium.service: Failed with result 'exit-code'.
Mar 20 19:05:13 runtime systemd[1]: cilium.service: Scheduled restart job, restart counter is at 1.
Mar 20 19:05:13 runtime systemd[1]: Stopped cilium.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Happened again at https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1675/testReport/junit/(root)/Suite-runtime/RuntimeConntrackInVethModeTest_Conntrack_related_configuration_options_for_endpoints/.

**Comment by sahid** [comment]
Happened again at https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/2089/ related PR: #18414

**Comment by sahid** [comment]
We can also notice goroutines that are probably not clean in right way:

```goroutine 92100 [running]:
goroutine 92100 runtime/debug.Stack()
goroutine 92100 	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
goroutine 92100 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc00410ed10)
goroutine 92100 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:86 +0x92
goroutine 92100 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc00410ea80, 0xc003884500)
goroutine 92100 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:411 +0x994
goroutine 92100 github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0014bd4d0, 0x7a4?)
goroutine 92100 	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x32c
goroutine 92100 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
goroutine 92100 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x13b
goroutine 92100 sync.(*Once).doSlow(0xc0019d9801?, 0x43fd85?)
goroutine 92100 	/usr/local/go/src/sync/once.go:68 +0xc2
goroutine 92100 sync.(*Once).Do(...)
goroutine 92100 	/usr/local/go/src/sync/once.go:59
goroutine 92100 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0x0?)
goroutine 92100 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:233 +0x45
goroutine 92100 created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
goroutine 92100 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:229 +0x76```

**Comment by joestringer** [comment]
@sahid can you expand the above output to include more context? Sometimes in the CI Cilium will print stack traces purely to highlight log-held locks, not because there's a panic. At a glance this looks like it may be the case for the stack trace you posted, but it's hard to tell without seeing a few lines earlier.

**Comment by sahid** [comment]
Sure, I have downloaded archive from [RuntimeKafka_Kafka_Policy_Role_Egress.zip](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/2089/artifact/0efb5a58_RuntimeKafka_Kafka_Policy_Role_Egress.zip) Then I have looked in `container_cilium.log` and found several errors like the one bellow:

```
evel=info msg="Initializing daemon" subsys=daemon
level=debug msg="Starting new controller" name=endpoint-gc subsys=controller uuid=a2931ef1-e618-4828-affc-a8cc79364b52
level=info msg="Using Managed Neighbor Kernel support" subsys=daemon
level=debug msg="Controller func execution time: 640.79µs" name=endpoint-gc subsys=controller uuid=a2931ef1-e618-4828-affc-a8cc79364b52
level=info msg="Inheriting MTU from external network interface" device=enp0s3 ipAddr=10.0.2.15 mtu=1500 subsys=mtu
level=debug msg="Performing regular background work" subsys=nodemanager syncInterval=1m0s
level=debug msg="creating new EventQueue" name=config-modify-queue numBufferedEvents=10 subsys=eventqueue
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ipcache subsys=bpf
level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1" seconds=0.327356458 subsys=lock-lib
goroutine 1 [running]:
goroutine 1 runtime/debug.Stack()
goroutine 1 	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc00050c738)
goroutine 1 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:57 +0x92
goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).Open(0xc00050c6c0)
goroutine 1 	/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:543 +0x95
goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).DumpWithCallback(0xc00050c6c0, 0xc000232940)
goroutine 1 	/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:604 +0x5b
goroutine 1 github.com/cilium/cilium/daemon/cmd.NewDaemon({0x32e0520?, 0xc0008fe540}, 0xc0002daca0, 0xc00019b950, {0x32f67a8, 0xc000336700})
goroutine 1 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:512 +0x1558
goroutine 1 github.com/cilium/cilium/daemon/cmd.runDaemon()
goroutine 1 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1750 +0x7da
goroutine 1 github.com/cilium/cilium/daemon/cmd.glob..func1(0x4b51ee0?, {0x2daa5b7?, 0xa?, 0xa?})
goroutine 1 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:129 +0x3aa
goroutine 1 github.com/spf13/cobra.(*Command).execute(0x4b51ee0, {0xc00006e0c0, 0xa, 0xa})
goroutine 1 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:860 +0x663
goroutine 1 github.com/spf13/cobra.(*Command).ExecuteC(0x4b51ee0)
goroutine 1 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
goroutine 1 github.com/spf13/cobra.(*Command).Execute(...)
goroutine 1 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:902
goroutine 1 github.com/cilium/cilium/daemon/cmd.Execute()
goroutine 1 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:143 +0x45
goroutine 1 main.main()
goroutine 1 	/go/src/github.com/cilium/cilium/daemon/main.go:15 +0x17
level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ipcache subsys=bpf
level=debug msg="getting identity cache for identity allocator manager" subsys=identity-cache
level=debug msg="creating new EventQueue" name=repository-change-queue numBufferedEvents=100 subsys=eventqueue
level=debug msg="creating new EventQueue" name=repository-reaction-queue numBufferedEvents=100 subsys=eventqueue
```

I was under the impression that the gorountine did not finished properly. But now as you mentioned It, this may just be stack trace generated to highlight locks.

**Comment by joaoubaldo** [comment]
We've experienced a similar pattern with Cilium v1.14.12, running in EKS, panicking after receiving the terminate signal. The stack trace is different though:
```
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/controller/manager.go:102 +0x59a"
"2024-07-18T09:25:44.072Z","created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 343518"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/controller/controller.go:201 +0x109"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc00400a5a0, {0xc0042191f0, 0x0, 0xc0085512f0, 0x2540be400, 0x0, 0x0, 0x0, {0x3c7f710, 0xc00ac5a7d0}})"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpointsynchronizer.go:128 +0x3c6"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/k8s/watchers.(*EndpointSynchronizer).RunK8sCiliumEndpointSync.func1({0x3c7f710, 0xc00ac5a7d0})"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint_status.go:355 +0x314"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/endpoint.(*Endpoint).GetCiliumEndpointStatus(0xc005ea8a80, {0x3c340c0, 0x5c30bc0})"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint_status.go:130 +0x91"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/endpoint.getEndpointNetworking(0xc008c72660)"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/node/address.go:287 +0x25"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/node.GetCiliumEndpointNodeIP()"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/node/address.go:279 +0x25"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/node.GetIPv4()"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/node/address.go:48 +0xb4"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/node.getLocalNode()"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/node/local_node_store.go:115"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Get(...)"
"2024-07-18T09:25:44.072Z","/go/src/github.com/cilium/cilium/pkg/stream/sinks.go:25 +0x191"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/stream.First[...]({_, _}, {_, _})"
"2024-07-18T09:25:44.072Z","<autogenerated>:1 +0x21"
"2024-07-18T09:25:44.072Z","github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Observe(0x3c7f668?, {0x3c7f710?, 0xc014c340f0?}, 0xc00f2b35c0?, 0xc00d712258?)"
"2024-07-18T09:25:44.072Z","goroutine 345267 [running]:"
"2024-07-18T09:25:44.071Z","[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14307a1]"
"2024-07-18T09:25:44.071Z","panic: runtime error: invalid memory address or nil pointer dereference"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""38.601µs"" function=""client.(*compositeClientset).onStop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""2.8µs"" function=""authmap.newAuthMap.func2 (cell.go:30)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""6.88µs"" function=""configmap.newMap.func2 (cell.go:26)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""3.5µs"" function=""signalmap.newMap.func2 (cell.go:47)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""6.131µs"" function=""nodemap.newNodeMap.func2 (cell.go:26)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""1.23µs"" function=""eventsmap.newEventsMap.func2 (cell.go:45)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""131.603µs"" function=""*cni.cniConfigManager.Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""72.192µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Node].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""84.282µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNode].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""2.3µs"" function=""node.NewLocalNodeStore.func2 (local_node_store.go:95)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""49.602µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""22.151µs"" function=""*manager.diffStore[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""67.061µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s.Endpoints].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""9.869µs"" function=""*manager.diffStore[*github.com/cilium/cilium/pkg/k8s.Endpoints].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""86.201µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Pod].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""187.874µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Namespace].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""41.851µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNetworkPolicy].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""52.311µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumClusterwideNetworkPolicy].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""82.962µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumCIDRGroup].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""33.491µs"" function=""endpointmanager.newDefaultEndpointManager.func2 (cell.go:205)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""362.508µs"" function=""cmd.newPolicyTrifecta.func2 (policy.go:139)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""31.921µs"" function=""*manager.manager.Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=6.811377ms function=""*internal.ClusterMesh.Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""2.85µs"" function=""agent.newMonitorAgent.func2 (cell.go:91)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""15.87µs"" function=""*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumL2AnnouncementPolicy].Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""8.979µs"" function=""*job.group.Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""97.822µs"" function=""proxy.newProxy.func2 (cell.go:70)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""666.454µs"" function=""signal.provideSignalManager.func2 (cell.go:28)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Datapath signal listener done"" subsys=signal"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Datapath signal listener exiting"" subsys=signal"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=405.75613ms function=""cmd.newDaemonPromise.func2 (daemon_main.go:1698)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stopped serving cilium API at unix:///var/run/cilium/cilium.sock"" subsys=daemon"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""All endpoints' goroutines stopped."" subsys=daemon"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Waiting for all endpoints' goroutines to be stopped."" subsys=daemon"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stopping fswatcher"" config=tls-server subsys=hubble"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""21.421µs"" function=""utime.initUtimeSync.func2 (cell.go:48)"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""14.431µs"" function=""*job.group.Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Stop hook executed"" duration=""13.021µs"" function=""*job.group.Stop"" subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=Stopping subsys=hive"
"2024-07-18T09:25:44.071Z","time=""2024-07-18T09:25:43Z"" level=info msg=""Signal received"" signal=terminated subsys=hive"
```

**Comment by joestringer** [comment]
Hi @joaoubaldo , thanks for the report. It looks like the underlying cause is different from this original issue so it'd be better to start a dedicated issue for it so we can avoid confusing the discussion with the previous discussions on this issue.

Could you try this out with Cilium 1.15.7 and see if you still observe the same? If so, please file a new GitHub issue.

I'll close this one out since the original report is pretty old and unlikely to affect any currently-maintained version of Cilium.
