### ISSUE TITLE
CI: RuntimeConntrackInVethModeTest Conntrack-related configuration options for endpoints: `container "server" unexpectedly was able to ping to "client"`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#19598]
### Test Name

```shell
RuntimeConntrackInVethModeTest Conntrack-related configuration options for endpoints
```

### Failure Output

```shell
container "server" unexpectedly was able to ping to "client" IP:"f00d::a0f:0:0:6283"
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
container "server" unexpectedly was able to ping to "client" IP:"f00d::a0f:0:0:6283"
Expected command: docker exec -i  server xping -6 -W 5 -c 5 -x 1111 f00d::a0f:0:0:6283
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 PING f00d::a0f:0:0:6283 (f00d::a0f:0:0:6283): 56 data bytes
	 64 bytes from f00d::a0f:0:0:6283: seq=0 ttl=63 time=0.103 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=1 ttl=63 time=0.116 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=2 ttl=63 time=0.116 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=3 ttl=63 time=0.139 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=4 ttl=63 time=0.186 ms
	 
	 --- f00d::a0f:0:0:6283 ping statistics ---
	 5 packets transmitted, 5 packets received, 0% packet loss
	 round-trip min/avg/max = 0.103/0.132/0.186 ms
	 
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/runtime/connectivity.go:288
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
```

### Standard Error

```shell
06:30:37 STEP: Running BeforeAll block for EntireTestsuite RuntimeConntrackInVethModeTest
06:30:40 STEP: Setting PolicyEnforcement=always
06:30:42 STEP: Running BeforeEach block for EntireTestsuite RuntimeConntrackInVethModeTest
06:30:48 STEP: Setting up policy: /home/vagrant/go/src/github.com/cilium/cilium/test/runtime/manifests/ct-test-policy.json
06:30:48 STEP: Getting Endpoint IDs
06:30:48 STEP: Endpoint ID for "server" = "917"
06:30:48 STEP: Endpoint ID for "client" = "1918"
06:30:48 STEP: Testing with endpoint configuration option: ConntrackLocal=Disabled
06:30:49 STEP: ============= Starting Connectivity Test ============= 
06:30:49 STEP: Getting IPs of each spawned container
06:30:49 STEP: client container Docker networking: map["EndpointID":"b57284e2cc5fff0284ee3755aad2cd09f344eb9ceb4e3c9a8dad1bb7387677ad" "IPv4":"10.15.226.121" "IPv6":"f00d::a0f:0:0:6283" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"client" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:30:49 STEP: server container Docker networking: map["EndpointID":"fe3066b34bf86eb4d4d7aafd5ecb3ffdab0db97870bcc73bc04a7267d1f94e5e" "IPv4":"10.15.246.21" "IPv6":"f00d::a0f:0:0:418e" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"server" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:30:49 STEP: httpd1 container Docker networking: map["EndpointID":"8d68d70d74da206961a13fda83c023361737159c2e6e82a238410f13515b3576" "IPv4":"10.15.226.129" "IPv6":"f00d::a0f:0:0:d13c" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"httpd1" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:30:49 STEP: httpd2 container Docker networking: map["EndpointID":"14cd0ce775d99f2e7ed392e7f20fc68d575a22c31fc980d4810d0cf3961582e1" "IPv4":"10.15.19.211" "IPv6":"f00d::a0f:0:0:39e4" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"httpd2" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:30:49 STEP: curl1 container Docker networking: map["EndpointID":"0eea3268f7be8dd7408042e0b30042ec1f177f09c97e44a7cf7f6e8bd9a8dd14" "IPv4":"10.15.29.189" "IPv6":"f00d::a0f:0:0:c857" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"curl" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:30:49 STEP: httpd1 container Docker networking: map["EndpointID":"9cada7ac46a975a1caacd8af2c1da438fbaf2da88c78d9e740308dc368516b8d" "IPv4":"10.15.149.78" "IPv6":"f00d::a0f:0:0:e472" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"curl2" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:30:49 STEP: Showing policies imported to Cilium
[
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.curl": ""
      }
    },
    "egress": [
      {
        "toPorts": [
          {
            "ports": [
              {
                "port": "80",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "curl",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.server": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "reserved:host": ""
            }
          },
          {
            "matchLabels": {
              "any:id.client": ""
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "server",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.client": ""
      }
    },
    "egress": [
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "any:id.server": ""
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "egress-from-client-to-server",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.httpd": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.curl": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "80",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "httpd",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.httpd": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.curl2": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "8080",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "httpd",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.httpd_deny": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.curl": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "9090",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "httpd_deny",
        "source": "unspec"
      }
    ]
  }
]
Revision: 11

06:30:49 STEP: Container "curl" test connectivity to "httpd1"
06:30:49 STEP: Container "curl" test connectivity to "httpd1"
06:30:49 STEP: Container "curl2" test connectivity to "httpd1"
06:30:54 STEP: Container "curl2" test connectivity to "httpd1"
06:30:59 STEP: Container "curl" test connectivity to "httpd2"
06:31:04 STEP: Container "curl" test connectivity to "httpd2"
06:31:09 STEP: Container "curl2" test connectivity to "httpd2"
06:31:15 STEP: Container "curl2" test connectivity to "httpd2"
06:31:20 STEP: Container "client" test connectivity to "server"
06:31:24 STEP: Container "client" test connectivity to "server"
06:31:28 STEP: Container "client" test connectivity to "server"
06:31:28 STEP: Container "client" test connectivity to "server"
06:31:28 STEP: Container "client" test connectivity to "server"
06:31:31 STEP: Container "client" test connectivity to "server"
06:31:34 STEP: Container "client" test connectivity to "server"
06:31:38 STEP: Container "client" test connectivity to "server"
06:31:41 STEP: Testing bidirectional connectivity from client to server
06:31:41 STEP: container server pinging client IPv6 (should NOT work)
06:31:50 STEP: container server pinging client IPv4 (should NOT work)
06:31:59 STEP: ============= Finished Connectivity Test ============= 
06:31:59 STEP: Testing with endpoint configuration option: ConntrackLocal=Enabled
06:32:07 STEP: ============= Starting Connectivity Test ============= 
06:32:07 STEP: Getting IPs of each spawned container
06:32:07 STEP: client container Docker networking: map["EndpointID":"b57284e2cc5fff0284ee3755aad2cd09f344eb9ceb4e3c9a8dad1bb7387677ad" "IPv4":"10.15.226.121" "IPv6":"f00d::a0f:0:0:6283" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"client" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:32:07 STEP: server container Docker networking: map["EndpointID":"fe3066b34bf86eb4d4d7aafd5ecb3ffdab0db97870bcc73bc04a7267d1f94e5e" "IPv4":"10.15.246.21" "IPv6":"f00d::a0f:0:0:418e" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"server" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:32:07 STEP: httpd1 container Docker networking: map["EndpointID":"8d68d70d74da206961a13fda83c023361737159c2e6e82a238410f13515b3576" "IPv4":"10.15.226.129" "IPv6":"f00d::a0f:0:0:d13c" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"httpd1" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:32:07 STEP: httpd2 container Docker networking: map["EndpointID":"14cd0ce775d99f2e7ed392e7f20fc68d575a22c31fc980d4810d0cf3961582e1" "IPv4":"10.15.19.211" "IPv6":"f00d::a0f:0:0:39e4" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"httpd2" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:32:07 STEP: curl1 container Docker networking: map["EndpointID":"0eea3268f7be8dd7408042e0b30042ec1f177f09c97e44a7cf7f6e8bd9a8dd14" "IPv4":"10.15.29.189" "IPv6":"f00d::a0f:0:0:c857" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"curl" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:32:07 STEP: httpd1 container Docker networking: map["EndpointID":"9cada7ac46a975a1caacd8af2c1da438fbaf2da88c78d9e740308dc368516b8d" "IPv4":"10.15.149.78" "IPv6":"f00d::a0f:0:0:e472" "IPv6Gateway":"f00d::a0f:0:0:93b5" "Name":"curl2" "NetworkID":"0d06fc8fd57279a23b1179c89b9ef204f0c92cc23d54f80df979b8e14f6ec516"]
06:32:07 STEP: Showing policies imported to Cilium
[
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.curl": ""
      }
    },
    "egress": [
      {
        "toPorts": [
          {
            "ports": [
              {
                "port": "80",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "curl",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.server": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "reserved:host": ""
            }
          },
          {
            "matchLabels": {
              "any:id.client": ""
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "server",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.client": ""
      }
    },
    "egress": [
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "any:id.server": ""
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "egress-from-client-to-server",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.httpd": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.curl": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "80",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "httpd",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.httpd": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.curl2": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "8080",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "httpd",
        "source": "unspec"
      }
    ]
  },
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.httpd_deny": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.curl": ""
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "9090",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "httpd_deny",
        "source": "unspec"
      }
    ]
  }
]
Revision: 11

06:32:07 STEP: Container "curl" test connectivity to "httpd1"
06:32:07 STEP: Container "curl" test connectivity to "httpd1"
06:32:07 STEP: Container "curl2" test connectivity to "httpd1"
06:32:12 STEP: Container "curl2" test connectivity to "httpd1"
06:32:17 STEP: Container "curl" test connectivity to "httpd2"
06:32:22 STEP: Container "curl" test connectivity to "httpd2"
06:32:27 STEP: Container "curl2" test connectivity to "httpd2"
06:32:32 STEP: Container "curl2" test connectivity to "httpd2"
06:32:38 STEP: Container "client" test connectivity to "server"
06:32:42 STEP: Container "client" test connectivity to "server"
06:32:46 STEP: Container "client" test connectivity to "server"
06:32:46 STEP: Container "client" test connectivity to "server"
06:32:46 STEP: Container "client" test connectivity to "server"
06:32:49 STEP: Container "client" test connectivity to "server"
06:32:52 STEP: Container "client" test connectivity to "server"
06:32:55 STEP: Container "client" test connectivity to "server"
06:32:58 STEP: Testing bidirectional connectivity from client to server
06:32:58 STEP: container server pinging client IPv6 (should NOT work)
FAIL: container "server" unexpectedly was able to ping to "client" IP:"f00d::a0f:0:0:6283"
Expected command: docker exec -i  server xping -6 -W 5 -c 5 -x 1111 f00d::a0f:0:0:6283
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 PING f00d::a0f:0:0:6283 (f00d::a0f:0:0:6283): 56 data bytes
	 64 bytes from f00d::a0f:0:0:6283: seq=0 ttl=63 time=0.103 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=1 ttl=63 time=0.116 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=2 ttl=63 time=0.116 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=3 ttl=63 time=0.139 ms
	 64 bytes from f00d::a0f:0:0:6283: seq=4 ttl=63 time=0.186 ms
	 
	 --- f00d::a0f:0:0:6283 ping statistics ---
	 5 packets transmitted, 5 packets received, 0% packet loss
	 round-trip min/avg/max = 0.103/0.132/0.186 ms
	 
Stderr:
 	 

=== Test Finished at 2022-04-26T06:33:03Z====
06:33:03 STEP: Running JustAfterEach block for EntireTestsuite RuntimeConntrackInVethModeTest
===================== TEST FAILED =====================
06:33:03 STEP: Running AfterFailed block for EntireTestsuite RuntimeConntrackInVethModeTest
cmd: sudo cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                     
	 163        Disabled           Disabled          31681      container:id.httpd_deny       f00d::a0f:0:0:39e4   10.15.19.211    ready   
	                                                            container:id.service1                                                      
	 290        Disabled           Disabled          1          reserved:host                                                      ready   
	 336        Disabled           Disabled          37860      container:id.curl             f00d::a0f:0:0:c857   10.15.29.189    ready   
	 581        Disabled           Disabled          4          reserved:health               f00d::a0f:0:0:521b   10.15.177.67    ready   
	 917        Disabled           Disabled          11764      container:id.server           f00d::a0f:0:0:418e   10.15.246.21    ready   
	 1384       Disabled           Disabled          2680       container:id.httpd            f00d::a0f:0:0:d13c   10.15.226.129   ready   
	                                                            container:id.service1                                                      
	 1918       Disabled           Disabled          1930       container:id.client           f00d::a0f:0:0:6283   10.15.226.121   ready   
	 4044       Disabled           Disabled          50402      container:id.curl2            f00d::a0f:0:0:e472   10.15.149.78    ready   
	 
Stderr:
 	 

cmd: sudo cilium policy get
Exitcode: 0 
Stdout:
 	 []
	 Revision: 1
	 
Stderr:
 	 

cmd: sudo cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                     
	 163        Disabled           Disabled          31681      container:id.httpd_deny       f00d::a0f:0:0:39e4   10.15.19.211    ready   
	                                                            container:id.service1                                                      
	 290        Disabled           Disabled          1          reserved:host                                                      ready   
	 336        Disabled           Disabled          37860      container:id.curl             f00d::a0f:0:0:c857   10.15.29.189    ready   
	 581        Disabled           Disabled          4          reserved:health               f00d::a0f:0:0:521b   10.15.177.67    ready   
	 917        Disabled           Disabled          11764      container:id.server           f00d::a0f:0:0:418e   10.15.246.21    ready   
	 1384       Disabled           Disabled          2680       container:id.httpd            f00d::a0f:0:0:d13c   10.15.226.129   ready   
	                                                            container:id.service1                                                      
	 1918       Disabled           Disabled          1930       container:id.client           f00d::a0f:0:0:6283   10.15.226.121   ready   
	 4044       Disabled           Disabled          50402      container:id.curl2            f00d::a0f:0:0:e472   10.15.149.78    ready   
	 
Stderr:
 	 

cmd: sudo cilium bpf policy get --all
Exitcode: 0 
Stdout:
 	 /sys/fs/bpf/tc/globals/cilium_policy_00163:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
	 Allow    Egress      reserved:unknown              ANY          NONE         0       0         
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_00290:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
	 Allow    Egress      reserved:unknown              ANY          NONE         0       0         
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_00336:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
	 Allow    Egress      reserved:unknown              ANY          NONE         0       0         
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_00581:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
	 Allow    Egress      reserved:unknown              ANY          NONE         0       0         
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_00917:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES      PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         16628743   260188    
	 Allow    Egress      reserved:unknown              ANY          NONE         16605422   259795    
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_01384:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
	 Allow    Egress      reserved:unknown              ANY          NONE         0       0         
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_01918:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES     PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         9623240   166938    
	 Allow    Egress      reserved:unknown              ANY          NONE         9621806   166946    
	 
	 
	 /sys/fs/bpf/tc/globals/cilium_policy_04044:
	 
	 POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
	 Allow    Ingress     reserved:unknown              ANY          NONE         0       0         
	 Allow    Egress      reserved:unknown              ANY          NONE         0       0         
	 
	 
	 
Stderr:
 	 goroutine 1 [running]:
	 goroutine 1 runtime/debug.Stack()
	 goroutine 1 	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
	 goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc0005435d8)
	 goroutine 1 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:57 +0x92
	 goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).Open(0xc000543560)
	 goroutine 1 	/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:543 +0x95
	 goroutine 1 github.com/cilium/cilium/pkg/maps/policymap.Open({0xc0004b07b0?, 0xc00079fc48?})
	 goroutine 1 	/go/src/github.com/cilium/cilium/pkg/maps/policymap/policymap.go:423 +0x2e
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.dumpMap({0xc0004b07b0?, 0xc00000e010?})
	 goroutine 1 	/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:85 +0x47
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.listAllMaps()
	 goroutine 1 	/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:68 +0x185
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.glob..func20(0x39ae660?, {0xc00087cf20, 0x0, 0x1})
	 goroutine 1 	/go/src/github.com/cilium/cilium/cilium/cmd/bpf_policy_get.go:41 +0x4b
	 goroutine 1 github.com/spf13/cobra.(*Command).execute(0x39ae660, {0xc00087cf10, 0x1, 0x1})
	 goroutine 1 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:860 +0x663
	 goroutine 1 github.com/spf13/cobra.(*Command).ExecuteC(0x39afa60)
	 goroutine 1 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
	 goroutine 1 github.com/spf13/cobra.(*Command).Execute(...)
	 goroutine 1 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:902
	 goroutine 1 github.com/cilium/cilium/cilium/cmd.Execute()
	 goroutine 1 	/go/src/github.com/cilium/cilium/cilium/cmd/root.go:36 +0x25
	 goroutine 1 main.main()
	 goroutine 1 	/go/src/github.com/cilium/cilium/cilium/main.go:15 +0x17
	 

===================== Exiting AfterFailed =====================
06:33:12 STEP: Running AfterEach for block EntireTestsuite RuntimeConntrackInVethModeTest
06:33:15 STEP: Setting PolicyEnforcement=default
06:33:15 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|18a66ddc_RuntimeConntrackInVethModeTest_Conntrack-related_configuration_options_for_endpoints.zip]]
06:33:17 STEP: Running AfterAll block for EntireTestsuite RuntimeConntrackInVethModeTest
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/2017/testReport/junit/(root)/Suite-runtime/RuntimeConntrackInVethModeTest_Conntrack_related_configuration_options_for_endpoints/
- ZIP file(s): 
[18a66ddc_RuntimeConntrackInVethModeTest_Conntrack-related_configuration_options_for_endpoints.zip](https://github.com/cilium/cilium/files/8575055/18a66ddc_RuntimeConntrackInVethModeTest_Conntrack-related_configuration_options_for_endpoints.zip)

**Comment by christarazi** [comment]
Same as https://github.com/cilium/cilium/issues/12891.

**Comment by christarazi** [comment]
Seen in https://github.com/cilium/cilium/pull/19570#pullrequestreview-954112450.
