### ISSUE TITLE
CI: CIFuzz / Fuzzing: fuzz_parser_decode - nil pointer dereference in Hubble decodeNetworkInterface 

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#20457]
## CI failure

Observed in https://github.com/cilium/cilium/runs/7253767533?check_suite_focus=true

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x24d809d]
goroutine 17 [running, locked to thread]:
github.com/cilium/cilium/pkg/hubble/parser/threefour.(*Parser).decodeNetworkInterface(0x10c0008ec600, 0x0, 0x10c00062bd88)
	github.com/cilium/cilium/pkg/hubble/parser/threefour/parser.go:669 +0x15d
github.com/cilium/cilium/pkg/hubble/parser/threefour.(*Parser).Decode(0x10c0008ec600, {0x10c00027b4d0, 0x2b, 0x2b}, 0x10c0008d5d40)
	github.com/cilium/cilium/pkg/hubble/parser/threefour/parser.go:209 +0x170c
github.com/cilium/cilium/pkg/hubble/parser.(*Parser).Decode(0x10c0008c13e0, 0x10c0002e5dc0)
	github.com/cilium/cilium/pkg/hubble/parser/parser.go:110 +0x945
github.com/cilium/cilium/pkg/hubble/parser.FuzzParserDecode({0x60c000023bc0, 0x78, 0x78})
	github.com/cilium/cilium/pkg/hubble/parser/hubble_parser_fuzzer.go:68 +0x609
main.LLVMFuzzerTestOneInput(...)
	./main.4024208955.go:28

[...]

2022-07-08 15:12:23,004 - root - INFO - Fuzzer: fuzz_parser_decode. Detected bug.
2022-07-08 15:12:23,005 - root - INFO - Trying to reproduce crash using: /tmp/tmptcehe_a4/crash-928395206191e19d0d0367a0465f6fd00dd994b8.
2022-07-08 15:12:23,844 - root - INFO - Reproduce command returned: 77. Reproducible on /github/workspace/build-out/fuzz_parser_decode.
2022-07-08 15:12:23,845 - root - INFO - Crash is reproducible.
2022-07-08 15:12:23,891 - root - INFO - Downloading latest build.
```

[artifacts.zip](https://github.com/cilium/cilium/files/9082458/artifacts.zip)

**Comment by gandro** [comment]
The tests were added recently https://github.com/cncf/cncf-fuzzing/tree/main/projects/cilium

**Comment by gandro** [comment]
I'm late to the party, will be fixed by https://github.com/cilium/cilium/pull/20446
