### ISSUE TITLE
CI: control-plane/services/nodeport/v1.22: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#20651]
In a PR that only made changes to the CNI plugin, I observed this on Travis:

https://app.travis-ci.com/github/cilium/cilium/jobs/577440300#L994

```
...
  TEST  github.com/cilium/cilium/test/control-plane/services/nodeport/v1.22
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/test/control-plane/services/nodeport/v1.22   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config
level=info msg="Trying to auto-enable \"enable-node-port\", \"enable-external-ips\", \"bpf-lb-sock\", \"enable-host-port\", \"enable-session-affinity\" features" subsys=daemon
level=info msg="Detected MTU 1460" subsys=mtu
level=info msg="L7 proxies are disabled" subsys=daemon
level=info msg="Reading old endpoints..." subsys=daemon
level=info msg="No old endpoints found." subsys=daemon
level=info msg="Retrieved node information from kubernetes node" nodeName=nodeport-control-plane subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=172.18.0.4 ipAddr.ipv6="fc00:f853:ccd:e793::4" k8sNodeIP=172.18.0.4 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:nodeport-control-plane kubernetes.io/os:linux node-role.kubernetes.io/control-plane: node-role.kubernetes.io/master: node.kubernetes.io/exclude-from-external-load-balancers:]" nodeName=nodeport-control-plane subsys=k8s v4Prefix=10.244.0.0/24 v6Prefix="fd00:10:244::/64"
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=info msg="Detected devices" devices="[]" subsys=linux-datapath
level=info msg="BPF host routing requires enable-bpf-masquerade. Falling back to legacy host routing (enable-host-legacy-routing=true)." subsys=daemon
level=info msg="Enabling k8s event listener" subsys=k8s-watcher
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Skipping kvstore configuration" subsys=daemon
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Initializing kubernetes IPAM" subsys=ipam v4Prefix=1.1.1.0/24 v6Prefix="cafe::/96"
level=warning msg="Failed to remove old router IPs (restored IP: <nil>) from cilium_host. Manual intervention is required to remove all other old IPs." error="Link not found" subsys=daemon
level=info msg="Restoring endpoints..." subsys=daemon
level=info msg="Endpoints restored" failed=0 restored=0 subsys=daemon
level=info msg="Addressing information:" subsys=daemon
level=info msg="  Cluster-Name: default" subsys=daemon
level=info msg="  Cluster-ID: 0" subsys=daemon
level=info msg="  Local node-name: nodeport-control-plane" subsys=daemon
level=info msg="  Node-IPv6: fc00:f853:ccd:e793::4" subsys=daemon
level=info msg="  External-Node IPv4: 172.18.0.4" subsys=daemon
level=info msg="  Internal-Node IPv4: 1.1.1.2" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.244.0.0/24" subsys=daemon
level=info msg="  Loopback IPv4: 169.254.42.1" subsys=daemon
level=info msg="  Local IPv4 addresses:" subsys=daemon
level=info msg="  - 10.0.0.2" subsys=daemon
level=info msg="  - 10.0.0.3" subsys=daemon
level=info msg="  - 10.0.0.4" subsys=daemon
fatal error: concurrent map writes

goroutine 210 [running]:
runtime.throw({0x30f5045?, 0xc00104ef78?})
	/home/travis/.gimme/versions/go1.18.4.linux.amd64/src/runtime/panic.go:992 +0x71 fp=0xc001116e80 sp=0xc001116e50 pc=0x43b151
runtime.mapassign(0x30?, 0xc0007ac1b0?, 0x8?)
	/home/travis/.gimme/versions/go1.18.4.linux.amd64/src/runtime/map.go:595 +0x4d6 fp=0xc001116f00 sp=0xc001116e80 pc=0x411d76
github.com/cilium/cilium/pkg/datapath/fake.(*FakeNodeHandler).NodeAdd(_, {{0xc0000745b0, 0x10}, {0x30bce5e, 0x7}, {0xc0003437c0, 0x3, 0x4}, 0xc0003fabd8, {0x0, ...}, ...})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/datapath/fake/node.go:24 +0x28 fp=0xc001116f28 sp=0xc001116f00 pc=0x13ced48
github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeUpdated.func3({0x3637728?, 0xc0003fa008?})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/node/manager/manager.go:550 +0xb8 fp=0xc001117170 sp=0xc001116f28 pc=0x2079478
github.com/cilium/cilium/pkg/node/manager.(*Manager).Iter(0xc0001de8f0?, 0xc0011173f8)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/node/manager/manager.go:186 +0xe6 fp=0xc001117218 sp=0xc001117170 pc=0x2076766
github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeUpdated(_, {{0xc0000745b0, 0x10}, {0x30bce5e, 0x7}, {0xc0003437c0, 0x3, 0x4}, 0xc0003fabd8, {0x0, ...}, ...})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/node/manager/manager.go:549 +0x11d8 fp=0xc0011177d0 sp=0xc001117218 pc=0x2078f58
github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).NodeUpdated(_, {{0xc0000745b0, 0x10}, {0x30bce5e, 0x7}, {0xc0003437c0, 0x3, 0x4}, 0xc0003fabd8, {0x0, ...}, ...})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:227 +0x59 fp=0xc001117900 sp=0xc0011177d0 pc=0x2160779
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit.func1({0x3056620?, 0xc0007a7700?})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:56 +0x295 fp=0xc001117ba8 sp=0xc001117900 pc=0x245f0b5
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:232
k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc0007a3e90?, {0x3056620?, 0xc0007a7700?})
	<autogenerated>:1 +0x3f fp=0xc001117bc8 sp=0xc001117ba8 pc=0x114fa3f
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2bcdac0?, 0xc00107c3a8?})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:108 +0x2a5 fp=0xc001117c78 sp=0xc001117bc8 pc=0x1e47e25
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0003432c0, 0xc0010700c0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x566 fp=0xc001117dd8 sp=0xc001117c78 pc=0x113d906
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc001064120)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36 fp=0xc001117e10 sp=0xc001117dd8 pc=0x113ab76
k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
	<autogenerated>:1 +0x26 fp=0xc001117e28 sp=0xc001117e10 pc=0x114f026
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40ff25?)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e fp=0xc001117e48 sp=0xc001117e28 pc=0x10da4de
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x10da045?, {0x35fdd00, 0xc00107e030}, 0x1, 0xc0010486c0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6 fp=0xc001117ec8 sp=0xc001117e48 pc=0x10da376
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001064188?, 0x3b9aca00, 0x0, 0x0?, 0x7fc554bf34d0?)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89 fp=0xc001117f18 sp=0xc001117ec8 pc=0x10da269
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc001064120, 0xc0010486c0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c5 fp=0xc001117fc0 sp=0xc001117f18 pc=0x113a8c5
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit.func6()
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:128 +0x2f fp=0xc001117fe0 sp=0xc001117fc0 pc=0x245e4af
runtime.goexit()
	/home/travis/.gimme/versions/go1.18.4.linux.amd64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001117fe8 sp=0xc001117fe0 pc=0x46ea01
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:128 +0x5f
...
```

(More stack traces are available on the build link, I trimmed it as GitHub was complaining about the issue text being too long).

**Comment by gandro** [comment]
cc @joamaki

**Comment by joamaki** [comment]
Well oops, looks like it was rather silly to make the assumption that the NodeHandler callbacks are only called sequentially. It seems we have the NodeAdd and NodeUpdate being called concurrently. I'll slap a mutex into to the fake node handler.
