### ISSUE TITLE
Panic while shutting down Cilium agent where some fields were not initialized

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#21264]
```
2022-09-08T22:48:24.759005350Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x268f542]
2022-09-08T22:48:24.759007649Z 
2022-09-08T22:48:24.759009565Z goroutine 407 [running]:
2022-09-08T22:48:24.759011375Z github.com/cilium/cilium/daemon/cmd.NewDaemon.func5()
2022-09-08T22:48:24.759013104Z 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:839 +0x22
2022-09-08T22:48:24.759014773Z github.com/cilium/cilium/daemon/cmd.(*cleanupFuncList).Run(0xc0000733c0)
2022-09-08T22:48:24.759016549Z 	/go/src/github.com/cilium/cilium/daemon/cmd/cleanup.go:44 +0x9d
2022-09-08T22:48:24.759018212Z github.com/cilium/cilium/daemon/cmd.(*daemonCleanup).Clean(0xc000b1b710)
2022-09-08T22:48:24.759019875Z 	/go/src/github.com/cilium/cilium/daemon/cmd/cleanup.go:51 +0x35
2022-09-08T22:48:24.759021812Z github.com/cilium/cilium/daemon/cmd.registerDaemonHooks.func2({0x2977a40, 0x353ae80})
2022-09-08T22:48:24.759023510Z 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1579 +0x30
2022-09-08T22:48:24.759025313Z go.uber.org/fx/internal/lifecycle.(*Lifecycle).runStopHook(0xc000146630, {0x3568240, 0xc00012d5c0}, {0xc000b284b0, 0xc000a67488, {{0xc000a3da00, 0x3a}, {0x3e638eb, 0x31}, 0x14c}})
2022-09-08T22:48:24.759034482Z 	/go/src/github.com/cilium/cilium/vendor/go.uber.org/fx/internal/lifecycle/lifecycle.go:195 +0x208
2022-09-08T22:48:24.759036452Z go.uber.org/fx/internal/lifecycle.(*Lifecycle).Stop(0xc000146630, {0x3568240, 0xc00012d5c0})
2022-09-08T22:48:24.759038148Z 	/go/src/github.com/cilium/cilium/vendor/go.uber.org/fx/internal/lifecycle/lifecycle.go:160 +0x348
2022-09-08T22:48:24.759039870Z go.uber.org/fx.withTimeout.func1()
2022-09-08T22:48:24.759041616Z 	/go/src/github.com/cilium/cilium/vendor/go.uber.org/fx/app.go:784 +0x85
2022-09-08T22:48:24.759043288Z created by go.uber.org/fx.withTimeout
2022-09-08T22:48:24.759044969Z 	/go/src/github.com/cilium/cilium/vendor/go.uber.org/fx/app.go:772 +0xec
```

It looks that we might be trying to access some fields that are not initialized when the daemon is shutting down. The code that panic is
```
	// This is done in preCleanup so that proxy stops serving DNS traffic before shutdown
	cleaner.preCleanupFuncs.Add(func() {
		proxy.DefaultDNSProxy.Cleanup()
	})
```

cc @joamaki

**Comment by joamaki** [comment]
Looks like `proxy.DefaultDNSProxy` is nil if `--enable-l7proxy=false` and this wasn't checked. Surprising we didn't have a test catching this. PR coming in a sec..
