### ISSUE TITLE
Ingress + egress + l7proxy=false results in panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aranselmo** [cilium/cilium#21354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In attempting to test the new 1.12.X ingress functionality in combination with egress on the same server, I ran into situation where my cilium pods would crash the instant an ingress object was created. 

This stemmed from the egress instructions at https://docs.cilium.io/en/latest/network/egress-gateway/#id1 indicating to deploy with l7Proxy=false, but apparently  a hidden dependency of ingress on l7Proxy=true which isn't documented in https://docs.cilium.io/en/latest/network/servicemesh/ingress/

I'm using the latest master branch and deploying with the following parameters
helm install --kube-context aa2 -n kube-system cilium ~/_dev/cilium/install/kubernetes/cilium --set kubeProxyReplacement=strict,k8sServiceHost=10.10.10.61,k8sServicePort=6443,cluster.name=aa-cluster-1,cluster.id=9,ipam.operator.clusterPoolIPv4PodCIDRList="10.237.64.0/18",ingressController.enabled=true,egressGateway.enabled=true,bpf.masquerade=true,l7Proxy=false

The cilium pods come up fine and cilium status showed success, but then as soon as I deploy the ingress below cilium pods crash with the logs message displayed below

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-facerecog-in
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: receiver-service
            port:
              number: 8000
        path: /receiver
        pathType: Prefix
      - backend:
          service:
            name: video-processor
            port:
              number: 8082
        path: /video
        pathType: Prefix
      - backend:
          service:
            name: frontend
            port:
              number: 8081
        path: /frontend
        pathType: Prefix
```

### Cilium Version

1.12.90 latest master branch

### Kernel Version

5.19.8-1.el8.elrepo.x86_64

### Kubernetes Version

v1.24.3

### Sysdump

[cilium-sysdump-20220919-124909.zip](https://github.com/cilium/cilium/files/9599036/cilium-sysdump-20220919-124909.zip)

### Relevant log output

```shell
level=info msg="     _ _ _" subsys=daemon
level=info msg=" ___|_| |_|_ _ _____" subsys=daemon
level=info msg="|  _| | | | | |     |" subsys=daemon
level=info msg="|___|_|_|_|___|_|_|_|" subsys=daemon
level=info msg="Cilium 1.12.90 1d6770ba 2022-09-08T15:27:19+02:00 go version go1.19.1 linux/amd64" subsys=daemon
level=info msg="Envoy version check disabled" subsys=daemon
level=info msg="clang (10.0.0) and kernel (5.19.8) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=warning msg="CONFIG_LWTUNNEL_BPF optional kernel parameter is not in kernel (needed for: Lightweight Tunnel hook for IP-in-IP encapsulation)" subsys=probes
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Mounted cgroupv2 filesystem at /run/cilium/cgroupv2" subsys=cgroups
level=info msg="Parsing base label prefixes from default label list" subsys=labels-filter
level=info msg="Parsing additional label prefixes from user inputs: []" subsys=labels-filter
level=info msg="Final label prefixes to be used for identity evaluation:" subsys=labels-filter
level=info msg=" - reserved:.*" subsys=labels-filter
level=info msg=" - :io\\.kubernetes\\.pod\\.namespace" subsys=labels-filter
level=info msg=" - :io\\.cilium\\.k8s\\.namespace\\.labels" subsys=labels-filter
level=info msg=" - :app\\.kubernetes\\.io" subsys=labels-filter
level=info msg=" - !:io\\.kubernetes" subsys=labels-filter
level=info msg=" - !:kubernetes\\.io" subsys=labels-filter
level=info msg=" - !:.*beta\\.kubernetes\\.io" subsys=labels-filter
level=info msg=" - !:k8s\\.io" subsys=labels-filter
level=info msg=" - !:pod-template-generation" subsys=labels-filter
level=info msg=" - !:pod-template-hash" subsys=labels-filter
level=info msg=" - !:controller-revision-hash" subsys=labels-filter
level=info msg=" - !:annotation.*" subsys=labels-filter
level=info msg=" - !:etcd_node" subsys=labels-filter
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.63.0.0/16
level=info msg=Started subsys=hive
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Using Managed Neighbor Kernel support" subsys=daemon
level=info msg="Trying to auto-enable \"enable-node-port\", \"enable-external-ips\", \"bpf-lb-sock\", \"enable-host-port\", \"enable-session-affinity\" features" subsys=daemon
level=info msg="Inheriting MTU from external network interface" device=eth1 ipAddr=10.10.10.63 mtu=1500 subsys=mtu
level=info msg="L7 proxies are disabled" subsys=daemon
level=warning msg="enable-envoy-config is not functional when L7 proxies are disabled" subsys=daemon
level=info msg="Restored ingress IPs" ingress="[10.237.65.73/32]" subsys=daemon
level=info msg="Restored backends from maps" failedBackends=0 restoredBackends=12 subsys=service
level=info msg="Restored services from maps" failedServices=0 restoredServices=16 subsys=service
level=info msg="Reading old endpoints..." subsys=daemon
level=info msg="Waiting until all Cilium CRDs are available" subsys=k8s
level=info msg="All Cilium CRDs have been found and are available" subsys=k8s
level=info msg="Creating or updating CiliumNode resource" node=r3-aa2-n2 subsys=nodediscovery
level=info msg="Retrieved node information from cilium node" nodeName=r3-aa2-n2 subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.10.10.63 ipAddr.ipv6="<nil>" k8sNodeIP=10.10.10.63 labels="map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:r3-aa2-n2 kubernetes.io/os:linux topology.kubernetes.io/region:r3 topology.kubernetes.io/zone:r3-aa2-2]" nodeName=r3-aa2-n2 subsys=k8s v4Prefix=10.237.65.0/24 v6Prefix="<nil>"
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=info msg="Detected devices" devices="[eth0 eth1]" subsys=linux-datapath
level=info msg="Masquerading IP selected for device" device=eth0 ipv4=192.168.122.220 subsys=node
level=info msg="Masquerading IP selected for device" device=eth1 ipv4=10.10.10.63 subsys=node
level=info msg="Setting gso_max_size to 65536 and gro_max_size to 65536" device=eth0 subsys=big-tcp
level=info msg="Setting gso_max_size to 65536 and gro_max_size to 65536" device=eth1 subsys=big-tcp
level=info msg="Enabling k8s event listener" subsys=k8s-watcher
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Skipping kvstore configuration" subsys=daemon
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=10.237.65.5 ipv6="<nil>" subsys=node
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Initializing cluster-pool IPAM" subsys=ipam v4Prefix=10.237.65.0/24 v6Prefix="<nil>"
level=info msg="Restoring endpoints..." subsys=daemon
level=info msg="Waiting until local node addressing before starting watchers depending on it" subsys=k8s-watcher
level=warning msg="CiliumEgressNATPolicy is deprecated and will be removed in version 1.13. Use CiliumEgressGatewayPolicy instead." subsys=klog
level=warning msg="CiliumEgressNATPolicy is deprecated and will be removed in version 1.13. Use CiliumEgressGatewayPolicy instead." subsys=klog
level=info msg="Endpoints restored" failed=0 restored=5 subsys=daemon
level=info msg="Addressing information:" subsys=daemon
level=info msg="  Cluster-Name: aa-cluster-1" subsys=daemon
level=info msg="  Cluster-ID: 9" subsys=daemon
level=info msg="  Local node-name: r3-aa2-n2" subsys=daemon
level=info msg="  Node-IPv6: <nil>" subsys=daemon
level=info msg="  External-Node IPv4: 10.10.10.63" subsys=daemon
level=info msg="  Internal-Node IPv4: 10.237.65.5" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.237.65.0/24" subsys=daemon
level=info msg="  Loopback IPv4: 169.254.42.1" subsys=daemon
level=info msg="  Local IPv4 addresses:" subsys=daemon
level=info msg="  - 192.168.122.220" subsys=daemon
level=info msg="  - 10.10.10.63" subsys=daemon
level=info msg="  - 10.237.65.5" subsys=daemon
level=info msg="  Ingress IPv4: 10.237.65.73" subsys=daemon
level=info msg="Creating or updating CiliumNode resource" node=r3-aa2-n2 subsys=nodediscovery
level=info msg="Adding local node to cluster" node="{r3-aa2-n2 aa-cluster-1 [{InternalIP 10.10.10.63} {CiliumInternalIP 10.237.65.5}] 10.237.65.0/24 [] <nil> [] 10.237.65.34 <nil> 10.237.65.73 <nil> 9 local 0 map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:r3-aa2-n2 kubernetes.io/os:linux topology.kubernetes.io/region:r3 topology.kubernetes.io/zone:r3-aa2-2] 1 }" subsys=nodediscovery
level=info msg="Waiting until all pre-existing resources have been received" subsys=k8s-watcher
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 376 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2bde7e0?, 0x5112370})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x3110001?})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x2bde7e0, 0x5112370})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/cilium/cilium/pkg/proxy.(*Proxy).AllocateProxyPort(0x0, {0xc00007bbc0, 0x25}, 0x0)
	/go/src/github.com/cilium/cilium/pkg/proxy/proxy.go:401 +0x157
github.com/cilium/cilium/pkg/envoy.ParseResources({0x0?, 0x0?}, {0xc0003071a0, 0x5, 0x0?}, 0x1, {0x7f503d71fbd8, 0x0})
	/go/src/github.com/cilium/cilium/pkg/envoy/ciliumenvoyconfig.go:301 +0xabe
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumEnvoyConfig(0xc000ad1440, 0xc000672b00)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_envoy_config.go:95 +0x368
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumEnvoyConfigInit.func1({0x30d37a0?, 0xc000672b00?})
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_envoy_config.go:40 +0xb7
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:232
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2c4cb40?, 0xc000a916f8?})
	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:108 +0x2a5
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000f9c960, 0xc0010e98c0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x596
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0010e17a0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d9bf?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x10aeb85?, {0x36a3440, 0xc0006e9680}, 0x1, 0xc0003ef1a0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0010e1808?, 0x3b9aca00, 0x0, 0x20?, 0x7f503d75ff80?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0xc0010e17a0, 0xc0003ef1a0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c6
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumEnvoyConfigInit
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_envoy_config.go:83 +0x43b
level=error msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=error msg="goroutine 376 [running]:" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2bde7e0?, 0x5112370})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x3110001?})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75" subsys=klog
level=error msg="panic({0x2bde7e0, 0x5112370})" subsys=klog
level=error msg="\t/usr/local/go/src/runtime/panic.go:884 +0x212" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/proxy.(*Proxy).AllocateProxyPort(0x0, {0xc00007bbc0, 0x25}, 0x0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/proxy/proxy.go:401 +0x157" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/envoy.ParseResources({0x0?, 0x0?}, {0xc0003071a0, 0x5, 0x0?}, 0x1, {0x7f503d71fbd8, 0x0})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/envoy/ciliumenvoyconfig.go:301 +0xabe" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumEnvoyConfig(0xc000ad1440, 0xc000672b00)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_envoy_config.go:95 +0x368" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumEnvoyConfigInit.func1({0x30d37a0?, 0xc000672b00?})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_envoy_config.go:40 +0xb7" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:232" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2c4cb40?, 0xc000a916f8?})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:108 +0x2a5" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000f9c960, 0xc0010e98c0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x596" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0010e17a0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d9bf?)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x10aeb85?, {0x36a3440, 0xc0006e9680}, 0x1, 0xc0003ef1a0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0010e1808?, 0x3b9aca00, 0x0, 0x20?, 0x7f503d75ff80?)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/wait.Until(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).Run(0xc0010e17a0, 0xc0003ef1a0)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c6" subsys=klog
level=error msg="created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumEnvoyConfigInit" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_envoy_config.go:83 +0x43b" subsys=klog
level=fatal msg="Panic in Kubernetes runtime handler" subsys=k8s
level=info msg="Initializing identity allocator" subsys=identity-cache
level=info msg="Allocating identities between range" cluster-id=9 max=65535 min=256 subsys=identity-cache
level=info msg="Initializing ClusterMesh routing" path=/var/lib/cilium/clustermesh/ subsys=daemon
level=info msg="Setting up BPF datapath" bpfClockSource=ktime bpfInsnSet=v3 subsys=datapath-loader
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.core.bpf_jit_enable sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.all.rp_filter sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.fib_multipath_use_neigh sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=kernel.unprivileged_bpf_disabled sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=kernel.timer_migration sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.forwarding sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.rp_filter sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.accept_local sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.send_redirects sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.forwarding sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.rp_filter sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.accept_local sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.send_redirects sysParamValue=0
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="Trace[1458323237]: \"DeltaFIFO Pop Process\" ID:cert-manager/cert-manager-cainjector-6d4984d5f5-ffd5z,Depth:14,Reason:slow event handlers blocking the queue (19-Sep-2022 12:48:21.045) (total time: 472ms):" subsys=klog
level=info msg="Trace[1458323237]: [472.274266ms] [472.274266ms] END" subsys=klog
```

### Anything else?

I was really hoping to use cilium ingress, egress, and wireguard together, but it seems that wirguard and egress aren't able to support l7proxy and ingress is secretly reliant on it.

I highly recommend updating https://docs.cilium.io/en/latest/network/servicemesh/ingress/ to add l7Proxy=true to the deploy steps and make a paragraph calling out the requirement of l7proxy and why ingress needs it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
good spot, thanks for reporting this issue. Just curious if you are keen to contribute on this docs improvement as well.

**Comment by aranselmo** [comment]
I'm glad to review, but I'm afraid I don't know enough about the l7proxy requirement in order to write up anything. 

At minimum though, I'd think just adding to the helm and cli install commands with the l7Proxy=true part and adding a sentence or something indicating why l7proxy is required would be good.

Bonus points if it then points out incompatibilities like wireguard (which can't be used with l7proxy=true apparently) and egress's partial incompatibility with l7proxy.

**Comment by pchaigno** [comment]
> Bonus points if it then points out incompatibilities like wireguard (which can't be used with l7proxy=true apparently) and egress's partial incompatibility with l7proxy.

I think we should just state in the docs that those features are incompatible without discussing l7Proxy and then we should also fatal in the agent if someone tries to use both features at the same time.

**Comment by sayboras** [comment]
seems related to this https://github.com/cilium/cilium/issues/18773 as well.

**Comment by gandro** [comment]
> > Bonus points if it then points out incompatibilities like wireguard (which can't be used with l7proxy=true apparently) and egress's partial incompatibility with l7proxy.
> 
> I think we should just state in the docs that those features are incompatible without discussing l7Proxy and then we should also fatal in the agent if someone tries to use both features at the same time.

For WireGuard, we already do this:
https://github.com/cilium/cilium/blob/54f3e7c67402943fb85f85733a02c0bb8e2d100f/daemon/cmd/daemon_main.go#L1620-L1623

I agree that we should extend the check to other features that are known to not work.

**Comment by aranselmo** [comment]
Just as a heads up. This same error occurs not only for ingress but also for --set-string extraConfig.enable-envoy-config=true and deploying a CiliumClusterwideEnvoyConfig

Which probably makes sense but just wanted to make sure in case it needs to be looked at in two places of code

**Comment by aranselmo** [comment]
Just out of curiosity, is there any roadmap to supporting wireguard encryption with l7proxy enabled? As it is, ingress/envoy seems to preclude any use of encryption since wireguard won't work with the hidden l7proxy=true requirement and ipsec won't work with proxy replacement?

**Comment by gandro** [comment]
> Just out of curiosity, is there any roadmap to supporting wireguard encryption with l7proxy enabled? As it is, ingress/envoy seems to preclude any use of encryption since wireguard won't work with the hidden l7proxy=true requirement and ipsec won't work with proxy replacement?

Yes: #19401 

However it's currently a low-priority item for 1.13.

**Comment by youngnick** [comment]
Now that running Wireguard and L7proxy are supported together, the easiest way to stop this happening is to add validation rules to the Helm chart, which will prevent people from having Ingress or Gateway API supported _enabled_ with Layer 7 routing support _disabled_.
