### ISSUE TITLE
Panic when agent receives shutdown signal during startup

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#21585]
When the agent receives a shutdown signal shortly after starting, it sometimes panic:
```
01:24:22.171066016Z level=info msg="Shutting down... " subsys=daemon
01:24:22.171135682Z level=info msg="Exiting due to signal" signal=terminated subsys=daemon
01:24:22.171145268Z level=info msg="HTTP server Shutdown: context deadline exceeded" subsys=daemon
01:24:22.171152535Z level=info msg="Stopped serving cilium API at unix:///var/run/cilium/cilium.sock" subsys=daemon
01:24:22.171159295Z level=info msg="Finished regenerating restored endpoints" regenerated=1 subsys=daemon total=2
01:24:22.171184499Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_calls_01154 subsys=daemon
01:24:22.171756178Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_policy_01154 subsys=daemon
01:24:22.171785750Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_lb4_source_range subsys=daemon
01:24:22.240990659Z level=info msg="Waiting for all endpoints' go routines to be stopped." subsys=daemon
01:24:22.241267438Z level=info msg="All endpoints' goroutines stopped." subsys=daemon
01:24:22.244801620Z panic: runtime error: invalid memory address or nil pointer dereference
01:24:22.244943481Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2320cc2]
01:24:22.244969643Z 
01:24:22.244976479Z goroutine 56 [running]:
01:24:22.244981271Z github.com/cilium/cilium/daemon/cmd.NewDaemon.func4()
01:24:22.244986296Z 	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:685 +0x22
01:24:22.244999524Z github.com/cilium/cilium/daemon/cmd.(*cleanupFuncList).Run(0x481d600)
01:24:22.245052275Z 	/go/src/github.com/cilium/cilium/daemon/cmd/cleanup.go:55 +0x9d
01:24:22.245064558Z github.com/cilium/cilium/daemon/cmd.(*daemonCleanup).registerSigHandler.func1()
01:24:22.245136062Z 	/go/src/github.com/cilium/cilium/daemon/cmd/cleanup.go:74 +0x249
01:24:22.245168347Z created by github.com/cilium/cilium/daemon/cmd.(*daemonCleanup).registerSigHandler
01:24:22.245225358Z 	/go/src/github.com/cilium/cilium/daemon/cmd/cleanup.go:63 +0x145
```
We can see that it wasn't started long ago from the `Finished regenerating restored endpoints` log.

This is happening on v1.11.9.

**Comment by akash-gautam** [comment]
@aanm Not yet, I will start with it soon.

**Comment by akash-gautam** [comment]
@aanm Unfortunately I won't be able to make time for this in the next few weeks so it might be better to unassign me so that other folks can take this up if they want.

**Comment by christarazi** [comment]
@mjgrzybek Are you looking into this issue?

**Comment by joestringer** [comment]
This was originally reported in v1.11.x which is no longer maintained. I suggest we close this for now and re-open if there are clear reproduction instructions.
