### ISSUE TITLE
CI: [Travis] github.com/cilium/cilium/daemon/cmd  panic: send on closed channel    

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#21852]
See in https://app.travis-ci.com/github/cilium/cilium/jobs/586349585
```
goroutine 675 [running]:                                                                                                                          
github.com/cilium/cilium/pkg/identity/cache.(*localIdentityCache).release(0x400097f400, 0x40009aa300)                                             
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/local.go:139 +0x148                                                           
github.com/cilium/cilium/pkg/identity/cache.(*CachingIdentityAllocator).Release(0x40001eaf60, {0x3159220, 0x4000757140}, 0x40009aa300, 0x0?)      
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/allocator.go:427 +0x2bc                                                       
github.com/cilium/cilium/pkg/ipcache.(*IPCache).releaseCIDRIdentities(0x40003c3280, {0x3159220, 0x4000757140}, {0x40009aa4c0, 0x2, 0x400105f1f0?})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:220 +0x208                                                                   
github.com/cilium/cilium/pkg/ipcache.(*asyncPrefixReleaser).run(0x40000c9130, {0x3159220, 0x4000757140}, {0x400105f1e0, 0x1, 0x1})                
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/gc.go:103 +0x1ac                                                                     
github.com/cilium/cilium/pkg/ipcache.newAsyncPrefixReleaser.func1({0x400105f1e0, 0x1, 0x1})                                                       
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/gc.go:53 +0x84                                                                       
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0x40000fed20)                                                                              
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x45c                                                                
created by github.com/cilium/cilium/pkg/trigger.NewTrigger                                                                                        
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:122 +0x1b8      
```

@joestringer This seems to have been caused by https://github.com/cilium/cilium/commit/4afbcc38ce91118f1cb4a9f715a268775cdf7f6e

**Comment by joestringer** [comment]
:+1: initial triage is that the unit tests shut down the identity allocator and the ipcache in the wrong order that can trigger this race condition / crash. The identity allocator is not currently integrated into the main `Daemon.Close()` function so this only impacts the testsuite. We should be able to move identtiy allocator cleanup into that function.
