### ISSUE TITLE
CI: PANIC  package: github.com/cilium/cilium/daemon/cmd

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#22410]
## CI failure

saw this failure in travis CI: https://app.travis-ci.com/github/cilium/cilium/jobs/589683447

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   PANIC  package: github.com/cilium/cilium/daemon/cmd • Test   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

panic: send on closed channel

goroutine 723 [running]:

github.com/cilium/cilium/pkg/identity/cache.(*localIdentityCache).release(0x4000624d80, 0x4000710340)
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/local.go:139 +0x148
github.com/cilium/cilium/pkg/identity/cache.(*CachingIdentityAllocator).Release(0x400051daa0, {0x325eb40, 0x4001126660}, 0x4000710340, 0x6f?)
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/allocator.go:427 +0x2bc
github.com/cilium/cilium/pkg/ipcache.(*IPCache).releaseCIDRIdentities(0x4000fd5300, {0x325eb40, 0x4001126660}, {0x4000710600, 0x2, 0x400171ee00?})
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:220 +0x208
github.com/cilium/cilium/pkg/ipcache.(*asyncPrefixReleaser).run(0x4000783270, {0x325eb40, 0x4001126660}, {0x400171edf0, 0x1, 0x1})
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/gc.go:103 +0x1ac
github.com/cilium/cilium/pkg/ipcache.newAsyncPrefixReleaser.func1({0x400171edf0, 0x1, 0x1})
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/gc.go:53 +0x84
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0x4000a15c20)
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x45c
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
        /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:122 +0x1b8

FAIL    github.com/cilium/cilium/daemon/cmd     11.814s
```

it's from this pull request: https://github.com/cilium/cilium/pull/22409 this pull request only touches hubble L7 parser, so i don't think the failure is caused by this change 🤔

**Comment by christarazi** [comment]
Dup of https://github.com/cilium/cilium/issues/21852.
