### ISSUE TITLE
CI: controlplane tests crash with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22430]
Master branch today at commit d095e010883e during v1.13 dev cycle:

```
$ go test -count=1 ./test/controlplane/
level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config
level=error msg="Invoke failed" ="cmd.glob..func2 (daemon_main.go:1627)" error="could not build arguments for function \"github.com/cilium/cilium/daemon/cmd\".glob..func2 (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1627): failed to build promise.Promise[*github.com/cilium/cilium/daemon/cmd.Daemon]: could not build arguments for function \"github.com/cilium/cilium/daemon/cmd\".newDaemonPromise (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1642): failed to build *agent.Controller: missing dependencies for function \"github.com/cilium/cilium/pkg/bgpv1/agent\".NewController (/home/joe/git/cilium/pkg/bgpv1/agent/controller.go:188): missing type: *option.DaemonConfig" subsys=hive
level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config
level=error msg="Invoke failed" ="cmd.glob..func2 (daemon_main.go:1627)" error="could not build arguments for function \"github.com/cilium/cilium/daemon/cmd\".glob..func2 (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1627): failed to build promise.Promise[*github.com/cilium/cilium/daemon/cmd.Daemon]: could not build arguments for function \"github.com/cilium/cilium/daemon/cmd\".newDaemonPromise (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1642): failed to build *agent.Controller: missing dependencies for function \"github.com/cilium/cilium/pkg/bgpv1/agent\".NewController (/home/joe/git/cilium/pkg/bgpv1/agent/controller.go:188): missing type: *option.DaemonConfig" subsys=hive
--- FAIL: TestControlPlane (0.00s)
    --- FAIL: TestControlPlane/CNPStatusNodesGC (0.00s)
        testcase.go:144: Failed to start cilium agent: could not build arguments for function "github.com/cilium/cilium/daemon/cmd".glob..func2 (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1627): failed to build promise.Promise[*github.com/cilium/cilium/daemon/cmd.Daemon]: could not build arguments for function "github.com/cilium/cilium/daemon/cmd".newDaemonPromise (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1642): failed to build *agent.Controller: missing dependencies for function "github.com/cilium/cilium/pkg/bgpv1/agent".NewController (/home/joe/git/cilium/pkg/bgpv1/agent/controller.go:188): missing type: *option.DaemonConfig
    --- FAIL: TestControlPlane/IdentityGC (0.00s)
        testcase.go:144: Failed to start cilium agent: could not build arguments for function "github.com/cilium/cilium/daemon/cmd".glob..func2 (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1627): failed to build promise.Promise[*github.com/cilium/cilium/daemon/cmd.Daemon]: could not build arguments for function "github.com/cilium/cilium/daemon/cmd".newDaemonPromise (/home/joe/git/cilium/daemon/cmd/daemon_main.go:1642): failed to build *agent.Controller: missing dependencies for function "github.com/cilium/cilium/pkg/bgpv1/agent".NewController (/home/joe/git/cilium/pkg/bgpv1/agent/controller.go:188): missing type: *option.DaemonConfig
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2a972fd]

goroutine 164 [running]:
testing.tRunner.func1.2({0x2ea5ce0, 0x572ea10})
        /snap/go/current/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /snap/go/current/src/testing/testing.go:1399 +0x39f
panic({0x2ea5ce0, 0x572ea10})
        /snap/go/current/src/runtime/panic.go:884 +0x212
github.com/cilium/cilium/test/controlplane/suite.(*agentHandle).tearDown(0x0)
        /home/joe/git/cilium/test/controlplane/suite/agent.go:33 +0x1d
github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StopAgent(0xc000ea6820)
        /home/joe/git/cilium/test/controlplane/suite/testcase.go:152 +0x25
panic({0x2ea5ce0, 0x572ea10})
        /snap/go/current/src/runtime/panic.go:884 +0x212
github.com/cilium/cilium/test/controlplane/suite.(*operatorHandle).tearDown(0x0)
        /home/joe/git/cilium/test/controlplane/suite/operator.go:19 +0x19
github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StopOperator(0xc000ea6820)
        /home/joe/git/cilium/test/controlplane/suite/testcase.go:190 +0x25
runtime.Goexit()
        /snap/go/current/src/runtime/panic.go:522 +0x185
testing.(*common).FailNow(0xc0001031e0)
        /snap/go/current/src/testing/testing.go:871 +0x4c
testing.(*common).Fatalf(0xc0001031e0, {0x34d5732?, 0x347f671?}, {0xc000f11e70?, 0xc000e9ee80?, 0x30?})
        /snap/go/current/src/testing/testing.go:955 +0x65
github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StartAgent(0xc000ea6820)
        /home/joe/git/cilium/test/controlplane/suite/testcase.go:144 +0x1bb
github.com/cilium/cilium/test/controlplane/identities.init.0.func1(0x0?)
        /home/joe/git/cilium/test/controlplane/identities/identity_gc.go:147 +0xea
testing.tRunner(0xc0001031e0, 0x3650068)
        /snap/go/current/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /snap/go/current/src/testing/testing.go:1493 +0x35f
FAIL    github.com/cilium/cilium/test/controlplane      0.037s
FAIL
```

**Comment by joestringer** [comment]
Duplicate of #22224
