### ISSUE TITLE
CI: ERROR: libFuzzer: out-of-memory (used: 2563Mb; limit: 2560Mb)

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#22459]
Seen in https://github.com/cilium/cilium/actions/runs/3587050351/jobs/6036956527
```
#128	pulse  cov: 576 ft: 1397 corp: 40/1493b exec/s: 12 rss: 2222Mb
==237== ERROR: libFuzzer: out-of-memory (used: 2563Mb; limit: 2560Mb)
   To change the out-of-memory limit use -rss_limit_mb=<N>

Live Heap Allocations: 25402573 bytes in 2026 chunks; quarantined: 2513583 bytes in 5779 chunks; 8112 other chunks; total chunks: 15917; showing top 95% (at most 8 unique contexts)
24120920 byte(s) (94%) in 11 allocation(s)
    #0 0x52ef96 in __interceptor_malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x4ad997 in operator new(unsigned long) cxa_noexception.cpp
    #2 0x458342 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #3 0x7fc464c6f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: __interceptor_malloc--operator new(unsigned long)--main
1048576 byte(s) (4%) in 1 allocation(s)
    #0 0x52ef96 in __interceptor_malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x4ad997 in operator new(unsigned long) cxa_noexception.cpp
    #2 0x43f689 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
    #3 0x42ecef in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #4 0x458342 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #5 0x7fc464c6f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: __interceptor_malloc--operator new(unsigned long)--fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&)
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x7f,0x45,0x4c,0x46,0x1,0x1,0x1,0x2f,0x2c,0x1,0x0,0xff,0x0,0x81,0x81,0x7e,0x5,0xf,0xfb,0x45,0x1,0x46,0x10,0xf,0xf,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xa,0x0,0x0,0x0,0x0,0x1,0x8,0x0,0x4,0x0,0x0,0x0,0x31,0x10,0x0,0x0,0x15,0xff,0x0,0x0,
\177ELF\001\001\001/,\001\000\377\000\201\201~\005\017\373E\001F\020\017\017\000\000\000\000\000\000\000\012\000\000\000\000\001\010\000\004\000\000\0001\020\000\000\025\377\000\000
artifact_prefix='/tmp/tmpz2a9n7jy/'; Test unit written to /tmp/tmpz2a9n7jy/oom-7b102ba1ae7fd10051c50f4fbd9d2caaa9548177
Base64: f0VMRgEBAS8sAQD/AIGBfgUP+0UBRhAPDwAAAAAAAAAKAAAAAAEIAAQAAAAxEAAAFf8AAA==
SUMMARY: libFuzzer: out-of-memory
stat::number_of_executed_units: 220
stat::average_exec_per_sec:     7
stat::new_units_added:          0
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              2564
2022-11-30 21:28:05,387 - root - INFO - Fuzzer: fuzz_elf_open. Detected bug.
2022-11-30 21:28:05,389 - root - INFO - Trying to reproduce crash using: /tmp/tmpz2a9n7jy/oom-7b102ba1ae7fd10051c50f4fbd9d2caaa9548177.
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 95, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 91, in main
    return run_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 61, in run_fuzzers_entrypoint
    result = run_fuzzers.run_fuzzers(config)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 302, in run_fuzzers
    if not fuzz_target_runner.run_fuzz_targets():
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 130, in run_fuzz_targets
    result = self.run_fuzz_target(target)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 245, in run_fuzz_target
    return fuzz_target_obj.fuzz()
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 187, in fuzz
    if self.is_crash_reportable(crash.input_path,
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 289, in is_crash_reportable
    reproducible_on_code_change = self.is_reproducible(
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 250, in is_reproducible
    result = engine_impl.reproduce(target_path,
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 391, in reproduce
    raise TimeoutError('Reproducing timed out\n' + result.output)
TimeoutError: Reproducing timed out
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1337
INFO: Loaded 1 modules   (7101 inline 8-bit counters): 7101 [0x126ee88, 0x1270a45), 
INFO: Loaded 1 PC tables (7101 PCs): 7101 [0x10c000080000,0x10c00009bbd0), 
/github/workspace/build-out/fuzz_elf_open: Running 1 inputs 100 time(s) each.
Running: /tmp/tmpz2a9n7jy/oom-7b102ba1ae7fd10051c50f4fbd9d2caaa95[481](https://github.com/cilium/cilium/actions/runs/3587050351/jobs/6036956527#step:5:482)77
```

Disabling workflow as a consequence https://github.com/cilium/cilium/actions/workflows/tests-cifuzz.yaml

/cc @DavidKorczynski

**Comment by joestringer** [comment]
Worth also considering whether fuzz_elf_open here is just fuzzing the upstream golang `debug/elf` libraries or is there actually a Cilium aspect to this. Longer term we'll get rid of those code paths through https://github.com/cilium/cilium/issues/22245 anyway, at which point we'll probably want to get rid of this fuzzer since the underlying code goes away.

**Comment by aanm** [comment]
cc @AdamKorcz

**Comment by AdamKorcz** [comment]
It looks like a fuzzer is finding an OOM-issue here: Not a Golang OOM panic but the fuzzer allocates more memory than OSS-Fuzz  has allowed it.
