### ISSUE TITLE
CI: RuntimeDatapathPrivilegedUnitTests Run Tests / TestControlPlane/IdentityGC

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#22470]
### Test Name

```shell
RuntimeDatapathPrivilegedUnitTests Run Tests
github.com/cilium/cilium/test/controlplane • TestControlPlane/IdentityGC
```

### Failure Output

```shell
[19:26:19] �[38;5;103m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓�[0m
	 [19:26:19] �[38;5;103m┃�[0m   �[91m�[91mPANIC�[0m�[0m  package: github.com/cilium/cilium/test/controlplane • TestControlPlane/IdentityGC   �[38;5;103m┃�[0m
	 [19:26:19] �[38;5;103m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛�[0m
	 [19:26:19] panic: close of closed channel                                                                  
	 [19:26:19]                                                                                                 
	 [19:26:19] goroutine 508 [running]:                                                                        
	 [19:26:19] github.com/cilium/cilium/operator/cmd.startSynchronizingCiliumNodes.func9()                     
	 [19:26:19] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/cilium_node.go:225 +0x129            
	 [19:26:19] created by github.com/cilium/cilium/operator/cmd.startSynchronizingCiliumNodes                  
	 [19:26:19] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/cilium_node.go:223 +0xd18            
	 [19:26:19] FAIL	github.com/cilium/cilium/test/controlplane	0.544s                                            
	 [19:26:19]                                                                                                 
	 [19:26:19] ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
	 [19:26:19] │  STATUS │ ELAPSED │                             PACKAGE                             │ COVER  │ PASS │ FAIL │ SKIP  │
	 [19:26:19] │─────────┼─────────┼─────────────────────────────────────────────────────────────────┼────────┼──────┼──────┼───────│
	 [19:26:19] │  �[91mPANIC�[0m  │  0.00s  │ github.com/cilium/cilium/test/controlplane                      │   --   │  --  │  --  │  --   │
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
```

### Standard Output

```shell
[19:26:19] �[38;5;103m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓�[0m
	 [19:26:19] �[38;5;103m┃�[0m   �[91m�[91mPANIC�[0m�[0m  package: github.com/cilium/cilium/test/controlplane • TestControlPlane/IdentityGC   �[38;5;103m┃�[0m
	 [19:26:19] �[38;5;103m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛�[0m
	 [19:26:19] panic: close of closed channel                                                                  
	 [19:26:19]                                                                                                 
	 [19:26:19] goroutine 508 [running]:                                                                        
	 [19:26:19] github.com/cilium/cilium/operator/cmd.startSynchronizingCiliumNodes.func9()                     
	 [19:26:19] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/cilium_node.go:225 +0x129            
	 [19:26:19] created by github.com/cilium/cilium/operator/cmd.startSynchronizingCiliumNodes                  
	 [19:26:19] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/cilium_node.go:223 +0xd18            
	 [19:26:19] FAIL	github.com/cilium/cilium/test/controlplane	0.544s                                            
	 [19:26:19]                                                                                                 
	 [19:26:19] ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
	 [19:26:19] │  STATUS │ ELAPSED │                             PACKAGE                             │ COVER  │ PASS │ FAIL │ SKIP  │
	 [19:26:19] │─────────┼─────────┼─────────────────────────────────────────────────────────────────┼────────┼──────┼──────┼───────│
	 [19:26:19] │  �[91mPANIC�[0m  │  0.00s  │ github.com/cilium/cilium/test/controlplane                      │   --   │  --  │  --  │  --   │
```

### Standard Error

```shell
make: *** [Makefile:124: tests-privileged] Error 1
```

### Resources

- Jenkins URL:  https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4119/testReport/junit/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/
- ZIP file(s): 
[3e851d6a_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/10130931/3e851d6a_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip)

### Anything else?

close of closed channel happens here in `operator/cmd/cilium_node.go`:
```
	go func() {
		cache.WaitForCacheSync(ctx.Done(), ciliumNodeInformer.HasSynced)
		close(k8sCiliumNodesCacheSynced)
```

**Comment by jrajahalme** [comment]
Looks like `ControlPlaneTest.StopOperator()` should wait for the go-routine at https://github.com/cilium/cilium/blob/master/operator/cmd/cilium_node.go#L223-L251 to finish before allowing `StartOperator()` to be called again?

**Comment by jrajahalme** [comment]
Another failure on the same test, panic on close of another channel: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4131/

**Comment by joamaki** [comment]
Will take a look at fixing this. Btw, also related is: https://github.com/cilium/cilium/issues/21818.

**Comment by joestringer** [comment]
Following @pippolo84 's pointer above, I'll close this as "fixed". If anyone observes this again later, we can always choose to reopen the investigation.
