### ISSUE TITLE
kafka: producing messages denied by policy crashes Cilium agent

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#2255]
- Cilium version:
`Cilium 1.0.0-rc2 40557c1 Sun, 3 Dec 2017 22:10:46 +0100 go version go1.9 linux/amd64`
- Kernel version:
`Linux minikube 4.9.13 #1 SMP Thu Oct 19 17:14:00 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: Kubernetes 1.8.0
`Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}`

I run the `kafka-console-producer.sh` script which is shipped with Kafka 0.10.1.0, to produce a message into a topic, which is not allowed by Cilium policy (only `fetch` and a few other `apiKey`s, but not `produce`).

This crashes the Cilium agent every single time with the following logs:
```
time="2017-12-05T07:41:48Z" level=debug msg="Proxying request Kafka connection" from="rx:10.15.42.253:41086->10.15.28.238:10000" to="tx:closed"
time="2017-12-05T07:41:48Z" level=debug msg="Handling Kafka request" id="rx:10.15.42.253:41086->10.15.28.238:10000<->tx:closed" req="apiKey=3,apiVersion=2,len=45: {\"Version\":2,\"CorrelationID\":0,\"ClientID\":\"console-producer\",\"Topics\":[\"authaudit\"],\"AllowAutoTopicCreation\":false}"
time="2017-12-05T07:41:48Z" level=debug msg="Found IPv4 proxy entry" obj="10.15.59.20:9092"
time="2017-12-05T07:41:48Z" level=debug msg="Applying rule" req="apiKey=3,apiVersion=2,len=45: {\"Version\":2,\"CorrelationID\":0,\"ClientID\":\"console-producer\",\"Topics\":[\"authaudit\"],\"AllowAutoTopicCreation\":false}" rule="[{\"apiKey\":\"fetch\",\"topic\":\"authaudit\"},{\"apiKey\":\"apiversions\"},{\"apiKey\":\"metadata\"},{\"apiKey\":\"findcoordinator\"},{\"apiKey\":\"joingroup\"},{\"apiKey\":\"leavegroup\"},{\"apiKey\":\"syncgroup\"},{\"apiKey\":\"offsets\"},{\"apiKey\":\"offsetcommit\"},{\"apiKey\":\"offsetfetch\"},{\"apiKey\":\"heartbeat\"}]"
time="2017-12-05T07:41:48Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=3,apiVersion=2,len=45: {\"Version\":2,\"CorrelationID\":0,\"ClientID\":\"console-producer\",\"Topics\":[\"authaudit\"],\"AllowAutoTopicCreation\":false}" rule.kafka="{ fetch  authaudit 0xc4206d4830 <nil>}"
time="2017-12-05T07:41:48Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=3,apiVersion=2,len=45: {\"Version\":2,\"CorrelationID\":0,\"ClientID\":\"console-producer\",\"Topics\":[\"authaudit\"],\"AllowAutoTopicCreation\":false}" rule.kafka="{ apiversions   0xc4206d4832 <nil>}"
time="2017-12-05T07:41:48Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=3,apiVersion=2,len=45: {\"Version\":2,\"CorrelationID\":0,\"ClientID\":\"console-producer\",\"Topics\":[\"authaudit\"],\"AllowAutoTopicCreation\":false}" rule.kafka="{ metadata   0xc4206d4834 <nil>}"
time="2017-12-05T07:41:48Z" level=debug msg="Dialing original destination" destination="10.15.59.20:9092" id="rx:10.15.42.253:41086->10.15.28.238:10000<->tx:closed" marker=4277797187
time="2017-12-05T07:41:48Z" level=debug msg="Setting packet marker of socket" fd=42 marker=4277797187
time="2017-12-05T07:41:48Z" level=debug msg="Forwarding Kafka request" id="rx:10.15.42.253:41086->10.15.28.238:10000<->tx:closed"
time="2017-12-05T07:41:48Z" level=debug msg="Logging Kafka L7 flow record" code=0 kafkaApiKey=metadata kafkaApiVersion=2 kafkaCorrelationID=0 type=Request verdict=Forwarded
time="2017-12-05T07:41:48Z" level=debug msg="Skipping writing to access log (logger nil)" file-path=
time="2017-12-05T07:41:48Z" level=debug msg="Enqueueing response message" conn="tx:0.0.0.0:0->nil" size=45
time="2017-12-05T07:41:48Z" level=debug msg="Proxying response Kafka connection" from="tx:0.0.0.0:0->nil" to="rx:10.15.42.253:41086->10.15.28.238:10000"
time="2017-12-05T07:41:48Z" level=debug msg="Enqueueing request message" conn="rx:10.15.42.253:41086->10.15.28.238:10000" size=105
time="2017-12-05T07:41:49Z" level=debug msg="Proxying request Kafka connection" from="rx:10.15.42.253:41092->10.15.28.238:10000" to="tx:closed"
time="2017-12-05T07:41:49Z" level=debug msg="Ignoring Kafka message due to parse error" error="cannot decode message: unexpected EOF" request.kafka="apiKey=0,apiVersion=2,len=101: null"
time="2017-12-05T07:41:49Z" level=debug msg="Handling Kafka request" id="rx:10.15.42.253:41092->10.15.28.238:10000<->tx:closed" req="apiKey=0,apiVersion=2,len=101: null"
time="2017-12-05T07:41:49Z" level=debug msg="Found IPv4 proxy entry" obj="10.15.59.20:9092"
time="2017-12-05T07:41:49Z" level=debug msg="Applying rule" req="apiKey=0,apiVersion=2,len=101: null" rule="[{\"apiKey\":\"fetch\",\"topic\":\"authaudit\"},{\"apiKey\":\"apiversions\"},{\"apiKey\":\"metadata\"},{\"apiKey\":\"findcoordinator\"},{\"apiKey\":\"joingroup\"},{\"apiKey\":\"leavegroup\"},{\"apiKey\":\"syncgroup\"},{\"apiKey\":\"offsets\"},{\"apiKey\":\"offsetcommit\"},{\"apiKey\":\"offsetfetch\"},{\"apiKey\":\"heartbeat\"}]"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ fetch  authaudit 0xc4206d4830 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ apiversions   0xc4206d4832 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ metadata   0xc4206d4834 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ findcoordinator   0xc4206d4836 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ joingroup   0xc4206d4838 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ leavegroup   0xc4206d483a <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ syncgroup   0xc4206d483c <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ offsets   0xc4206d483e <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ offsetcommit   0xc4206d4840 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ offsetfetch   0xc4206d4842 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Matching Kafka rule" request.kafka="apiKey=0,apiVersion=2,len=101: null" rule.kafka="{ heartbeat   0xc4206d4844 <nil>}"
time="2017-12-05T07:41:49Z" level=debug msg="Kafka request is denied by policy" id="rx:10.15.42.253:41092->10.15.28.238:10000<->tx:closed"
time="2017-12-05T07:41:49Z" level=debug msg="Logging Kafka L7 flow record" code=29 kafkaApiKey=produce kafkaApiVersion=2 kafkaCorrelationID=1 type=Request verdict=Denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15e00e7]

goroutine 1459 [running]:
github.com/cilium/cilium/pkg/kafka.produceTopics(0x0, 0xc400000005, 0xc4207abb60, 0x1c)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/kafka/request.go:95 +0x37
github.com/cilium/cilium/pkg/kafka.(*RequestMessage).GetTopics(0xc4209257a0, 0xc420b1bc68, 0x1, 0x1)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/kafka/request.go:79 +0x272
github.com/cilium/cilium/pkg/proxy.(*kafkaLogRecord).log(0xc42115e340, 0x1c3ee1f, 0x7, 0x1c3d3be, 0x6, 0x1d, 0xc4211c4240, 0x21)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/proxy/kafka.go:233 +0x5dd
github.com/cilium/cilium/pkg/proxy.(*kafkaRedirect).handleRequest(0xc42024d180, 0xc420c33a80, 0xc4209257a0)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/proxy/kafka.go:270 +0xd34
github.com/cilium/cilium/pkg/proxy.(*kafkaRedirect).(github.com/cilium/cilium/pkg/proxy.handleRequest)-fm(0xc420c33a80, 0xc4209257a0)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/proxy/kafka.go:374 +0x3e
github.com/cilium/cilium/pkg/proxy.handleRequest(0xc420c33a80, 0xc4209256e0, 0x0, 0xc420b1bfa0)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/proxy/kafka.go:339 +0x295
github.com/cilium/cilium/pkg/proxy.(*kafkaRedirect).handleRequestConnection(0xc42024d180, 0xc420c33a80)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/proxy/kafka.go:374 +0x1cd
created by github.com/cilium/cilium/pkg/proxy.createKafkaRedirect.func1
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/proxy/kafka.go:122 +0x183
```

The producer fails with the following output:
```
[2017-12-05 07:41:49,765] WARN Got error produce response with correlation id 1 on topic-partition authaudit-0, retrying (2 attempts left). Error: NETWORK_EXCEPTION (org.apache.kafka.clients.producer.internals.Sender)
[2017-12-05 07:41:50,867] WARN Got error produce response with correlation id 4 on topic-partition authaudit-0, retrying (1 attempts left). Error: NETWORK_EXCEPTION (org.apache.kafka.clients.producer.internals.Sender)
[2017-12-05 07:41:51,970] WARN Got error produce response with correlation id 6 on topic-partition authaudit-0, retrying (0 attempts left). Error: NETWORK_EXCEPTION (org.apache.kafka.clients.producer.internals.Sender)
[2017-12-05 07:41:53,074] ERROR Error when sending message to topic authaudit with key: null, value: 4 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.
```

**Comment by manalibhutiyani** [comment]
That seems weird. We do handle `apiVersion=2` and produce messages. Will take a look

**Comment by rlenglet** [comment]
The problem may be the "unexpected EOF". Unfortunately I was grepping the logs for "kafka" and couldn't collect the full logs before the agent restarted.

**Comment by rlenglet** [comment]
Could be a duplicate of #2231.

**Comment by rlenglet** [comment]
This log message looks suspicious:
```
msg="Enqueueing response message" conn="tx:0.0.0.0:0->nil" size=45
```
It looks like the connection wasn't open correctly, although it's open just above, in `kafkaRedirect.handleRequest`.

**Comment by rlenglet** [comment]
FYI, the IP addresses are:
* 10.15.42.253: producer
* 10.15.59.20: kafka broker (where the policy is enforced at ingress)
* 10.15.28.238: compute node (single-node cluster)

**Comment by rlenglet** [comment]
I think the connection handling in `kafkaRedirect.handleRequest` is incorrect.

1. There is a connection to the server, i.e. `pair.tx.conn` is not `nil`, and it's closed, which is why it shows up as `tx:closed` in the logs.
2. Because the connection is closed, a new connection is open, which is a correct behavior, cf. https://github.com/cilium/cilium/blob/master/pkg/proxy/kafka.go#L285, https://github.com/cilium/cilium/blob/master/pkg/proxy/kafka.go#L296.
3. The opening of this connection succeeds, because we see no `"Unable to dial original destination"` error message.
4. The connection is attempted to be assigned to `pair.tx`, cf. https://github.com/cilium/cilium/blob/master/pkg/proxy/kafka.go#L305.
5. However, because the current connection is not `nil`, the implementation of `proxyConnection.SetConnection` does not replace the current, closed connection with the new, open connection. Cf. https://github.com/cilium/cilium/blob/master/pkg/proxy/socket.go#L147.

I think it is the implementation of `proxyConnection.SetConnection` that is buggy. It should replace the existing connection if the current `c.conn` is **either `nil` OR closed**.

Alternatively, `c.conn` should be set to `nil` wherever the connection is detected to be closed.
But that would require changing at least 2 methods in the Kafka proxy and probably other places in Oxy:
https://github.com/cilium/cilium/blob/master/pkg/proxy/kafka.go#L327
https://github.com/cilium/cilium/blob/master/pkg/proxy/kafka.go#L350

@manalibhutiyani, @tgraf, what's your preference?

**Comment by rlenglet** [comment]
Nope, I was wrong. `c.conn` is already `nil`, which is why it shows as `tx:closed`.
This is not the bug.

**Comment by rlenglet** [comment]
This log message also looks suspicious:
```
msg="Proxying request Kafka connection" from="rx:10.15.42.253:41092->10.15.28.238:10000" to="tx:closed"
```
`tx` shouldn't be closed at this point. This indicates that `tx.conn` is `nil`, which shouldn't happen since the connection just got opened.

**Comment by rlenglet** [comment]
This log message indicates that the `ciliumDialer` function returned a non-`nil` `net.Conn` connection which was improperly initialized with a zero `LocalAddr()` and a `nil` `RemoteAddr()`:
```
msg="Enqueueing response message" conn="tx:0.0.0.0:0->nil" size=45
```

**Comment by tgraf** [comment]
The kafka parser does not initialize the Topics slice on error:
``` golang
        if err != nil {
                return nil, err
        }
        req.Topics = make([]string, len)
```

But it returns nil so I'm not sure how the panic can happen yet
