### ISSUE TITLE
CI: Travis: nil pointer derference in `github.com/cilium/cilium/pkg/azure/ipam `

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#22550]
## CI failure

- Observed in https://github.com/cilium/cilium/pull/22533 which does not contain any code changes
- https://app.travis-ci.com/github/cilium/cilium/jobs/590254288#L539
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                               
┃   PANIC  package: github.com/cilium/cilium/pkg/azure/ipam • Test   ┃                                                               
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                               
panic: runtime error: invalid memory address or nil pointer dereference                                                              
[signal SIGSEGV: segmentation violation code=0x1 addr=0x248 pc=0x1cddded]                                                            

                                                                                                                                   
goroutine 15 [running]:                                                                                                              
github.com/cilium/cilium/pkg/azure/ipam.(*Node).ResyncInterfacesAndIPs(0xc0003be360, {0x0?, 0x0?}, 0xc000208d90)                     
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:165 +0x2ed                                                   
github.com/cilium/cilium/pkg/ipam.(*Node).recalculate(0xc0004ffe60)                                                                  
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:418 +0x97                                                          
github.com/cilium/cilium/pkg/ipam.(*NodeManager).resyncNode(0x0?, {0x0?, 0x0?}, 0xc0004ffe60, 0xc0001e0280, {0x0?, 0x0?, 0x37de700?})
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:451 +0x5c                                                  
github.com/cilium/cilium/pkg/ipam.(*NodeManager).Resync.func1(0x1ca5a06?, 0xc0001f4820?)                                             
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:500 +0x46                                                  
created by github.com/cilium/cilium/pkg/ipam.(*NodeManager).Resync                                                                   
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:499 +0x24f                                                 
FAIL	github.com/cilium/cilium/pkg/azure/ipam	0.043s         
```

**Comment by qmonnet** [comment]
Hit in https://github.com/cilium/cilium/issues/22550 (https://github.com/cilium/cilium/actions/runs/4576571631/jobs/8080886056?pr=24214)

**Comment by jrajahalme** [comment]
Happened here: https://github.com/cilium/cilium/actions/runs/5410757250/jobs/9832633333?pr=26549
