### ISSUE TITLE
CI: panic in test/controlplane

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#22748]
### Test Name

```shell
Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests
```

### Failure Output

```shell
[20:52:09] level=info msg="Reading old endpoints..." subsys=daemon
	 [20:52:09] level=info msg="No old endpoints found." subsys=daemon
	 [20:52:09] panic: close of closed channel
	 [20:52:09] 
	 [20:52:09] goroutine 697 [running]:
	 [20:52:09] github.com/cilium/cilium/operator/watchers.UnmanagedKubeDNSPodsInit({0x3ad76a8?, 0xc00083ed40?})
	 [20:52:09] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/watchers/pod.go:140 +0x268
	 [20:52:09] github.com/cilium/cilium/operator/cmd.enableUnmanagedKubeDNSController({0x3ad76a8?, 0xc00083ed40})
	 [20:52:09] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/k8s_pod_controller.go:35 +0x59
	 [20:52:09] created by github.com/cilium/cilium/operator/cmd.(*legacyOnLeader).onStart
	 [20:52:09] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/root.go:432 +0x435
	 [20:52:09] FAIL	github.com/cilium/cilium/test/controlplane	0.489s
	 [20:52:13] OK: 1 passed
```

and 

```
	 [20:54:42] ?   	github.com/cilium/cilium/tools/spdxconv	[no test files]
	 [20:54:42] ?   	github.com/cilium/cilium/tools/sysctlfix	[no test files]
	 [20:54:42] �[38;5;103m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓�[0m  
	 [20:54:42] �[38;5;103m┃�[0m   �[91m�[91mPANIC�[0m�[0m  package: github.com/cilium/cilium/test/controlplane • TestControlPlane/IdentityGC   �[38;5;103m┃�[0m  
	 [20:54:42] �[38;5;103m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛�[0m  
	 [20:54:42] panic: close of closed channel                                                                    
	 [20:54:42]                                                                                                   
	 [20:54:42] goroutine 697 [running]:                                                                          
	 [20:54:42] github.com/cilium/cilium/operator/watchers.UnmanagedKubeDNSPodsInit({0x3ad76a8?, 0xc00083ed40?})  
	 [20:54:42] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/watchers/pod.go:140 +0x268                 
	 [20:54:42] github.com/cilium/cilium/operator/cmd.enableUnmanagedKubeDNSController({0x3ad76a8?, 0xc00083ed40})
	 [20:54:42] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/k8s_pod_controller.go:35 +0x59         
	 [20:54:42] created by github.com/cilium/cilium/operator/cmd.(*legacyOnLeader).onStart                        
	 [20:54:42] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/root.go:432 +0x435                     
	 [20:54:42] FAIL	github.com/cilium/cilium/test/controlplane	0.489s         
```
```


### Stack Trace

```shell
See above.
```

### Standard Output

```shell
See above.
```

### Standard Error

```shell
See above.
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4316/
- ZIP file(s): 
[af82d25c_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/10235406/af82d25c_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip)

**Comment by borkmann** [comment]
(@joamaki mentioned to look into a fix)
