### ISSUE TITLE
CI: Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests: `panic: *resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Events() called from /home/vagrant/go/src/github.com/cilium/cilium/operator/pkg/lbipam/lbipam.go:215 has a broken event handler that did not call Done() before event was garbage collected`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#23272]
### Test Name

```shell
RuntimeDatapathPrivilegedUnitTests Run Tests
```

### Failure Output

```shell
Failed to run privileged unit tests
```

### Stack Trace

```shell
Regression

Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests
Failing for the past 1 build (Since Failed#4653 )
Took 6 min 18 sec.
Attachments
Files
35b36d39_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip
Stacktrace

/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 [01:50:40] make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 [01:50:45] PRIVILEGED_TESTS=true PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/go/src/github.com/cilium/cilium/bpf CGO_ENABLED=0 go test  -mod=vendor -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" \
	 [01:50:45] 	./... -test.v -timeout 600s  -json -covermode=count -coverprofile=coverage.out | tparse -follow
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/daemon	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/endpoint	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/ipam	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/metrics	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/policy	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/prefilter	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/recorder	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/client/service	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/flow	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/client	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/client/connectivity	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/client/restapi	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/models	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/server	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/server/restapi	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/health/server/restapi/connectivity	[no test files]
	 [01:50:53] ?   	github.com/cilium/cilium/api/v1/models	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/observer	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/client	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/client/metrics	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/client/operator	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/models	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/server	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/server/restapi	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/server/restapi/metrics	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/operator/server/restapi/operator	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/peer	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/recorder	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/relay	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/daemon	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/endpoint	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/ipam	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/metrics	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/policy	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/prefilter	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/recorder	[no test files]
	 [01:50:56] ?   	github.com/cilium/cilium/api/v1/server/restapi/service	[no test files]
	 [01:50:57] ?   	github.com/cilium/cilium/bugtool	[no test files]
	 [01:50:57] === RUN   Test
	 [01:50:57] OK: 2 passed
	 [01:50:57] --- PASS: Test (0.01s)

...

	 [01:52:21] === RUN   TestRemoveRequestedIP
	 [01:52:21] level=info msg=Invoked duration="58.777µs" function="lbipam.mkTestFixture.func7 (lbipam_fixture_test.go:148)" subsys=hive
	 [01:52:21] level=info msg=Invoked duration="3.338µs" function="lbipam.glob..func1 (lbipam.go:73)" subsys=hive
	 [01:52:21] level=info msg="Start hook executed" duration=783ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumLoadBalancerIPPool].Start" subsys=hive
	 [01:52:21] level=info msg="Start hook executed" duration=268ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Start" subsys=hive
	 [01:52:21] level=info msg="Starting LB IPAM" subsys=lbipam
	 [01:52:21] level=info msg="LB-IPAM initializing" subsys=lbipam
	 [01:52:21] level=info msg="Start hook executed" duration="40.324µs" function="*lbipam.LBIPAM.Start" subsys=hive
	 [01:52:21] level=info msg="LB-IPAM done initializing" subsys=lbipam
	 [01:52:21] level=info msg="Stop hook executed" duration="42.886µs" function="*lbipam.LBIPAM.Stop" subsys=hive
	 [01:52:21] level=info msg="Stop hook executed" duration="15.039µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Stop" subsys=hive
	 [01:52:21] level=info msg="Stop hook executed" duration="6.041µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumLoadBalancerIPPool].Stop" subsys=hive
	 [01:52:21] --- PASS: TestRemoveRequestedIP (0.10s)
	 [01:52:21] === RUN   TestNonMatchingLBClass
	 [01:52:21] level=info msg=Invoked duration="42.496µs" function="lbipam.mkTestFixture.func7 (lbipam_fixture_test.go:148)" subsys=hive
	 [01:52:21] level=info msg=Invoked duration="3.142µs" function="lbipam.glob..func1 (lbipam.go:73)" subsys=hive
	 [01:52:21] level=info msg="Start hook executed" duration=645ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumLoadBalancerIPPool].Start" subsys=hive
	 [01:52:21] level=info msg="Start hook executed" duration=293ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Start" subsys=hive
	 [01:52:21] level=info msg="Starting LB IPAM" subsys=lbipam
	 [01:52:21] level=info msg="LB-IPAM initializing" subsys=lbipam
	 [01:52:21] level=info msg="Start hook executed" duration="37.974µs" function="*lbipam.LBIPAM.Start" subsys=hive
	 [01:52:21] level=info msg="LB-IPAM done initializing" subsys=lbipam
	 [01:52:21] level=info msg="Stop hook executed" duration="74.135µs" function="*lbipam.LBIPAM.Stop" subsys=hive
	 [01:52:21] level=info msg="Stop hook executed" duration="18.088µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Stop" subsys=hive
	 [01:52:21] level=info msg="Stop hook executed" duration="13.667µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumLoadBalancerIPPool].Stop" subsys=hive
	 [01:52:21] --- PASS: TestNonMatchingLBClass (0.10s)
	 [01:52:21] === RUN   TestChangePoolSelector
	 [01:52:21] level=info msg=Invoked duration="491.099µs" function="lbipam.mkTestFixture.func7 (lbipam_fixture_test.go:148)" subsys=hive
	 [01:52:21] level=info msg=Invoked duration="11.065µs" function="lbipam.glob..func1 (lbipam.go:73)" subsys=hive
	 [01:52:21] level=info msg="Start hook executed" duration="1.124µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumLoadBalancerIPPool].Start" subsys=hive
	 [01:52:21] level=info msg="Start hook executed" duration=421ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Start" subsys=hive
	 [01:52:21] level=info msg="Starting LB IPAM" subsys=lbipam
	 [01:52:21] level=info msg="LB-IPAM initializing" subsys=lbipam
	 [01:52:21] level=info msg="Start hook executed" duration="55.888µs" function="*lbipam.LBIPAM.Start" subsys=hive
	 [01:52:21] panic: *resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Events() called from /home/vagrant/go/src/github.com/cilium/cilium/operator/pkg/lbipam/lbipam.go:215 has a broken event handler that did not call Done() before event was garbage collected
	 [01:52:21] 
	 [01:52:21] goroutine 5 [running]:
	 [01:52:21] github.com/cilium/cilium/pkg/k8s/resource.(*resource[...]).Events.func1.1()
	 [01:52:21] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/k8s/resource/resource.go:343 +0x6a
```

### Standard Output

```shell
None
```

### Standard Error

```shell
01:50:38 STEP: Running BeforeAll block for EntireTestsuite RuntimeDatapathPrivilegedUnitTests
FAIL: Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2

(Same as stacktrace)
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4653/testReport/junit/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/
- ZIP file(s): [35b36d39_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/10486478/35b36d39_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip)

**Comment by christarazi** [comment]
cc @joamaki

**Comment by joamaki** [comment]
Ok fun issue. There's a flaky test (TestRequestIPWithMismatchedLabel) that calls t.Fatal from a closure that's invoked by a reactor assigned to the fake client.. which causes the goroutine executing lbipam.Run() to be killed in the middle of the event loop, which then causes a future test to fail with this panic as the garbage collector hits the event finalizer.

The panic can be fixed by turning the t.Fatal's in the `AwaitPool` closures into t.Error's, but we'll still hit the flaky test. Assigning to @dylandreimerink to finish up a fix.
