### ISSUE TITLE
CI: ConformanceGatewayAPI / gateway-api-conformance-test: `panic: test timed out after 10m0s`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#23299]
## CI failure

<details><summary>Output</summary>
<p>

```txt
=== RUN   TestConformance
    conformance_test.go:47: Running conformance tests with cilium GatewayClass
    suite.go:124: Test Setup: Ensuring GatewayClass has been accepted
    suite.go:127: Test Setup: Applying base manifests
    apply.go:196: Creating gateway-conformance-infra Namespace
    apply.go:196: Creating same-namespace Gateway
    apply.go:196: Creating all-namespaces Gateway
    apply.go:196: Creating backend-namespaces Gateway
    apply.go:196: Creating infra-backend-v1 Service
    apply.go:196: Creating infra-backend-v1 Deployment
    apply.go:196: Creating infra-backend-v2 Service
    apply.go:196: Creating infra-backend-v2 Deployment
    apply.go:196: Creating infra-backend-v3 Service
    apply.go:196: Creating infra-backend-v3 Deployment
    apply.go:196: Creating gateway-conformance-app-backend Namespace
    apply.go:196: Creating app-backend-v1 Service
    apply.go:196: Creating app-backend-v1 Deployment
    apply.go:196: Creating app-backend-v2 Service
    apply.go:196: Creating app-backend-v2 Deployment
    apply.go:196: Creating gateway-conformance-web-backend Namespace
    apply.go:196: Creating web-backend Service
    apply.go:196: Creating web-backend Deployment
    suite.go:130: Test Setup: Applying programmatic resources
    apply.go:147: Creating certificate 
    suite.go:134: Test Setup: Ensuring Gateways and Pods from base manifests are ready
    helpers.go:442: Ready condition set to False, expected True
    helpers.go:446: Ready was not in conditions list
    helpers.go:112: gateway-conformance-infra/all-namespaces Gateway not ready yet
    helpers.go:442: Ready condition set to False, expected True
    helpers.go:446: Ready was not in conditions list
    helpers.go:112: gateway-conformance-infra/all-namespaces Gateway not ready yet
    helpers.go:442: Ready condition set to False, expected True
    helpers.go:446: Ready was not in conditions list
    helpers.go:112: gateway-conformance-infra/all-namespaces Gateway not ready yet
    helpers.go:442: Ready condition set to False, expected True
    helpers.go:446: Ready was not in conditions list
    helpers.go:112: gateway-conformance-infra/all-namespaces Gateway not ready yet
    helpers.go:456: Ready condition set to False, expected True
    apply.go:196: Creating gateway-secret-missing-referenced-secret Gateway
=== RUN   TestConformance/GatewaySecretMissingReferencedSecret/Gateway_listener_should_have_a_false_ResolvedRefs_condition_with_reason_InvalidCertificateRef
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:425: Conditions matched expectations
    helpers.go:343: Gateway status listeners matched expectations
=== CONT  TestConformance/GatewaySecretMissingReferencedSecret
    apply.go:204: Deleting gateway-secret-missing-referenced-secret Gateway
=== RUN   TestConformance/GatewaySecretReferenceGrantAllInNamespace
    suite.go:188: Applying tests/gateway-secret-reference-grant-specific.yaml
    apply.go:196: Creating gateway-secret-reference-grant Gateway
    apply.go:196: Creating reference-grant-specific ReferenceGrant
=== RUN   TestConformance/GatewaySecretReferenceGrantAllInNamespace/Gateway_listener_should_have_a_true_ResolvedRefs_condition_and_a_true_Ready_condition
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:425: Conditions matched expectations
    helpers.go:343: Gateway status listeners matched expectations
=== CONT  TestConformance/GatewaySecretReferenceGrantAllInNamespace
    apply.go:204: Deleting reference-grant-specific ReferenceGrant
    apply.go:204: Deleting gateway-secret-reference-grant Gateway
=== RUN   TestConformance/GatewaySecretReferenceGrantSpecific
    suite.go:188: Applying tests/gateway-secret-reference-grant-specific.yaml
    apply.go:196: Creating gateway-secret-reference-grant Gateway
    apply.go:196: Creating reference-grant-specific ReferenceGrant
=== RUN   TestConformance/GatewaySecretReferenceGrantSpecific/Gateway_listener_should_have_a_true_ResolvedRefs_condition_and_a_true_Ready_condition
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:343: Expected 1 Gateway status listeners, got 0
    helpers.go:425: Conditions matched expectations
    helpers.go:343: Gateway status listeners matched expectations
=== CONT  TestConformance/GatewaySecretReferenceGrantSpecific
    apply.go:204: Deleting reference-grant-specific ReferenceGrant
    apply.go:204: Deleting gateway-secret-reference-grant Gateway
=== RUN   TestConformance/HTTPRouteCrossNamespace
    suite.go:188: Applying tests/httproute-cross-namespace.yaml
    apply.go:196: Creating cross-namespace HTTPRoute
    helpers.go:276: Expected 1 Route parents, got 0
    helpers.go:425: Conditions matched expectations
    helpers.go:276: Route parents matched expectations

...

panic: test timed out after 10m0s

goroutine 1663 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.5/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc00030a9c0, {0x219ed1d?, 0x524225?}, 0x22c4ae8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x37a
testing.runTests.func1(0xc0006d59e0?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1846 +0x6e
testing.tRunner(0xc00030a9c0, 0xc00081fcd8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
testing.runTests(0xc0006c3860?, {0x36f37e0, 0x16, 0x16}, {0x7f8d2ced8108?, 0x40?, 0x371f1a0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc0006c3860)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1726 +0x5d9
main.main()
	_testmain.go:89 +0x1aa

goroutine 51 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc0006f7980)
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:271 +0xa7
created by k8s.io/client-go/util/workqueue.newQueue
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:63 +0x1bc

goroutine 50 [chan receive]:
testing.(*T).Run(0xc00030ab60, {0x21a261b?, 0x21a7701?}, 0xc0004fade0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1494 +0x37a
sigs.k8s.io/gateway-api/conformance/utils/suite.(*ConformanceTestSuite).Run(0xc00014b3f0, 0xc00030ab60?, {0xc0005d9000, 0x16, 0xc0005b3930?})
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/suite/suite.go:146 +0x12a
github.com/cilium/cilium/operator/pkg/gateway-api.TestConformance(0xc00030ab60)
	/home/runner/work/cilium/cilium/operator/pkg/gateway-api/conformance_test.go:60 +0x4d4
testing.tRunner(0xc00030ab60, 0x22c4ae8)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 52 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0006f7b00)
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:233 +0x305
created by k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:70 +0x25b

goroutine 53 [chan receive, 10 minutes]:
k8s.io/client-go/transport.(*dynamicClientCert).Run(0xc00047fb00, 0xc000102de0)
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/transport/cert_rotation.go:147 +0x279
created by k8s.io/client-go/transport.(*tlsTransportCache).get
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/transport/cache.go:116 +0x4ac

goroutine 23 [sync.Cond.Wait, 6 minutes]:
sync.runtime_notifyListWait(0xc00047fad0, 0x1)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/sema.go:517 +0x14c
sync.(*Cond).Wait(0x24ec3e8?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/sync/cond.go:70 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0006f7980)
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:157 +0x9e
k8s.io/client-go/transport.(*dynamicClientCert).processNextWorkItem(0xc00047fb00)
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/transport/cert_rotation.go:156 +0x58
k8s.io/client-go/transport.(*dynamicClientCert).runWorker(0xc0000796a0?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/transport/cert_rotation.go:151 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x39?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x524225?, {0x24dcea0, 0xc000628060}, 0x1, 0xc000102de0)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x5248c0?, 0x3b9aca00, 0x0, 0x60?, 0xc000079780?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc0000797d0?, 0x104a946?, 0xc0006f7b00?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x25
created by k8s.io/client-go/transport.(*dynamicClientCert).Run
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/transport/cert_rotation.go:140 +0x1b3

goroutine 24 [select, 6 minutes]:
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext({0x24fea38, 0xc00030e300}, 0xc000798000, 0x10483ca?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:660 +0xe5
k8s.io/apimachinery/pkg/util/wait.poll({0x24fea38, 0xc00030e300}, 0x38?, 0x10478e5?, 0xc0004be0b0?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:596 +0x9a
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x24fea38, 0xc00030e300}, 0x0?, 0x0?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:547 +0x49
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0x0?, 0x0?, 0x0?)
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:538 +0x7c
created by k8s.io/client-go/transport.(*dynamicClientCert).Run
	/home/runner/work/cilium/cilium/vendor/k8s.io/client-go/transport/cert_rotation.go:142 +0x26a

goroutine 25 [select, 10 minutes]:
k8s.io/apimachinery/pkg/util/wait.ContextForChannel.func1()
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:303 +0x71
created by k8s.io/apimachinery/pkg/util/wait.ContextForChannel
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:302 +0xc5

goroutine 26 [select, 6 minutes]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1()
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:710 +0x1c5
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/home/runner/work/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:693 +0xca

goroutine 1669 [chan receive]:
testing.(*testContext).waitParallel(0xc0004c14f0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1557 +0xab
testing.(*T).Parallel(0xc000727520)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1272 +0x1d6
sigs.k8s.io/gateway-api/conformance/tests.glob..func18.1(0x24fea38?)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/httproute-matching.go:74 +0x5f
testing.tRunner(0xc000727520, 0xc0008b2d80)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 1673 [select]:
net/http.(*persistConn).roundTrip(0xc00089ea20, 0xc00016c0c0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:2620 +0x974
net/http.(*Transport).roundTrip(0x36ef380, 0xc0009ea300)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:595 +0x7ba
net/http.(*Transport).RoundTrip(0xc000019230?, 0x24dd3c0?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc0009ea300, {0x24dd3c0, 0x36ef380}, {0x21195c0?, 0xc00006c501?, 0x0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:251 +0x5f7
net/http.(*Client).send(0x371b5a0, 0xc0009ea300, {0x1?, 0x1?, 0x0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:175 +0x9b
net/http.(*Client).do(0x371b5a0, 0xc0009ea300)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:715 +0x8fc
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:581
sigs.k8s.io/gateway-api/conformance/utils/roundtripper.(*DefaultRoundTripper).CaptureRoundTrip(0xc000704b98, {{{0x218c202, 0x4}, {0x0, 0x0}, 0x0, {0xc000ab91d0, 0xf}, {0x24cca40, 0x1}, ...}, ...})
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/roundtripper/roundtripper.go:112 +0x33e
sigs.k8s.io/gateway-api/conformance/utils/http.WaitForConsistentResponse.func1()
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:152 +0x75
sigs.k8s.io/gateway-api/conformance/utils/http.awaitConvergence(0xc000727ba0, 0x3, 0xc000019b28)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:125 +0xd2
sigs.k8s.io/gateway-api/conformance/utils/http.WaitForConsistentResponse(_, {_, _}, {{{0x218c202, 0x4}, {0x0, 0x0}, 0x0, {0xc000ab91d0, 0xf}, ...}, ...}, ...)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:151 +0xc5
sigs.k8s.io/gateway-api/conformance/utils/http.MakeRequestAndExpectEventuallyConsistentResponse(0xc000727ba0, {0x24dd7e0, 0xc000704b98}, {0xc000ab91d0, 0xf}, {{{0x0, 0x0}, {0x218b194, 0x3}, {0x24cca40, ...}, ...}, ...})
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:108 +0x355
sigs.k8s.io/gateway-api/conformance/tests.glob..func18.1(0x24fea38?)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/httproute-matching.go:75 +0xbb
testing.tRunner(0xc000727ba0, 0xc0008b3170)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 1668 [select]:
net/http.(*persistConn).roundTrip(0xc00089e900, 0xc00086dfc0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:2620 +0x974
net/http.(*Transport).roundTrip(0x36ef380, 0xc000bebb00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:595 +0x7ba
net/http.(*Transport).RoundTrip(0xc000651230?, 0x24dd3c0?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc000bebb00, {0x24dd3c0, 0x36ef380}, {0x21195c0?, 0xc00006a001?, 0x0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:251 +0x5f7
net/http.(*Client).send(0x371b5a0, 0xc000bebb00, {0x1?, 0x1?, 0x0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:175 +0x9b
net/http.(*Client).do(0x371b5a0, 0xc000bebb00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:715 +0x8fc
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/client.go:581
sigs.k8s.io/gateway-api/conformance/utils/roundtripper.(*DefaultRoundTripper).CaptureRoundTrip(0xc000704b98, {{{0x218c202, 0x4}, {0x0, 0x0}, 0x0, {0xc000ab91d0, 0xf}, {0x24cca40, 0x1}, ...}, ...})
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/roundtripper/roundtripper.go:112 +0x33e
sigs.k8s.io/gateway-api/conformance/utils/http.WaitForConsistentResponse.func1()
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:152 +0x75
sigs.k8s.io/gateway-api/conformance/utils/http.awaitConvergence(0xc000727380, 0x3, 0xc000651b28)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:125 +0xd2
sigs.k8s.io/gateway-api/conformance/utils/http.WaitForConsistentResponse(_, {_, _}, {{{0x218c202, 0x4}, {0x0, 0x0}, 0x0, {0xc000ab91d0, 0xf}, ...}, ...}, ...)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:151 +0xc5
sigs.k8s.io/gateway-api/conformance/utils/http.MakeRequestAndExpectEventuallyConsistentResponse(0xc000727380, {0x24dd7e0, 0xc000704b98}, {0xc000ab91d0, 0xf}, {{{0x0, 0x0}, {0x218b194, 0x3}, {0x24cca40, ...}, ...}, ...})
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/http/http.go:108 +0x355
sigs.k8s.io/gateway-api/conformance/tests.glob..func18.1(0x24fea38?)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/httproute-matching.go:75 +0xbb
testing.tRunner(0xc000727380, 0xc0008b2c60)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 1479 [select]:
net/http.(*persistConn).writeLoop(0xc00089ea20)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:1752 +0x1791

goroutine 1481 [select]:
net/http.(*persistConn).writeLoop(0xc00089e900)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:1752 +0x1791

goroutine 1672 [chan receive]:
testing.(*testContext).waitParallel(0xc0004c14f0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1557 +0xab
testing.(*T).Parallel(0xc000727a00)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1272 +0x1d6
sigs.k8s.io/gateway-api/conformance/tests.glob..func18.1(0x24fea38?)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/httproute-matching.go:74 +0x5f
testing.tRunner(0xc000727a00, 0xc0008b3050)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 1655 [chan receive]:
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1412 +0x4a5
testing.tRunner(0xc000bc0000, 0xc0004fade0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1452 +0x144
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 1653 [IO wait]:
internal/poll.runtime_pollWait(0x7f8d04875858, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc000914400?, 0xc000477000?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000914400, {0xc000477000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000914400, {0xc000477000?, 0xc000477005?, 0x6bb?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000153c0, {0xc000477000?, 0xc00008f800?, 0xc000864f98?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0006796b0, {0xc000477000?, 0x0?, 0x50af6f?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/crypto/tls/conn.go:787 +0x3d
bytes.(*Buffer).ReadFrom(0xc000865078, {0x24d08c0, 0xc0006796b0})
	/opt/hostedtoolcache/go/1.19.5/x64/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000864e00, {0x7f8d0472d998?, 0xc000678bb8}, 0x1000?)
	/opt/hostedtoolcache/go/1.19.5/x64/src/crypto/tls/conn.go:809 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000864e00, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/crypto/tls/conn.go:616 +0x116
crypto/tls.(*Conn).readRecord(...)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/httproute-matching.go:74 +0x5f
testing.tRunner(0xc0007276c0, 0xc0008b2e10)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f

goroutine 1480 [IO wait]:
internal/poll.runtime_pollWait(0x7f8d04875588, 0x72)
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc000bb4f80?, 0xc000ce1000?, 0x0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000bb4f80, {0xc000ce1000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.19.5/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000bb4f80, {0xc000ce1000?, 0x408171?, 0x4?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00069a350, {0xc000ce1000?, 0x0?, 0x0?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc00089e900, {0xc000ce1000?, 0xc0009bb5c0?, 0xc000090d30?})
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc000482300)
	/opt/hostedtoolcache/go/1.19.5/x64/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc000482300, 0x1)
	/opt/hostedtoolcache/go/1.19.5/x64/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc00089e900)
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.19.5/x64/src/net/http/transport.go:1751 +0x173e

goroutine 1671 [chan receive]:
testing.(*testContext).waitParallel(0xc0004c14f0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1557 +0xab
testing.(*T).Parallel(0xc000727860)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1272 +0x1d6
sigs.k8s.io/gateway-api/conformance/tests.glob..func18.1(0x24fea38?)
	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/httproute-matching.go:74 +0x5f
testing.tRunner(0xc000727860, 0xc0008b2fc0)
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.5/x64/src/testing/testing.go:1493 +0x35f
FAIL	github.com/cilium/cilium/operator/pkg/gateway-api	600.072s
FAIL
Error: Process completed with exit code 1.
```

</p>
</details>

Zip sysdump: [cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/10492511/cilium-sysdump-out.zip.zip)

Link: https://github.com/cilium/cilium/actions/runs/3998428448

**Comment by christarazi** [comment]
cc @sayboras

**Comment by sayboras** [comment]
Interesting, this is the first time we got panic on this job, let me take a look.

**Comment by sayboras** [comment]
Re-run seems fine, I am not sure what's wrong though :thinking: 

https://github.com/cilium/cilium/actions/runs/3998428448

**Comment by sayboras** [comment]
I am unable to replicate this issue. 

Also, the panic seems to be related to conformance tests from upstream. Ideally, there should be no panic at due to test failure. 

Closing this issue, we can re-open it if it happens again. From my side, I will report to upstream on panic issue.
