### ISSUE TITLE
endpoint: "panic: assignment to entry in nil map"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2394]
I was working on some local changes on top of master @ 9f80e753f5b0 ("Ginkgo: MonitorTest wait until pods are ready"), ran `tests/15-check-container-id.sh` and exited with containers still running. After `systemctl restart cilium`, cilium failed to come back up successfully due to the below nil dereference.

Potentially related to 22d4ac1af112 ("pkg/endpoint: fix stuck state "restoring" when restoring endpoints")
(+@aanm) (#2324)

cilium log:
```
Dec 21 14:30:16 cilium-master cilium-agent[2009]: time="2017-12-21T14:30:16-08:00" level=info msg="Restoring old cilium endpoints..."
Dec 21 14:30:16 cilium-master cilium-agent[2009]: time="2017-12-21T14:30:16-08:00" level=debug msg="Reading directory" endpointID=63464 file-path=/var/run/cilium/state/63464/lxc_config.
Dec 21 14:30:16 cilium-master cilium-agent[2009]: time="2017-12-21T14:30:16-08:00" level=debug msg="Found endpoint C header file" endpointID=63464 file-path=/var/run/cilium/state/63464/
Dec 21 14:30:16 cilium-master cilium-agent[2009]: time="2017-12-21T14:30:16-08:00" level=info msg="No workload could be associated with endpoint, removing endpoint" endpointID=63464
Dec 21 14:30:16 cilium-master cilium-agent[2009]: panic: assignment to entry in nil map
Dec 21 14:30:16 cilium-master cilium-agent[2009]: goroutine 157 [running]:
Dec 21 14:30:16 cilium-master cilium-agent[2009]: github.com/cilium/cilium/pkg/endpoint.(*EndpointStatus).addStatusLog(0xc420057c80, 0xc420084a50)
Dec 21 14:30:16 cilium-master cilium-agent[2009]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:748 +0x4f
Dec 21 14:30:16 cilium-master cilium-agent[2009]: github.com/cilium/cilium/pkg/endpoint.(*Endpoint).logStatusLocked(0xc4202fe1e0, 0x0, 0x0, 0x1c5b63f, 0x11)
Dec 21 14:30:16 cilium-master cilium-agent[2009]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1125 +0x156
Dec 21 14:30:16 cilium-master cilium-agent[2009]: github.com/cilium/cilium/pkg/endpoint.(*Endpoint).SetStateLocked(0xc4202fe1e0, 0x1c56ac0, 0xd, 0x1c5b63f, 0x11, 0xc420084a00)
Dec 21 14:30:16 cilium-master cilium-agent[2009]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1438 +0x134
Dec 21 14:30:16 cilium-master cilium-agent[2009]: main.(*Daemon).deleteEndpoint(0xc420010240, 0xc4202fe1e0, 0x1)
Dec 21 14:30:16 cilium-master cilium-agent[2009]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:305 +0x10c
Dec 21 14:30:16 cilium-master cilium-agent[2009]: main.(*Daemon).SyncState.func1(0xc420060701, 0xc420010240, 0xc4202fe1e0, 0xc420060700, 0xc420060770)
Dec 21 14:30:16 cilium-master cilium-agent[2009]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/state.go:70 +0xa06
Dec 21 14:30:16 cilium-master cilium-agent[2009]: created by main.(*Daemon).SyncState
Dec 21 14:30:16 cilium-master cilium-agent[2009]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/state.go:66 +0x1e4
```

Here's the contents of /var/run/cilium/state when cilium refuses to come up with the above failure:
```
$ ls /var/run/cilium/state/                                                                                                                                         
63464  63464_next  bpf_host.o  bpf_overlay.o  encap.state  globals  netdev_config.h
```

**Comment by joestringer** [comment]
I've tried reproducing this on master, and can't, so it's likely related to some of my own changes. I'll reopen if I see it separately.
