### ISSUE TITLE
Potential nil dereference in v1.12

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#24047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some end-users were running with PR https://github.com/cilium/cilium/pull/23957 merged when they saw a segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2062233]

goroutine 189 [running]:
github.com/cilium/cilium/pkg/egressgateway.(*policyGatewayConfig).selectsNodeAsGateway(...)
	/go/src/github.com/cilium/cilium/pkg/egressgateway/policy.go:86
github.com/cilium/cilium/pkg/egressgateway.(*PolicyConfig).regenerateGatewayConfig(0xc0001608c0, 0xc000c8a240?)
	/go/src/github.com/cilium/cilium/pkg/egressgateway/policy.go:106 +0x2f3
github.com/cilium/cilium/pkg/egressgateway.(*Manager).regenerateGatewayConfigs(...)
	/go/src/github.com/cilium/cilium/pkg/egressgateway/manager.go:240
github.com/cilium/cilium/pkg/egressgateway.(*Manager).reconcile(0xc000c8a240)
	/go/src/github.com/cilium/cilium/pkg/egressgateway/manager.go:423 +0xac
github.com/cilium/cilium/pkg/egressgateway.(*Manager).runReconciliationAfterK8sSync.func1()
	/go/src/github.com/cilium/cilium/pkg/egressgateway/manager.go:113 +0x73
created by github.com/cilium/cilium/pkg/egressgateway.(*Manager).runReconciliationAfterK8sSync
	/go/src/github.com/cilium/cilium/pkg/egressgateway/manager.go:103 +0x56
```

Need to figure out if this is an issue with the cherry-pick or the actual fix.

### Cilium Version

1.12 tip.

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
We weren't able to reproduce; this seems to have been an installation error.
