### ISSUE TITLE
CI: ebpf unit test failed when required to generate report

### ISSUE THREAD

**Issue by wanlin31** [cilium/cilium#24082]
### OS + Kernel
```
uname -a
Linux wanlindu-cilium-ebpf-testvm-image-ubuntu2204 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
### Checked out commit
```
git log
commit 66e5ec75ed8bbb96c4129634a75f01662cc439b3 (HEAD -> master, origin/master, origin/HEAD)
```
### Commands to run the test
```
# Install the newest version of golang.
sudo add-apt-repository ppa:longsleep/golang-backports -y && sudo apt update && sudo apt install golang-go -y

# Install clang-10 llvm-10
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
sudo add-apt-repository -y "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
sudo apt install clang-10 llvm-10
```

### Run test without report
```
make -C bpf/tests clean
CLANG=clang-10 LLC=llc-10 make -C test/ run_bpf_tests

make: Entering directory '/home/wanlindu/upstream_cilium/cilium/test'
make -C ../bpf/tests all
make[1]: Entering directory '/home/wanlindu/upstream_cilium/cilium/bpf/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wanlindu/upstream_cilium/cilium/bpf/tests'
go test ./bpf_tests -exec sudo -bpf-test-path /home/wanlindu/upstream_cilium/cilium/bpf/tests
ok  	github.com/cilium/cilium/test/bpf_tests	1.603s
make: Leaving directory '/home/wanlindu/upstream_cilium/cilium/test'
```
### Run test require report
```
CLANG=clang-10 LLC=llc-10 make -C test/ run_bpf_tests COVER=1
make: Entering directory '/home/wanlindu/upstream_cilium/cilium/test'
make -C ../bpf/tests all
make[1]: Entering directory '/home/wanlindu/upstream_cilium/cilium/bpf/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wanlindu/upstream_cilium/cilium/bpf/tests'
go test ./bpf_tests -exec sudo -bpf-test-path /home/wanlindu/upstream_cilium/cilium/bpf/tests -coverage-report /home/wanlindu/upstream_cilium/cilium/bpf-coverage.html -coverage-format html
--- FAIL: TestBPF (18.96s)
    --- FAIL: TestBPF/session_affinity_test.o (11.68s)
panic: runtime error: index out of range [2451] with length 2451 [recovered]
	panic: runtime error: index out of range [2451] with length 2451

goroutine 130 [running]:
testing.tRunner.func1.2({0x1c00500, 0xc0075b6498})
	/usr/lib/go-1.20/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/lib/go-1.20/src/testing/testing.go:1529 +0x39f
panic({0x1c00500, 0xc0075b6498})
	/usr/lib/go-1.20/src/runtime/panic.go:884 +0x213
github.com/cilium/coverbee.InstrumentCollection(0xc000206510, {0x0, 0x0})
	/home/wanlindu/upstream_cilium/cilium/vendor/github.com/cilium/coverbee/instrumentation.go:277 +0x25ff
github.com/cilium/coverbee.InstrumentAndLoadCollection(0x4fda00?, {{{0x0, 0x0}, {0x0, 0x0, 0x0}}, {0x0, 0x4000000, 0x0, 0x0}, ...}, ...)
	/home/wanlindu/upstream_cilium/cilium/vendor/github.com/cilium/coverbee/instrumentation.go:27 +0x46
github.com/cilium/cilium/test/bpf_tests.loadAndRunSpec(0xc000982340, {0x2012350?, 0xc0007a7d40?}, {0x0, 0x0})
	/home/wanlindu/upstream_cilium/cilium/test/bpf_tests/bpf_test.go:137 +0x21a
github.com/cilium/cilium/test/bpf_tests.TestBPF.func1(0xc000883860?)
	/home/wanlindu/upstream_cilium/cilium/test/bpf_tests/bpf_test.go:90 +0x3c
testing.tRunner(0xc000982340, 0xc0044fed20)
	/usr/lib/go-1.20/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/lib/go-1.20/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/cilium/cilium/test/bpf_tests	19.012s
FAIL
make: *** [Makefile:92: run_bpf_tests] Error 1
```

This issue has been seen with Ubuntu20.04.4 + 5.13, Ubuntu20.04.3 + 5.11, Ubuntu20.04.2 + 5.8, Ubuntu20.04+ 5.4 when asked to generate reports.

@anfernee

**Comment by wanlin31** [comment]
Closed by https://github.com/cilium/cilium/pull/24094

Verified with  Ubuntu22.04 + 5.15:
```
CLANG=clang-10 LLC=llc-10 make -C test/ run_bpf_tests COVER=1
make: Entering directory '/home/wanlindu/upstream_cilium/cilium/test'
make -C ../bpf/tests all
make[1]: Entering directory '/home/wanlindu/upstream_cilium/cilium/bpf/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wanlindu/upstream_cilium/cilium/bpf/tests'
go test ./bpf_tests -exec sudo -bpf-test-path /home/wanlindu/upstream_cilium/cilium/bpf/tests -coverage-report /home/wanlindu/upstream_cilium/cilium/bpf-coverage.html -coverage-format html
ok  	github.com/cilium/cilium/test/bpf_tests	82.449s
make: Leaving directory '/home/wanlindu/upstream_cilium/cilium/test'
```
