### ISSUE TITLE
Ginkgo CI: build timed out with 'context-deadline exceeded' error message

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2416]
Relevant output:
```
12:49:20 RuntimePolicyEnforcement Policy Enforcement Always 
12:49:20   Always to Never with policy
12:49:20   /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:262
13:55:49 level=error msg="cannot get endpoint ids" testName=RuntimePolicyEnforcement
13:56:18 level=error msg="cannot get endpoint identity ids" error="cannot get endpoint list: Error: cannot get endpoint list: context deadline exceeded\n\nError: cannot get endpoint list: context deadline exceeded\n\n" testName=RuntimePolicyEnforcement
13:56:18 level=error msg="cannot gather files for cmd 'sudo cp -r /var/run/cilium /vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib': cp: cannot create special file '/vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib/cilium.sock': Operation not permitted\ncp: cannot create special file '/vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib/monitor.sock': Operation not permitted\ncp: cannot create special file '/vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib/health.sock': Operation not permitted\ncp: cannot create special file '/vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib/cilium.sock': Operation not permitted\ncp: cannot create special file '/vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib/monitor.sock': Operation not permitted\ncp: cannot create special file '/vagrant//test_results/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy//lib/health.sock': Operation not permitted\n" testName=RuntimePolicyEnforcement
13:56:46 
13:56:46 • Failure in Spec Setup (BeforeEach) [4044.900 seconds]
13:56:46 RuntimePolicyEnforcement
13:56:46 /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:49
13:56:46   Policy Enforcement Always
13:56:46   /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:234
13:56:46     Always to Never with policy [BeforeEach]
13:56:46     /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:262
13:56:46 
13:56:46     Expected
13:56:46         <bool>: false
13:56:46     to be true
13:56:46 
13:56:46     /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:243
```

Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/746/execution/node/56/log/

There are multiple issues here:

1. The context-deadline-exceeded messages
2. Ginkgo CI taking about an hour to time out. 

These need to be tackled separately.

**Comment by ianvernon** [comment]
It's worrisome that there is the output of 'context deadline exceeded' - this usually indicates some sort of deadlock in the agent. 

Logs for the test that failed are attached at https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/746/ in the tar file under 'Build Artifacts'. The folder for the test that failed in this archive is `RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy`. Might be useful to check the output of `gops_stack.txt` within that directory for potential deadlock candidates.

**Comment by ianvernon** [comment]
The logs from the aforementioned archive show that the agent was stuck as soon as the test ran:
```
cmd: "sudo cilium policy delete --all" exitCode: %!q(bool=true) 
 Revision: 234

level=debug msg="spinning up container with command \"docker run -d --name app --net cilium-net -l id.app cilium/demo-httpd\""
cmd: "sudo docker run -d --name app --net cilium-net -l id.app cilium/demo-httpd" exitCode: %!q(bool=true) 
 1cf090e828bda18a2bd6f1ae4314383df646acebe385fba8c18d17727e5f5942

cmd: "cilium endpoint list | grep -c regenerat" exitCode: %!q(bool=false) 
 0
Error: cannot get endpoint list: context deadline exceeded
```

The test that ran before this test is:
```
12:48:37 ------------------------------
12:48:37 RuntimePolicyEnforcement Policy Enforcement Always 
12:48:37   Container creation
12:48:37   /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:246
12:48:46 STEP: Create a new container
12:49:20 
12:49:20 • [SLOW TEST:44.322 seconds]
12:49:20 RuntimePolicyEnforcement
12:49:20 /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:49
12:49:20   Policy Enforcement Always
12:49:20   /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:234
12:49:20     Container creation
12:49:20     /root/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:246
12:49:20 ------------------------------
```

Since each`It` in Ginkgo is ran in a random order each time the tests are ran, this could be an issue revealed by the specific ordering during this test run.

**Comment by ianvernon** [comment]
The random seed used for this test:
```
Random Seed: 1514895093
```

We can run the tests again with this seed, which will run them in the same order, per https://onsi.github.io/ginkgo/#spec-permutation : 

> Ginkgo uses the current time to seed the randomization. It prints out the seed near the beginning of the test output. If you notice test intermittent test failures that you think may be due to test pollution, you can use the seed from a failing suite to exactly reproduce the spec order for that suite. To do this pass the --seed=SEED flag.

**Comment by ianvernon** [comment]
I've opened a PR with the seed hardcoded to see if this reproduces on Jenkins: https://github.com/cilium/cilium/pull/2428

**Comment by ianvernon** [comment]
Update: I closed the PR #2428 , as it did not reproduce with the same seed. I suspect there is a deadlock bug in Cilium somewhere :(

**Comment by eloycoto** [comment]
Hi @ianvernon sorry, I made some work here, but I didn't get the root of the problem. 

The issue is in this call, that it's reaching the timeout:
 
https://github.com/cilium/cilium/blob/master/pkg/client/endpoint.go#L78-L80


I'll try to reproduce the problem in the following days ;-)

**Comment by ianvernon** [comment]
@eloycoto another build failed after #2512 was merged: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1003/ .

**Comment by eloycoto** [comment]
I had a chat with @aanm and he found the problem in the `gop stacks`

```
goroutine 109082 [select, 78 minutes]:
net/http.(*persistConn).roundTrip(0xc420786900, 0xc420895b80, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1898 +0x974
net/http.(*Transport).RoundTrip(0xc42034e0f0, 0xc420498200, 0xc42034e0f0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:391 +0x74c
net/http.send(0xc420498200, 0x2b5bd80, 0xc42034e0f0, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc420c4ec50, 0x411d08)
	/usr/local/go/src/net/http/client.go:249 +0x162
net/http.(*Client).send(0xc420303710, 0xc420498200, 0x0, 0x0, 0x0, 0xc420c4ec50, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:173 +0x108
net/http.(*Client).Do(0xc420303710, 0xc420498200, 0x2c05960, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:595 +0x254
github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*Client).doRequest(0xc420255080, 0xc420c8e820, 0xc420d03e30, 0xc4203d9280, 0x7a, 0xc420c8e820)
	/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/api.go:368 +0xbc
github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*KV).getInternal(0xc420d03f60, 0xc420327480, 0x73, 0x0, 0xc420d03f68, 0xc4202b3d40, 0xc4208413c0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/kv.go:104 +0x238
github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*KV).Get(0xc420d03f60, 0xc420327480, 0x73, 0xc420d03f68, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/kv.go:38 +0x8c
github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*Lock).monitorLock(0xc42047c780, 0xc4208a7dd0, 0x24, 0xc42083b200)
	/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/lock.go:362 +0xd8
created by github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api.(*Lock).Lock
	/go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/consul/api/lock.go:239 +0x5b5
```

Attached the runtime data. 
[RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy.zip](https://github.com/cilium/cilium/files/1634995/RuntimePolicyEnforcementPolicyEnforcementAlwaysAlwaystoNeverwithpolicy.zip)

**Comment by ianvernon** [comment]
We haven't seen this in quite some time; this seems to have been solved by the recent key-value store changes.
