### ISSUE TITLE
CI:  Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests (pkg/datapath/linux: panic: test timed out after 10m0s)

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#24342]
### Test Name

```shell
Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests
```

### Failure Output

```shell
[07:37:22] 	github.com/cilium/cilium/pkg/datapath/linux	coverage: 38.8% of statements
	 [07:37:22] panic: test timed out after 10m0s
	 [07:37:22] running tests:
	 [07:37:22] 	Test (10m0s)
	 [07:37:22] 
	 [07:37:22] goroutine 98 [running]:
	 [07:37:22] testing.(*M).startAlarm.func1()
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:2241 +0x3b9
	 [07:37:22] created by time.goFunc
	 [07:37:22] 	/usr/local/go/src/time/sleep.go:176 +0x32
	 [07:37:22] 
	 [07:37:22] goroutine 1 [chan receive, 10 minutes]:
	 [07:37:22] testing.(*T).Run(0xc000884820, {0x27b38b4?, 0x56ef25?}, 0x28e7378)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1630 +0x405
	 [07:37:22] testing.runTests.func1(0x4076700?)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:2036 +0x45
	 [07:37:22] testing.tRunner(0xc000884820, 0xc000729c80)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1576 +0x10b
	 [07:37:22] testing.runTests(0xc0008b0140?, {0x4033120, 0x1, 0x1}, {0xc0008be260?, 0x100c0008be1a0?, 0x4074fc0?})
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:2034 +0x489
	 [07:37:22] testing.(*M).Run(0xc0008b0140)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1906 +0x63a
	 [07:37:22] main.main()
	 [07:37:22] 	_testmain.go:80 +0x1c5
	 [07:37:22] 
	 [07:37:22] goroutine 25 [chan receive]:
	 [07:37:22] k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc0005302a0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:271 +0xa7
	 [07:37:22] created by k8s.io/client-go/util/workqueue.newQueue
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:63 +0x1bc
	 [07:37:22] 
	 [07:37:22] goroutine 26 [select]:
	 [07:37:22] k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000530420)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:233 +0x305
	 [07:37:22] created by k8s.io/client-go/util/workqueue.newDelayingQueue
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:70 +0x25b
	 [07:37:22] 
	 [07:37:22] goroutine 27 [chan receive, 9 minutes]:
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).runTest(...)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:813
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).run(0xc000395a00)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:618 +0x1bd
	 [07:37:22] gopkg.in/check%2ev1.Run({0x2728e00?, 0xc000892640?}, 0x3f92740?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x2a
	 [07:37:22] gopkg.in/check%2ev1.RunAll(0x3f92740?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x85
	 [07:37:22] gopkg.in/check%2ev1.TestingT(0xc0008849c0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x27c
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.Test(0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/datapath_test.go:13 +0x19
	 [07:37:22] testing.tRunner(0xc0008849c0, 0x28e7378)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1576 +0x10b
	 [07:37:22] created by testing.(*T).Run
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1629 +0x3ea
	 [07:37:22] 
	 [07:37:22] goroutine 80 [select, 9 minutes]:
	 [07:37:22] gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc0001485a0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:464 +0x8d
	 [07:37:22] created by gopkg.in/check%2ev1.(*resultTracker).start
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:444 +0x56
	 [07:37:22] 
	 [07:37:22] goroutine 88 [runnable, locked to thread]:
	 [07:37:22] golang.org/x/sys/unix.anyToSockaddr(0x1e?, 0xc000d937a0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_linux.go:975 +0x91a
	 [07:37:22] golang.org/x/sys/unix.Getsockname(0x1c?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_linux.go:1274 +0x6d
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkSocket).GetPid(0xc0008723c0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:808 +0x1e
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute(0xc00074f880, 0x4151c6?, 0x1c)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:523 +0x2c5
	 [07:37:22] github.com/vishvananda/netlink.(*Handle).NeighListExecute(0x4064d10, {0xa, 0x2d, 0x0, 0x0, 0x0})
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:251 +0x1f4
	 [07:37:22] github.com/vishvananda/netlink.(*Handle).NeighList(...)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:224
	 [07:37:22] github.com/vishvananda/netlink.NeighList(0xc0004175e0?, 0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:210 +0x4c
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.(*linuxPrivilegedIPv6OnlyTestSuite).TestArpPingHandling(0xc000892640, 0xc00019f1d0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/node_linux_test.go:1222 +0x10af
	 [07:37:22] reflect.Value.call({0x2728e00?, 0xc000892640?, 0x3e13?}, {0x27b35bc, 0x4}, {0xc0008acf08, 0x1, 0x1?})
	 [07:37:22] 	/usr/local/go/src/reflect/value.go:586 +0xb07
	 [07:37:22] reflect.Value.Call({0x2728e00?, 0xc000892640?, 0xc0003b8ac0?}, {0xc000158f08?, 0x3213?, 0xc000158e96?})
	 [07:37:22] 	/usr/local/go/src/reflect/value.go:370 +0xbc
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc00019f1d0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:775 +0x632
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:669 +0xa2
	 [07:37:22] created by gopkg.in/check%2ev1.(*suiteRunner).forkCall
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:666 +0x285
	 [07:37:22] 
	 [07:37:22] goroutine 71 [syscall, 9 minutes]:
	 [07:37:22] syscall.Syscall6(0x6?, 0x0?, 0x0?, 0x1?, 0x0?, 0xc000761dc8?, 0x40e508?)
	 [07:37:22] 	/usr/local/go/src/syscall/syscall_linux.go:91 +0x36
	 [07:37:22] golang.org/x/sys/unix.recvfrom(0x0?, {0xc000761e98?, 0x0?, 0x0?}, 0x0?, 0x0?, 0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:538 +0x70
	 [07:37:22] golang.org/x/sys/unix.Recvfrom(0x0?, {0xc000761e98, 0x10000, 0x10000}, 0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_unix.go:325 +0x7b
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc0008cb1a0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:762 +0x65
	 [07:37:22] github.com/vishvananda/netlink.linkSubscribeAt.func2()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2184 +0x90
	 [07:37:22] created by github.com/vishvananda/netlink.linkSubscribeAt
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2181 +0x2fb
	 [07:37:22] 
	 [07:37:22] goroutine 40 [chan receive, 9 minutes]:
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen.func1()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:373 +0x6e5
	 [07:37:22] created by github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:358 +0x327
	 [07:37:22] 
	 [07:37:22] goroutine 44 [syscall, 9 minutes]:
	 [07:37:22] syscall.Syscall6(0xc00071f980?, 0x0?, 0xc00090f858?, 0x451ed6?, 0x28?, 0xc00090f878?, 0x40e508?)
	 [07:37:22] 	/usr/local/go/src/syscall/syscall_linux.go:91 +0x36
	 [07:37:22] golang.org/x/sys/unix.recvfrom(0x7fffd0a443c8?, {0xc00090f948?, 0x3c?, 0x3c?}, 0xc0003b8980?, 0xc0003b8980?, 0x190000003c?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:538 +0x70
	 [07:37:22] golang.org/x/sys/unix.Recvfrom(0xc0003b8980?, {0xc00090f948, 0x10000, 0x10000}, 0x4658?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_unix.go:325 +0x7b
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0x2?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:762 +0x65
	 [07:37:22] github.com/vishvananda/netlink.routeSubscribeAt.func2()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/route_linux.go:1462 +0xab
	 [07:37:22] created by github.com/vishvananda/netlink.routeSubscribeAt
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/route_linux.go:1459 +0x30a
	 [07:37:22] 
	 [07:37:22] goroutine 46 [chan send, 9 minutes]:
	 [07:37:22] github.com/vishvananda/netlink.linkSubscribeAt.func2()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2222 +0x3cd
	 [07:37:22] created by github.com/vishvananda/netlink.linkSubscribeAt
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2181 +0x2fb
	 [07:37:22] 
	 [07:37:22] goroutine 47 [chan receive, 9 minutes]:
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen.func1()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:371 +0x68b
	 [07:37:22] created by github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:358 +0x327
	 [07:37:22] FAIL	github.com/cilium/cilium/pkg/datapath/linux	600.068s
	 [07:37:23] ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                     
	 [07:37:23] ┃   PANIC  package: github.com/cilium/cilium/pkg/datapath/linux • Test   ┃                                                     
	 [07:37:23] ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                     
	 [07:37:23] panic: test timed out after 10m0s                                                                                              
	 [07:37:23] running tests:                                                                                                                 
	 [07:37:23] 	Test (10m0s)
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Failed to run privileged unit tests
Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged NO_COLOR=1 | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
```

### Standard Output

```shell
[07:37:22] 	github.com/cilium/cilium/pkg/datapath/linux	coverage: 38.8% of statements
	 [07:37:22] panic: test timed out after 10m0s
	 [07:37:22] running tests:
	 [07:37:22] 	Test (10m0s)
	 [07:37:22] 
	 [07:37:22] goroutine 98 [running]:
	 [07:37:22] testing.(*M).startAlarm.func1()
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:2241 +0x3b9
	 [07:37:22] created by time.goFunc
	 [07:37:22] 	/usr/local/go/src/time/sleep.go:176 +0x32
	 [07:37:22] 
	 [07:37:22] goroutine 1 [chan receive, 10 minutes]:
	 [07:37:22] testing.(*T).Run(0xc000884820, {0x27b38b4?, 0x56ef25?}, 0x28e7378)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1630 +0x405
	 [07:37:22] testing.runTests.func1(0x4076700?)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:2036 +0x45
	 [07:37:22] testing.tRunner(0xc000884820, 0xc000729c80)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1576 +0x10b
	 [07:37:22] testing.runTests(0xc0008b0140?, {0x4033120, 0x1, 0x1}, {0xc0008be260?, 0x100c0008be1a0?, 0x4074fc0?})
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:2034 +0x489
	 [07:37:22] testing.(*M).Run(0xc0008b0140)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1906 +0x63a
	 [07:37:22] main.main()
	 [07:37:22] 	_testmain.go:80 +0x1c5
	 [07:37:22] 
	 [07:37:22] goroutine 25 [chan receive]:
	 [07:37:22] k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc0005302a0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:271 +0xa7
	 [07:37:22] created by k8s.io/client-go/util/workqueue.newQueue
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/queue.go:63 +0x1bc
	 [07:37:22] 
	 [07:37:22] goroutine 26 [select]:
	 [07:37:22] k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000530420)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:233 +0x305
	 [07:37:22] created by k8s.io/client-go/util/workqueue.newDelayingQueue
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:70 +0x25b
	 [07:37:22] 
	 [07:37:22] goroutine 27 [chan receive, 9 minutes]:
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).runTest(...)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:813
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).run(0xc000395a00)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:618 +0x1bd
	 [07:37:22] gopkg.in/check%2ev1.Run({0x2728e00?, 0xc000892640?}, 0x3f92740?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x2a
	 [07:37:22] gopkg.in/check%2ev1.RunAll(0x3f92740?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x85
	 [07:37:22] gopkg.in/check%2ev1.TestingT(0xc0008849c0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x27c
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.Test(0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/datapath_test.go:13 +0x19
	 [07:37:22] testing.tRunner(0xc0008849c0, 0x28e7378)
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1576 +0x10b
	 [07:37:22] created by testing.(*T).Run
	 [07:37:22] 	/usr/local/go/src/testing/testing.go:1629 +0x3ea
	 [07:37:22] 
	 [07:37:22] goroutine 80 [select, 9 minutes]:
	 [07:37:22] gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc0001485a0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:464 +0x8d
	 [07:37:22] created by gopkg.in/check%2ev1.(*resultTracker).start
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:444 +0x56
	 [07:37:22] 
	 [07:37:22] goroutine 88 [runnable, locked to thread]:
	 [07:37:22] golang.org/x/sys/unix.anyToSockaddr(0x1e?, 0xc000d937a0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_linux.go:975 +0x91a
	 [07:37:22] golang.org/x/sys/unix.Getsockname(0x1c?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_linux.go:1274 +0x6d
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkSocket).GetPid(0xc0008723c0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:808 +0x1e
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute(0xc00074f880, 0x4151c6?, 0x1c)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:523 +0x2c5
	 [07:37:22] github.com/vishvananda/netlink.(*Handle).NeighListExecute(0x4064d10, {0xa, 0x2d, 0x0, 0x0, 0x0})
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:251 +0x1f4
	 [07:37:22] github.com/vishvananda/netlink.(*Handle).NeighList(...)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:224
	 [07:37:22] github.com/vishvananda/netlink.NeighList(0xc0004175e0?, 0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:210 +0x4c
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.(*linuxPrivilegedIPv6OnlyTestSuite).TestArpPingHandling(0xc000892640, 0xc00019f1d0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/node_linux_test.go:1222 +0x10af
	 [07:37:22] reflect.Value.call({0x2728e00?, 0xc000892640?, 0x3e13?}, {0x27b35bc, 0x4}, {0xc0008acf08, 0x1, 0x1?})
	 [07:37:22] 	/usr/local/go/src/reflect/value.go:586 +0xb07
	 [07:37:22] reflect.Value.Call({0x2728e00?, 0xc000892640?, 0xc0003b8ac0?}, {0xc000158f08?, 0x3213?, 0xc000158e96?})
	 [07:37:22] 	/usr/local/go/src/reflect/value.go:370 +0xbc
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc00019f1d0)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:775 +0x632
	 [07:37:22] gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:669 +0xa2
	 [07:37:22] created by gopkg.in/check%2ev1.(*suiteRunner).forkCall
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:666 +0x285
	 [07:37:22] 
	 [07:37:22] goroutine 71 [syscall, 9 minutes]:
	 [07:37:22] syscall.Syscall6(0x6?, 0x0?, 0x0?, 0x1?, 0x0?, 0xc000761dc8?, 0x40e508?)
	 [07:37:22] 	/usr/local/go/src/syscall/syscall_linux.go:91 +0x36
	 [07:37:22] golang.org/x/sys/unix.recvfrom(0x0?, {0xc000761e98?, 0x0?, 0x0?}, 0x0?, 0x0?, 0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:538 +0x70
	 [07:37:22] golang.org/x/sys/unix.Recvfrom(0x0?, {0xc000761e98, 0x10000, 0x10000}, 0x0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_unix.go:325 +0x7b
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0xc0008cb1a0?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:762 +0x65
	 [07:37:22] github.com/vishvananda/netlink.linkSubscribeAt.func2()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2184 +0x90
	 [07:37:22] created by github.com/vishvananda/netlink.linkSubscribeAt
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2181 +0x2fb
	 [07:37:22] 
	 [07:37:22] goroutine 40 [chan receive, 9 minutes]:
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen.func1()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:373 +0x6e5
	 [07:37:22] created by github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:358 +0x327
	 [07:37:22] 
	 [07:37:22] goroutine 44 [syscall, 9 minutes]:
	 [07:37:22] syscall.Syscall6(0xc00071f980?, 0x0?, 0xc00090f858?, 0x451ed6?, 0x28?, 0xc00090f878?, 0x40e508?)
	 [07:37:22] 	/usr/local/go/src/syscall/syscall_linux.go:91 +0x36
	 [07:37:22] golang.org/x/sys/unix.recvfrom(0x7fffd0a443c8?, {0xc00090f948?, 0x3c?, 0x3c?}, 0xc0003b8980?, 0xc0003b8980?, 0x190000003c?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:538 +0x70
	 [07:37:22] golang.org/x/sys/unix.Recvfrom(0xc0003b8980?, {0xc00090f948, 0x10000, 0x10000}, 0x4658?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_unix.go:325 +0x7b
	 [07:37:22] github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive(0x2?)
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:762 +0x65
	 [07:37:22] github.com/vishvananda/netlink.routeSubscribeAt.func2()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/route_linux.go:1462 +0xab
	 [07:37:22] created by github.com/vishvananda/netlink.routeSubscribeAt
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/route_linux.go:1459 +0x30a
	 [07:37:22] 
	 [07:37:22] goroutine 46 [chan send, 9 minutes]:
	 [07:37:22] github.com/vishvananda/netlink.linkSubscribeAt.func2()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2222 +0x3cd
	 [07:37:22] created by github.com/vishvananda/netlink.linkSubscribeAt
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:2181 +0x2fb
	 [07:37:22] 
	 [07:37:22] goroutine 47 [chan receive, 9 minutes]:
	 [07:37:22] github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen.func1()
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:371 +0x68b
	 [07:37:22] created by github.com/cilium/cilium/pkg/datapath/linux.(*DeviceManager).Listen
	 [07:37:22] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/datapath/linux/devices.go:358 +0x327
	 [07:37:22] FAIL	github.com/cilium/cilium/pkg/datapath/linux	600.068s
	 [07:37:23] ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                     
	 [07:37:23] ┃   PANIC  package: github.com/cilium/cilium/pkg/datapath/linux • Test   ┃                                                     
	 [07:37:23] ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                     
	 [07:37:23] panic: test timed out after 10m0s                                                                                              
	 [07:37:23] running tests:                                                                                                                 
	 [07:37:23] 	Test (10m0s)
```

### Standard Error

```shell
make: *** [Makefile:124: tests-privileged] Error 1
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/5485/
- ZIP file(s): 
[822df592_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/10958562/822df592_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip)

**Comment by lmb** [comment]
Another one: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/5685/consoleFull

**Comment by lmb** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/5767/testReport/junit/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/

**Comment by pippolo84** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/6024/testReport/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/

[3157230c_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/11212177/3157230c_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip)

**Comment by julianwiedmann** [comment]
> Isn't this a duplicate of #22373?

sure looks like it :+1:. Closing as dup.
