### ISSUE TITLE
Potential nil dereference while handling ingress events

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#24347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Cilium operator crashed with a segmentation violation while handling an ingress-related event. I've hit this during a conformance test [here](https://github.com/cilium/cilium/actions/runs/4384508720/jobs/7676070438).

### Cilium Version

Recent commit on master: 8b2070337d

### Kernel Version

Not relevant

### Kubernetes Version

Not relevant

### Sysdump

[cilium-sysdump.zip](https://github.com/cilium/cilium/files/10959514/cilium-sysdump.zip)

### Relevant log output

```shell
2023-03-10T12:52:09.342894095Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x219c412]
2023-03-10T12:52:09.342902395Z 
2023-03-10T12:52:09.342906895Z goroutine 453 [running]:
2023-03-10T12:52:09.344878190Z github.com/cilium/cilium/operator/pkg/ingress.(*Controller).garbageCollectOwnedResources(0xc0006ff320, 0x414946?)
2023-03-10T12:52:09.345030090Z 	/go/src/github.com/cilium/cilium/operator/pkg/ingress/ingress.go:661 +0x132
2023-03-10T12:52:09.345040990Z github.com/cilium/cilium/operator/pkg/ingress.(*Controller).handleIngressAddedEvent(0xc0006ff320, {0xc0015f50d0?})
2023-03-10T12:52:09.345160190Z 	/go/src/github.com/cilium/cilium/operator/pkg/ingress/ingress.go:255 +0x113
2023-03-10T12:52:09.345169690Z github.com/cilium/cilium/operator/pkg/ingress.(*Controller).handleEvent(0xc0007e8a20?, {0x25a1060?, 0xc000ccb800?})
2023-03-10T12:52:09.345598088Z 	/go/src/github.com/cilium/cilium/operator/pkg/ingress/ingress.go:494 +0x4e5
2023-03-10T12:52:09.345887688Z github.com/cilium/cilium/operator/pkg/ingress.(*Controller).processEvent(0xc0006ff320)
2023-03-10T12:52:09.346440686Z 	/go/src/github.com/cilium/cilium/operator/pkg/ingress/ingress.go:215 +0xf1
2023-03-10T12:52:09.346805785Z github.com/cilium/cilium/operator/pkg/ingress.(*Controller).Run(0xc0006ff320)
2023-03-10T12:52:09.347340184Z 	/go/src/github.com/cilium/cilium/operator/pkg/ingress/ingress.go:205 +0x2b4
2023-03-10T12:52:09.348730880Z created by github.com/cilium/cilium/operator/cmd.(*legacyOnLeader).onStart
2023-03-10T12:52:09.349290879Z 	/go/src/github.com/cilium/cilium/operator/cmd/root.go:677 +0x2d9d
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
cc @sayboras

**Comment by sayboras** [comment]
Thanks, assign the issue to myself, will take a look later. As we didn't see it in 1.12 or 1.13, this could only happen in master branch.
