### ISSUE TITLE
Cilium Operator crashes when CiliumEndpoint CRD is disabled

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#24396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Operator crashes when endpoint CRD is disabled: `disable-endpoint-crd: "true"`

```
188 2023-03-15T16:37:15.327129738Z Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer der    eference)
189 2023-03-15T16:37:15.328109280Z goroutine 461 [running]:
190 2023-03-15T16:37:15.328116488Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1f5f440?, 0x3e79d70})
191 2023-03-15T16:37:15.328118655Z  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x84
192 2023-03-15T16:37:15.328123571Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
193 2023-03-15T16:37:15.328124738Z  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x80
194 2023-03-15T16:37:15.328126321Z panic({0x1f5f440, 0x3e79d70})
195 2023-03-15T16:37:15.328131071Z  /usr/local/go/src/runtime/panic.go:884 +0x20c
196 2023-03-15T16:37:15.328137988Z github.com/cilium/cilium/operator/watchers.endpointUpdated(0x4000886ea0)
197 2023-03-15T16:37:15.328139196Z  /go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:216 +0x4c
```

### Cilium Version

v1.13.0

This doesn't appear to happen in master, it happens on both v1.13.0 as well as (current) v1.13.2 release branch.

### Kernel Version

5.15.0-60-generic

### Kubernetes Version

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

### Sysdump

[operator-panic.zip](https://github.com/cilium/cilium/files/10984255/operator-panic.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by doniacld** [comment]
I have been able to reproduce it on main adding the following flags to the existing ones in [kind-values.yaml](https://github.com/cilium/cilium/blob/main/contrib/testing/kind-values.yaml).

```yaml
enableCiliumEndpointSlice: true
disableEndpointCRD: true
identityAllocationMode: "kvstore"
etcd: # the ETCD config varies, but this is not important
  enabled: true
```


The panic happened when endpoints are updated in this part of the [code](https://github.com/cilium/cilium/blob/main/operator/watchers/cilium_endpoint.go#L216).
The `cesController` is not initialized and therefore nil. This part of the code should not be called in this configuration.
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 394 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2081620?, 0x40bbe20})
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4001577928?})
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x78
panic({0x2081620, 0x40bbe20})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/cilium/cilium/operator/watchers.endpointUpdated(0x40006de820)
        /go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:218 +0xd0
github.com/cilium/cilium/operator/watchers.CiliumEndpointsInit.func1.1({0x24a9360?, 0x40006de820?})
        /go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:85 +0x2c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:232
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x20d9860?, 0x4000d91128?})
        /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:123 +0x25c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x4000634a00, 0x40009a4d40)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x4c4
k8s.io/client-go/tools/cache.(*controller).processLoop(0x400014ecf0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xffff652df488?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000956001?, {0x28d38e0, 0x4000c22000}, 0x1, 0x40019789c0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x400014ed58?, 0x3b9aca00, 0x0, 0x20?, 0xffff65250940?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0x400014ecf0, 0x40019789c0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x274
github.com/cilium/cilium/operator/watchers.CiliumEndpointsInit.func1.4()
        /go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:118 +0x84
created by github.com/cilium/cilium/operator/watchers.CiliumEndpointsInit.func1
        /go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:116 +0x374
level=error msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=error msg="goroutine 394 [running]:" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2081620?, 0x40bbe20})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c" subsys=klog
level=error msg="k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4001577928?})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x78" subsys=klog
level=error msg="panic({0x2081620, 0x40bbe20})" subsys=klog
level=error msg="\t/usr/local/go/src/runtime/panic.go:884 +0x1f4" subsys=klog
level=error msg="github.com/cilium/cilium/operator/watchers.endpointUpdated(0x40006de820)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:218 +0xd0" subsys=klog
level=error msg="github.com/cilium/cilium/operator/watchers.CiliumEndpointsInit.func1.1({0x24a9360?, 0x40006de820?})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/operator/watchers/cilium_endpoint.go:85 +0x2c" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:232" subsys=klog
level=error msg="github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x20d9860?, 0x4000d91128?})" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:123 +0x25c" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x4000634a00, 0x40009a4d40)" subsys=klog
level=error msg="\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x4c4" subsys=klog
level=error msg="k8s.io/client-go/tools/cache.(*controller).processLoop(0x400014ecf0)" subsys=klog
level=fatal msg="Panic in Kubernetes runtime handler" subsys=k8s
```

**Comment by tommyp1ckles** [comment]
Hmm seems like disableEndpointCRD should prevent the CEP watcher from starting.
