### ISSUE TITLE
Cilium: Close() called without calling InitIdentityAllocator() first

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#24423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Terminating Cilium process via ^C triggers below panic:
```

^Clevel=info msg="Signal received" signal=interrupt subsys=hive
level=info msg="Shutting down... " subsys=daemon
level=info msg=Stopping subsys=hive
level=info msg="Stopped serving cilium API at unix:///var/run/cilium/cilium.sock" subsys=daemon
level=info msg="Waiting for all endpoints' goroutines to be stopped." subsys=daemon
level=info msg="All endpoints' goroutines stopped." subsys=daemon
level=info msg="Stop hook executed" duration="139.316µs" function="cmd.newDaemonPromise.func2 (daemon_main.go:1661)" subsys=hive
level=info msg="Stop hook executed" duration="1.68µs" function="monitor.(*dropMonitor).OnStop" subsys=hive
level=info msg="Stop hook executed" duration="20.289µs" function="*manager.manager.Stop" subsys=hive
level=panic msg="Close() called without calling InitIdentityAllocator() first" subsys=identity-cache
level=info msg="Stopped reading perf buffer" startTime="2023-03-17 09:16:47.295628841 +0000 UTC m=+5.086296656" subsys=monitor-agent
panic: (*logrus.Entry) 0xc0005f1b90

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000155a40, 0x0, {0xc00007ae40, 0x3c})
	/root/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc000155a40, 0x0, {0xc000f3f5d8?, 0xc000207040?, 0x3?})
	/root/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:342
github.com/cilium/cilium/pkg/identity/cache.(*CachingIdentityAllocator).Close(0xc001091740)
	/root/go/src/github.com/cilium/cilium/pkg/identity/cache/allocator.go:261 +0xdc
github.com/cilium/cilium/daemon/cmd.newPolicyTrifecta.func2({0x2ecd8e0?, 0x493900?})
	/root/go/src/github.com/cilium/cilium/daemon/cmd/policy.go:138 +0xb2
github.com/cilium/cilium/pkg/hive.Hook.Stop(...)
	/root/go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:42
github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Stop(0xc000573740, {0x37db990?, 0xc0001fa6c0?})
	/root/go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:139 +0x333
github.com/cilium/cilium/pkg/hive.(*Hive).Stop(0xc00064a000, {0x37db990, 0xc0001fa6c0})
	/root/go/src/github.com/cilium/cilium/pkg/hive/hive.go:252 +0xc9
github.com/cilium/cilium/pkg/hive.(*Hive).Run(0xc00064a000)
	/root/go/src/github.com/cilium/cilium/pkg/hive/hive.go:182 +0x21d
github.com/cilium/cilium/daemon/cmd.runApp(0x52e3460?, {0x327bc72?, 0x9?, 0x9?})
	/root/go/src/github.com/cilium/cilium/daemon/cmd/root.go:67 +0xe5
github.com/spf13/cobra.(*Command).execute(0x52e3460, {0xc0000720b0, 0x9, 0x9})
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x52e3460)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:968
github.com/cilium/cilium/daemon/cmd.Execute()
	/root/go/src/github.com/cilium/cilium/daemon/cmd/root.go:78 +0x65
main.main()
	/root/go/src/github.com/cilium/cilium/daemon/main.go:15 +0x17
```

### Cilium Version

master tree

### Kernel Version

-

### Kubernetes Version

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nebril** [comment]
This seems to have been fixed by https://github.com/cilium/cilium/pull/24694
