### ISSUE TITLE
l7 policies do not work in gke

### ISSUE THREAD

**Issue by lenhattan86** [cilium/cilium#24679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Environment: 
* gke (with dataplane v2 & auto-repair disabled)
* cilium 1.13.0

Steps to reproduce:
* make sure no CNP (cilium network policies) are added.
```
$ kubectl get cnp -A
No resources found
```
* deploy deathstar, spaceship and xwing from https://github.com/cilium/star-wars-demo/blob/master/01-deathstar.yaml and https://github.com/cilium/star-wars-demo/blob/master/02-xwing.yaml. In this case I changed `replicas=1` but it does not matter.
```
kubectl get pods -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE                              NOMINATED NODE   READINESS GATES
deathstar-7bd4f99db8-q46nx   1/1     Running   0          5s    172.19.0.46    gke-infra-gke-gp1-a4e93c2c-00d5   <none>           <none>
spaceship-69789b6f5-g4tjg    1/1     Running   0          8d    172.19.0.144   gke-infra-gke-gp1-a4e93c2c-scr5   <none>           <none>
xwing-5f4b9fdc6-nr4lj        1/1     Running   0          8d    172.19.0.51    gke-infra-gke-gp1-a4e93c2c-00d5   <none>           <none>

```
* Apply l7_policy https://github.com/cilium/star-wars-demo/blob/master/policy/l7_policy.yaml
```
$ kubectl get cnp
NAME                       AGE
deathstar-api-protection   4s

$kubectl describe cnp
Name:         deathstar-api-protection
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  cilium.io/v2
Kind:         CiliumNetworkPolicy
Metadata:
  Creation Timestamp:  2023-03-31T17:14:54Z
  Generation:          1
  Managed Fields:
    API Version:  cilium.io/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:endpointSelector:
          .:
          f:matchLabels:
            .:
            f:class:
            f:org:
        f:ingress:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2023-03-31T17:14:54Z
  Resource Version:  5510654
  UID:               5af586dd-98ae-4d4a-a5d0-f8fae144919f
Spec:
  Endpoint Selector:
    Match Labels:
      Class:  deathstar
      Org:    empire
  Ingress:
    From Endpoints:
      Match Labels:
        Class:  spaceship
    To Ports:
      Ports:
        Port:      80
        Protocol:  TCP
      Rules:
        Http:
          Method:  GET
          Path:    /v1/
          Method:  POST
          Path:    /v1/request-landing$
          Headers:
            X-Has-Force: True
          Method:  PUT
          Path:    /v1/exhaust-port$
Events:            <none>
```
* attack from xwing to deathstar
```
kubectl exec -ti xwing-5f4b9fdc6-nr4lj -- curl -XPUT -H 'X-Has-Force: True' deathstar.default.svc.cluster.local/v1/exhaust-port
```

Actual:  curl timed out
```
curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56
```
Expected:
```
Panic: deathstar exploded

goroutine 1 [running]:
main.HandleGarbage(0x2080c3f50, 0x2, 0x4, 0x425c0, 0x5, 0xa)
        /code/src/github.com/empire/deathstar/
        temp/main.go:9 +0x64
main.main()
        /code/src/github.com/empire/deathstar/
        temp/main.go:5 +0x85
```

### Cilium Version

cilium-cli: v0.13.1 compiled with go1.20 on linux/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.13.1
cilium image (running): v1.13.0

### Kernel Version

```
kubectl exec -n kube-system cilium-rfl92 -- uname -a
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
Linux gke-infra-gke-gp1-a4e93c2c-scr5 5.4.0-1086-gke #93-Ubuntu SMP Mon Oct 17 13:32:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14-gke.1800", GitCommit:"1eab5b8da4acab130c72aea21eb7ed3e96523ca2", GitTreeState:"clean", BuildDate:"2022-12-07T09:32:46Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230331-101840.zip](https://github.com/cilium/cilium/files/11124454/cilium-sysdump-20230331-101840.zip)

### Relevant log output

```shell
gke cluster

kubectl get pods -n kube-system
NAME                                         READY   STATUS    RESTARTS     AGE
cilium-mt88m                                 1/1     Running   0            2d19h
cilium-node-init-ppjp5                       1/1     Running   0            2d19h
cilium-node-init-q9clr                       1/1     Running   0            2d19h
cilium-node-init-w2xfc                       1/1     Running   0            2d19h
cilium-operator-7cd45877b-st5m5              1/1     Running   0            2d19h
cilium-rfl92                                 1/1     Running   0            2d19h
cilium-tlqvf                                 1/1     Running   0            2d19h
event-exporter-gke-5dc976447f-dp5q6          2/2     Running   0            8d
fluentbit-gke-4c9rj                          2/2     Running   0            8d
fluentbit-gke-56bq6                          2/2     Running   2 (8d ago)   8d
fluentbit-gke-jz2kz                          2/2     Running   0            8d
gke-metrics-agent-4xfcz                      1/1     Running   0            7d17h
gke-metrics-agent-9xh9k                      1/1     Running   0            7d17h
gke-metrics-agent-gsdld                      1/1     Running   0            7d17h
hubble-relay-6dc9cb87d5-6tdtl                1/1     Running   0            2d19h
kube-dns-7d44cdb5d5-4s9xt                    4/4     Running   0            8d
kube-dns-7d44cdb5d5-5xmcm                    4/4     Running   0            8d
kube-dns-autoscaler-fbc66b884-8gl76          1/1     Running   0            8d
kube-proxy-gke-infra-gke-gp1-a4e93c2c-00d5   1/1     Running   1 (8d ago)   8d
kube-proxy-gke-infra-gke-gp1-a4e93c2c-djjh   1/1     Running   0            8d
kube-proxy-gke-infra-gke-gp1-a4e93c2c-scr5   1/1     Running   0            8d
metrics-server-v0.5.2-866bc7fbf8-nnt5k       2/2     Running   0            8d
netd-bwvgz                                   1/1     Running   0            8d
netd-hbx8p                                   1/1     Running   0            8d
netd-kj2v5                                   1/1     Running   1 (8d ago)   8d
pdcsi-node-h84km                             2/2     Running   0            8d
pdcsi-node-jz7ls                             2/2     Running   0            8d
pdcsi-node-t48hq                             2/2     Running   2 (8d ago)   8d
```

hubble observe on default/xwing-5f4b9fdc6-nr4lj 
```
$ kubectl exec -it cilium-mt88m -n kube-system  -- hubble observe --pod default/xwing-5f4b9fdc6-nr4lj -f

Mar 31 17:40:54.248: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: SYN)
Mar 31 17:40:54.248: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: SYN)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) policy-verdict:L3-L4 INGRESS ALLOWED (TCP Flags: SYN)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-proxy FORWARDED (TCP Flags: SYN)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <- default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK)
Mar 31 17:40:54.249: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK)
Mar 31 17:40:54.453: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:40:54.661: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:40:55.077: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:40:55.269: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK)
Mar 31 17:40:55.909: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:40:57.285: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK)
Mar 31 17:40:57.577: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:41:00.869: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:41:00.869: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:41:01.381: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <- default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Mar 31 17:41:01.381: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK)
Mar 31 17:41:07.525: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:41:07.525: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:41:09.573: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <- default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Mar 31 17:41:09.573: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK)
Mar 31 17:41:20.837: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:41:20.837: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:41:25.701: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <- default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Mar 31 17:41:25.701: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK)
Mar 31 17:41:47.973: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:41:47.973: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:42:41.221: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-stack FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:42:41.221: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) DBG_CAPTURE_DELIVERY VERDICT_UNKNOWN (TCP Flags: ACK, PSH)
Mar 31 17:42:41.222: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) -> default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-proxy FORWARDED (TCP Flags: ACK, PSH)
Mar 31 17:42:41.222: default/xwing-5f4b9fdc6-nr4lj:56450 (ID:54246) <- default/deathstar-7bd4f99db8-q46nx:80 (ID:42441) to-endpoint FORWARDED (TCP Flags: RST)
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
My mistake, I mis-read the issue.

**Comment by lenhattan86** [comment]
@squeed  do we have anyone to take a look at this issue?

**Comment by christarazi** [comment]
Did you try with the latest v1.13.x?

**Comment by lenhattan86** [comment]
> 
Not yet, will try in a couple of days. 
Any reason why later version could work?

**Comment by paulbhart** [comment]
I can atest that L7 tests fail using dataplane V1 + GKE.  Research to understand whether it can work has been difficult. I have found two documents wrt to Calico (what is typically preinstalled as the CNI for GKE for V1 dataplane).  both are talk about CNI chaining (i.e. that both calico and cilium will exist I assume). The first link seems only "valid" for < 1.13 releases https://docs.cilium.io/en/v1.12/gettingstarted/cni-chaining-calico/ and clearly calls out that CNI chaining causes issues for Layer 7 Policy.  and refers to https://github.com/cilium/cilium/issues/12454.  I had hoped that maybe in 1.13 they didn't need the CNI chaining documenation as they fixed this somehow, but that isn't my experience at the moment.

**Comment by paulbhart** [comment]
also, let me know I can post more information wrt to my configuration and the error message if that is helpful.

**Comment by lenhattan86** [comment]
The issue still there in gke dpv1 & cilium 1.15.1
