### ISSUE TITLE
CI: TestResource_WithFakeClient panic

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#24696]
## CI failure

https://app.travis-ci.com/github/cilium/cilium/builds/261984304

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━���━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   PANIC  package: github.com/cilium/cilium/pkg/k8s/resource • TestResource_WithFakeClient   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
panic: runtime error: invalid memory address or nil pointer dereference [recovered]            
	panic: runtime error: invalid memory address or nil pointer dereference                        
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x158bad0]                      
                                                                                               
goroutine 14 [running]:                                                                        
testing.tRunner.func1.2({0x17bd7c0, 0x2d1ae00})                                                
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1526 +0x1c8           
testing.tRunner.func1()                                                                        
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1529 +0x364           
panic({0x17bd7c0, 0x2d1ae00})                                                                  
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/runtime/panic.go:884 +0x1f4              
github.com/cilium/cilium/pkg/k8s/resource_test.TestResource_WithFakeClient(0x4000425a00)       
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/resource/resource_test.go:167 +0xa70  
testing.tRunner(0x4000425a00, 0x1b812d0)                                                       
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1576 +0x104           
created by testing.(*T).Run                                                                    
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1629 +0x370           
FAIL	github.com/cilium/cilium/pkg/k8s/resource	60.044s   
```

**Comment by lmb** [comment]
Another one: https://github.com/cilium/cilium/actions/runs/5066341866/jobs/9096028130?pr=25484
