### ISSUE TITLE
Upgrading/ Reverting vpc-cni addon [v1.12.6-eksbuild.1 <-> v1.12.5-eksbuild.2] on EKS v1.24 breaks underlying network with Cilium as CNI

### ISSUE THREAD

**Issue by ajaykumarmandapati** [cilium/cilium#25131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While upgrading `vpc-cni` addon [v1.12.6-eksbuild.1 <-> v1.12.5-eksbuild.2] on EKS cluster `v1.24` breaks networking for all pods in `terminating` state and new pods that come up in `pending` state.

**This is the error message we received after upgrading the `vpc-cni` plugin on any workload that was trying to be scheduled :**

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6e7f82eed3c3c40752c08e8fa672029640c64eb5b966f22597154d9cd1ac6bcb": plugin type="egress-v4-cni" name="egress-v4-cni" failed (add): netplugin failed: "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5598b4660a2c]\n\ngoroutine 1 [running, locked to thread]:\nmain.cmdAdd(0xc000180850)\n\t/go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/egress-v4-cni-plugin/cni.go:256 +0xbec\ngithub.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc0000d5ed8, 0xc000180850, {0x5598b4798d18, 0xc0000b8e40}, 0x5598b4796be8)\n\t/go/pkg/mod/github.com/containernetworking/cni@v0.8.1/pkg/skel/skel.go:166 +0x20a\ngithub.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc0000d5ed8, 0x5598b48e5000?, 0xc0000d5ec0?, 0x5598b44be809?, {0x5598b4798d18, 0xc0000b8e40}, {0xc000018108, 0x15})\n\t/go/pkg/mod/github.com/containernetworking/cni@v0.8.1/pkg/skel/skel.go:218 +0x245\ngithub.com/containernetworking/cni/pkg/skel.PluginMainWithError(...)\n\t/go/pkg/mod/github.com/containernetworking/cni@v0.8.1/pkg/skel/skel.go:275\ngithub.com/containernetworking/cni/pkg/skel.PluginMain(0x5598b4667db5?, 0x17?, 0xc0000d5f60?, {0x5598b4798d18?, 0xc0000b8e40?}, {0xc000018108?, 0x0?})\n\t/go/pkg/mod/github.com/containernetworking/cni@v0.8.1/pkg/skel/skel.go:290 +0xd1\nmain.main()\n\t/go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/egress-v4-cni-plugin/cni.go:250 +0x8e\n" 
```

**This is the error message we received after upgrading the `vpc-cni` plugin on any pods that were in terminating phase :**

```
error killing pod: failed to "KillPodSandbox" for "a10c54e7-3cad-41d0-aaa4-440db2df3ceb" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"3e96ad4dcb4183d542d0bbaecc5bef1d31cca718b95d3f796f6de3805bad5fd5\": plugin type=\"egress-v4-cni\" name=\"egress-v4-cni\" failed (delete): failed to parse config: json: cannot unmarshal string into Go struct field NetConf.mtu of type int" 
```

**Note:**  Know workaround, deleting `cilium-daemonset` pod on the node solves this issue

### Cilium Version

`v1.13.2`

### Kernel Version

`Bottlerocket OS 1.13.3 (aws-k8s-1.24)`
`5.15.102`

### Kubernetes Version

`v1.24.10-eks-48e63af`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
This appears to be the line that is failing: https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.12/cmd/egress-v4-cni-plugin/cni.go#L256

It means the AWS plugin is failing to parse the cni configuration. Can you please include the file(s) in `/etc/cni/net.d/`?

**Comment by squeed** [comment]
It is unlikely that we caused this, since libcni also requires the CNI configuration to be valid json, but anything is possible.

**Comment by justenwalker** [comment]
I've raised a similar issue here on the VPC CNI plugin; since the stack trace seems to be coming from there: https://github.com/aws/amazon-vpc-cni-k8s/issues/2364

**Comment by justenwalker** [comment]
Looks like there was a breaking change in the cni configuration for the MTU Parameters. Looks like a  Cilium fix would be required.

See: https://github.com/aws/amazon-vpc-cni-k8s/issues/2364#issuecomment-1529926817

**Comment by squeed** [comment]
Gotcha. 1.14 already fixes this properly, I’ll look in to a fix for 1.13 and earlier.

**Comment by justenwalker** [comment]
@squeed FYI
https://github.com/aws/amazon-vpc-cni-k8s/issues/2364#issuecomment-1530117595
> Note that https://github.com/aws/amazon-vpc-cni-k8s/pull/2353 refactored the conflist as well, and the name change (egress-v4-plugin -> egress-plugin) could cause a problem for Cilium in the next release, v1.13.x

**Comment by squeed** [comment]
Cilium doesn’t hard-code the AWS portion of the config; it injects itself in to whatever is already there.

However, it doesn’t re-trigger generation if the “source” config changes. (1.14 already fixed this, but it’s not so easy to backport). I’ll see how we can handle this gracefully in 1.13 and before.

**Comment by squeed** [comment]
The problem is that in v1.13 and prior, we only generate the CNI configuration file on agent startup. If the "source" configuration file (i.e. 10-aws-cni.conflist) changes after startup, we miss that.

The "easiest" fix is to exit the agent when the file changes, but maybe there's a better way. Hmm.

**Comment by rrey** [comment]
@squeed just to be sure I get your last comment the proper way: If one faces the issue reported here triggering a rollout of the cilium daemonset shall allow it to regenerate the conf properly and fix the issue ?

**Comment by squeed** [comment]
@rrey that's correct. I'm still thinking about a proper fix.

**Comment by rrey** [comment]
For people that may land here, I confirm that the cilium daemonset rollout fixes the issue while the real fix is coming.

**Comment by NesManrique** [comment]
> The problem is that in v1.13 and prior, we only generate the CNI configuration file on agent startup. If the "source" configuration file (i.e. 10-aws-cni.conflist) changes after startup, we miss that.
> 
> The "easiest" fix is to exit the agent when the file changes, but maybe there's a better way. Hmm.

I just hit this in my clusters. Only doubt I have is what could trigger a "source" configuration file change?

**Comment by meysam81** [comment]
If you've read the comments thus far and still haven't been able to fix the issue, in my case, removing the `/etc/cni/net.d/05-cilium.conflist` from the worker nodes of AWS EKS manually fixed the issue. The `cilium uninstall` didn't do it automatically!
