### ISSUE TITLE
CI: hive/job: Timed out after 10m

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#25276]
## CI failure

Seems like something in hive/job can trigger breakage/hanging behaviour in the main branch:

```
	 [08:10:17] panic: test timed out after 10m0s
	 [08:10:17] running tests:
	 [08:10:17] 	TestOneShot_RetryRecoverNoShutdown (9m44s)
	 [08:10:17] 
	 [08:10:17] goroutine 81 [running]:
	 [08:10:17] testing.(*M).startAlarm.func1()
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:2241 +0x3b9
	 [08:10:17] created by time.goFunc
	 [08:10:17] 	/usr/local/go/src/time/sleep.go:176 +0x32
	 [08:10:17] 
	 [08:10:17] goroutine 1 [chan receive]:
	 [08:10:17] testing.(*T).Run(0xc000144680, {0x88377d?, 0x5637a5?}, 0x8ba1c0)
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1630 +0x405
	 [08:10:17] testing.runTests.func1(0xba5d80?)
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:2036 +0x45
	 [08:10:17] testing.tRunner(0xc000144680, 0xc0001afb68)
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1576 +0x10b
	 [08:10:17] testing.runTests(0xc0001741e0?, {0xb9c6e0, 0x14, 0x14}, {0x2?, 0x0?, 0xba53c0?})
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:2034 +0x489
	 [08:10:17] testing.(*M).Run(0xc0001741e0)
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1906 +0x63a
	 [08:10:17] go.uber.org/goleak.VerifyTestMain({0x921f00?, 0xc0001741e0?}, {0xc0001afea8, 0x1, 0x1})
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/go.uber.org/goleak/testmain.go:53 +0x6b
	 [08:10:17] github.com/cilium/cilium/pkg/hive/job.TestMain(0x87465b?)
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:30 +0x6f
	 [08:10:17] main.main()
	 [08:10:17] 	_testmain.go:118 +0x1ef
	 [08:10:17] 
	 [08:10:17] goroutine 67 [select]:
	 [08:10:17] github.com/cilium/cilium/pkg/hive.(*Hive).waitForSignalOrShutdown(0xc0003520a0)
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/hive.go:203 +0x19f
	 [08:10:17] github.com/cilium/cilium/pkg/hive.(*Hive).Run(0xc0003520a0)
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/hive.go:184 +0x147
	 [08:10:17] github.com/cilium/cilium/pkg/hive/job.TestOneShot_RetryRecoverNoShutdown(0xc0003361a0)
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:341 +0x196
	 [08:10:17] testing.tRunner(0xc0003361a0, 0x8ba1c0)
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1576 +0x10b
	 [08:10:17] created by testing.(*T).Run
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1629 +0x3ea
	 [08:10:17] 
	 [08:10:17] goroutine 27 [syscall]:
	 [08:10:17] os/signal.signal_recv()
	 [08:10:17] 	/usr/local/go/src/runtime/sigqueue.go:152 +0x2f
	 [08:10:17] os/signal.loop()
	 [08:10:17] 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
	 [08:10:17] created by os/signal.Notify.func1.1
	 [08:10:17] 	/usr/local/go/src/os/signal/signal.go:151 +0x2a
	 [08:10:17] 
	 [08:10:17] goroutine 68 [chan receive (nil chan)]:
	 [08:10:17] github.com/cilium/cilium/pkg/hive/job.TestOneShot_RetryRecoverNoShutdown.func2()
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:335 +0x45
	 [08:10:17] created by github.com/cilium/cilium/pkg/hive/job.TestOneShot_RetryRecoverNoShutdown
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:334 +0x18c
	 [08:10:17] FAIL	github.com/cilium/cilium/pkg/hive/job	600.106s
	 [08:10:17] ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
	 [08:10:17] ┃   PANIC  package: github.com/cilium/cilium/pkg/hive/job • TestOneShot_RetryRecoverNoShutdown   ┃
	 [08:10:17] ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
	 [08:10:17] panic: test timed out after 10m0s                                                                 
	 [08:10:17] running tests:                                                                                    
	 [08:10:17] 	TestOneShot_RetryRecoverNoShutdown (9m44s)                                                        
	 [08:10:17]                                                                                                   
	 [08:10:17] goroutine 81 [running]:                                                                           
	 [08:10:17] testing.(*M).startAlarm.func1()                                                                   
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:2241 +0x3b9                                                  
	 [08:10:17] created by time.goFunc                                                                            
	 [08:10:17] 	/usr/local/go/src/time/sleep.go:176 +0x32                                                         
	 [08:10:17]                                                                                                   
	 [08:10:17] goroutine 1 [chan receive]:                                                                       
	 [08:10:17] testing.(*T).Run(0xc000144680, {0x88377d?, 0x5637a5?}, 0x8ba1c0)                                  
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1630 +0x405                                                  
	 [08:10:17] testing.runTests.func1(0xba5d80?)                                                                 
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:2036 +0x45                                                   
	 [08:10:17] testing.tRunner(0xc000144680, 0xc0001afb68)                                                       
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1576 +0x10b                                                  
	 [08:10:17] testing.runTests(0xc0001741e0?, {0xb9c6e0, 0x14, 0x14}, {0x2?, 0x0?, 0xba53c0?})                  
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:2034 +0x489                                                  
	 [08:10:17] testing.(*M).Run(0xc0001741e0)                                                                    
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1906 +0x63a                                                  
	 [08:10:17] go.uber.org/goleak.VerifyTestMain({0x921f00?, 0xc0001741e0?}, {0xc0001afea8, 0x1, 0x1})           
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/go.uber.org/goleak/testmain.go:53 +0x6b      
	 [08:10:17] github.com/cilium/cilium/pkg/hive/job.TestMain(0x87465b?)                                         
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:30 +0x6f                   
	 [08:10:17] main.main()                                                                                       
	 [08:10:17] 	_testmain.go:118 +0x1ef                                                                           
	 [08:10:17]                                                                                                   
	 [08:10:17] goroutine 67 [select]:                                                                            
	 [08:10:17] github.com/cilium/cilium/pkg/hive.(*Hive).waitForSignalOrShutdown(0xc0003520a0)                   
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/hive.go:203 +0x19f                         
	 [08:10:17] github.com/cilium/cilium/pkg/hive.(*Hive).Run(0xc0003520a0)                                       
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/hive.go:184 +0x147                         
	 [08:10:17] github.com/cilium/cilium/pkg/hive/job.TestOneShot_RetryRecoverNoShutdown(0xc0003361a0)            
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:341 +0x196                 
	 [08:10:17] testing.tRunner(0xc0003361a0, 0x8ba1c0)                                                           
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1576 +0x10b                                                  
	 [08:10:17] created by testing.(*T).Run                                                                       
	 [08:10:17] 	/usr/local/go/src/testing/testing.go:1629 +0x3ea                                                  
	 [08:10:17]                                                                                                   
	 [08:10:17] goroutine 27 [syscall]:                                                                           
	 [08:10:17] os/signal.signal_recv()                                                                           
	 [08:10:17] 	/usr/local/go/src/runtime/sigqueue.go:152 +0x2f                                                   
	 [08:10:17] os/signal.loop()                                                                                  
	 [08:10:17] 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19                                               
	 [08:10:17] created by os/signal.Notify.func1.1                                                               
	 [08:10:17] 	/usr/local/go/src/os/signal/signal.go:151 +0x2a                                                   
	 [08:10:17]                                                                                                   
	 [08:10:17] goroutine 68 [chan receive (nil chan)]:                                                           
	 [08:10:17] github.com/cilium/cilium/pkg/hive/job.TestOneShot_RetryRecoverNoShutdown.func2()                  
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:335 +0x45                  
	 [08:10:17] created by github.com/cilium/cilium/pkg/hive/job.TestOneShot_RetryRecoverNoShutdown               
	 [08:10:17] 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/hive/job/job_test.go:334 +0x18c                 
	 [08:10:17] FAIL	github.com/cilium/cilium/pkg/hive/job	600.106s    
```

**Comment by joestringer** [comment]
cc @dylandreimerink

**Comment by joestringer** [comment]
Possibly related to https://github.com/cilium/cilium/issues/25177 / https://github.com/cilium/cilium/pull/25211

**Comment by dylandreimerink** [comment]
PR https://github.com/cilium/cilium/pull/25293 should fix this. Seems like I picked up a bad habbit regarding channels which causes a deadlock in a fraction of cases, never knew.
