### ISSUE TITLE
Cilium-operator status Crashloopbackoff

### ISSUE THREAD

**Issue by quynhlab** [cilium/cilium#25280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium-operator status Crashloopbackoff

### Cilium Version

v1.13.1

### Kernel Version

5.15.0-67-generic

### Kubernetes Version

v1.27.1+rke2r1

### Relevant log output

```shell
level=info msg="Connected to apiserver" subsys=k8s-client
2023-05-05T11:14:02.756133151+07:00 panic: runtime error: invalid memory address or nil pointer dereference
2023-05-05T11:14:02.756163892+07:00 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15fbe90]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
2023-05-05T11:14:02.756224553+07:00 	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00095a810, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc000024000, 0x15}, {0xc0007ce920, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
2023-05-05T11:14:02.756567839+07:00 	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xc0004834d0?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:310 +0x47c
2023-05-05T11:14:02.756650648+07:00 k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x1b?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:198 +0x5c
2023-05-05T11:14:02.756715598+07:00 k8s.io/client-go/discovery.ServerGroupsAndResources({0x2dceb28, 0xc000457470})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:392 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:356 +0x25
2023-05-05T11:14:02.756813931+07:00 k8s.io/client-go/discovery.withRetries(0x2, 0xc0006d7380)
2023-05-05T11:14:02.756848322+07:00 	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:621 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x2de4b80?)
2023-05-05T11:14:02.756916755+07:00 	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/discovery/discovery_client.go:355 +0x3a
github.com/cilium/cilium/pkg/k8s/version.Update({0x2de4b80, 0xc0007aea00}, 0x1)
2023-05-05T11:14:02.756981486+07:00 	/go/src/github.com/cilium/cilium/pkg/k8s/version/version.go:309 +0x82
github.com/cilium/cilium/pkg/k8s/client.(*compositeClientset).onStart(0xc0007aea00, {0x7faf01ee7788?, 0xc000146700})
	/go/src/github.com/cilium/cilium/pkg/k8s/client/cell.go:216 +0x15d
2023-05-05T11:14:02.757069236+07:00 github.com/cilium/cilium/pkg/hive.Hook.Start(...)
2023-05-05T11:14:02.757081076+07:00 	/go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:35
2023-05-05T11:14:02.757148206+07:00 github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start(0xc000a0f0b0, {0x2dbfa40?, 0xc000a0dc80?})
	/go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:104 +0x32e
2023-05-05T11:14:02.757253878+07:00 github.com/cilium/cilium/pkg/hive.(*Hive).Start(0xc000a1e780, {0x2dbfa40, 0xc000a0dc80})
	/go/src/github.com/cilium/cilium/pkg/hive/hive.go:239 +0xb5
2023-05-05T11:14:02.757294175+07:00 github.com/cilium/cilium/pkg/hive.(*Hive).Run(0xc000a1e780)
	/go/src/github.com/cilium/cilium/pkg/hive/hive.go:167 +0x7c
2023-05-05T11:14:02.757396669+07:00 github.com/cilium/cilium/operator/cmd.init.4.func1(0x45058a0?, {0x29ba417?, 0x2?, 0x2?})
2023-05-05T11:14:02.757452935+07:00 	/go/src/github.com/cilium/cilium/operator/cmd/root.go:171 +0x71
github.com/spf13/cobra.(*Command).execute(0x45058a0, {0xc0000720a0, 0x2, 0x2})
2023-05-05T11:14:02.757543959+07:00 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:920 +0x847
2023-05-05T11:14:02.757558577+07:00 github.com/spf13/cobra.(*Command).ExecuteC(0x45058a0)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
2023-05-05T11:14:02.757588625+07:00 github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:968
2023-05-05T11:14:02.757629394+07:00 github.com/cilium/cilium/operator/cmd.Execute()
2023-05-05T11:14:02.757672578+07:00 	/go/src/github.com/cilium/cilium/operator/cmd/root.go:119 +0x25
main.main()
	/go/src/github.com/cilium/cilium/operator/main.go:13 +0x17
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report! It looks a bit like there's a race condition or unexpected input from the kube-apiserver that's triggering a failure case in the cilium-operator. Does this ever resolve itself after cilium-operator restart?

I've assigned this to sig/agent for followup.

**Comment by squeed** [comment]
In v1.13.2, we bumped the kubernetes client-go from 1.26.0 to 1.26.4; this includes several back-ported fixes to the discovery client ([1](https://github.com/kubernetes/kubernetes/pull/116145), [2](https://github.com/kubernetes/kubernetes/pull/115865)). Would you be able to try Cilium v1.13.2 in a cluster?
