### ISSUE TITLE
failed to update vtepInfo 

### ISSUE THREAD

**Issue by zongzw** [cilium/cilium#26287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I did upgrading cilium with the following vtep info, 
```
helm upgrade cilium ./cilium-main/install/kubernetes/cilium \
              --namespace kube-system \
	      --set debug.enabled=true \
	      --set kubeProxyReplacement=strict \
	      --set ipam.mode="kubernetes" \
	      --set k8sServiceHost=10.250.16.103 \
	      --set k8sServicePort=6443 \
	      --set l7Proxy=false \
              --set vtep.enabled="true" \
              --set vtep.endpoint="10.250.16.105" \
              --set vtep.cidr="10.0.20.1/24" \
              --set vtep.mac="fa:16:3e:8f:47:51" \
              --set vtep.mask="255.255.255.0"
```

The cilium-agent pod reports

```
level=debug msg="Executing stop hook" function="gops.registerGopsHooks.func2 (cell.go:51)" subsys=hive
level=info msg="Stopped gops server" address="127.0.0.1:9890" subsys=gops
level=info msg="Stop hook executed" duration="131.674µs" function="gops.registerGopsHooks.func2 (cell.go:51)" subsys=hive
level=fatal msg="failed to start: daemon creation failed: Unable to set up VTEP ipcache mappings: update map cilium_vtep_map: can't marshal value: *vtep.VtepEndpointInfo doesn't marshal to 16 bytes" subsys=daemon
level=debug msg="Controller func execution time: 141.075µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=4d80e198-c41f-457e-9a2b-1c5f5fa8254c
level=debug msg="Starting new controller" name=bpf-map-sync-cilium_vtep_map subsys=controller uuid=e91c8557-9f8f-4f2a-97d7-6f88438b8deb
level=debug msg="Starting periodic BPF map error resolver" file-path=/sys/fs/bpf/tc/globals/cilium_vtep_map name=cilium_vtep_map remaining=1 subsys=bpf
level=debug msg="BPF map error resolver completed" duration="218.306µs" file-path=/sys/fs/bpf/tc/globals/cilium_vtep_map name=cilium_vtep_map remaining=1 resolved=0 scanned=1 subsys=bpf
level=debug msg="Controller func execution time: 250.495µs" name=bpf-map-sync-cilium_vtep_map subsys=controller uuid=e91c8557-9f8f-4f2a-97d7-6f88438b8deb
level=debug msg="Controller run failed" consecutiveErrors=1 error="1 map sync errors" name=bpf-map-sync-cilium_vtep_map subsys=controller uuid=e91c8557-9f8f-4f2a-97d7-6f88438b8deb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1456387]

goroutine 1144 [running]:
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Observe(0x3b96750?, {0x3b96718?, 0xc000a2f6d0?}, 0x0?, 0x0?)
	<autogenerated>:1 +0x27
github.com/cilium/cilium/pkg/stream.First[...]({_, _}, {_, _})
	/go/src/github.com/cilium/cilium/pkg/stream/sinks.go:25 +0x1a3
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Get(...)
	/go/src/github.com/cilium/cilium/pkg/node/local_node_store.go:116
github.com/cilium/cilium/pkg/node.getLocalNode()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:49 +0xad
github.com/cilium/cilium/pkg/node.GetK8sExternalIPv4()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:316 +0x2a
github.com/cilium/cilium/pkg/datapath/linux.(*addressFamilyIPv4).LocalAddresses(0xc0026be398?)
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/node_addressing.go:96 +0x45
github.com/cilium/cilium/daemon/cmd.(*Daemon).syncHostIPs(0xc001c78600)
	/go/src/github.com/cilium/cilium/daemon/cmd/datapath.go:175 +0xc2
github.com/cilium/cilium/daemon/cmd.newDaemon.func6({0xc0026bf220?, 0xc0026bee88?})
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:1191 +0x26
github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc001dc4c60, {0xc001acc1f8, 0x0, 0x37e8480, 0xdf8475800, 0x0, 0x0, 0x0, {0x3b96718, 0xc000115360}})
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:201 +0x11d
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:97 +0xad2
```

In short, there were 2 abnormal messages:

`"failed to start: daemon creation failed: Unable to set up VTEP ipcache mappings: update map cilium_vtep_map: can't marshal value: *vtep.VtepEndpointInfo doesn't marshal to 16 bytes" subsys=daemon` and `panic: runtime error: invalid memory address or nil pointer dereference`.

By searching the code, the error messages seem to be related with:

```
// Function to update vtep map with VTEP CIDR
func UpdateVTEPMapping(newCIDR *cidr.CIDR, newTunnelEndpoint net.IP, vtepMAC mac.MAC) error {
	key := NewKey(newCIDR.IP)

	mac, err := vtepMAC.Uint64()
	if err != nil {
		return fmt.Errorf("invalid VTEP MAC: %w", err)
	}

	value := VtepEndpointInfo{
		VtepMAC: mac,
	}

	ip4 := newTunnelEndpoint.To4()
	copy(value.TunnelEndpoint[:], ip4)

	log.WithFields(logrus.Fields{
		logfields.V4Prefix: newCIDR.IP,
		logfields.MACAddr:  vtepMAC,
		logfields.Endpoint: newTunnelEndpoint,
	}).Debug("Updating vtep map entry")

	return VtepMap().Update(&key, &value)
}

```

The panic happens at `return VtepMap().Update(&key, &value)`, 

Not sure if there is something with the Map Creation? or my mis-configuration for cilium upgrading?

```
// NewMap instantiates a Map.
func NewMap(name string) *Map {
	return &Map{
		Map: *bpf.NewMap(
			name,
			ebpf.Hash,
			&Key{},
			&VtepEndpointInfo{},
			MaxEntries,
			0,
		).WithCache().WithPressureMetric().
			WithEvents(option.Config.GetEventBufferConfig(name)),
	}
}
```
 
This part of code was initiated by @vincentmli , updated by @ti-mo.  I need your help to conform my searching. Also hope this can help to locate this situation.

### Cilium Version

1.14.0-dev, 
I switched back to 1.12.10, it turns back to work.

### Kernel Version

Linux k8s-1-22-cilium 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report!

cc @joamaki may have an idea about the underlying cause for this issue.

**Comment by joamaki** [comment]
Looks like the "LocalNodeStore.Observe" crash is due to a controller left in the background trying to access it after it has been stopped (and the "localNode" global variable set back to nil), so the bug is that the "syncHostIPs" controller isn't stopped properly. I'll take a look at this today.

The real issue here seems to be with `vtep.VtepEndpointInfo doesn't marshal to 16 bytes"` which causes the start of the agent to be aborted. @ti-mo could this potentially be related to the recent BPF map changes, e.g. they're now surfacing a bug that existed?

**Comment by ti-mo** [comment]
Yep, addressing this today. It's due to the map changes. I'll add a check to the alignchecker that compares binary.Size() and reflect size of all types, there might be more we haven't caught.
