### ISSUE TITLE
POTENTIAL DEADLOCK: cilium agent will exit

### ISSUE THREAD

**Issue by sofat1989** [cilium/cilium#27205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
goroutine 201983306 wants to lock 0xc0322d83d0, but this lock 0xc0322d83d0 is held by goroutine 873300070. 
goroutine 873300070 is also waiting for the other lock 0xc00089bce0. But  goroutine 155665 locks 0xc00089bce0

According to the logs, the lock 0xc0322d83d0 seems that it is ctMap.natMapLock
```
unc doGC4(m *Map, filter *GCFilter) gcStats {
	ctMap := mapInfo[m.mapType]
	if ctMap.natMapLock != nil {
		ctMap.natMapLock.Lock()
		defer ctMap.natMapLock.Unlock()
	}
```

When removing the endpoints or errors happening in creating endpoint, it will call the func deleteEndpointQuiet and call ctmap.GC(m, filter). They will try to lock this at first. After locking this, it will tried to lock 0xc00089bce0.
Here both of these two locks are locked by the ctmap gc goroutine.

For the logs, usually we see that the deleting endpoint goroutine will wait for  this lock 0xc0322d83d0 for more than 30 seconds. In deleting func, it has a filter. So it will be faster than ctmap gc goroutine. The ctmap gc goroutine will go through the whole ctmap without any filters. **So maybe here there are not deadlocks, ithe ctmap gc goroutine indeed takes more than 5m to go the gc?**

Relative Logs：
```
2023-07-25T23:52:50.869901893-07:00 stderr F POTENTIAL DEADLOCK:
2023-07-25T23:52:50.869944215-07:00 stderr F Previous place where the lock was grabbed
2023-07-25T23:52:50.869947979-07:00 stderr F goroutine 873300070 lock 0xc0322d83d0
2023-07-25T23:52:50.870203989-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:117 go-deadlock.(*RWMutex).Lock ??? <<<<<
2023-07-25T23:52:50.870211399-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:51 lock.(*internalRWMutex).Lock ???
2023-07-25T23:52:50.87023879-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:14 endpoint.(*Endpoint).lockAlive ???
2023-07-25T23:52:50.870251653-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2141 endpoint.(*Endpoint).Delete ???
2023-07-25T23:52:50.870262062-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:379 endpointmanager.(*EndpointManager).removeEndpoint ???
...
2023-07-25T23:52:50.87027225-07:00 stderr F /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:723 cmd.(*Daemon).deleteEndpointQuiet ???
2023-07-25T23:52:50.870286142-07:00 stderr F /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:752 cmd.(*Daemon).DeleteEndpoint ???
*

2023-07-25T23:52:51.877244633-07:00 stderr F Here is what goroutine 873300070 doing now
2023-07-25T23:52:51.877284024-07:00 stderr F goroutine 873300070 [semacquire, 5 minutes]:
2023-07-25T23:52:51.877305805-07:00 stderr F sync.runtime_SemacquireMutex(0x7fb5f3d6afff?, 0x48?, 0x40ecaf?)
2023-07-25T23:52:51.877308316-07:00 stderr F    /usr/local/go/src/runtime/sema.go:77 +0x25
2023-07-25T23:52:51.877310732-07:00 stderr F sync.(*Mutex).lockSlow(0xc00089bce0)
2023-07-25T23:52:51.877313214-07:00 stderr F    /usr/local/go/src/sync/mutex.go:171 +0x271
2023-07-25T23:52:51.877316391-07:00 stderr F sync.(*Mutex).Lock(0xc00089bce0)
2023-07-25T23:52:51.877319023-07:00 stderr F    /usr/local/go/src/sync/mutex.go:90 +0x51
2023-07-25T23:52:51.877327151-07:00 stderr F github.com/sasha-s/go-deadlock.lock(0xc014985410, {0x42d9160, 0xc00089bce0})
2023-07-25T23:52:51.877330339-07:00 stderr F    /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:230 +0x1bb
2023-07-25T23:52:51.877333074-07:00 stderr F github.com/sasha-s/go-deadlock.(*Mutex).Lock(0xc00089bce0)
2023-07-25T23:52:51.87733548-07:00 stderr F     /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:85 +0x5b
2023-07-25T23:52:51.877338534-07:00 stderr F github.com/cilium/cilium/pkg/lock.(*internalMutex).Lock(0xc00089bce0)
2023-07-25T23:52:51.877340862-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:80 +0x25
2023-07-25T23:52:51.877343294-07:00 stderr F github.com/cilium/cilium/pkg/maps/ctmap.doGC4(0xc01b5f6a00, 0xc0405f5a70)
2023-07-25T23:52:51.877345628-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:429 +0xc5
2023-07-25T23:52:51.877351127-07:00 stderr F github.com/cilium/cilium/pkg/maps/ctmap.doGC(0xc01b5f6a00, 0xc014985a70)
2023-07-25T23:52:51.877353588-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:532 +0x13e
2023-07-25T23:52:51.877355912-07:00 stderr F github.com/cilium/cilium/pkg/maps/ctmap.GC(0xc01b5f6a00, 0xc014985a70)
2023-07-25T23:52:51.877358121-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:552 +0xbc
2023-07-25T23:52:51.877361465-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).garbageCollectConntrack(0xc0322d8380, 0xc0405f5a70)
2023-07-25T23:52:51.877363858-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1038 +0x3e5
2023-07-25T23:52:51.877366361-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).scrubIPsInConntrackTableLocked(0xc0322d8380)
2023-07-25T23:52:51.877369292-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1043 +0x185
2023-07-25T23:52:51.877371841-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).leaveLocked(0xc0322d8380, 0xc02c79dcc0, {0x1, 0x0})
2023-07-25T23:52:51.877374198-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1159 +0x95f
2023-07-25T23:52:51.877376528-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Delete(0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877386745-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2194 +0x15f9
2023-07-25T23:52:51.877389857-07:00 stderr F github.com/cilium/cilium/pkg/endpointmanager.(*EndpointManager).removeEndpoint(0xc00020d8c0, 0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877392145-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:380 +0x86
2023-07-25T23:52:51.87739442-07:00 stderr F github.com/cilium/cilium/pkg/endpointmanager.(*EndpointManager).RemoveEndpoint(0xc00020d8c0, 0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877396761-07:00 stderr F    /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:394 +0x55
2023-07-25T23:52:51.87739912-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpointQuiet(0xc000174300, 0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877401818-07:00 stderr F    /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:724 +0x65
2023-07-25T23:52:51.877404127-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpoint(0xc000174300, 0xc0322d8380)
...
2023-07-25T23:52:51.877410896-07:00 stderr F    /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:753 +0xa1b
2023-07-25T23:52:51.87741316-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*deleteEndpointID).Handle(0xc028696938, {0xc026c0b100, {0xc01c1334a4, 0x4d}})
*
```

```
2023-07-25T23:52:51.893855251-07:00 stderr F goroutine 155665 lock 0xc00089bce0
2023-07-25T23:52:51.893877763-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:85 go-deadlock.(*Mutex).Lock ??? <<<<<
2023-07-25T23:52:51.89388162-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:80 lock.(*internalMutex).Lock ???
2023-07-25T23:52:51.893885193-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:429 ctmap.doGC4 ???
2023-07-25T23:52:51.893891573-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:531 ctmap.doGC ???
2023-07-25T23:52:51.893894383-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:551 ctmap.GC ???
2023-07-25T23:52:51.893906375-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:195 gc.runGC ???
2023-07-25T23:52:51.893909423-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:96 gc.Enable.func1 ???
```

In this node, the pods are created and deleted frequently. So ctmap.GC will be called frequently. 

```
11305-2023-07-30T11:34:53.388377789-07:00 stderr F level=debug msg="Goroutine took lock for for more than 0.10 seconds" goroutine=" 741435572" seconds=0.568098249 subsys=lock-lib
11758-2023-07-30T11:35:10.481061981-07:00 stderr F level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 741435572" seconds=81.696626242 subsys=lock-lib
```

I tried to set the ConntrackLocal to enabled by the command `cilium config`, but it is failed.
```
evel=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=0s bpfWaitForELF=2.720967ms bpfWriteELF=3.573113ms containerID=190e51ff76 datapathPolicyRevision=1 desiredPolicyRevision=2 endpointID=971 error="failed to write ELF file: 971_next/bpf_lxc.o: no such string \"cilium_ct6_65535\" in ELF" identity=31432 ipv4=10.9.61.137 ipv6=10.9.61.137 
```
And the ConntrackLocal cannot be set by the flag, it is hardcoded .
```
option.Config.Opts.SetBool(option.ConntrackLocal, false)
```

Questsions:
1. Whether there is a deadlock in ctmap gc? Why ctmap gc take so much time?
```
# cilium bpf ct list global |wc -l
43994
```
2. Can we use the ConntrackLocal? and how to enable this? Does ConntrackLocal have some disadvantages?
3. 

### Cilium Version

1.13.1

### Kernel Version

5.15.0-26-generic

### Kubernetes Version

1.18

### Relevant log output
```
2023-07-25T23:52:50.869901893-07:00 stderr F POTENTIAL DEADLOCK:
2023-07-25T23:52:50.869944215-07:00 stderr F Previous place where the lock was grabbed
2023-07-25T23:52:50.869947979-07:00 stderr F goroutine 873300070 lock 0xc0322d83d0
2023-07-25T23:52:50.870203989-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:117 go-deadlock.(*RWMutex).Lock ??? <<<<<
2023-07-25T23:52:50.870211399-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:51 lock.(*internalRWMutex).Lock ???
2023-07-25T23:52:50.87023879-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:14 endpoint.(*Endpoint).lockAlive ???
2023-07-25T23:52:50.870251653-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2141 endpoint.(*Endpoint).Delete ???
2023-07-25T23:52:50.870262062-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:379 endpointmanager.(*EndpointManager).removeEndpoint ???
2023-07-25T23:52:50.870265115-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:393 endpointmanager.(*EndpointManager).RemoveEndpoint ???
2023-07-25T23:52:50.87027225-07:00 stderr F /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:723 cmd.(*Daemon).deleteEndpointQuiet ???
2023-07-25T23:52:50.870282257-07:00 stderr F /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:705 cmd.(*Daemon).deleteEndpoint ???
2023-07-25T23:52:50.870286142-07:00 stderr F /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:752 cmd.(*Daemon).DeleteEndpoint ???
2023-07-25T23:52:50.870295496-07:00 stderr F /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:809 cmd.(*deleteEndpointID).Handle ???
2023-07-25T23:52:50.870323553-07:00 stderr F /go/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/delete_endpoint_id.go:65 endpoint.(*DeleteEndpointID).ServeHTTP ???
2023-07-25T23:52:50.87032871-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 middleware.NewOperationExecutor.func1 ???
2023-07-25T23:52:50.870379125-07:00 stderr F /usr/local/go/src/net/http/server.go:2109 http.HandlerFunc.ServeHTTP ???
2023-07-25T23:52:50.870384463-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:78 middleware.NewRouter.func1 ???
2023-07-25T23:52:50.870386973-07:00 stderr F /usr/local/go/src/net/http/server.go:2109 http.HandlerFunc.ServeHTTP ???
2023-07-25T23:52:50.870389701-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 middleware.Redoc.func1 ???
2023-07-25T23:52:50.870436354-07:00 stderr F /usr/local/go/src/net/http/server.go:2109 http.HandlerFunc.ServeHTTP ???
2023-07-25T23:52:50.87045096-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 middleware.Spec.func1 ???
2023-07-25T23:52:50.870456296-07:00 stderr F /usr/local/go/src/net/http/server.go:2109 http.HandlerFunc.ServeHTTP ???
2023-07-25T23:52:50.870469608-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:64 metrics.(*APIEventTSHelper).ServeHTTP ???
2023-07-25T23:52:50.870479208-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 api.(*APIPanicHandler).ServeHTTP ???
2023-07-25T23:52:50.870483553-07:00 stderr F /usr/local/go/src/net/http/server.go:2947 http.serverHandler.ServeHTTP ???
2023-07-25T23:52:50.870492518-07:00 stderr F /usr/local/go/src/net/http/server.go:1991 http.(*conn).serve ???
2023-07-25T23:52:50.870496896-07:00 stderr F
2023-07-25T23:52:50.870514875-07:00 stderr F Have been trying to lock it again for more than 5m10s
2023-07-25T23:52:50.870522077-07:00 stderr F goroutine 201983306 lock 0xc0322d83d0
2023-07-25T23:52:50.870546934-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:138 go-deadlock.(*RWMutex).RLock ??? <<<<<
2023-07-25T23:52:50.870552582-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:67 lock.(*internalRWMutex).RLock ???
2023-07-25T23:52:50.870556058-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:53 endpoint.(*Endpoint).unconditionalRLock ???
2023-07-25T23:52:50.870595601-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/endpoint/identifiers.go:30 endpoint.(*Endpoint).GetK8sPodName ???
2023-07-25T23:52:50.870617353-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpointsynchronizer.go:403 watchers.deleteCEP ???
2023-07-25T23:52:50.870623114-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpointsynchronizer.go:310 watchers.(*EndpointSynchronizer).RunK8sCiliumEndpointSync.func2 ???
2023-07-25T23:52:50.870630979-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/controller/controller.go:305 controller.(*Controller).runController ???
2023-07-25T23:52:50.870634482-07:00 stderr F
2023-07-25T23:52:51.877244633-07:00 stderr F Here is what goroutine 873300070 doing now
2023-07-25T23:52:51.877284024-07:00 stderr F goroutine 873300070 [semacquire, 5 minutes]:
2023-07-25T23:52:51.877305805-07:00 stderr F sync.runtime_SemacquireMutex(0x7fb5f3d6afff?, 0x48?, 0x40ecaf?)
2023-07-25T23:52:51.877308316-07:00 stderr F 	/usr/local/go/src/runtime/sema.go:77 +0x25
2023-07-25T23:52:51.877310732-07:00 stderr F sync.(*Mutex).lockSlow(0xc00089bce0)
2023-07-25T23:52:51.877313214-07:00 stderr F 	/usr/local/go/src/sync/mutex.go:171 +0x271
2023-07-25T23:52:51.877316391-07:00 stderr F sync.(*Mutex).Lock(0xc00089bce0)
2023-07-25T23:52:51.877319023-07:00 stderr F 	/usr/local/go/src/sync/mutex.go:90 +0x51
2023-07-25T23:52:51.877327151-07:00 stderr F github.com/sasha-s/go-deadlock.lock(0xc014985410, {0x42d9160, 0xc00089bce0})
2023-07-25T23:52:51.877330339-07:00 stderr F 	/go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:230 +0x1bb
2023-07-25T23:52:51.877333074-07:00 stderr F github.com/sasha-s/go-deadlock.(*Mutex).Lock(0xc00089bce0)
2023-07-25T23:52:51.87733548-07:00 stderr F 	/go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:85 +0x5b
2023-07-25T23:52:51.877338534-07:00 stderr F github.com/cilium/cilium/pkg/lock.(*internalMutex).Lock(0xc00089bce0)
2023-07-25T23:52:51.877340862-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:80 +0x25
2023-07-25T23:52:51.877343294-07:00 stderr F github.com/cilium/cilium/pkg/maps/ctmap.doGC4(0xc01b5f6a00, 0xc0405f5a70)
2023-07-25T23:52:51.877345628-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:429 +0xc5
2023-07-25T23:52:51.877351127-07:00 stderr F github.com/cilium/cilium/pkg/maps/ctmap.doGC(0xc01b5f6a00, 0xc014985a70)
2023-07-25T23:52:51.877353588-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:532 +0x13e
2023-07-25T23:52:51.877355912-07:00 stderr F github.com/cilium/cilium/pkg/maps/ctmap.GC(0xc01b5f6a00, 0xc014985a70)
2023-07-25T23:52:51.877358121-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:552 +0xbc
2023-07-25T23:52:51.877361465-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).garbageCollectConntrack(0xc0322d8380, 0xc0405f5a70)
2023-07-25T23:52:51.877363858-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1038 +0x3e5
2023-07-25T23:52:51.877366361-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).scrubIPsInConntrackTableLocked(0xc0322d8380)
2023-07-25T23:52:51.877369292-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:1043 +0x185
2023-07-25T23:52:51.877371841-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).leaveLocked(0xc0322d8380, 0xc02c79dcc0, {0x1, 0x0})
2023-07-25T23:52:51.877374198-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1159 +0x95f
2023-07-25T23:52:51.877376528-07:00 stderr F github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Delete(0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877386745-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2194 +0x15f9
2023-07-25T23:52:51.877389857-07:00 stderr F github.com/cilium/cilium/pkg/endpointmanager.(*EndpointManager).removeEndpoint(0xc00020d8c0, 0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877392145-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:380 +0x86
2023-07-25T23:52:51.87739442-07:00 stderr F github.com/cilium/cilium/pkg/endpointmanager.(*EndpointManager).RemoveEndpoint(0xc00020d8c0, 0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877396761-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:394 +0x55
2023-07-25T23:52:51.87739912-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpointQuiet(0xc000174300, 0xc0322d8380, {0x1, 0x0})
2023-07-25T23:52:51.877401818-07:00 stderr F 	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:724 +0x65
2023-07-25T23:52:51.877404127-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpoint(0xc000174300, 0xc0322d8380)
2023-07-25T23:52:51.877406332-07:00 stderr F 	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:706 +0xdf
2023-07-25T23:52:51.877408604-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).DeleteEndpoint(0xc000174300, {0xc01c1334a4, 0x4d})
2023-07-25T23:52:51.877410896-07:00 stderr F 	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:753 +0xa1b
2023-07-25T23:52:51.87741316-07:00 stderr F github.com/cilium/cilium/daemon/cmd.(*deleteEndpointID).Handle(0xc028696938, {0xc026c0b100, {0xc01c1334a4, 0x4d}})
2023-07-25T23:52:51.877415496-07:00 stderr F 	/go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:810 +0x377
2023-07-25T23:52:51.877419248-07:00 stderr F github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*DeleteEndpointID).ServeHTTP(0xc028757bf0, {0x4c1e7c0, 0xc03d405140}, 0xc026c0b100)
2023-07-25T23:52:51.877422139-07:00 stderr F 	/go/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/delete_endpoint_id.go:66 +0x2cc
2023-07-25T23:52:51.877424525-07:00 stderr F github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x4c1e7c0, 0xc03d405140}, 0xc026c0b100)
2023-07-25T23:52:51.877426765-07:00 stderr F 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0xad
2023-07-25T23:52:51.877429024-07:00 stderr F net/http.HandlerFunc.ServeHTTP(0xc02884d620, {0x4c1e7c0, 0xc03d405140}, 0xc026c0b100)
2023-07-25T23:52:51.877431596-07:00 stderr F 	/usr/local/go/src/net/http/server.go:2109 +0x43
2023-07-25T23:52:51.877433836-07:00 stderr F github.com/go-openapi/runtime/middleware.NewRouter.func1({0x4c1e7c0, 0xc03d405140}, 0xc000bc4b00)
2023-07-25T23:52:51.877436163-07:00 stderr F 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:78 +0xd1
2023-07-25T23:52:51.877439064-07:00 stderr F net/http.HandlerFunc.ServeHTTP(0xc028dca380, {0x4c1e7c0, 0xc03d405140}, 0xc000bc4b00)
2023-07-25T23:52:51.877441356-07:00 stderr F 	/usr/local/go/src/net/http/server.go:2109 +0x43
2023-07-25T23:52:51.877443629-07:00 stderr F github.com/go-openapi/runtime/middleware.Redoc.func1({0x4c1e7c0, 0xc03d405140}, 0xc000bc4b00)
2023-07-25T23:52:51.877445861-07:00 stderr F 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x1a2
2023-07-25T23:52:51.877467641-07:00 stderr F net/http.HandlerFunc.ServeHTTP(0xc028db3780, {0x4c1e7c0, 0xc03d405140}, 0xc000bc4b00)
2023-07-25T23:52:51.877470548-07:00 stderr F 	/usr/local/go/src/net/http/server.go:2109 +0x43
2023-07-25T23:52:51.877472872-07:00 stderr F github.com/go-openapi/runtime/middleware.Spec.func1({0x4c1e7c0, 0xc03d405140}, 0xc000bc4b00)
2023-07-25T23:52:51.877475123-07:00 stderr F 	/go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x18c
2023-07-25T23:52:51.877477381-07:00 stderr F net/http.HandlerFunc.ServeHTTP(0xc028db37c0, {0x4c1e7c0, 0xc03d405140}, 0xc000bc4b00)
2023-07-25T23:52:51.877483458-07:00 stderr F 	/usr/local/go/src/net/http/server.go:2109 +0x43
2023-07-25T23:52:51.877486134-07:00 stderr F github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc028de1140, {0x4c2f680, 0xc028b73c00}, 0xc000bc4b00)
2023-07-25T23:52:51.877488365-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:64 +0x2d9
2023-07-25T23:52:51.877493748-07:00 stderr F github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0xc028d9baf0, {0x4c2f680, 0xc028b73c00}, 0xc000bc4b00)
2023-07-25T23:52:51.877496187-07:00 stderr F 	/go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 +0xe9
2023-07-25T23:52:51.877498488-07:00 stderr F net/http.serverHandler.ServeHTTP({0xc0264ec960}, {0x4c2f680, 0xc028b73c00}, 0xc000bc4b00)
2023-07-25T23:52:51.87750076-07:00 stderr F 	/usr/local/go/src/net/http/server.go:2947 +0x474
2023-07-25T23:52:51.877503039-07:00 stderr F net/http.(*conn).serve(0xc01d160460, {0x4c31258, 0xc037d3bd40})
2023-07-25T23:52:51.877505338-07:00 stderr F 	/usr/local/go/src/net/http/server.go:1991 +0x195c
2023-07-25T23:52:51.87750758-07:00 stderr F created by net/http.(*Server).Serve
2023-07-25T23:52:51.877509826-07:00 stderr F 	/usr/local/go/src/net/http/server.go:3102 +0x9e5


2023-07-25T23:52:51.884155517-07:00 stderr F goroutine 155665 lock 0x650e5a0
2023-07-25T23:52:51.884164685-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:85 go-deadlock.(*Mutex).Lock ??? <<<<<
2023-07-25T23:52:51.88416816-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:80 lock.(*internalMutex).Lock ???
2023-07-25T23:52:51.884216755-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:495 ctmap.doGC4 ???
2023-07-25T23:52:51.884219998-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:531 ctmap.doGC ???
2023-07-25T23:52:51.884222583-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:551 ctmap.GC ???

2023-07-25T23:52:51.893855251-07:00 stderr F goroutine 155665 lock 0xc00089bce0
2023-07-25T23:52:51.893877763-07:00 stderr F /go/src/github.com/cilium/cilium/vendor/github.com/sasha-s/go-deadlock/deadlock.go:85 go-deadlock.(*Mutex).Lock ??? <<<<<
2023-07-25T23:52:51.89388162-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:80 lock.(*internalMutex).Lock ???
2023-07-25T23:52:51.893885193-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:429 ctmap.doGC4 ???
2023-07-25T23:52:51.893891573-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:531 ctmap.doGC ???
2023-07-25T23:52:51.893894383-07:00 stderr F /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:551 ctmap.GC ???
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
> Whether there is a deadlock in ctmap gc? Why ctmap gc take so much time?

Did the lock ever get released? I would expect that the GC goroutine if it deadlocked, to never resolve, and you would see the CT map continue to grow without being cleaned up.

It's possible that the GC took 5m simply because of the lock contention in the case of extremely high churn, but 5m seems very, very high so I'm suspecting a deadlock.

> Can we use the ConntrackLocal? and how to enable this? Does ConntrackLocal have some disadvantages?

ConntrackLocal means to use per endpoint CT, rather than global CT map. As you may have noticed already, ConntrackLocal is not very well maintained. The current recommendation is to keep it disabled and use global CT.

**Comment by sofat1989** [comment]
@christarazi The cilium agent exited so that we don't know whether the lock is released at last.
