### ISSUE TITLE
id allocator panic: index out of range

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#2808]
i saw this panic with cilium/cilium:v0.13.1:

```
panic: runtime error: index out of range

goroutine 495 [running]:
math/rand.(*rngSource).Uint64(...)
        /usr/local/go/src/math/rand/rng.go:246
math/rand.(*rngSource).Int63(0xc420266000, 0x63fc8e442fb58d08)
        /usr/local/go/src/math/rand/rng.go:231 +0x8a
math/rand.(*Rand).Int63(0xc420440b70, 0x63fc8e442fb58d08)
        /usr/local/go/src/math/rand/rand.go:82 +0x33
math/rand.(*Rand).Int31(0xc420440b70, 0x63fc8e44)
        /usr/local/go/src/math/rand/rand.go:96 +0x2b
math/rand.(*Rand).Int31n(0xc420440b70, 0x43a6, 0xc400003c2b)
        /usr/local/go/src/math/rand/rand.go:131 +0x4f
math/rand.(*Rand).Intn(0xc420440b70, 0x43a6, 0x3c2b)
        /usr/local/go/src/math/rand/rand.go:145 +0x45
math/rand.(*Rand).Perm(0xc420440b70, 0xff00, 0xc420101718, 0xc4226a9918, 0xbb6ddd)
        /usr/local/go/src/math/rand/rand.go:198 +0xa2
github.com/cilium/cilium/pkg/kvstore/allocator.(*Allocator).selectAvailableID(0xc420101700, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:366 +0xaa
github.com/cilium/cilium/pkg/kvstore/allocator.(*Allocator).lockedAllocate(0xc420101700, 0x2c3df80, 0xc4226a08d0, 0x0, 0xc4226a0a20, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:434 +0x71e
github.com/cilium/cilium/pkg/kvstore/allocator.(*Allocator).Allocate(0xc420101700, 0x2c3df80, 0xc4226a08d0, 0x1, 0xc4214d3ee8, 0xc42236ecb0, 0xc42294a680)
        /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:533 +0x360
github.com/cilium/cilium/pkg/policy.AllocateIdentity(0xc4226a08d0, 0xc42236ee00, 0x1, 0x1, 0xc4214d3cb8)
        /go/src/github.com/cilium/cilium/pkg/policy/identity.go:331 +0x1bd
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).identityLabelsChanged(0xc421bec240, 0x2c4ade0, 0xc4202fb500, 0x1, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1752 +0x36b
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runLabelsResolver.func1(0xc421f807c0, 0x1)
        /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1720 +0x45
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc421fe2f00)
        /go/src/github.com/cilium/cilium/pkg/controller/controller.go:174 +0x87
created by github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController
        /go/src/github.com/cilium/cilium/pkg/controller/manager.go:81 +0x2c8
level=panic msg="Agent pipe closed, shutting down"
```

```
cilium version
Client: 1.0.0-rc4 3523143 2018-01-30T17:03:18+01:00 go version go1.9 linux/amd64
Daemon: 1.0.0-rc4 3523143 2018-01-30T17:03:18+01:00 go version go1.9 linux/amd64
```

**Comment by ianvernon** [comment]
The panic appears to be from the monitor?:

`pkg/monitor/monitor.go`:
```
// agentPipeReader reads agent events from the agentPipe and distributes to all listeners
func (m *Monitor) agentPipeReader(agentPipe io.Reader, stop chan struct{}) {
	meta, p := payload.Meta{}, payload.Payload{}

	for {
		select {
		default:
			err := payload.ReadMetaPayload(agentPipe, &meta, &p)
			if err == io.EOF || err == io.ErrUnexpectedEOF {
				log.Panic("Agent pipe closed, shutting down")
			} else if err != nil {
				log.WithError(err).Panic("Unable to read from agent pipe")
			}

			m.send(p)

		case <-stop:
			return
		}
	}
}
```

**Comment by aanm** [comment]
~the panic is because of the int cast of an unsigned int64~
```
	for _, r := range idRandomizer.Perm(int(a.max - a.min + 1)) {
		id := ID(r) + a.min
		tried++
		if _, ok := a.cache[id]; !ok && a.localKeys.lookupID(id) == "" {
			return id, id.String()
		}
	}
```

**Comment by aanm** [comment]
@tgraf `math/rand` is not safe for concurrent access we need to have a (write) lock for the `idRandomizer`

**Comment by tgraf** [comment]
> math/rand is not safe for concurrent access we need to have a (write) lock for the idRandomizer

Ah! Good catch!
