### ISSUE TITLE
goleak: Errors on successful test run: found unexpected goroutines: k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28541]
Hit in privileged tests on https://github.com/cilium/cilium/pull/27253 , https://github.com/cilium/cilium/actions/runs/6484779045/job/17610788489#step:16:418 .

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 77 in state select, with k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop on top of the stack:
goroutine 77 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0007d0420)
	/host/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:276 +0x305
created by k8s.io/client-go/util/workqueue.newDelayingQueue in goroutine 66
	/host/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:113 +0x21f
]
```

**Comment by joestringer** [comment]
I'm gonna close this as duplicate. Looks like this issue was recently introduced in v1.15 dev cycle though.
