### ISSUE TITLE
*make generate-k8s-api* broken on developer vagrant VMs

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#2959]
I was trying to set up a developer vagrant environment as per:
http://cilium.readthedocs.io/en/latest/contributing/#developer-requirements
However `make generate-k8s-api`  is failing
due to k8s generator bug which was recently fixed, but is not part of cilium dev vagrant image yet.

```vagrant@runtime1:~/go/src/github.com/cilium/cilium$ GOPATH=/home/vagrant/go make generate-k8s-api
can't load package: package github.com/cilium/cilium/common/tests: C source files not allowed when not using cgo or SWIG: bpf-event-test.c
cd "/home/vagrant/go/src/k8s.io/code-generator" && \
./generate-groups.sh all \
    github.com/cilium/cilium/pkg/k8s/client \
    github.com/cilium/cilium/pkg/k8s/apis \
    "cilium.io:v1,v2" \
    --go-header-file "/home/vagrant/go/src/github.com/cilium/cilium/hack/custom-boilerplate.go.txt"
Generating deepcopy funcs
F0227 21:35:39.808420   14270 main.go:74] Error: Failed executing generator: some packages had errors:
type "k8s.io/apimachinery/pkg/runtime.Object" in k8s:deepcopy-gen:interfaces tag of type k8s.io/apimachinery/pkg/runtime.Object is not an interface, but: ""
type "k8s.io/apimachinery/pkg/runtime.Object" in k8s:deepcopy-gen:interfaces tag of type k8s.io/apimachinery/pkg/runtime.Object is not an interface, but: ""
goroutine 1 [running]:
k8s.io/code-generator/vendor/github.com/golang/glog.stacks(0xc42279b200, 0xc422fc7000, 0x1a1, 0x1f7)
    /home/vagrant/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).output(0x8577a0, 0xc400000003, 0xc4236c5290, 0x8330e0, 0x7, 0x4a, 0x0)
    /home/vagrant/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:717 +0x322
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).printf(0x8577a0, 0x3, 0x6e2516, 0x9, 0xc4245bbf30, 0x1, 0x1)
    /home/vagrant/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/code-generator/vendor/github.com/golang/glog.Fatalf(0x6e2516, 0x9, 0xc4245bbf30, 0x1, 0x1)
    /home/vagrant/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
    /home/vagrant/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:74 +0x221
Makefile:162: recipe for target 'generate-k8s-api' failed```


As a work-around I tried: go get k8s.io/apimachinery && cd /home/vagrant/go/src/k8s.io/apimachinery && git checkout kubernetes-1.9.2

**Comment by manalibhutiyani** [comment]
Tried again today

```
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ export GOPATH=/home/vagrant/go
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ go get -u k8s.io/code-generator
package k8s.io/code-generator: no Go files in /home/vagrant/go/src/k8s.io/code-generator
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ make generate-k8s-api
can't load package: package github.com/cilium/cilium/test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c unit-test.c
cd "/home/vagrant/go/src/k8s.io/code-generator" && \
./generate-groups.sh all \
    github.com/cilium/cilium/pkg/k8s/client \
    github.com/cilium/cilium/pkg/k8s/apis \
    "cilium.io:v2" \
    --go-header-file "/home/vagrant/go/src/github.com/cilium/cilium/hack/custom-boilerplate.go.txt"
Generating deepcopy funcs
F0409 19:40:50.135209   12416 main.go:81] Error: Failed executing generator: some packages had errors:
type "k8s.io/apimachinery/pkg/runtime.Object" in k8s:deepcopy-gen:interfaces tag of type k8s.io/apimachinery/pkg/runtime.Object is not an interface, but: ""
Makefile:163: recipe for target 'generate-k8s-api' failed
make: *** [generate-k8s-api] Error 255
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ 
```
For external developers, this might be dissuading to manually pull all dependencies IMHO

Spoke offline to @aanm 
`We decided that its better if we switch to dep for the dependencies`

**Comment by ianvernon** [comment]
We should just package anything that is not explicitly a runtime dependency into a Docker container   that builds stuff, like we do with the docs.
