### ISSUE TITLE
fatal error: internal error - misuse of itab

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#29759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

````
root@karmada-01-b:~# kubectl logs -n kube-system cilium-znckr config 
fatal error: internal error - misuse of itab

goroutine 1 [running]:
runtime.throw({0x27de9b4?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000a07b0 sp=0xc0000a0780 pc=0x43901d
runtime.getitab(0x23c81c0?, 0x226e320?, 0x1?)
        /usr/local/go/src/runtime/iface.go:36 +0x2c6 fp=0xc0000a07f8 sp=0xc0000a07b0 pc=0x40a906
runtime.assertE2I2(0x4387c8?, {0x226e320?, 0x2b45bd0?})
        /usr/local/go/src/runtime/iface.go:461 +0x34 fp=0xc0000a0828 sp=0xc0000a07f8 pc=0x40b854
runtime.preprintpanics(0xc000098050?)
        /usr/local/go/src/runtime/panic.go:582 +0xd1 fp=0xc0000a0888 sp=0xc0000a0828 pc=0x437ed1
panic({0x226e320, 0x2b45bd0})
        /usr/local/go/src/runtime/panic.go:985 +0x3ac fp=0xc0000a0948 sp=0xc0000a0888 pc=0x438bcc
internal/reflectlite.(*rtype).Elem(0x0?)
        /usr/local/go/src/internal/reflectlite/type.go:620 +0x112 fp=0xc0000a0968 sp=0xc0000a0948 pc=0x46f612
errors.init()
        /usr/local/go/src/errors/wrap.go:104 +0x49 fp=0xc0000a0990 sp=0xc0000a0968 pc=0x472389
runtime.doInit(0x3fb6240)
        /usr/local/go/src/runtime/proc.go:6329 +0x126 fp=0xc0000a0ac0 sp=0xc0000a0990 pc=0x448be6
runtime.doInit(0x3fc1f40)
        /usr/local/go/src/runtime/proc.go:6306 +0x71 fp=0xc0000a0bf0 sp=0xc0000a0ac0 pc=0x448b31
runtime.doInit(0x3fce6c0)
        /usr/local/go/src/runtime/proc.go:6306 +0x71 fp=0xc0000a0d20 sp=0xc0000a0bf0 pc=0x448b31
runtime.doInit(0x40063e0)
        /usr/local/go/src/runtime/proc.go:6306 +0x71 fp=0xc0000a0e50 sp=0xc0000a0d20 pc=0x448b31
runtime.doInit(0x3fb5660)
        /usr/local/go/src/runtime/proc.go:6306 +0x71 fp=0xc0000a0f80 sp=0xc0000a0e50 pc=0x448b31
runtime.main()
        /usr/local/go/src/runtime/proc.go:233 +0x1d3 fp=0xc0000a0fe0 sp=0xc0000a0f80 pc=0x43b8f3
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000a0fe8 sp=0xc0000a0fe0 pc=0x469f01

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000074fb0 sp=0xc000074f90 pc=0x43bcf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc000074fe0 sp=0xc000074fb0 pc=0x43bb8d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x469f01
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000075790 sp=0xc000075770 pc=0x43bcf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000757c8 sp=0xc000075790 pc=0x42704e
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000757e0 sp=0xc0000757c8 pc=0x41bd06
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000757e8 sp=0xc0000757e0 pc=0x469f01
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0x2b42480?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000075f70 sp=0xc000075f50 pc=0x43bcf6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x421bc00)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000075fa0 sp=0xc000075f70 pc=0x4250f3
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000075fc8 sp=0xc000075fa0 pc=0x4256c5
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000075fe0 sp=0xc000075fc8 pc=0x41bca6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x469f01
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa
```

### Cilium Version

root@karmada-01-b:~# cilium version
cilium-cli: v0.13.0 compiled with go1.20 on linux/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.14.4
cilium image (running): v1.13.0

### Kernel Version

root@karmada-01-b:~# uname -r
6.2.0-37-generic

### Kubernetes Version

1.28.1

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Oof. This looks like an internal Go runtime bug. Or memory corruption. If you look at the stack dump, it doesn't contain any Cilium code.

Is it possible to reproduce?

If this happens again, please update the issue. Right now, there's not enough to go on.
