### ISSUE TITLE
Race condition in prometheus metrics: `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by buroa** [cilium/cilium#30102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I get a crashing pod with the following error:

```
 fatal error: concurrent map writes
 fatal error: concurrent map writes

 goroutine 2470 [running]:
 github.com/cilium/cilium/pkg/maps/metricsmap.promMetrics[...].upsert(0x3ecf190?, {{0x3920462, 0x7}, {0x396254b, 0x17}}, 0xc0011ae4c8)
     /go/src/github.com/cilium/cilium/pkg/maps/metricsmap/metricsmap.go:222 +0x117
 github.com/cilium/cilium/pkg/maps/metricsmap.(*metricsmapCollector).Collect.func1(0xc00704b350, 0x0?)
     /go/src/github.com/cilium/cilium/pkg/maps/metricsmap/metricsmap.go:235 +0xd5
 github.com/cilium/cilium/pkg/maps/metricsmap.metricsMap.IterateWithCallback.func1({0x3303760?, 0xc00704b350?}, {0x32417e0?, 0xc0011ae4c8?})
     /go/src/github.com/cilium/cilium/pkg/maps/metricsmap/metricsmap.go:105 +0x49
 github.com/cilium/cilium/pkg/ebpf.(*Map).IterateWithCallback(0x6046380, {0x3303760, 0xc00704b350}, {0x32417e0, 0xc0011ae4c8}, 0xc005a08c50)
     /go/src/github.com/cilium/cilium/pkg/ebpf/map.go:190 +0x191
 github.com/cilium/cilium/pkg/maps/metricsmap.metricsMap.IterateWithCallback({0xc00008f400?}, 0xc005a08d10)
     /go/src/github.com/cilium/cilium/pkg/maps/metricsmap/metricsmap.go:102 +0x85
 github.com/cilium/cilium/pkg/maps/metricsmap.(*metricsmapCollector).Collect(0xc0006c84e0, 0xc005a08f60?)
     /go/src/github.com/cilium/cilium/pkg/maps/metricsmap/metricsmap.go:229 +0x65
 github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
     /go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x102
 created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 1929
     /go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/registry.go:547 +0xbab
```

Looks like this is the commit that introduced it: https://github.com/cilium/cilium/commit/f8e94721fcebe4f9e0d45d4d914949ffb7467ad1

### Cilium Version

Cilium `1.15.0-rc.0`

### Kernel Version

Linux `6.1.69`

### Kubernetes Version

K8s `v1.29.0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by buroa** [comment]
Related: https://github.com/cilium/cilium/issues/20651, https://github.com/cilium/cilium/issues/12460
