### ISSUE TITLE
connection refused on healthz endpoint

### ISSUE THREAD

**Issue by cjvirtucio87** [cilium/cilium#30341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`cilium` pod's startup probe is failing with the following error:

```
Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused
```

I tried calling the URL through port-forward and I get `Empty reply from server` with only the following showing up in the pod's logs:

```
level=debug msg="Controller func execution time: 2.197122ms" name=k8s-heartbeat subsys=controller uuid=e3621c34-b064-474b-b150-c597cf7d256f
level=debug msg="Performing regular background work" subsys=nodemanager syncInterval=1m0s
level=debug msg="Controller func execution time: 5.769µs" name=dns-garbage-collector-job subsys=controller uuid=0bcd6aa2-6fa1-469a-8018-924cd47c6533
level=debug msg="Controller func execution time: 93.14µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=47b437a3-b7ac-4761-80ac-258fd0f172a0
level=debug msg="Controller func execution time: 82.592µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=47b437a3-b7ac-4761-80ac-258fd0f172a0
```

### Cilium Version

```
cilium-cli: v0.15.20 compiled with go1.21.6 on linux/amd64
cilium image (default): v1.14.5
cilium image (stable): v1.14.5
cilium image (running): 1.14.5
```

### Kernel Version

```
Linux cluster-control.home.cjvirtuc.io 5.14.0-362.13.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 14:07:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.2+k3s1
```

### Sysdump

[cilium-sysdump-20240120-161227.zip](https://github.com/cilium/cilium/files/13999253/cilium-sysdump-20240120-161227.zip)

### Relevant log output

`daemonsets/cilium` logs:

```
level=debug msg="Controller func execution time: 89.548┬╡s" name=metricsmap-bpf-prom-sync subsys=controller uuid=f3cf2052-abda-4c63-a474-74f08248bbf5
level=debug msg="Controller func execution time: 95.299┬╡s" name=metricsmap-bpf-prom-sync subsys=controller uuid=f3cf2052-abda-4c63-a474-74f08248bbf5
level=debug msg="Controller func execution time: 2.353214ms" name=k8s-heartbeat subsys=controller uuid=454ee676-e6b5-407f-8c27-691943d6e043
level=debug msg="Controller func execution time: 85.79┬╡s" name=metricsmap-bpf-prom-sync subsys=controller uuid=f3cf2052-abda-4c63-a474-74f08248bbf5
level=debug msg="Controller func execution time: 154.472┬╡s" name=metricsmap-bpf-prom-sync subsys=controller uuid=f3cf2052-abda-4c63-a474-74f08248bbf5
```

`deployments/cilium-operator` logs:

```
level=info msg="Cilium pod running for node; marking accordingly" nodeName=cluster-control.home.cjvirtuc.io subsys=watchers
level=info msg="Restarting unmanaged pod, started 255h25m37.837693957s ago" k8sPodName=kube-system/coredns-77ccd57875-qm5bx subsys=cilium-operator-generic
level=info msg="Cilium pod scheduled but not running for node; setting taint" nodeName=cluster-control.home.cjvirtuc.io subsys=watchers
level=info msg="Marking identity for later deletion" identity=21484 k8sUID=59f34546-8449-4e8e-be57-e33b68b14510 subsys=identity-heartbeat
level=info msg="Marking identity for later deletion" identity=48353 k8sUID=56ca24c1-bf14-44ef-9f24-30064eba6638 subsys=identity-heartbeat
```

### Anything else?

This is being deployed on a single node k3s cluster. I believe that is why only one `cilium-operator` pod is ready:

```
$ kubectl --namespace cilium get pods
NAME                               READY   STATUS    RESTARTS         AGE
cilium-operator-775cdf757-hplzg    1/1     Running   5 (7h55m ago)    13d
hubble-ui-5dfbdddc49-7rdw4         2/2     Running   10 (7h55m ago)   13d
hubble-relay-b47b6dff7-lddk8       0/1     Pending   0                24m
cilium-operator-667c9dfd8f-p2t8h   0/1     Pending   0                23m
cilium-operator-667c9dfd8f-f85b7   0/1     Pending   0                23m
cilium-2h6g4                       0/1     Running   6 (2m24s ago)    23m
```

```
$ kubectl --namespace cilium get pods --output json | jq -r '.items[] | select((.metadata.name | contains("cilium-operator")) and (.status.conditions[] | select(.reason == "Unschedulable") | length > 0) ) | .metadata.name'
cilium-operator-667c9dfd8f-p2t8h
cilium-operator-667c9dfd8f-f85b7
```

could that be related?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cjvirtucio87** [comment]
`cilium-health` output on the cilium pod:

```
# cilium-health status
Error: Cannot get status: Get "http://localhost/v1beta/status": dial unix /var/run/cilium/health.sock: connect: connection refused

# ls /var/run/cilium/health.sock
/var/run/cilium/health.sock
# cilium-health get
Error: Cannot get health for local instance: Get "http://localhost/v1beta/healthz": dial unix /var/run/cilium/health.sock: connect: connection refused

# cilium-health ping
Error: Cannot ping: Get "http://localhost/v1beta/healthz": dial unix /var/run/cilium/health.sock: connect: connection refused

#
```

**Comment by cjvirtucio87** [comment]
[this solution](https://github.com/cilium/cilium/issues/30177#issuecomment-1898918292) fixed it for me. I'm not sure how that file is related; would be nice have some clarification for posterity. I'll leave this open in case any of the maintainers wish to chime in.

**Comment by squeed** [comment]
Cilium is failing a health check because it is waiting for a CRD to be created:

```
goroutine 1 [select]:
github.com/cilium/cilium/pkg/k8s/synced.SyncCRDs({0x3fc1600, 0xc000198f50}, {0x3ffe320?, 0xc0000d5ef0}, {0xc0015f2000, 0xc, 0xefd360?}, 0x602aba0?, 0xc001cfe300)
	/go/src/github.com/cilium/cilium/pkg/k8s/synced/crd.go:178 +0x650
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).WaitForCRDsToRegister(0xc001cfe2c0, {0x3fc1600, 0xc000198f50})
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:411 +0x5a
github.com/cilium/cilium/daemon/cmd.newDaemon({0x3fc1600, 0xc000198f50}, 0xc000cfbf40, 0xc001117c20)
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:860 +0x339f
```

The question: which CRDs? I'm not sure yet!

**Comment by squeed** [comment]
Aha, we will log this, but the CRD registration timeout is longer than the startup probe. Can you please try setting the configuration field `crd-wait-timeout: 30s`? That should cause it to output the missing CRD.

**Comment by cjvirtucio87** [comment]
interesting. nothing stands out.

logs from all pods in the `cilium` namespace and grepping for `(crd|CRD)`:

[cilium_logs.txt](https://github.com/cilium/cilium/files/14074538/cilium_logs.txt)

though perhaps this is because I'm no longer able to replicate after the [fix](https://github.com/cilium/cilium/issues/30341#issuecomment-1902810919).

**Comment by tillpos-tony** [comment]
You need to restart the operator first and then restart the Cilium daemonset
