### ISSUE TITLE
Cilium failed to reconnect to one remote etcd cluster after etcd upgrade

### ISSUE THREAD

**Issue by rcanderson23** [cilium/cilium#30797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We upgraded all our cilium etcd clusters in our clustermesh. We observed one Cilium pod in one cluster get stuck at 4/5 clusters ready:
```
ClusterMesh:            4/5 clusters ready, 13292 global-services
   REDACT-01-use1: not-ready, 41 nodes, 3997 endpoints, 0 identities, 4187 services, 4 failures (last: 18m31s ago)
   └  quorum check failed 39 times in a row: 18m21.655367018s since last heartbeat update has been received
   └  remote configuration: expected=false, retrieved=false
   └  synchronization status: nodes=false, endpoints=false,
```
10m later:
```
ClusterMesh:            4/5 clusters ready, 13286 global-services
   REDACT-01-use1: not-ready, 41 nodes, 3997 endpoints, 0 identities, 4187 services, 4 failures (last: 28m28s ago)
   └  quorum check failed 60 times in a row: 28m9.506119043s since last heartbeat update has been received
   └  remote configuration: expected=false, retrieved=false
   └  synchronization status: nodes=false, endpoints=false, identities=false, services=false
```
Confirmed that the etcd cluster was healthy and that this was the only pod in all six clusters that exhibited this issue (~300 nodes total in the mesh) and haven't seen this on previous etcd upgrades.

We ended up deleting the pod in question to get a new cilium pod which connected to all etcd clusters without issue. 

### Cilium Version

1.14.6

### Kernel Version

Linux 5.15.148 #1 SMP Wed Feb 7 02:54:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.25.16-eks-77b1e4e

### Relevant log output

```shell
level=info msg="Remote kvstore watcher successfully synchronized and registered" clusterName=REDACT-01-use1 subsys=allocator
{"level":"warn","ts":"2024-02-15T17:02:24.622789Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007a8a80/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/ip/v1/default/ subsys=shared-store
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/nodes/v1/REDACT-01-use1/ subsys=shared-store
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=shared-store
level=info msg="Stopped remote kvstore watcher" clusterName=REDACT-01-use1 subsys=allocator
level=info msg="Stopped watch store manager" clusterName=REDACT-01-use1 subsys=shared-store
level=info msg="Creating etcd client" ConfigPath=/var/lib/cilium/clustermesh/REDACT-01-use1 KeepAliveHeartbeat=15s KeepAliveTimeout=25s ListLimit=256 MaxInflight=100 RateLimit=100 subsys=kvstore
{"level":"warn","ts":"2024-02-15T17:02:24.623134Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007a8a80/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
level=warning msg="Failed to revoke lock session while closing etcd client" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="context canceled" subsys=kvstore
level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" subsys=kvstore
level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" etcdEndpoint="https://REDACT-01-use1-etcd.mesh.prod-001.cloud.teleportinfra.sh:2379" subsys=kvstore version=3.5.11
level=info msg="Connection to remote cluster established" clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 kvstoreErr="<nil>" kvstoreStatus="Waiting for initial connection to be established" subsys=clustermesh
level=warning msg="Remote cluster doesn't have cluster configuration, falling back to the old behavior. This is expected when connecting to the old cluster running Cilium without cluster configuration feature." clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 kvstoreErr="<nil>" kvstoreStatus="Waiting for initial connection to be established" subsys=clustermesh
level=info msg="Starting watch store manager" clusterName=REDACT-01-use1 subsys=shared-store
level=info msg="Starting restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/ip/v1/default/ subsys=shared-store
level=info msg="Starting remote kvstore watcher" clusterName=REDACT-01-use1 subsys=allocator
level=info msg="Starting restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/nodes/v1/REDACT-01-use1/ subsys=shared-store
level=info msg="Starting restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=shared-store
{"level":"warn","ts":"2024-02-15T17:02:35.716098Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Internal desc = server closed the stream without sending trailers"}
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="rpc error: code = Internal desc = server closed the stream without sending trailers" prefix=cilium/state/ip/v1/default/ subsys=kvstore watcher=cilium/state/ip/v1/default/
{"level":"warn","ts":"2024-02-15T17:02:35.716445Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Internal desc = server closed the stream without sending trailers"}
{"level":"warn","ts":"2024-02-15T17:02:35.716529Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Internal desc = server closed the stream without sending trailers"}
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="rpc error: code = Internal desc = server closed the stream without sending trailers" prefix=cilium/state/identities/v1/id subsys=kvstore watcher=cilium/state/identities/v1/id
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="rpc error: code = Internal desc = server closed the stream without sending trailers" prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=kvstore watcher=cilium/state/services/v1/REDACT-01-use1/
{"level":"warn","ts":"2024-02-15T17:02:45.141203Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/nodes/v1/REDACT-01-use1/ subsys=shared-store
{"level":"warn","ts":"2024-02-15T17:02:45.141448Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
{"level":"warn","ts":"2024-02-15T17:02:45.141448Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="context canceled" prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=kvstore watcher=cilium/state/services/v1/REDACT-01-use1/
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=shared-store
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="context canceled" prefix=cilium/state/ip/v1/default/ subsys=kvstore watcher=cilium/state/ip/v1/default/
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/ip/v1/default/ subsys=shared-store
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this report @rcanderson23.

While the logs are useful, what we really need is a sysdump, which has a lot more logs that might help reproduce any issue. If the issue happens again, please consider collecting a sysdump using https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem

Thanks again.

**Comment by rcanderson23** [comment]
Hello @youngnick 

We experienced this issue again during an etcd upgrade across our clustermesh'd clusters. 3 cilium pods in two different clusters experienced it where they were connected to 4/5 clusters. I managed to use `cilium sysdump` on both clusters before restarting the pods. Looking through the files, there is information that we don't necessarily want to post on the net publicly. Is there specific files that would be useful so I can do a targeted redaction?

Thanks

**Comment by rcanderson23** [comment]
We have experienced this a few more times seemingly coinciding with some network disruptions on our VPC peering connections. I have taken a sysdump with the latest instance where connections to two etcd clusters were lost, it was able to successfully reconnect to one of them but failed to connect to the other.

**Comment by taraspos** [comment]
Can confirm that this is happening after upgrade to v1.15.8 as well

**Comment by rcanderson23** [comment]
Looking through the gops stack file in the sysdump, I found this:
```
goroutine 319 [semacquire, 40 minutes]:
sync.runtime_Semacquire(0xc55da4?)
	/usr/local/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc026a45020?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x48
github.com/cilium/cilium/pkg/clustermesh/common.(*remoteCluster).releaseOldConnection(0xc001eab320)
	/go/src/github.com/cilium/cilium/pkg/clustermesh/common/remote_cluster.go:117 +0x45
github.com/cilium/cilium/pkg/clustermesh/common.(*remoteCluster).restartRemoteConnection.func1({0x4023238, 0xc018c86820})
	/go/src/github.com/cilium/cilium/pkg/clustermesh/common/remote_cluster.go:141 +0x45
github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc0009f7a40, {{{0x3a4280e, 0x1a}}, {0x0, 0x0}, 0xc0013305b0, 0x1, 0xc0013305d0, 0x0, 0x0, ...})
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:254 +0x10f
created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 1
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:111 +0x458
```

This lines up with the issue and seems that it is getting stuck releasing the old connection blocking new connection.
[gops-cilium-nk6tz-cilium-agent-20240822-172256-stack.txt](https://github.com/user-attachments/files/16750376/gops-cilium-nk6tz-cilium-agent-20240822-172256-stack.txt)

**Comment by giorio94** [comment]
Thanks for the gops stack dump, that's useful. 

From an initial look, `releaseOldConnection` appears to be stuck while trying to release the identities watcher:

```
goroutine 149727 [semacquire, 40 minutes]:
sync.runtime_Semacquire(0x40a360?)
	/usr/local/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc040276900?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x48
github.com/cilium/cilium/pkg/allocator.(*cache).stop(0xc0250b4738)
	/go/src/github.com/cilium/cilium/pkg/allocator/cache.go:252 +0x36
github.com/cilium/cilium/pkg/allocator.(*Allocator).Delete(...)
	/go/src/github.com/cilium/cilium/pkg/allocator/allocator.go:413
github.com/cilium/cilium/pkg/allocator.(*RemoteCache).close(...)
	/go/src/github.com/cilium/cilium/pkg/allocator/allocator.go:1062
github.com/cilium/cilium/pkg/allocator.(*Allocator).WatchRemoteKVStore(0xc00d2ae000, {0x4023238, 0xc03fdb2640}, 0xc022268510, 0xc03fd6d700)
	/go/src/github.com/cilium/cilium/pkg/allocator/allocator.go:954 +0x533
github.com/cilium/cilium/pkg/allocator.(*RemoteCache).Watch(...)
	/go/src/github.com/cilium/cilium/pkg/allocator/allocator.go:1027
github.com/cilium/cilium/pkg/clustermesh.(*remoteCluster).Run.func5({0x4023238, 0xc03fdb2640})
	/go/src/github.com/cilium/cilium/pkg/clustermesh/remote_cluster.go:125 +0x7c
github.com/cilium/cilium/pkg/kvstore/store.(*wsmCommon).ready.func1()
	/go/src/github.com/cilium/cilium/pkg/kvstore/store/watchstoremgr.go:67 +0x93
created by github.com/cilium/cilium/pkg/kvstore/store.(*wsmCommon).ready in goroutine 149723
	/go/src/github.com/cilium/cilium/pkg/kvstore/store/watchstoremgr.go:65 +0x26c
```

In turn, the allocator is stuck [stopping the etcd watcher](https://github.com/giorio94/cilium/blob/88c3024189e2aede62b47966a7edb5c8071649f1/pkg/kvstore/allocator/allocator.go#L628):

```
goroutine 149704 [semacquire, 40 minutes]:
sync.runtime_Semacquire(0x2000107?)
	/usr/local/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc000472e70?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x48
github.com/cilium/cilium/pkg/kvstore.(*Watcher).Stop.func1()
	/go/src/github.com/cilium/cilium/pkg/kvstore/events.go:89 +0x15e
sync.(*Once).doSlow(0x0?, 0xc040735c40?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/cilium/cilium/pkg/kvstore.(*Watcher).Stop(0xc01fbb1dc8?)
	/go/src/github.com/cilium/cilium/pkg/kvstore/events.go:86 +0x3c
github.com/cilium/cilium/pkg/kvstore/allocator.(*kvstoreBackend).ListAndWatch(0xc040400b80, {0x4023120?, 0x67a7260?}, {0x40248d0, 0xc0250b4738}, 0xc040276900)
	/go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:628 +0x936
github.com/cilium/cilium/pkg/allocator.(*cache).start.func1()
	/go/src/github.com/cilium/cilium/pkg/allocator/cache.go:243 +0x48
created by github.com/cilium/cilium/pkg/allocator.(*cache).start in goroutine 149727
	/go/src/github.com/cilium/cilium/pkg/allocator/cache.go:242 +0x10f
```

Because the watcher is blocked trying to [push events (following an etcd relist) into the channel](https://github.com/giorio94/cilium/blob/88c3024189e2aede62b47966a7edb5c8071649f1/pkg/kvstore/etcd.go#L818-L822) that at that point the allocator is no longer reading from:

```
goroutine 149705 [chan send, 40 minutes]:
github.com/cilium/cilium/pkg/kvstore.(*etcdClient).Watch(0xc0181f39e0, {0x4023120, 0x67a7260}, 0xc040735c40)
	/go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:818 +0x990
created by github.com/cilium/cilium/pkg/kvstore.(*etcdClient).ListAndWatch in goroutine 149704
	/go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1681 +0x12e
```

The best fix to me looks modifying the `kvstoreBackend.ListAndWatch` function (and the corresponding interface) completely dropping the `stopChan` and just using the context as a signal of termination. That would also leave a single range loop over the events channel, ensuring that it is always correctly drained on shutdown. Most likely, it is also appropriate to make that events channel unbuffered, so that it is way easier to detect problems like this (which with the current configuration would occur once the channel buffer fills). I'll raise a PR for that.
