### ISSUE TITLE
CI: Runtime (Privledged): Test/ProxySuite/TestPortAllocator: panic: test timed out after 10m0s

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#31046]
## CI failure

Instance(s):
* https://github.com/cilium/cilium/actions/runs/8078628105/job/22071526995

```
level=info msg="Adding new proxy port rules for listener1:10927" id=listener1 subsys=proxy
coverage: 1.4% of statements
panic: test timed out after 10m0s
running tests:
	Test (10m0s)
	Test/ProxySuite (10m0s)
	Test/ProxySuite/TestPortAllocator (10m0s)

goroutine 35 [running]:
testing.(*M).startAlarm.func1()
	/root/sdk/go1.22.0/src/testing/testing.go:2366 +0x385
created by time.goFunc
	/root/sdk/go1.22.0/src/time/sleep.go:177 +0x2d

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0004ec340, {0x3089524?, 0x0?}, 0x32040a8)
	/root/sdk/go1.22.0/src/testing/testing.go:1750 +0x3ab
testing.runTests.func1(0xc0004ec340)
	/root/sdk/go1.22.0/src/testing/testing.go:2161 +0x37
testing.tRunner(0xc0004ec340, 0xc000033c60)
	/root/sdk/go1.22.0/src/testing/testing.go:1689 +0xfb
testing.runTests(0xc00084a960, {0x51a65c0, 0x2, 0x2}, {0x1?, 0x5288ce?, 0x51e9840?})
	/root/sdk/go1.22.0/src/testing/testing.go:2159 +0x445
testing.(*M).Run(0xc000a41220)
	/root/sdk/go1.22.0/src/testing/testing.go:2027 +0x68b
main.main()
	_testmain.go:83 +0x193

goroutine 20 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0004ec4e0, {0x277c294?, 0x0?}, 0xc0009bc7f0)
	/root/sdk/go1.22.0/src/testing/testing.go:1750 +0x3ab
github.com/cilium/checkmate.(*suiteRunner).run(0xc000a66100, 0xc0004ec4e0)
	/host/vendor/github.com/cilium/checkmate/check.go:473 +0x128
github.com/cilium/checkmate.Run(0xc0004ec4e0, {0x2b06740?, 0x5776000?}, 0x3f7a955?)
	/host/vendor/github.com/cilium/checkmate/run.go:100 +0x35
github.com/cilium/checkmate.RunAll(...)
	/host/vendor/github.com/cilium/checkmate/run.go:93
github.com/cilium/checkmate.TestingT(0xc0004ec4e0)
	/host/vendor/github.com/cilium/checkmate/run.go:86 +0xb4
github.com/cilium/cilium/pkg/proxy.Test(0xc0004ec4e0?)
	/host/pkg/proxy/proxy_test.go:21 +0x13
testing.tRunner(0xc0004ec4e0, 0x32040a8)
	/root/sdk/go1.22.0/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/root/sdk/go1.22.0/src/testing/testing.go:1742 +0x390

goroutine 21 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000a7a000, {0x277c2a0?, 0xc0000a1710?}, 0xc000a6c780)
	/root/sdk/go1.22.0/src/testing/testing.go:1750 +0x3ab
github.com/cilium/checkmate.(*suiteRunner).forkCall(...)
	/host/vendor/github.com/cilium/checkmate/check.go:515
github.com/cilium/checkmate.(*suiteRunner).forkTest(0xc000a66100, 0xc000a7a000, 0xc0004f25b0)
	/host/vendor/github.com/cilium/checkmate/check.go:536 +0x125
github.com/cilium/checkmate.(*suiteRunner).run.func1(0xc000a7a000)
	/host/vendor/github.com/cilium/checkmate/check.go:482 +0xed
testing.tRunner(0xc000a7a000, 0xc0009bc7f0)
	/root/sdk/go1.22.0/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 20
	/root/sdk/go1.22.0/src/testing/testing.go:1742 +0x390

goroutine 23 [chan receive (nil chan), 10 minutes]:
github.com/cilium/cilium/pkg/proxy.(*Proxy).ackProxyPort(0xc000a469c0, {0xc000a5d110?, 0x309544e?}, {0x309544e, 0x9}, 0xc000a5d230)
	/host/pkg/proxy/proxy.go:240 +0x22c
github.com/cilium/cilium/pkg/proxy.(*Proxy).AckProxyPort(0xc000a469c0, {0x3517f58, 0x5776000}, {0x309544e, 0x9})
	/host/pkg/proxy/proxy.go:218 +0x105
github.com/cilium/cilium/pkg/proxy.(*ProxySuite).TestPortAllocator(0x0?, 0xc000a861c0)
	/host/pkg/proxy/proxy_test.go:99 +0xed8
reflect.Value.call({0x2b06740?, 0x5776000?, 0x613?}, {0x30896b0, 0x4}, {0xc000a74ef0, 0x1, 0x1?})
	/root/sdk/go1.22.0/src/reflect/value.go:596 +0xce5
reflect.Value.Call({0x2b06740?, 0x5776000?, 0x7ff9098d55b8?}, {0xc0000a1ef0?, 0x51eb680?, 0xc000a861c0?})
	/root/sdk/go1.22.0/src/reflect/value.go:380 +0xb9
github.com/cilium/checkmate.(*suiteRunner).forkTest.func1(0xc000a861c0)
	/host/vendor/github.com/cilium/checkmate/check.go:554 +0x53b
github.com/cilium/checkmate.(*suiteRunner).forkTest.(*suiteRunner).forkCall.func2(0xc000a7a340?)
	/host/vendor/github.com/cilium/checkmate/check.go:517 +0x45
testing.tRunner(0xc000a7a340, 0xc000a6c780)
	/root/sdk/go1.22.0/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 21
	/root/sdk/go1.22.0/src/testing/testing.go:1742 +0x390
```

**Comment by tommyp1ckles** [comment]
[Closing](https://github.com/cilium/cilium/issues/31151#issuecomment-1979272046)
