### ISSUE TITLE
CI: Runtime Test (privileged): TestConflictResolution: panic: runtime error: invalid memory address or nil pointer dereference in LBIPAM

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#31075]
## CI failure

Hit on https://github.com/cilium/cilium/pull/29581 , which touches lbmap formatting routines but does not appear to be used by the test that fails below.

https://github.com/cilium/cilium/actions/runs/8099499661/job/22135490182#step:16:180

```
--- FAIL: TestConflictResolution (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f65e20]

goroutine 35 [running]:
testing.tRunner.func1.2({0x22377a0, 0x3eb0f90})
	/root/sdk/go1.22.0/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/root/sdk/go1.22.0/src/testing/testing.go:1634 +0x377
panic({0x22377a0?, 0x3eb0f90?})
	/root/sdk/go1.22.0/src/runtime/panic.go:770 +0x132
github.com/cilium/cilium/operator/pkg/lbipam.(*LBRange).EqualCIDR(0xc0007848c0?, {{0x29cfdf0?, 0x4495340?}, 0xc0000100a8?}, {{0x237f1c0?, 0x0?}, 0xc0000100a8?})
	/host/operator/pkg/lbipam/range_store.go:151 +0x60
github.com/cilium/cilium/operator/pkg/lbipam.(*LBIPAM).handlePoolModified(0xc0007848c0, {0x29cfdf0, 0x4495340}, 0xc0009eb380)
	/host/operator/pkg/lbipam/lbipam.go:1392 +0x10f3
github.com/cilium/cilium/operator/pkg/lbipam.(*LBIPAM).poolOnUpsert(0xc0007848c0, {0x29cfdf0, 0x4495340}, {{0x10?, 0x7fe325874a68?}, {0x10?, 0x3f0a9c0?}}, 0xc0009eb200?)
	/host/operator/pkg/lbipam/lbipam.go:279 +0xc8
github.com/cilium/cilium/operator/pkg/lbipam.(*LBIPAM).handlePoolEvent(0xc0007848c0, {0x29cfdf0?, 0x4495340?}, {{0x2627d4e, 0x6}, {{0xc0002faa58, 0x6}, {0x0, 0x0}}, 0xc0009eb200, ...})
	/host/operator/pkg/lbipam/lbipam.go:233 +0x1c7
github.com/cilium/cilium/operator/pkg/lbipam.(*newFixture).UpsertPool(0xc0009dde20, 0xc0006a89c0, 0xc0009eb200)
	/host/operator/pkg/lbipam/lbipam_fixture_test.go:177 +0x[195](https://github.com/cilium/cilium/actions/runs/8099499661/job/22135490182#step:16:197)
github.com/cilium/cilium/operator/pkg/lbipam.TestConflictResolution(0xc0006a89c0)
	/host/operator/pkg/lbipam/lbipam_test.go:56 +0x485
testing.tRunner(0xc0006a89c0, 0x277b800)
	/root/sdk/go1.22.0/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/root/sdk/go1.22.0/src/testing/testing.go:1742 +0x390
```

**Comment by joestringer** [comment]
Similar failure in that PR in `ci-integration` test:

https://github.com/cilium/cilium/actions/runs/8099499771/job/22135392161#step:8:159

```
INTEGRATION_TESTS=true CGO_ENABLED=0 go test  -mod=vendor -vet=all -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/datapath.datapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" ./... -timeout 600s  -json -covermode=count -coverprofile=coverage.out | tparse
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                           
┃   PANIC  package: github.com/cilium/cilium/operator/pkg/lbipam • TestConflictResolution   ┃                                                                                           
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                           
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                                     
	panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f65e20]                                                                                                                 
                                                                                                                                                                                        
goroutine 12 [running]:                                                                                                                                                                 
testing.tRunner.func1.2({0x22377a0, 0x3ecaf90})                                                                                                                                         
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:[163](https://github.com/cilium/cilium/actions/runs/8099499771/job/22135392161#step:8:164)1 +0x24a                                                                                                                   
testing.tRunner.func1()                                                                                                                                                                 
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1634 +0x377                                                                                                                   
panic({0x22377a0?, 0x3ecaf90?})                                                                                                                                                         
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132                                                                                                                      
github.com/cilium/cilium/operator/pkg/lbipam.(*LBRange).EqualCIDR(0xc00021d260?, {{0x29cfe10?, 0x44af340?}, 0xc0000100a8?}, {{0x237f1c0?, 0x0?}, 0xc0000100a8?})                        
	/home/runner/work/cilium/cilium/operator/pkg/lbipam/range_store.go:151 +0x60                                                                                                            
github.com/cilium/cilium/operator/pkg/lbipam.(*LBIPAM).handlePoolModified(0xc00021d260, {0x29cfe10, 0x44af340}, 0xc00091c900)                                                           
	/home/runner/work/cilium/cilium/operator/pkg/lbipam/lbipam.go:1392 +0x10f3                                                                                                              
github.com/cilium/cilium/operator/pkg/lbipam.(*LBIPAM).poolOnUpsert(0xc00021d260, {0x29cfe10, 0x44af340}, {{0x10?, 0x7ffb43523108?}, {0x10?, 0x3f249c0?}}, 0xc00091c180?)               
	/home/runner/work/cilium/cilium/operator/pkg/lbipam/lbipam.go:279 +0xc8                                                                                                                 
github.com/cilium/cilium/operator/pkg/lbipam.(*LBIPAM).handlePoolEvent(0xc00021d260, {0x29cfe10?, 0x44af340?}, {{0x2627d4e, 0x6}, {{0xc000379538, 0x6}, {0x0, 0x0}}, 0xc00091c180, ...})
	/home/runner/work/cilium/cilium/operator/pkg/lbipam/lbipam.go:233 +0x1c7                                                                                                                
github.com/cilium/cilium/operator/pkg/lbipam.(*newFixture).UpsertPool(0xc00090be20, 0xc0002a0b60, 0xc00091c180)                                                                         
	/home/runner/work/cilium/cilium/operator/pkg/lbipam/lbipam_fixture_test.go:177 +0x195                                                                                                   
github.com/cilium/cilium/operator/pkg/lbipam.TestConflictResolution(0xc0002a0b60)                                                                                                       
	/home/runner/work/cilium/cilium/operator/pkg/lbipam/lbipam_test.go:56 +0x485                                                                                                            
testing.tRunner(0xc0002a0b60, 0x277b800)                                                                                                                                                
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:[168](https://github.com/cilium/cilium/actions/runs/8099499771/job/22135392161#step:8:169)9 +0xfb                                                                                                                    
created by testing.(*T).Run in goroutine 1                                                                                                                                              
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:[174](https://github.com/cilium/cilium/actions/runs/8099499771/job/22135392161#step:8:175)2 +0x390                                                                                                                   
FAIL	github.com/cilium/cilium/operator/pkg/lbipam	0.047s
```

**Comment by joestringer** [comment]
Found a failure on the `main` branch as well, so this should not be related to the linked PR.

https://github.com/cilium/cilium/actions/runs/8099499771/job/22135392161

**Comment by joestringer** [comment]
cc @dylandreimerink

**Comment by tommyp1ckles** [comment]
@joestringer @dylandreimerink Was investigating this one a bit a couple days ago - looks like https://github.com/cilium/cilium/commit/344180046abdb8c0057864031d7091d57aa91467 was trying to address this.  I wasn't able to reproduce this following this patch.

**Comment by joestringer** [comment]
@tommyp1ckles hmm. These reports were this week, and if based on main, should include that commit.. for instance https://github.com/cilium/cilium/actions/runs/8099499771/attempts/1 uses https://github.com/cilium/cilium/commit/ce25c55e4baffd05337a27d07b7a729035e35595 which was committed yesterday, whereas https://github.com/cilium/cilium/commit/344180046abdb8c0057864031d7091d57aa91467 was committed last week. Seems like the problem still exists.

**Comment by tommyp1ckles** [comment]
@tklauser Assigning you for now since you may already have context here, do you have any cycles to take a look at this one.   Looking through ci-runtime tests this seems to happen somewhat often.

**Comment by tommyp1ckles** [comment]
Hmm actually, looking at this more, something fishy might be going on, taking at the failure on ce25c55 that one should indeed have the fix, but looking at the stack track we see that the call to EqualCIDR happens on line [1392](https://github.com/cilium/cilium/blob/ce25c55e4baffd05337a27d07b7a729035e35595/operator/pkg/lbipam/lbipam.go#L1392) ... notice that the oneliner for the fix patch (i.e. `existingRanges = slices.Clone(existingRanges)`) is above that, so we'd expect the new failure to be on 1393 .. not still on 1932.

Looking at the workflow, I'm not exactly sure what's going on with the checkout here:

```

Checking out the ref
  /usr/bin/git checkout --progress --force c64facda2117212e9868ebd501bab87bca9d02af
  Previous HEAD position was ce25c55e operator: Implement cache to be used for Cilium Identity management
  HEAD is now at c64facda     daemon: add BackendSlot to Service6Key.String and Service4Key.String
```

**Comment by tommyp1ckles** [comment]
It looks like that workflow ran https://github.com/cilium/cilium/pull/29581/commits/c64facda2117212e9868ebd501bab87bca9d02af 😕

**Comment by joestringer** [comment]
Ah, was I misinterpreting the GitHub actions workflow interface here? I filtered by branch to `main` with the assumption that the failures correspond to both the action workflow in main as well as the target code in main, but maybe the way I filtered the interface was only selecting _workflows_ used from main, even though the target code was actually from a PR.

**Comment by joestringer** [comment]
Perhaps if I filter by `push` events instead, it should pick up only workflows triggered by merging code into the maintained Cilium branches.

I'm going to close this out for now, tentatively expecting we've already resolved the underlying failure. If we observe this failure again then we can always reopen or file a fresh issue.

**Comment by tommyp1ckles** [comment]
@joestringer I was confused as well, when I see the `main`on the workflow summary I assume it's a scheduled workflow on main branch.  Perhaps there is some misunderstanding with this or with how we configure the workflows.
