### ISSUE TITLE
panic on maglev load balancing

### ISSUE THREAD

**Issue by FizikRoot** [cilium/cilium#31433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I did a simple test when the maglev balancing algorithm failed for 3 servers.
If we resize the table(m), the crash will no longer be reproduced.
```
func (s *MaglevTestSuite) TestBackendSimpleLookup(c *C) {
	m := uint64(16348) // DefaultTableSize = 16381

	backendsMap := map[string]*loadbalancer.Backend{
		"fb59a2c92cd08014": {Weight: 1, ID: 0},
		"fb59a5c92cd0852d": {Weight: 1, ID: 1},
		"two":              {Weight: 1, ID: 2},
	}
	GetLookupTable(backendsMap, m)
}
```
in result test panic
```
        --- FAIL: Test/MaglevTestSuite/TestBackendSimpleLookup (0.02s)
panic: runtime error: index out of range [49044] with length 49044 [recovered]
	panic: runtime error: index out of range [49044] with length 49044

goroutine 13 [running]:
testing.tRunner.func1.2({0xb0b9840, 0xc000044390})
	/usr/local/opt/go/libexec/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/opt/go/libexec/src/testing/testing.go:1634 +0x377
panic({0xb0b9840?, 0xc000044390?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:770 +0x132
github.com/cilium/cilium/pkg/maglev.GetLookupTable(0xc0000e5720, 0x3fdc)
	/Users/19592934/cilium/pkg/maglev/maglev.go:174 +0x6d7
github.com/cilium/cilium/pkg/maglev.(*MaglevTestSuite).TestBackendSimpleLookup(0x0?, 0x0?)
	/Users/19592934/cilium/pkg/maglev/maglev_test.go:93 +0x1cf
reflect.Value.call({0xb0896a0?, 0xb5bf260?, 0xc0000e5e20?}, {0xaebf106, 0x4}, {0xc0000e5ef0, 0x1, 0x1c2a4a8853f7e?})
	/usr/local/opt/go/libexec/src/reflect/value.go:596 +0xce5
reflect.Value.Call({0xb0896a0?, 0xb5bf260?, 0xb7a9108?}, {0xc0000e5ef0?, 0xb55f940?, 0xc0000e8540?})
	/usr/local/opt/go/libexec/src/reflect/value.go:380 +0xb9
github.com/cilium/checkmate.(*suiteRunner).forkTest.func1(0xc0000e8540)
	/Users/19592934/cilium/vendor/github.com/cilium/checkmate/check.go:554 +0x53b
github.com/cilium/checkmate.(*suiteRunner).forkTest.(*suiteRunner).forkCall.func2(0xc0000c0000?)
	/Users/19592934/cilium/vendor/github.com/cilium/checkmate/check.go:517 +0x45
testing.tRunner(0xc0000c0000, 0xc000408080)
	/usr/local/opt/go/libexec/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 7
	/usr/local/opt/go/libexec/src/testing/testing.go:1742 +0x390
```

### Cilium Version

1.15.2 hash commit e8bed8d8343731422dc65b706c3617a40d0a8058

### Kernel Version

 Darwin Kernel Version 22.6.0

### Kubernetes Version

-

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xyz-li** [comment]
The table length must be a prime number

**Comment by squeed** [comment]
Yup, this is documented (albeit in a far-away comment).
