### ISSUE TITLE
Cilium 1.14.8: panic at controller/manager.go:102 seen after node stop

### ISSUE THREAD

**Issue by BryanStenson-okta** [cilium/cilium#31579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

we're running a very stock cilium 1.14.8 in chain mode over aws-cni (https://docs.cilium.io/en/v1.14/installation/cni-chaining-aws-cni/).  i can provide helm chart overrides if that's helpful.

observed cilium 1.14.8 panic with this message:
```
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1556 [running]:
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Observe(0x3c5e720?, {0x3c5e7c8?, 0xc00ae0f130?}, 0x6e692220746e656d?, 0x746365762f617266?)
	<autogenerated>:1 +0x21
github.com/cilium/cilium/pkg/stream.First[...]({_, _}, {_, _})
	/go/src/github.com/cilium/cilium/pkg/stream/sinks.go:25 +0x191
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Get(...)
	/go/src/github.com/cilium/cilium/pkg/node/local_node_store.go:115
github.com/cilium/cilium/pkg/node.getLocalNode()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:48 +0xb4
github.com/cilium/cilium/pkg/node.GetIPv4()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:279 +0x25
github.com/cilium/cilium/pkg/node.GetCiliumEndpointNodeIP()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:287 +0x25
github.com/cilium/cilium/pkg/endpoint.getEndpointNetworking(0xc00ac0aba0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint_status.go:130 +0x91
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).GetCiliumEndpointStatus(0xc0006c1500, {0x3c13320, 0x5bfeb60})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint_status.go:355 +0x314
github.com/cilium/cilium/pkg/k8s/watchers.(*EndpointSynchronizer).RunK8sCiliumEndpointSync.func1({0x3c5e7c8, 0xc00066a370})
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpointsynchronizer.go:128 +0x3c6
github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc0009c0240, {0xc0002f1420, 0x0, 0xc00123e840, 0x2540be400, 0x0, 0x0, 0x0, {0x3c5e7c8, 0xc00066a370}})
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:201 +0x109
created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 1518
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:102 +0x59a

```

### Cilium Version

1.14.8

### Kernel Version

5.10.205-195.807.amzn2.x86_64 #1 SMP Tue Jan 16 18:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

(this is the AWS EKS Bottlerocket AMI - `amazon/bottlerocket-aws-k8s-1.25-x86_64-v1.19.0-2b1a7872`)

### Kubernetes Version

`Server Version: v1.25.16-eks-508b6b3`

### Sysdump

generated `cilium-sysdump-20240324-224239.zip` file is 51MB, and this form has a 25MB limit.  lmk how I can get this to devs if necessary.

additionally, the node has been replaced, and i do not have logs for the specific cilium agent which paniced.

i think the best i might be able to offer is sysdump output from an identical node (same cluster, same AMI, same AWS AZ, same cilium version, etc) -- but this won't have the same workloads running as the one which paniced.

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1556 [running]:
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Observe(0x3c5e720?, {0x3c5e7c8?, 0xc00ae0f130?}, 0x6e692220746e656d?, 0x746365762f617266?)
	<autogenerated>:1 +0x21
github.com/cilium/cilium/pkg/stream.First[...]({_, _}, {_, _})
	/go/src/github.com/cilium/cilium/pkg/stream/sinks.go:25 +0x191
github.com/cilium/cilium/pkg/node.(*LocalNodeStore).Get(...)
	/go/src/github.com/cilium/cilium/pkg/node/local_node_store.go:115
github.com/cilium/cilium/pkg/node.getLocalNode()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:48 +0xb4
github.com/cilium/cilium/pkg/node.GetIPv4()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:279 +0x25
github.com/cilium/cilium/pkg/node.GetCiliumEndpointNodeIP()
	/go/src/github.com/cilium/cilium/pkg/node/address.go:287 +0x25
github.com/cilium/cilium/pkg/endpoint.getEndpointNetworking(0xc00ac0aba0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint_status.go:130 +0x91
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).GetCiliumEndpointStatus(0xc0006c1500, {0x3c13320, 0x5bfeb60})
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint_status.go:355 +0x314
github.com/cilium/cilium/pkg/k8s/watchers.(*EndpointSynchronizer).RunK8sCiliumEndpointSync.func1({0x3c5e7c8, 0xc00066a370})
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpointsynchronizer.go:128 +0x3c6
github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc0009c0240, {0xc0002f1420, 0x0, 0xc00123e840, 0x2540be400, 0x0, 0x0, 0x0, {0x3c5e7c8, 0xc00066a370}})
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:201 +0x109
created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 1518
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:102 +0x59a
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BryanStenson-okta** [comment]
53 seconds earlier, the node this pod was running on was cordoned, by our cluster autoscaler, karpenter.

within the same second as the observed panic, karpenter reported this node was deleted.

**Comment by BryanStenson-okta** [comment]
this may be related to https://github.com/cilium/cilium/issues/19204, although the place of panic is different

**Comment by BryanStenson-okta** [comment]
about 50 milliseconds before panic, i see this in the logs (parsed from json):
```
parsed_msg:
     duration: 73591
     function: *resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Node].Stop
     level: info
     msg: Stop hook executed
     subsys: hive
```

**Comment by squeed** [comment]
Uh oh! Thanks for the clear report.

Just to confirm, this only seems to happen on nodes that are going away?

**Comment by BryanStenson-okta** [comment]
> Just to confirm, this only seems to happen on nodes that are going away?

correct, and this is very intermittent -- we've had 10s of nodes replaced, and have only seen this 1 time.
