### ISSUE TITLE
CI: Runtime Test (privileged): `panic: Fail in goroutine after Test/ServerSuite/TestRequestStaleNonce has completed`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#31855]
From: https://github.com/cilium/cilium/actions/runs/8566213622/job/23475661233
[logs_22453019086.zip](https://github.com/cilium/cilium/files/14917321/logs_22453019086.zip)
```
time="2024-04-05T07:14:03Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:04Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:04Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:04Z" level=warning msg="NACK received for versions after 1 and up to 2; waiting for a version update before sending again" subsys=xds xdsAckedVersion=1 xdsClientNode="node0~10.0.0.0~node0~bar" xdsDetail=FAILFAIL xdsNonce=2 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-05T07:14:05Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:05Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:05Z" level=warning msg="NACK received for versions after  and up to 1; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="node0~10.0.0.0~node0~bar" xdsDetail= xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-05T07:14:05Z" level=warning msg="NACK received for versions after  and up to 2; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="node0~10.0.0.0~node0~bar" xdsDetail= xdsNonce=2 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-05T07:14:05Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:05Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:07Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:07Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
panic: Fail in goroutine after Test/ServerSuite/TestRequestStaleNonce has completed

goroutine 15 [running]:
testing.(*common).Fail(0xc00032b860)
	/root/sdk/go1.22.2/src/testing/testing.go:952 +0xd4
github.com/cilium/checkmate.(*C).Fail(0xc000337880)
	/host/vendor/github.com/cilium/checkmate/helpers.go:29 +0x34
github.com/cilium/checkmate.(*C).internalCheck(0xc000337880, {0xc35f0d, 0x5}, {0xb11d00, 0x128dd00}, {0xd3cc80, 0x128d260}, {0x0, 0x0, 0x0})
	/host/vendor/github.com/cilium/checkmate/helpers.go:217 +0x9da
github.com/cilium/checkmate.(*C).Check(...)
	/host/vendor/github.com/cilium/checkmate/helpers.go:152
github.com/cilium/cilium/pkg/envoy/xds.(*ServerSuite).TestRequestStaleNonce.func1()
	/host/pkg/envoy/xds/server_e2e_test.go:681 +0xa8
created by github.com/cilium/cilium/pkg/envoy/xds.(*ServerSuite).TestRequestStaleNonce in goroutine 14
	/host/pkg/envoy/xds/server_e2e_test.go:678 +0x4f6
FAIL	github.com/cilium/cilium/pkg/envoy/xds	4.029s
```

**Comment by sayboras** [comment]
Thanks for your issue. I can re-produce the similar failure with below command, will check if I can find a way to deflake it

```
$ go test -count 1000 -run Test/ServerSuite/TestRequestStaleNonce ./pkg/envoy/xds/...
time="2024-04-09T21:33:44+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:45+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:45+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:45+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:45+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:46+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:46+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:46+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:46+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:47+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:47+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:47+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:47+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:48+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:48+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:48+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:48+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:49+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:49+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:49+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:49+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:50+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:50+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:50+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:50+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:51+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:51+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:51+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:51+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:52+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:52+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:52+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:52+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:53+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:53+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:53+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:53+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:54+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:54+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:54+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:54+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:55+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:55+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:55+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:55+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:56+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:56+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:56+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:56+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:57+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:57+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:57+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:57+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:58+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:58+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:58+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:58+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:59+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:59+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:33:59+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:33:59+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:34:00+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:34:00+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:34:00+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:34:00+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:34:01+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:34:01+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:34:01+10:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-09T21:34:01+10:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-09T21:34:02+10:00" level=error msg="received nil request from xDS stream; stopping xDS stream handling" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
--- FAIL: Test (0.50s)
    --- FAIL: Test/ServerSuite (0.50s)
        --- FAIL: Test/ServerSuite/TestRequestStaleNonce (0.50s)
            server_e2e_test.go:782: 
                ... response *discoveryv3.DiscoveryResponse = &discoveryv3.DiscoveryResponse{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), VersionInfo:"3", Resources:[]*anypb.Any{(*anypb.Any)(0xc00038e5f0), (*anypb.Any)(0xc00038e640)}, Canary:false, TypeUrl:"type.googleapis.com/envoy.config.v3.DummyConfiguration", Nonce:"3", ControlPlane:(*corev3.ControlPlane)(nil)} ("version_info:\"3\" resources:{[type.googleapis.com/envoy.config.route.v3.RouteConfiguration]:{name:\"resource1\"}} resources:{[type.googleapis.com/envoy.config.route.v3.RouteConfiguration]:{name:\"resource0\"}} type_url:\"type.googleapis.com/envoy.config.v3.DummyConfiguration\" nonce:\"3\"")
                ... VersionInfo string = "4"
                ... Resources []protoreflect.ProtoMessage = []protoreflect.ProtoMessage{(*routev3.RouteConfiguration)(0x129a2a0)}
                ... Canary bool = false
                ... TypeUrl string = "type.googleapis.com/envoy.config.v3.DummyConfiguration"
                
panic: Fail in goroutine after Test has completed

goroutine 109 [running]:
testing.(*common).Fail(0xc0002596c0)
        /usr/lib/go/src/testing/testing.go:952 +0xd4
testing.(*common).Fail(0xc000259860)
        /usr/lib/go/src/testing/testing.go:946 +0x3c
testing.(*common).Fail(0xc000259a00)
        /usr/lib/go/src/testing/testing.go:946 +0x3c
github.com/cilium/checkmate.(*C).Fail(0xc000422380)
        /home/tammach/go/src/github.com/cilium/cilium/vendor/github.com/cilium/checkmate/helpers.go:29 +0x34
github.com/cilium/checkmate.(*C).internalCheck(0xc000422380, {0xc2b106, 0x5}, {0xb07200, 0x1281060}, {0xd30880, 0x1280550}, {0x0, 0x0, 0x0})
        /home/tammach/go/src/github.com/cilium/cilium/vendor/github.com/cilium/checkmate/helpers.go:217 +0x9da
github.com/cilium/checkmate.(*C).Check(...)
        /home/tammach/go/src/github.com/cilium/cilium/vendor/github.com/cilium/checkmate/helpers.go:152
github.com/cilium/cilium/pkg/envoy/xds.(*ServerSuite).TestRequestStaleNonce.func1()
        /home/tammach/go/src/github.com/cilium/cilium/pkg/envoy/xds/server_e2e_test.go:681 +0xa8
created by github.com/cilium/cilium/pkg/envoy/xds.(*ServerSuite).TestRequestStaleNonce in goroutine 108
        /home/tammach/go/src/github.com/cilium/cilium/pkg/envoy/xds/server_e2e_test.go:678 +0x498
FAIL    github.com/cilium/cilium/pkg/envoy/xds  17.576s
FAIL
```

**Comment by pippolo84** [comment]
Another hit here: https://github.com/cilium/cilium/actions/runs/8692855844/job/23838508284

Full logs: [logs_22776725965.zip](https://github.com/cilium/cilium/files/14994265/logs_22776725965.zip)

**Comment by jrajahalme** [comment]
@sayboras Addressed this same issue in a more comprehensive manner in the 2nd commit of #32004, please have a look. I suggest we close this PR in favor of #32004.
