### ISSUE TITLE
Cilium agent crashes when an egress rule with no endpointselector is applied

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3266]
### Title

Cilium agent crashes when an egress rule with no endpointselector is applied

### General Information

- Cilium version (run `cilium version`): v0.13.16

### How to reproduce the issue

Apply the following egress policy rule:
```
specs:
- egress:
  - toPorts:
    - ports:
      - port: "53"
        protocol: UDP
```

You'll see a traceback in the cilium agent logs:
```
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=covalent-cilium-enforcement-monitoring k8sApiVersion=cilium.io/v2 k8sNamespace=monitoring
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xebba85]

goroutine 617 [running]:
github.com/cilium/cilium/pkg/policy/api.(*EndpointSelector).Matches(0xc4203142d0, 0x2dc9fa0, 0xc421c89040, 0xc421c89040)
	/go/src/github.com/cilium/cilium/pkg/policy/api/selector.go:189 +0x75
github.com/cilium/cilium/pkg/policy.(*rule).resolveL4Policy(0xc4203142d0, 0xc42361fab0, 0xc42361fa10, 0xc421c88000, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/policy/rule.go:243 +0x84
github.com/cilium/cilium/pkg/policy.(*Repository).ResolveL4Policy(0xc4212d1980, 0xc42361fab0, 0x19, 0xc420025300, 0x45aa40)
	/go/src/github.com/cilium/cilium/pkg/policy/repository.go:145 +0x271
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).resolveL4Policy(0xc4204b5680, 0x2dedc80, 0xc42136a000, 0xc4212d1980, 0xc4201b4c80, 0x449baa, 0x44c92f)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:303 +0xc4
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc4204b5680, 0x2dedc80, 0xc42136a000, 0xc42361fcc8, 0xc4234abf00, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:703 +0x2bf
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).TriggerPolicyUpdatesLocked(0xc4204b5680, 0x2dedc80, 0xc42136a000, 0x0, 0xc422c74160, 0x45d964b800, 0xc42122c5c0, 0x1e)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:959 +0x97
github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1(0x2dedc80, 0xc42136a000, 0xc4204b5680, 0xc421ee4570)
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:256 +0x74
created by github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:254 +0xb2
level=panic msg="Agent pipe closed, shutting down"
```

**Comment by ianvernon** [comment]
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cat cnp.yaml 
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "foobar"
specs:
- egress:
  - toPorts:
    - ports:
      - port: "53"
        protocol: UDP
```

Importing a CNP with this specification gives me the following:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl apply -f cnp.yaml
The CiliumNetworkPolicy "foobar" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"cilium.io/v2", "kind":"CiliumNetworkPolicy", "metadata":map[string]interface {}{"name":"foobar", "namespace":"default", "creationTimestamp":"2018-03-22T21:53:45Z", "uid":"7eb22522-2e1b-11e8-b566-080027f05204", "selfLink":"", "clusterName":"", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cilium.io/v2\",\"kind\":\"CiliumNetworkPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"foobar\",\"namespace\":\"default\"},\"specs\":[{\"egress\":[{\"toPorts\":[{\"ports\":[{\"port\":\"53\",\"protocol\":\"UDP\"}]}]}]}]}\n"}}, "specs":[]interface {}{map[string]interface {}{"egress":[]interface {}{map[string]interface {}{"toPorts":[]interface {}{map[string]interface {}{"ports":[]interface {}{map[string]interface {}{"port":"53", "protocol":"UDP"}}}}}}}}}: validation failure list:
specs.endpointSelector in body is required
```

I presume you are not running your cluster with CRD validation. What K8s version are you running?

**Comment by ashwinp** [comment]
@ianvernon 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10+coreos.0", GitCommit:"db06c5223888db5169a6126fb82f323fce1f1eeb", GitTreeState:"clean", BuildDate:"2017-11-07T14:06:30Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tgraf** [comment]
@ianvernon We should still reject it in rule `sanitize()`

**Comment by ianvernon** [comment]
@tgraf fix is coming shortly.

**Comment by ianvernon** [comment]
@eloycoto this does not need an E2E test - it is tested in our unit tests.
