### ISSUE TITLE
cilium-agent null pointer crash

### ISSUE THREAD

**Issue by Learntotolearn** [cilium/cilium#33036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After installing version 1.15.5 of cilium and running it for a period of time, cilium-agent will crash due to a null pointer.

### Cilium Version

1.15.5

### Kernel Version

Linux est-2 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
## cilium-health status
Probe time:   2024-06-11T03:17:39Z
Nodes:
  diylink-test-3 (localhost):
    Host connectivity to 10.255.100.3:
      ICMP to stack:   OK, RTT=672.779µs
      HTTP to agent:   OK, RTT=380.714µs
    Endpoint connectivity to 10.0.0.179:
      ICMP to stack:   OK, RTT=624.924µs
      HTTP to agent:   OK, RTT=521.886µs
  diylink-test-2:
    Host connectivity to 10.255.100.2:
      ICMP to stack:   OK, RTT=686.285µs
      HTTP to agent:   Get "http://10.255.100.2:4240/hello": dial tcp 10.255.100.2:4240: connect: connection refused
    Endpoint connectivity to 10.0.1.89:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.0.1.89:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  diylink-test-4:
    Host connectivity to 10.255.100.4:
      ICMP to stack:   OK, RTT=647.198µs
      HTTP to agent:   Get "http://10.255.100.4:4240/hello": dial tcp 10.255.100.4:4240: connect: connection refused
    Endpoint connectivity to 10.0.2.68:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.0.2.68:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

## cilium-agent  logs
time="2024-06-11T03:15:00Z" level=info msg="Identity of endpoint changed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2306 identity=4 identityLabels="reserved:health" ipv4=10.0.2.68 ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaf407a]

goroutine 2576 [running]:
github.com/vishvananda/netlink.parseActions({0xc003b6e900?, 0x6, 0x4d4?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:916 +0xda
github.com/vishvananda/netlink.(*Flower).decode(0xc003b5b7a0, {0xc003b65400?, 0x13, 0x0?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:216 +0x85
github.com/vishvananda/netlink.parseFlowerData(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:1047
github.com/vishvananda/netlink.(*Handle).FilterList(0x60b7880, {0x3f39890, 0xc001cd38c0}, 0xfffffff2)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:492 +0x874
github.com/vishvananda/netlink.FilterList(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:403
github.com/cilium/cilium/pkg/datapath/loader.removeObsoleteNetdevPrograms()
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:245 +0x199
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).reloadHostDatapath(0xc0017f3e40, {0x3f594a8, 0xc00039ad20}, {0x3f80b60, 0xc0046a6600}, {0xc002c53a28, 0x12})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:430 +0x1b05
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).reloadDatapath(0xc0046e22a8?, {0x3f594a8, 0xc00039ad20}, {0x3f80b60, 0xc0046a6600}, 0xc003ddc718)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:448 +0x185
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).ReloadDatapath(0xc0046e2268?, {0x3f594a8, 0xc00039ad20}, {0x3f80b60?, 0xc0046a6600?}, 0xc0046e21e8)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:643 +0x18e
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).CompileOrLoad(0xc0017f3e40, {0x3f594a8, 0xc00039ad20}, {0x3f80b60?, 0xc0046a6600?}, 0xc0046e21e8)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:631 +0x5f4
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).realizeBPFState(0xc00086c700, 0xc0046e2000)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:674 +0x406
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc00086c700, 0xc0046e2000)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:590 +0x40e
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc00086c700, 0xc0046e2000)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:486 +0x9bd
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0014534d0, 0x6069af0?)
	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x1de
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:244 +0x133
sync.(*Once).doSlow(0xc0029c6fd0?, 0x44619c?)
	/usr/local/go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0xc0026bc240?)
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:232 +0x3c
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run in goroutine 1
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:228 +0x69
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Looks like a dup of https://github.com/cilium/cilium/issues/33340. Please see the upstream bug for the netlink lib that's linked there.
