### ISSUE TITLE
Kafka CI test is unstable

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3307]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1612/testReport/(root)/runtime/RuntimeValidatedKafka_Kafka_Policy_Ingress/

```
/root/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:229
Expected
    <int>: 0
to equal
    <int>: 1
/root/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/kafka.go:133
```

Expectations without any description are very hard to debug, in particular the ones that are being used by a lot of tests.

Please investigate and if no immediate fix is possible, disable the test.

**Comment by manalibhutiyani** [comment]
Hi Eloy, how/where do we see the ginkgo docker logs for this crash. I believe you added them recently?

**Comment by manalibhutiyani** [comment]
Nevermind I found it! One weird thing I observed it that I actually do not see any Kafka broker node in the endpoint list logs of this test.

**Comment by manalibhutiyani** [comment]
Cilium log:s
The Kafka and zookeeper establish the initial connection(with the correct session timeout of 20 sec) and then I see the following cilium CT 
entry logs:
Note: The zookeeper address is: 10.15.167.158
and Kafka is 10.15.101.61

Filtering address `10.15.101.61` in cilium logs:
```
Mar 24 20:46:43 runtime cilium-agent[15240]: level=debug msg="updating resource in cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=100
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="deleting resource from cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=114
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="endpoint IP cache Delete" cached-identity=3882 endpoint-ip=10.15.101.61 identity=3882
Mar 24 21:04:07 runtime cilium-agent[6276]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.167.158 entryDstPort=0 entryFlags=2 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.101.61 entrySrcSecID=17014 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Mar 24 21:04:07 runtime cilium-agent[6276]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.167.158 entryDstPort=0 entryFlags=2 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.101.61 entrySrcSecID=17014 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Mar 24 21:04:07 runtime cilium-agent[6276]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.167.158 entryDstPort=0 entryFlags=3 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.101.61 entrySrcSecID=17014 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
```

The connection gets closed in between (not sure if its due to the CT entry log I see in the cilium logs) and then Kafka tries to connect to zookeeper again and times out as the "connection timeout is 6sec). Note that the session timeout of 20 sec is being respected as the initial session is already established and the connection is closed after that. 
It looks like the Kafka endpoint is *missing* an endpoint ID and endpoint IP. @tgraf @rlenglet when does this usually happen?

Zookeeper logs:
```
2018-03-24 21:03:49,942 [myid:] - INFO  [main:ZooKeeperServer@838] - minSessionTimeout set to -1
2018-03-24 21:03:49,942 [myid:] - INFO  [main:ZooKeeperServer@847] - maxSessionTimeout set to -1
2018-03-24 21:03:49,958 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2018-03-24 21:03:58,630 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.15.101.61:44676
2018-03-24 21:03:58,644 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@942] - Client attempting to establish new session at /10.15.101.61:44676
2018-03-24 21:03:58,646 [myid:] - INFO  [SyncThread:0:FileTxnLog@203] - Creating new log file: log.1
2018-03-24 21:03:59,030 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@687] - Established session 0x16259d31ad80000 with negotiated timeout 20000 for client /**10.15.101.61**:44676
2018-03-24 21:03:59,031 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x16259d31ad80000
2018-03-24 21:03:59,046 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x16259d31ad80000, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
	at java.lang.Thread.run(Thread.java:748)
2018-03-24 21:03:59,051 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /10.15.101.61:44676 which had sessionid 0x16259d31ad80000
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
```


And finally Kafka logs:
```
[2018-03-24 21:03:52,439] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2018-03-24 21:03:52,440] INFO Initiating client connection, connectString=10.15.167.158:2181 sessionTimeout=20000 watcher=org.I0Itec.zkclient.ZkClient@1534f01b (org.apache.zookeeper.ZooKeeper)
[2018-03-24 21:03:52,462] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-03-24 21:03:52,470] INFO Opening socket connection to server 10.15.167.158/10.15.167.158:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-03-24 21:03:57,514] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.SocketException: Connection reset by peer
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-03-24 21:03:58,463] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-03-24 21:03:58,628] INFO Opening socket connection to server 10.15.167.158/10.15.167.158:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-03-24 21:03:58,634] INFO Socket connection established to 10.15.167.158/10.15.167.158:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-03-24 21:03:59,029] INFO Session establishment complete on server 10.15.167.158/10.15.167.158:2181, sessionid = 0x16259d31ad80000, **negotiated timeout = 20000 (org.apache.zookeeper.ClientCnxn)**
[2018-03-24 21:03:59,040] INFO Session: 0x16259d31ad80000 closed (org.apache.zookeeper.ZooKeeper)
[2018-03-24 21:03:59,041] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server '**10.15.167.158:2181**' **with timeout of 6000 ms**
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:115)
	at kafka.utils.ZkUtils$.withMetrics(ZkUtils.scala:92)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:350)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:194)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:92)
	at kafka.Kafka.main(Kafka.scala)
[2018-03-24 21:03:59,041] INFO shutting down (kafka.server.KafkaServer)
[2018-03-24 21:03:59,042] INFO EventThread shut down for session: 0x16259d31ad80000 (org.apache.zookeeper.ClientCnxn)
[2018-03-24 21:03:59,062] INFO shut down completed (kafka.server.KafkaServer)
[2018-03-24 21:03:59,063] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2018-03-24 21:03:59,070] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by manalibhutiyani** [comment]
aha!!
there is also a delete actually of this CT entry for Kafka in cilium logs:
```
Mar 24 20:46:21 runtime cilium-agent[15240]: level=debug msg="updating resource in cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=54
Mar 24 20:46:27 runtime cilium-agent[15240]: level=debug msg="updating resource in cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=64
Mar 24 20:46:43 runtime cilium-agent[15240]: level=debug msg="updating resource in cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=100
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="deleting resource from cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=114
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="endpoint IP cache Delete" cached-identity=3882 endpoint-ip=10.15.101.61 identity=3882
Mar 24 21:04:07 runtime cilium-agent[6276]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.167.158 entryDstPort=0 entryFlags=2 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.101.61 entrySrcSecID=17014 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Mar 24 21:04:07 runtime cilium-agent[6276]: level=debug msg="Ignoring CT map entry: no endpoint ID or IP given in filter" entryDstIP=10.15.167.158 entryDstPort=0 entryFlags=2 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.101.61 entrySrcSecID=17014 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
Mar 24 21:04:07 runtime cilium-agent[6276]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.167.158 entryDstPort=0 entryFlags=3 entryProto=1 entryProxyPort=0 entrySrcIP=10.15.101.61 entrySrcSecID=17014 filterEndpointID=0 filterEndpointIP="<nil>" filterType=timeout
```

**Comment by tgraf** [comment]
> It looks like the Kafka endpoint is missing an endpoint ID and endpoint IP. @tgraf @rlenglet when does this usually happen?

I assume you are talking about endpointID not being set in L7 access log records. That happens when the endpoint can't be found, usually because it already disappeared again.

> org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server '**10.15.167.158:2181**' **with timeout of 6000 ms**

This indicate that there is another timeout that we should increase.

**Comment by manalibhutiyani** [comment]
Yes it is the `zookeeper.connection.timeout.ms`
The `zookeeper.session.timeout.ms` is set correctly as per Kafka logs:
```
zookeeper.connection.timeout.ms = 6000
zookeeper.session.timeout.ms = 20000
```
The session timeout is set correctly, but the endpoint disappears after the initial session is established. I can increase `zookeeper.connection.timeout.ms` too, but I am a bit concerned about why the Kafka container disappeared.

By endpoint not being there, I meant the following cilium logs:
```
Mar 24 20:46:27 runtime cilium-agent[15240]: level=debug msg="updating resource in cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=64
Mar 24 20:46:43 runtime cilium-agent[15240]: level=debug msg="updating resource in cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=100
Mar 24 20:46:49 runtime cilium-agent[15240]: level=debug msg="Wait time for proxy updates: 185.619µs" containerID=395b5afd8c endpointID=4314 policyRevision=12
Mar 24 20:46:50 runtime cilium-agent[15240]: level=debug msg="DELETE /endpoint/{id} request" params="{HTTPRequest:0xc421929a00 ID:docker-endpoint:bbaa9ce5ac54b11428b3d9473af449f64f209d9b83da0b5407c261f4fb6a6a58}"
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="deleting resource from cache" xdsResourceName=10.15.101.61 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=114
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="endpoint IP cache Delete" cached-identity=3882 endpoint-ip=10.15.101.61 identity=3882
Mar 24 20:46:51 runtime cilium-agent[15240]: level=debug msg="DELETE /endpoint/{id} request" params="{HTTPRequest:0xc421944f00 ID:docker-endpoint:35da5f331fa78697bf52e143ef85a806612e13005e32536d42c91027c0a5e1b8}"
Mar 24 20:46:52 runtime cilium-agent[15240]: level=debug msg="DELETE /endpoint/{id} request" params="{HTTPRequest:0xc421568100 ID:docker-endpoint:65c6c97361356ee4623822ac967c766501c7b92fd6bfae9ef9fc93060aec8215}"
Mar 24 20:47:02 runtime cilium-agent[15240]: level=debug msg="Updated controller" name="sync-IPv6-identity-mapping (62502)" subsys=controller uuid=80fd7261-2fa4-11e8-875f-080027f05204
Mar 24 20:47:02 runtime cilium-agent[15240]: level=debug msg="preparing new cache transaction: upserting 1 entries, deleting 0 entries" xdsTypeURL=type.googleapis.com/cilium.NetworkPolicyHosts xdsVersionInfo=61
Mar 24 20:47:02 runtime cilium-agent[15240]: level=debug msg="inserting resource into cache" xdsResourceName=60312 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicyHosts xdsVersionInfo=61
Mar 24 20:47:02 runtime cilium-agent[15240]: level=debug msg="committing cache transaction and notifying of new version" xdsTypeURL=type.googleapis.com/cilium.NetworkPolicyHosts xdsVersionInfo=61
Mar 24 20:47:09 runtime cilium-agent[15240]: level=debug msg="Removed update controller" name="sync-IPv6-identity-mapping (62502)" subsys=controller uuid=80fd7261-2fa4-11e8-875f-080027f05204
Mar 24 20:47:09 runtime cilium-agent[15240]: level=debug msg="Shutting down controller" name="sync-IPv6-identity-mapping (62502)" subsys=controller uuid=80fd7261-2fa4-11e8-875f-080027f05204
Mar 24 20:47:23 runtime cilium-agent[15240]: level=debug msg="GET /endpoint/{id} request" endpointID="docker-endpoint:4c0d2dc586a51119b91d654458f0e3401d2e5cd3074961d4efda7c49a62079df"
Mar 24 20:47:23 runtime cilium-agent[15240]: level=debug msg="GET /endpoint/{id} request" endpointID="docker-endpoint:4c0d2dc586a51119b91d654458f0e3401d2e5cd3074961d4efda7c49a62079df"
Mar 24 20:47:26 runtime cilium-agent[15240]: level=debug msg="preparing new cache transaction: upserting 1 entries, deleting 0 entries" xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=161
Mar 24 20:47:26 runtime cilium-agent[15240]: level=debug msg="inserting resource into cache" xdsResourceName="f00d::a0f:0:0:56ec" xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=161
Mar 24 20:47:26 runtime cilium-agent[15240]: level=debug msg="committing cache transaction and notifying of new version" xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=161
Mar 24 20:47:50 runtime cilium-agent[15240]: level=debug msg="Wait time for proxy updates: 611.693µs" containerID=2416d1e2ff endpointID=33922 policyRevision=14
Mar 24 20:48:03 runtime cilium-agent[15240]: level=debug msg="DELETE /endpoint/{id} request" params="{HTTPRequest:0xc422e6ac00 ID:docker-endpoint:4c0d2dc586a51119b91d654458f0e3401d2e5cd3074961d4efda7c49a62079df}"
```

**Comment by tgraf** [comment]
It disappears because the zookeeper service can't be reached.

**Comment by manalibhutiyani** [comment]
^ ok, isn't that a bigger issue? That we can't reach the zookeeper service? Or does it just needs to wait a bit longer ? I can put out a PR to update the 
```
zookeeper.connection.timeout.ms = 20000
```
instead of default, but wanted to confirm if there is a bigger issue here of not being able to resolve the zookeeper service?

**Comment by tgraf** [comment]
Cilium keeps endpoints in drop all mode until policy has been resolved. This can take longer than 6 seconds if the system load is high, in particular in debug mode.

**Comment by manalibhutiyani** [comment]
Ah! thanks for explaining. I can increase the 

```
zookeeper.connection.timeout.ms = 20000

```
making change now. Will put in out for review in around 20-30 min.

**Comment by manalibhutiyani** [comment]
Out for review
https://github.com/cilium/cilium/pull/3308
