### ISSUE TITLE
01-ct: error from daemon: creating endpoint context deadline exceeded

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#332]
When installing natively, and having docker and cilium service running,  I get the following issue for 01-ct case:
```
[root@localhost tests]# ./01-ct.sh 
+ TEST_NET=cilium
+ trap cleanup EXIT
+ cleanup
+ docker rm -f server client httpd1 httpd2 curl
+ true
+ monitor_stop
+ '[' '!' -z '' ']'
+ monitor_start
+ MONITOR_PID=11139
+ docker network inspect cilium
+ sudo cilium monitor
[
    {
        "Name": "cilium",
        "Id": "569d7b794e9256be99fa0c8e9c47b45865ff458e23e92644646481698cd03ea3",
        "Scope": "local",
        "Driver": "cilium",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "cilium",
            "Options": {},
            "Config": [
                {
                    "Subnet": "0.0.0.0/0",
                    "Gateway": "10.4.0.1/32"
                },
                {
                    "Subnet": "::1/112"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
+ docker run -dt --net=cilium --name server -l id.server tgraf/netperf
ced76d8bffe81f5e2bae25df19dcb75f220f5df81d22370a00a2fa4be5cc4e74
+ docker run -dt --net=cilium --name httpd1 -l id.httpd httpd
34141341669bed19310c9be02dbd4f3f08e77c252d840f088b8f22ae630c9067
+ docker run -dt --net=cilium --name httpd2 -l id.httpd_deny httpd
342c35405e936aea99114c6c64057d27e6b10516cf041ae4177764408b3040f4
/usr/bin/docker-current: Error response from daemon: failed to create endpoint httpd2 on network cilium: NetworkDriver.CreateEndpoint: Error creating endpoint context deadline exceeded.
+ docker run -dt --net=cilium --name client -l id.client tgraf/netperf
b91c5e835420025f6b2c0ba0adb1273f199c76e6c5f0321f6818cd13a63be218
/usr/bin/docker-current: Error response from daemon: failed to create endpoint client on network cilium: NetworkDriver.CreateEndpoint: Error creating endpoint context deadline exceeded.
+ docker run -dt --net=cilium --name curl -l id.curl tgraf/netperf
226bcfebbe1d97712b453298b6f11522365aeca51cd45664b713f59dedaa3c0b
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.GlobalIPv6Address }}' client
+ CLIENT_IP=
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.IPAddress }}' client
+ CLIENT_IP4=
++ cilium endpoint list
++ grep id.client
++ awk '{ print $1}'
Error: cannot get endpoint list: context deadline exceeded

+ CLIENT_ID=
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.GlobalIPv6Address }}' server
+ SERVER_IP=f00d::ac14:a04:0:6481
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.IPAddress }}' server
+ SERVER_IP4=10.4.101.61
++ cilium endpoint list
++ grep id.server
++ awk '{ print $1}'
+ SERVER_ID=25729
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.GlobalIPv6Address }}' httpd1
+ HTTPD1_IP=f00d::ac14:a04:0:f8a
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.IPAddress }}' httpd1
+ HTTPD1_IP4=10.4.251.95
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.GlobalIPv6Address }}' httpd2
+ HTTPD2_IP=
++ docker inspect --format '{{ .NetworkSettings.Networks.cilium.IPAddress }}' httpd2
+ HTTPD2_IP4=
+ echo -n 'Sleeping 5 seconds...'
Sleeping 5 seconds...+ sleep 5
+ echo ' done.'
 done.
+ set -x
+ cilium endpoint list
ENDPOINT   IDENTITY        LABELS (source:key[=value])   IPv6                    IPv4           STATUS         
48896      <no label id>                                 f00d::ac14:a04:0:bf00   10.4.13.37     disconnected   
60670      <no label id>                                 f00d::ac14:a04:0:ecfe   10.4.167.158   disconnected   
4314       <no label id>                                 f00d::ac14:a04:0:10da   10.4.25.58     disconnected   
10687      <no label id>                                 f00d::ac14:a04:0:29bf   10.4.129.219   disconnected   
4432       267             cilium:id.curl                f00d::ac14:a04:0:1150   10.4.202.84    ready          
25729      265             cilium:id.server              f00d::ac14:a04:0:6481   10.4.101.61    ready          
3978       266             cilium:id.httpd               f00d::ac14:a04:0:f8a    10.4.251.95    ready          
56326      <no label id>                                 f00d::ac14:a04:0:dc06   10.4.129.91    disconnected   
+ cat
+ cilium -D policy import -
2017-03-17T13:37:58.018+01:00 localhost.localdomain DEBU 001 loadPolicy > Entering directory -...
2017-03-17T13:37:58.018+01:00 localhost.localdomain DEBU 002 loadPolicyFile > Loading file -
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 003 UnmarshalJSON > Resolving tree: &{path: Name:root Parent:<nil> Rules:[0xc42157e330 Coverage: [cilium:id.server] Allowing: [{accept reserved:host} {accept cilium:id.client}] Coverage: [cilium:id.httpd] Allowing: [{accept cilium:id.curl}] 0xc42157f3b0 Coverage: [cilium:id.httpd_deny] Allowing: [{accept cilium:id.curl}] 0xc42157f770] Children:map[] mergeable:false resolved:false}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 004 ResolveTree > Resolving policy node &{path: Name:root Parent:<nil> Rules:[0xc42157e330 Coverage: [cilium:id.server] Allowing: [{accept reserved:host} {accept cilium:id.client}] Coverage: [cilium:id.httpd] Allowing: [{accept cilium:id.curl}] 0xc42157f3b0 Coverage: [cilium:id.httpd_deny] Allowing: [{accept cilium:id.curl}] 0xc42157f770] Children:map[] mergeable:false resolved:false}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 005 resolveRules > Resolving rules of node &{path:root Name:root Parent:<nil> Rules:[0xc42157e330 Coverage: [cilium:id.server] Allowing: [{accept reserved:host} {accept cilium:id.client}] Coverage: [cilium:id.httpd] Allowing: [{accept cilium:id.curl}] 0xc42157f3b0 Coverage: [cilium:id.httpd_deny] Allowing: [{accept cilium:id.curl}] 0xc42157f770] Children:map[] mergeable:false resolved:false}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 006 Resolve > Resolving L4 rule &{Coverage:[cilium:id.curl] Allow:[{Ingress:[] Egress:[{Port:80 Protocol:tcp Redirect: Rules:[]}]}]}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 007 Resolve > Resolved label cilium:id.curl to path root.id.curl
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 008 Resolve > Resolving consumer rule Coverage: [cilium:id.server] Allowing: [{accept reserved:host} {accept cilium:id.client}]
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 009 Resolve > Resolved label cilium:id.server to path root.id.server
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 00a Resolve > Resolved label reserved:host to path root.host
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 00b Resolve > Resolved label cilium:id.client to path root.id.client
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 00c Resolve > Resolving consumer rule Coverage: [cilium:id.httpd] Allowing: [{accept cilium:id.curl}]
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 00d Resolve > Resolved label cilium:id.httpd to path root.id.httpd
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 00e Resolve > Resolved label cilium:id.curl to path root.id.curl
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 00f Resolve > Resolving L4 rule &{Coverage:[cilium:id.httpd] Allow:[{Ingress:[{Port:80 Protocol:tcp Redirect: Rules:[]}] Egress:[]}]}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 010 Resolve > Resolved label cilium:id.httpd to path root.id.httpd
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 011 Resolve > Resolving consumer rule Coverage: [cilium:id.httpd_deny] Allowing: [{accept cilium:id.curl}]
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 012 Resolve > Resolved label cilium:id.httpd_deny to path root.id.httpd_deny
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 013 Resolve > Resolved label cilium:id.curl to path root.id.curl
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 014 Resolve > Resolving L4 rule &{Coverage:[cilium:id.httpd_deny] Allow:[{Ingress:[{Port:9090 Protocol:tcp Redirect: Rules:[]}] Egress:[]}]}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 015 Resolve > Resolved label cilium:id.httpd_deny to path root.id.httpd_deny
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 016 UnmarshalJSON > Resolved tree: &{path:root Name:root Parent:<nil> Rules:[0xc42157e330 Coverage: [cilium:id.server] Allowing: [{accept reserved:host} {accept cilium:id.client}] Coverage: [cilium:id.httpd] Allowing: [{accept cilium:id.curl}] 0xc42157f3b0 Coverage: [cilium:id.httpd_deny] Allowing: [{accept cilium:id.curl}] 0xc42157f770] Children:map[] mergeable:true resolved:true}
2017-03-17T13:37:58.019+01:00 localhost.localdomain DEBU 017 func17 > Constructed policy object for import &{path:root Name:root Parent:<nil> Rules:[0xc42157e330 Coverage: [cilium:id.server] Allowing: [{accept reserved:host} {accept cilium:id.client}] Coverage: [cilium:id.httpd] Allowing: [{accept cilium:id.curl}] 0xc42157f3b0 Coverage: [cilium:id.httpd_deny] Allowing: [{accept cilium:id.curl}] 0xc42157f770] Children:map[] mergeable:true resolved:true}
+ BIDIRECTIONAL=1
+ connectivity_test
+ monitor_clear
+ set +x
+ docker exec -i curl bash -c 'curl --connect-timeout 5 -XGET http://[f00d::ac14:a04:0:f8a]:80'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    45  100    45    0     0  19067      0 --:--:-- --:--:-- --:--:-- 45000
<html><body><h1>It works!</h1></body></html>
+ monitor_clear
+ set +x
+ docker exec -i curl bash -c 'curl --connect-timeout 5 -XGET http://10.4.251.95:80'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    45  100    45    0     0  61141      0 --:--:-- --:--:-- --:--:-- 45000
<html><body><h1>It works!</h1></body></html>
+ monitor_clear
+ set +x
+ docker exec -i curl bash -c 'curl --connect-timeout 5 -XGET http://[]:80'
curl: (3) [globbing] bad range specification in column 9
+ monitor_clear
+ set +x
+ docker exec -i curl bash -c 'curl --connect-timeout 5 -XGET http://:80'
curl: (6) Couldn't resolve host ''
+ monitor_clear
+ set +x
+ docker exec -i client ping6 -c 5 f00d::ac14:a04:0:6481
Error response from daemon: Container b91c5e835420025f6b2c0ba0adb1273f199c76e6c5f0321f6818cd13a63be218 is not running
+ abort 'Error: Could not ping server container from client'
+ set +x
------------------------------------------------------------------------
                            Test Failed
Error: Could not ping server container from client

------------------------------------------------------------------------
#kernel
server
client
httpd1
httpd2
curl
```

The related `journalctl -u cilium.service` log outputs:
```
[...]
Mar 17 13:44:29 localhost.localdomain cilium-agent[7399]: INFO 05f regenerate > Regenerated program of endpoint 16996
Mar 17 13:44:46 localhost.localdomain cilium-agent[7399]: INFO 060 regenerate > Regenerated program of endpoint 16996
Mar 17 13:45:02 localhost.localdomain cilium-agent[7399]: INFO 061 regenerate > Regenerated program of endpoint 16996
Mar 17 13:45:18 localhost.localdomain cilium-agent[7399]: INFO 062 regenerate > Regenerated program of endpoint 45392
Mar 17 13:45:34 localhost.localdomain cilium-agent[7399]: INFO 063 regenerate > Regenerated program of endpoint 16996
Mar 17 13:45:50 localhost.localdomain cilium-agent[7399]: INFO 064 regenerate > Regenerated program of endpoint 45392
Mar 17 13:46:06 localhost.localdomain cilium-agent[7399]: INFO 065 regenerate > Regenerated program of endpoint 45392
Mar 17 13:46:21 localhost.localdomain cilium-agent[7399]: INFO 066 regenerate > Regenerated program of endpoint 16996
Mar 17 13:46:37 localhost.localdomain cilium-agent[7399]: INFO 067 regenerate > Regenerated program of endpoint 45392
Mar 17 13:46:53 localhost.localdomain cilium-agent[7399]: INFO 068 regenerate > Regenerated program of endpoint 45392
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: INFO 069 regenerate > Regenerated program of endpoint 16996
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: 2017/03/17 13:47:09 http: panic serving @: write unix /var/run/cilium/cilium.sock->@: write: broken pipe
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: goroutine 4766 [running]:
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.(*conn).serve.func1(0xc422088880)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1491 +0x12a
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: panic(0x1981320, 0xc421cb14f0)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/runtime/panic.go:458 +0x243
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*GetEndpointOK).WriteResponse(0xc421e967a0, 0x2921c40, 0xc4217f1040, 0x2910a80, 0x1c74468)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/get_endpoint_responses.go:55 +0x158
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc42044ee40, 0x2921c40, 0xc4217f1040, 0xc421da0780, 0xc420e2
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/context.go:439 +0x424
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*GetEndpoint).ServeHTTP(0xc4217b67e0, 0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/get_endpoint.go:54 +0x1f9
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.HandlerFunc.ServeHTTP(0xc420e740f0, 0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0xe2
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.HandlerFunc.ServeHTTP(0xc42135bb00, 0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xac
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.HandlerFunc.ServeHTTP(0xc421d8db00, 0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x8b
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.HandlerFunc.ServeHTTP(0xc421d8db40, 0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.serverHandler.ServeHTTP(0xc421d9b900, 0x2921c40, 0xc4217f1040, 0xc421da0780)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:2202 +0x7d
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.(*conn).serve(0xc422088880, 0x2923040, 0xc421d2a340)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1579 +0x4b7
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: created by net/http.(*Server).Serve
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:2293 +0x44d
Mar 17 13:47:25 localhost.localdomain cilium-agent[7399]: INFO 06a regenerate > Regenerated program of endpoint 49896
Mar 17 13:47:41 localhost.localdomain cilium-agent[7399]: INFO 06b regenerate > Regenerated program of endpoint 45392
Mar 17 13:47:56 localhost.localdomain cilium-agent[7399]: INFO 06c regenerate > Regenerated program of endpoint 49896
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: WARN 06d runInit > Command execution failed: exit status 1
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: WARN 06e runInit > Command output:
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: Join EP id=16996_next ifname=lxc405d5
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: Cannot find device "lxc405d5"
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: Cannot find device "lxc405d5"
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: WARN 06f triggerPolicyUpdates > Error while handling policy updates for endpoint 16996: error: "exit status 1" command output: "Join EP id=16996_next ifn
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: WARN 070 removeFromMaps > Update of policy map failed: Unable to delete element: no such file or directory
Mar 17 13:48:12 localhost.localdomain cilium-agent[7399]: WARN 071 removeFromMaps > Update of policy map failed: Unable to delete element: no such file or directory
Mar 17 13:48:28 localhost.localdomain cilium-agent[7399]: INFO 072 regenerate > Regenerated program of endpoint 49896
Mar 17 13:48:28 localhost.localdomain cilium-agent[7399]: WARN 073 handleCreateContainer > endpoint disappeared while processing event for b4cd9815a3425b46338064caba160a475f510fd0ac781a237650ca12a9e81c23, ignori
Mar 17 13:48:28 localhost.localdomain cilium-agent[7399]: WARN 074 handleCreateContainer > endpoint disappeared while processing event for 7e8b60b27709d84b2748c49307478251f9a7a4d9d6911b101afd5a674dc17f57, ignori
lines 214-266/266 (END)
```

**Comment by tgraf** [comment]
@borkmann I'm not seeing this error when running off head 563b424cff14040206bac02aa3c2241e87e028e6. Is the failure consistent?

**Comment by borkmann** [comment]
My HEAD is at 5017ec0c5846.

I'm using the packages from latest Fedora 25 installation:
```
# go version
go version go1.7.5 linux/amd64
```
```
# docker --version
Docker version 1.12.6, build ae7d637/1.12.6
```
systemd services:
```
# service docker status
Redirecting to /bin/systemctl status  docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-03-17 12:03:25 CET; 3h 32min ago
     Docs: http://docs.docker.com
 Main PID: 2388 (dockerd-current)
    Tasks: 25 (limit: 8192)
   Memory: 11.8M
      CPU: 17.977s
   CGroup: /system.slice/docker.service
           ├─2388 /usr/bin/dockerd-current --add-runtime oci=/usr/libexec/docker/docker-runc-current --default-runtime=oci --containerd /run/containerd.sock --exec-opt native.cgroupdriver=systemd --userland-prox
           └─7659 /usr/libexec/docker/docker-proxy-current -proto tcp -host-ip 0.0.0.0 -host-port 8500 -container-ip 172.17.0.2 -container-port 8500
```
And:
```
[root@localhost tests]# service cilium status
Redirecting to /bin/systemctl status  cilium.service
● cilium.service - cilium
   Loaded: loaded (/usr/lib/systemd/system/cilium.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-03-17 12:41:16 CET; 2h 54min ago
     Docs: https://github.com/cilium/cilium
 Main PID: 7399 (cilium-agent)
    Tasks: 12 (limit: 4915)
   Memory: 7.0M
      CPU: 30min 25.683s
   CGroup: /system.slice/cilium.service
           └─7399 /usr/bin/cilium-agent --consul 127.0.0.1:8500
```
Happens every time so far:
```
[...]
Mar 17 13:46:53 localhost.localdomain cilium-agent[7399]: INFO 068 regenerate > Regenerated program of endpoint 45392
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: INFO 069 regenerate > Regenerated program of endpoint 16996
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: 2017/03/17 13:47:09 http: panic serving @: write unix /var/run/cilium/cilium.sock->@: write: broken pipe
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: goroutine 4766 [running]:
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: net/http.(*conn).serve.func1(0xc422088880)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/net/http/server.go:1491 +0x12a
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]: panic(0x1981320, 0xc421cb14f0)
Mar 17 13:47:09 localhost.localdomain cilium-agent[7399]:         /usr/lib/golang/src/runtime/panic.go:458 +0x243
```

**Comment by borkmann** [comment]
Compiled recent clang from git, issue was that clang compilation takes up to 10s for `bpf_lxc.c` which causes the timeout (`endpoint context deadline exceeded`) to appear. Downgrading to older clang (f.e. 3.9) seems to resolve the issue.
