### ISSUE TITLE
Test: Issue when policy is updated

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#3329]
```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:229
cannot delete the policy
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/monitor.go:115
```

[test_results_Ginkgo-CI-Tests-Pipeline_1860.zip](https://github.com/cilium/cilium/files/1851592/test_results_Ginkgo-CI-Tests-Pipeline_1860.zip)

**Comment by eloycoto** [comment]
policy delete work, but the agent, attached the panic: 

```
cmd: "sudo cilium policy delete --all -o json | jq '.revision'" exitCode: 0 
 23

time="2018-03-27T08:40:14Z" level=debug msg="running command: sudo cilium policy wait 23"
cmd: "sudo cilium policy wait 23" exitCode: 1 
 Error: cannot list endpoints: Get http:///var/run/cilium/cilium.sock/v1beta/endpoint: dial unix /var/run/cilium/cilium.sock: connect: connection refused
Is the agent running?
```
```
Mar 27 08:40:14 runtime cilium-agent[3254]: level=debug msg="committing cache transaction and notifying of new version" xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy xdsVersionInfo=358
Mar 27 08:40:14 runtime cilium-agent[3254]: fatal error: concurrent map writes
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 61635 [running]:
Mar 27 08:40:14 runtime cilium-agent[3254]: runtime.throw(0x1de93da, 0x15)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc4240cb398 sp=0xc4240cb378 pc=0x42e095
Mar 27 08:40:14 runtime cilium-agent[3254]: runtime.mapassign_faststr(0x1affe40, 0xc421e5ce70, 0xc421cdbb40, 0x12, 0x12)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/hashmap_fast.go:783 +0x4f5 fp=0xc4240cb418 sp=0xc4240cb398 pc=0x40f495
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/envoy.(*XDSServer).UpdateNetworkPolicy(0xc4200e4460, 0x2e01220, 0xc421483400, 0xc4240464a0, 0xc421a59b00, 0xc421ad1d40, 0x0, 0x0, 0x2dbdb00, 0xc421fd50e0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/envoy/server.go:526 +0x695 fp=0xc4240cb5e0 sp=0xc4240cb418 pc=0x173bd75
Mar 27 08:40:14 runtime cilium-agent[3254]: main.(*Daemon).UpdateNetworkPolicy(0xc42203cc80, 0xc421483400, 0xc4240464a0, 0xc421a59b00, 0xc421ad1d40, 0x0, 0x1ba2ca0, 0xc421820e70)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:156 +0x8f fp=0xc4240cb640 sp=0xc4240cb5e0 pc=0x189ea8f
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/endpoint.(*Endpoint).updateNetworkPolicy(0xc421483400, 0x2e04ca0, 0xc42203cc80, 0xc4240464a0, 0xc421ad1d10)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:617 +0x516 fp=0xc4240cb820 sp=0xc4240cb640 pc=0x175c896
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc421483400, 0x2e04ca0, 0xc42203cc80, 0xc422e85660, 0x20, 0x1e16756, 0x2d, 0x0, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:693 +0x1a5b fp=0xc4240cbd20 sp=0xc4240cb820 pc=0x174810b
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421483400, 0x2e04ca0, 0xc42203cc80, 0x1e16756, 0x2d, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:872 +0x3ee fp=0xc4240cbee8 sp=0xc4240cbd20 pc=0x175e3de
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0x1e16756, 0x2d, 0x2e04ca0, 0xc42203cc80, 0xc420c693e0, 0xc421483400)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:946 +0x236 fp=0xc4240cbfb0 sp=0xc4240cbee8 pc=0x1762a56
Mar 27 08:40:14 runtime cilium-agent[3254]: runtime.goexit()
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4240cbfb8 sp=0xc4240cbfb0 pc=0x45f3f1
Mar 27 08:40:14 runtime cilium-agent[3254]: created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:929 +0x13f
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 1 [semacquire, 9 minutes]:
Mar 27 08:40:14 runtime cilium-agent[3254]: sync.runtime_Semacquire(0xc42038294c)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/sema.go:56 +0x39
Mar 27 08:40:14 runtime cilium-agent[3254]: sync.(*WaitGroup).Wait(0xc420382940)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/sync/waitgroup.go:131 +0x72
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/api/v1/server.(*Server).Serve(0xc421baaf00, 0x100000002, 0xc421468480)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/api/v1/server/server.go:307 +0x131
Mar 27 08:40:14 runtime cilium-agent[3254]: main.runDaemon()
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:825 +0xf7c
Mar 27 08:40:14 runtime cilium-agent[3254]: main.glob..func1(0x2dc0d40, 0xc42146b110, 0x0, 0x7)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:135 +0x30
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x2dc0d40, 0xc420010090, 0x7, 0x7, 0x2dc0d40, 0xc420010090)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x234
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2dc0d40, 0xc4213f2770, 0x1a51da0, 0xc420210960)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x2fe
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x2dc0d40, 0x0, 0xc4213f2200)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
Mar 27 08:40:14 runtime cilium-agent[3254]: main.main()
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:149 +0x13a
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 19 [chan receive]:
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2e922a0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/golang/glog/glog.go:882 +0x9f
Mar 27 08:40:14 runtime cilium-agent[3254]: created by github.com/cilium/cilium/vendor/github.com/golang/glog.init.0
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/golang/glog/glog.go:410 +0x203
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 37 [sleep]:
Mar 27 08:40:14 runtime cilium-agent[3254]: time.Sleep(0x37e11d600)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/time.go:65 +0x130
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/monitor.init.0.func1()
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/monitor/ifindex.go:63 +0x36
Mar 27 08:40:14 runtime cilium-agent[3254]: created by github.com/cilium/cilium/pkg/monitor.init.0
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/monitor/ifindex.go:45 +0x35
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 42 [syscall, 9 minutes]:
Mar 27 08:40:14 runtime cilium-agent[3254]: os/signal.signal_recv(0xc4200257c0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
Mar 27 08:40:14 runtime cilium-agent[3254]: os/signal.loop()
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Mar 27 08:40:14 runtime cilium-agent[3254]: created by os/signal.init.0
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 22 [IO wait, 9 minutes]:
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.runtime_pollWait(0x7fe1cade6f70, 0x72, 0xffffffffffffffff)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/netpoll.go:173 +0x57
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.(*pollDesc).wait(0xc420435f98, 0x72, 0xc420026d00, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.(*pollDesc).waitRead(0xc420435f98, 0xffffffffffffff00, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.(*FD).Accept(0xc420435f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
Mar 27 08:40:14 runtime cilium-agent[3254]: net.(*netFD).accept(0xc420435f80, 0x7fe1cae58000, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/net/fd_unix.go:238 +0x42
Mar 27 08:40:14 runtime cilium-agent[3254]: net.(*TCPListener).accept(0xc42000e0e0, 0xc420026f08, 0x445fe7, 0x10)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
Mar 27 08:40:14 runtime cilium-agent[3254]: net.(*TCPListener).Accept(0xc42000e0e0, 0x1, 0x1, 0xc42018b220, 0x1)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/net/tcpsock.go:247 +0x49
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/vendor/github.com/google/gops/agent.listen()
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/google/gops/agent/agent.go:105 +0x8a
Mar 27 08:40:14 runtime cilium-agent[3254]: created by github.com/cilium/cilium/vendor/github.com/google/gops/agent.Listen
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/google/gops/agent/agent.go:98 +0x428
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 48718 [select, 2 minutes]:
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc421bd9680)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/controller/controller.go:221 +0x2f0
Mar 27 08:40:14 runtime cilium-agent[3254]: created by github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/controller/manager.go:81 +0x2c8
Mar 27 08:40:14 runtime cilium-agent[3254]: goroutine 833 [IO wait]:
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.runtime_pollWait(0x7fe1cade6730, 0x72, 0x1)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/runtime/netpoll.go:173 +0x57
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.(*pollDesc).wait(0xc422e72518, 0x72, 0xffffffffffffff01, 0x2dd88a0, 0x2dc7660)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.(*pollDesc).waitRead(0xc422e72518, 0xc422e8b001, 0x1000, 0x1000)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Mar 27 08:40:14 runtime cilium-agent[3254]: internal/poll.(*FD).Read(0xc422e72500, 0xc422e8b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
Mar 27 08:40:14 runtime cilium-agent[3254]: os.(*File).read(0xc42000ea60, 0xc422e8b000, 0x1000, 0x1000, 0x0, 0x0, 0xc421b22300)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/os/file_unix.go:216 +0x4e
Mar 27 08:40:14 runtime cilium-agent[3254]: os.(*File).Read(0xc42000ea60, 0xc422e8b000, 0x1000, 0x1000, 0xc422021d38, 0x1, 0x591408)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/os/file.go:103 +0x6d
Mar 27 08:40:14 runtime cilium-agent[3254]: bufio.(*Reader).fill(0xc422021f60)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/bufio/bufio.go:97 +0x11a
Mar 27 08:40:14 runtime cilium-agent[3254]: bufio.(*Reader).ReadSlice(0xc422021f60, 0x5a0000c4237a210a, 0x0, 0xc422021df4, 0xc422021df0, 0xc4214e4898, 0x2dbdb50)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/bufio/bufio.go:338 +0x2c
Mar 27 08:40:14 runtime cilium-agent[3254]: bufio.(*Reader).ReadBytes(0xc422021f60, 0xc421eefe0a, 0x37, 0x19ac060, 0xc4233703c8, 0x0, 0x0)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/usr/local/go/src/bufio/bufio.go:416 +0x6b
Mar 27 08:40:14 runtime cilium-agent[3254]: github.com/cilium/cilium/monitor/launch.(*NodeMonitor).Run(0xc42203cd20, 0xc422e84180, 0x1b)
Mar 27 08:40:14 runtime cilium-agent[3254]: 	/home/vagrant/go/src/github.com/cilium/cilium/monitor/launch/launcher.go:98 +0xb3
```

**Comment by eloycoto** [comment]
Related with this nightly fail: 
https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/157/testReport/junit/k8s-1/9/NightlyPolicies_PolicyEnforcement_default_L3_Ingress_Label_L4_Ingress_Port_80_UDP_L7_No_Policy_Destination_service/

**Comment by rlenglet** [comment]
Fixed in https://github.com/cilium/cilium/pull/3326

**Comment by rlenglet** [comment]
My bad, this is a different issue than #3326.
