### ISSUE TITLE
Softlock during UpdateCiliumNodeResource when NodeController pending synchronization

### ISSUE THREAD

**Issue by sypakine** [cilium/cilium#34067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.13.18 and lower than v1.14.0

### What happened?

Problem

livelock between `NodeInit` and `BlockWaitGroupToSyncResources` (for Node resource). Additionally, the main daemon cell is also blocked.

If the nodeController OnUpdate function is called before the Node resource synchronizer go routine has locked the controller queue, the resource synchronizer is never able to mark the nodeController as synchronized, resulting in a live/deadlock.

When processing controller events, the controller locks the DeltaFIFO queue, in this case to process node update (OnUpdate):

```
...
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).NodesInit.func1.2({0x32d1b80?, 0xc000950b00?}, {0x32d1b80, 0xc001058b00})
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:84 +0xd4
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:239
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2d8eac0?, 0xc000ffb9c8?})
        /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:118 +0x2e3
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000f9e2c0, 0xc0002a3ec0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:598 +0x544
...
```

This go routine will eventually wait for the resource to be synched:

https://github.com/cilium/cilium/blob/19ff6c602372ef89eaab7ab4bb21482507e07b52/pkg/k8s/synced/resources.go#L127

However, while this lock is being held, the nodeController's hasSynced cannot be run:

https://github.com/cilium/cilium/blob/c9723a8df3cfa336da1f8457a864105d8349acfe/pkg/k8s/watchers/node.go#L93

```
goroutine 229 [sync.Mutex.Lock, 3 minutes]:
sync.runtime_SemacquireMutex(0xc000028a90?, 0x90?, 0x44e290?)
        /usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000f9e2c0)
        /usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x2?)
        /usr/local/go/src/sync/rwmutex.go:147 +0x31
k8s.io/client-go/tools/cache.(*DeltaFIFO).HasSynced(0xc000f9e2c0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:301 +0x2f
k8s.io/client-go/tools/cache.(*controller).HasSynced(0x46fdb2?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:161 +0x1b
k8s.io/client-go/tools/cache.WaitForCacheSync.func1()
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/shared_informer.go:288 +0x47
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil.ConditionFunc.WithContext.func1({0xc0008cd180, 0x2b5d3e0})
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:222 +0x13
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x38c9e10?, 0xc0008cd130?}, 0x4a0e39?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:235 +0x4c
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext({0x38c9e10, 0xc0008cd130}, 0xc000028cc0, 0x4468ab?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:662 +0x107
k8s.io/apimachinery/pkg/util/wait.poll({0x38c9e10, 0xc0008cd130}, 0xb6?, 0x38c9d30?, 0x5ab9220?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:596 +0x89
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x38c9e10?, 0xc0008cd130?}, 0x2b52e20?, 0x2b52e20?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:547 +0x53
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc0001f9ca0?, 0xc000028da8, 0x416210?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:538 +0x6b
k8s.io/client-go/tools/cache.WaitForCacheSync(0xc00029d1f0?, {0xc000028e58?, 0xc000028e80?, 0x12?})
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/shared_informer.go:285 +0x53
github.com/cilium/cilium/pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources.func1()
        /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:82 +0x1ad
created by github.com/cilium/cilium/pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources in goroutine 1
        /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:79 +0x1e9
```

nodeController.Run:
- https://github.com/cilium/cilium/blob/00775558241c36f8e55da6ef26f0a027ecc38b88/pkg/k8s/watchers/node.go#L94
BlockWaitGroupToSyncResources:
- https://github.com/cilium/cilium/blob/00775558241c36f8e55da6ef26f0a027ecc38b88/pkg/k8s/synced/resources.go#L82

---

Full stack trace:

- [trace.txt](https://github.com/user-attachments/files/16414970/trace.txt)
Note: some lines of code do not align with OSS Cilium v1.13.12 as we maintain internal patches on GKE. However, our patches do not change the Node Init on nodeController bootstrapping (although it appears that GKE multi-networking may increase the probability of encountering the issue: https://cloud.google.com/kubernetes-engine/docs/concepts/about-multinetwork-support-for-pods).

---

I see two broad fixes:

1.  register the CiliumNodeUpdater only after the cache has been synced:
   - https://github.com/cilium/cilium/blob/c9723a8df3cfa336da1f8457a864105d8349acfe/daemon/cmd/daemon.go#L728
2. Add/change`WaitForCacheSync` to include a timeout/return error
   - https://github.com/cilium/cilium/blob/c9723a8df3cfa336da1f8457a864105d8349acfe/pkg/k8s/watchers/node.go#L101

### How can we reproduce the issue?

I'm not able to reproduce this with KIND, as scale/churn is critical for reproduction. I am currently reproducing on GKE 1.29. 

Based on code review, I suspect this issue will also affect v1.14, but that has yet to be confirmed.

To capture the issue, changed the preStop lifecycle hook to dump the stacktrace before the pod is terminated due to the readiness check failure:

```
spec:
  template:
    spec:
      containers:
      - name: cilium-agent
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - /cni-uninstall.sh; gops stack $(gops | grep cilium-agent | awk "{ print $1 }") | tee -a /proc/1/fd/1; sleep 5; gops stack $(gops | grep cilium-agent | awk "{ print $1 }") | tee -a /proc/1/fd/1
```

### Cilium Version

`Cilium 1.13.12`

### Kernel Version

`kernel (6.1.85)`

### Kubernetes Version

`1.29`

### Relevant log output

Live-locked go routines:

```
goroutine 1 [chan receive, 3 minutes]:
github.com/cilium/cilium/pkg/k8s/synced.(*Resources).WaitForCacheSync(0xc000004310, {0xc000cae4b0?, 0x1, 0xc000a8a4b8?})
        /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:127 +0x265
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).WaitForCacheSync(...)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:375
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).GetK8sNode(0xc000004300, {0x7cdcb0fe4ef8?, 0x7cdcf7d6b108?}, {0xc0000761be, 0x1d})
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:117 +0x7c
github.com/cilium/cilium/pkg/k8s.retrieveNodeInformation({0x38c9e10, 0xc001050000}, {0x38a85e0, 0xc000004300}, {0xc0000761be, 0x1d})
        /go/src/github.com/cilium/cilium/pkg/k8s/init.go:84 +0x3a9
github.com/cilium/cilium/pkg/k8s.waitForNodeInformation({0x38c9e10, 0xc001050000}, {0x38a85e0, 0xc000004300}, {0xc0000761be, 0x1d})
        /go/src/github.com/cilium/cilium/pkg/k8s/init.go:45 +0x15c
github.com/cilium/cilium/pkg/k8s.WaitForNodeInformation({0x38c9e10?, 0xc001050000?}, {0x38a85e0?, 0xc000004300?})
        /go/src/github.com/cilium/cilium/pkg/k8s/init.go:150 +0x59
github.com/cilium/cilium/daemon/cmd.newDaemon({0x38c9e10?, 0xc001050000}, 0xc0010f0090, 0xc0000e8200, {0x38ed7e0, 0xc0000e9580}, 0x0, {0x39018a8, 0xc000e30fa0}, 0xc0010f8000)ilium/cilium/daemon/cmd/daemon.go:956 +0x3915
github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1({0x2ffed40, 0x495b00})
        /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1818 +0xc5
github.com/cilium/cilium/pkg/hive.Hook.Start(...)
        /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:35
github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start(0xc00077e960, {0x38c9e80?, 0xc000e32930?})
        /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:104 +0x2f4
github.com/cilium/cilium/pkg/hive.(*Hive).Start(0xc000668d80, {0x38c9e80, 0xc000e32930})
        /go/src/github.com/cilium/cilium/pkg/hive/hive.go:241 +0xf4
github.com/cilium/cilium/pkg/hive.(*Hive).Run(0xc000668d80)
        /go/src/github.com/cilium/cilium/pkg/hive/hive.go:167 +0x70
github.com/cilium/cilium/daemon/cmd.runApp(0xc000135e00?, {0x332345e?, 0x4?, 0x33232ea?})
        /go/src/github.com/cilium/cilium/daemon/cmd/root.go:84 +0x10a
github.com/spf13/cobra.(*Command).execute(0x5536440, {0xc000072090, 0x3, 0x3})
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x5536440)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:968
github.com/cilium/cilium/daemon/cmd.Execute()
        /go/src/github.com/cilium/cilium/daemon/cmd/root.go:96 +0x65
main.main()
        /go/src/github.com/cilium/cilium/daemon/main.go:9 +0xf
        
goroutine 230 [chan receive, 3 minutes]:
github.com/cilium/cilium/pkg/k8s/synced.(*Resources).WaitForCacheSync(0xc000004310, {0xc000dc9d70?, 0x1, 0xc000dc9d48?})
        /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:127 +0x265
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).WaitForCacheSync(...)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:375
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).GetK8sNode(0xc000004300, {0x0?, 0xc000dc9de0?}, {0xc0000761be, 0x1d})
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:117 +0x7c
github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).mutateNodeResource(0xc00055e000, 0xc0008eee00)
        /go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:430 +0x63
github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).UpdateCiliumNodeResource(0xc00055e000)
        /go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:378 +0x413
github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).updateLocalNode(0xc00055e000)
        /go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:319 +0x9a
github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).UpdateLocalNode(0xc00055e000)
        /go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:331 +0x93
github.com/cilium/cilium/pkg/k8s/watchers.(*ciliumNodeUpdater).updateCiliumNode(0xc0000805d0, 0xc001058b00)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:175 +0x10a
github.com/cilium/cilium/pkg/k8s/watchers.(*ciliumNodeUpdater).OnUpdateNode(0xda5c2079a504b0ea?, 0x40e58c?, 0x2ed5f20?, 0x0?)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:158 +0x16
github.com/cilium/cilium/pkg/k8s/watchers/subscriber.(*NodeChain).OnUpdateNode(0x32d1b80?, 0xc001058b00?, 0xc00049a3f0?, 0x32d1b80?)
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/subscriber/node.go:72 +0x152
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).NodesInit.func1.2({0x32d1b80?, 0xc000950b00?}, {0x32d1b80, 0xc001058b00})
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:84 +0xd4
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:239
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2d8eac0?, 0xc000ffb9c8?})
        /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:118 +0x2e3
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000f9e2c0, 0xc0002a3ec0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:598 +0x544
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000f0a090)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x30
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4468e0?, {0x388f8a0, 0xc00049a4e0}, 0x1, 0xc0000346c0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000127410?, 0x3b9aca00, 0x0, 0x40?, 0x7cdcb0dd1798?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0xc000f0a090, 0xc0000346c0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x315
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).NodesInit.func1 in goroutine 1
        /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:100 +0x53c

goroutine 229 [sync.Mutex.Lock, 3 minutes]:
sync.runtime_SemacquireMutex(0xc000028a90?, 0x90?, 0x44e290?)
        /usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000f9e2c0)
        /usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0x2?)
        /usr/local/go/src/sync/rwmutex.go:147 +0x31
k8s.io/client-go/tools/cache.(*DeltaFIFO).HasSynced(0xc000f9e2c0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:301 +0x2f
k8s.io/client-go/tools/cache.(*controller).HasSynced(0x46fdb2?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:161 +0x1b
k8s.io/client-go/tools/cache.WaitForCacheSync.func1()
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/shared_informer.go:288 +0x47
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil.ConditionFunc.WithContext.func1({0xc0008cd180, 0x2b5d3e0})
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:222 +0x13
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x38c9e10?, 0xc0008cd130?}, 0x4a0e39?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:235 +0x4c
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext({0x38c9e10, 0xc0008cd130}, 0xc000028cc0, 0x4468ab?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:662 +0x107
k8s.io/apimachinery/pkg/util/wait.poll({0x38c9e10, 0xc0008cd130}, 0xb6?, 0x38c9d30?, 0x5ab9220?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:596 +0x89
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x38c9e10?, 0xc0008cd130?}, 0x2b52e20?, 0x2b52e20?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:547 +0x53
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc0001f9ca0?, 0xc000028da8, 0x416210?)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:538 +0x6b
k8s.io/client-go/tools/cache.WaitForCacheSync(0xc00029d1f0?, {0xc000028e58?, 0xc000028e80?, 0x12?})
        /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/shared_informer.go:285 +0x53
github.com/cilium/cilium/pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources.func1()
        /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:82 +0x1ad
created by github.com/cilium/cilium/pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources in goroutine 1
        /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:79 +0x1e9
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sypakine** [comment]
Ah, comparing against v1.14 I found a closed issue for this: https://github.com/cilium/cilium/issues/23166

**Comment by sypakine** [comment]
Note: despite being mentioned in v1.13 backport notes, this was never backporting to v1.13 (although perhaps I am misreading the notes):

https://github.com/cilium/cilium/pull/23232
