### ISSUE TITLE
CI: Conformance Runtime (ci-runtime):  Runtime Test (privileged): `panic: invalid job name: "k8s-reflector-cilium-configs-cm-aLowPriority-kube-system", expected to match "^[a-z][a-z0-9_\\-]{0,100}$"`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#35044]
## CI failure

```
--- FAIL: TestWatchAllKeys (0.00s)
panic: invalid job name: "k8s-reflector-cilium-configs-cm-aLowPriority-kube-system", expected to match "^[a-z][a-z0-9_\\-]{0,100}$" [recovered]
	panic: invalid job name: "k8s-reflector-cilium-configs-cm-aLowPriority-kube-system", expected to match "^[a-z][a-z0-9_\\-]{0,100}$"

goroutine 51 [running]:
testing.tRunner.func1.2({0x28f9580, 0xc000a88a30})
	/root/sdk/go1.23.1/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/root/sdk/go1.23.1/src/testing/testing.go:1635 +0x35e
panic({0x28f9580?, 0xc000a88a30?})
	/root/sdk/go1.23.1/src/runtime/panic.go:785 +0x132
github.com/cilium/hive/job.OneShot({0xc0009993c0, 0x38}, 0xc000997ab8, {0x0, 0x0, 0x0})
	/host/vendor/github.com/cilium/hive/job/oneshot.go:27 +0xe5
github.com/cilium/cilium/pkg/k8s.RegisterReflector[...]({0x328b5a8, 0xc0001ed440}, 0x1, {{0xc0003b4dc0, 0x1b}, {0x32c8420, 0xc000421180}, {0x3268f68, 0xc0009979c8}, 0x2710, ...})
	/host/pkg/k8s/statedb.go:45 +0x3fd
github.com/cilium/cilium/pkg/dynamicconfig.RegisterConfigMapReflector({0x328b5a8, 0xc0001ed440}, 0xc0009974b8, {0xc000a6d200?, 0x2?, 0x7f70fe7e6108?}, {0x1, {0x2f45b9e, 0x8e}, {0x2ee0ba1, ...}})
	/host/pkg/dynamicconfig/table.go:93 +0x130
reflect.Value.call({0x295cd60?, 0x2fe3a08?, 0x0?}, {0x2e6641f, 0x4}, {0xc000a588a0, 0x4, 0x7f70fe7e6108?})
	/root/sdk/go1.23.1/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0x295cd60?, 0x2fe3a08?, 0x411085?}, {0xc000a588a0?, 0xc000a711c0?, 0x0?})
	/root/sdk/go1.23.1/src/reflect/value.go:365 +0xb9
go.uber.org/dig.defaultInvoker({0x295cd60?, 0x2fe3a08?, 0xc000a70fc0?}, {0xc000a588a0?, 0x298be60?, 0x32b3120?})
	/host/vendor/go.uber.org/dig/container.go:238 +0x25
go.uber.org/dig.(*Scope).Invoke(0xc000987cc0, {0x295cd60, 0x2fe3a08}, {0xc000548c30, 0x1, 0xc00064a000?})
	/host/vendor/go.uber.org/dig/invoke.go:160 +0x6c6
go.uber.org/dig.(*Container).Invoke(0xc000548c40?, {0x295cd60?, 0x2fe3a08?}, {0xc000548c30?, 0x2e6ed5d?, 0x8?})
	/host/vendor/go.uber.org/dig/invoke.go:82 +0x25
github.com/cilium/hive/cell.(*invoker).invoke(0xc000996ae0, 0xc000548ad0, {0x328ba08, 0xc0000f9218}, 0x5f5e100)
	/host/vendor/github.com/cilium/hive/cell/invoke.go:51 +0x38c
github.com/cilium/hive/cell.(*invoker).Apply.func1(0xc000987cc0?, 0x2844280?)
	/host/vendor/github.com/cilium/hive/cell/invoke.go:67 +0x28
github.com/cilium/hive.(*Hive).Populate(0xc000993a40, 0xc000548ad0)
	/host/vendor/github.com/cilium/hive/hive.go:316 +0x509
github.com/cilium/hive.(*Hive).Start(0xc000993a40, 0xc000548ad0, {0x328aee0, 0x526e7e0})
	/host/vendor/github.com/cilium/hive/hive.go:331 +0x57
github.com/cilium/cilium/pkg/dynamicconfig.fixture(0xc00033d6c0, {0x2f45b9e, 0x8e})
	/host/pkg/dynamicconfig/table_test.go:249 +0x312
github.com/cilium/cilium/pkg/dynamicconfig.TestWatchAllKeys(0xc00033d6c0)
	/host/pkg/dynamicconfig/table_test.go:45 +0x135
testing.tRunner(0xc00033d6c0, 0x2fe38b8)
	/root/sdk/go1.23.1/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/root/sdk/go1.23.1/src/testing/testing.go:1743 +0x390
FAIL	github.com/cilium/cilium/pkg/dynamicconfig	0.044s
```

https://github.com/cilium/cilium/actions/runs/11019174590/job/30601210627

[cilium-sysdumps.zip](https://github.com/user-attachments/files/17139359/cilium-sysdumps.zip)

**Comment by christarazi** [comment]
cc @ovidiutirla

**Comment by ovidiutirla** [comment]
Please rebase on main, a fix should already be in there. Also, there is some work ongoing to remove the panic for the unsupported job names and sanitize instead. Relevant: https://github.com/cilium/hive/pull/16

**Comment by chaunceyjiang** [comment]
https://github.com/cilium/cilium/pull/35009

**Comment by ovidiutirla** [comment]
We'll make the restriction more lenient, see the above PR in hive.
