### ISSUE TITLE
cilium-cli/connectivity: nil pointer dereference in `detectCiliumVersion`

### ISSUE THREAD

**Issue by DmitriyMV** [cilium/cilium#35800]
## Bug report

```
+ /drone/src/_out/cilium connectivity test --test-namespace cilium-test --external-target google.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x242ef5b]

goroutine 100 [running]:
github.com/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).detectCiliumVersion(0xc0003d8600, {0x39fb080?, 0xc000b8a800?})
	/cilium/connectivity/check/features.go:511 +0x37b
github.com/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0xc0003d8600, {0x39fb080, 0xc000b8a800?}, 0xc001031f98)
	/cilium/connectivity/check/context.go:275 +0xd2
github.com/cilium/cilium-cli/connectivity.Run({0x39fb080, 0xc000b8a800}, 0xc0003d8600, 0xc001031fb0, 0xc001021f98?)
	/cilium/connectivity/suite.go:174 +0x68
github.com/cilium/cilium-cli/internal/cli/cmd.newCmdConnectivityTest.func1.2()
	/cilium/internal/cli/cmd/connectivity.go:93 +0xe9
created by github.com/cilium/cilium-cli/internal/cli/cmd.newCmdConnectivityTest.func1
	/cilium/internal/cli/cmd/connectivity.go:91 +0x61d
```

**General Information**

cilium version: v0.15.2
kube: 1.28

**Comment by tklauser** [comment]
Thanks for the report and sorry for taking so long to address this. PR #35802 will fix this.
