### ISSUE TITLE
CI: Cilium E2E Upgrade - no-errors-in-logs - Cilium API handler panicked

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#36109]
## CI failure

- Hit three times in https://github.com/cilium/cilium/actions/runs/11958841576
- Sysdump: [cilium-sysdump-6-final.zip](https://github.com/user-attachments/files/17866835/cilium-sysdump-6-final.zip)

```
❌ Found 1 logs in kind-kind/kube-system/cilium-n8nvt (cilium-agent) matching list of errors that must be investigated:
time="2024-11-21T18:06:53.413851782Z" level=warning msg="Cilium API handler panicked" client=@ method=GET panic_message="write unix /var/run/cilium/cilium.sock->@: write: broken pipe" subsys=api url=/v1/healthz (1 occurrences)
```

**Comment by harsimran-pabla** [comment]
Adding full stack : 

```
2024-11-21T18:06:53.410544908Z time="2024-11-21T18:06:53.398401173Z" level=debug msg="Endpoint labels unchanged, skipping resolution of identity" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2265 identity=8 identityLabels="reserved:ingress" ipv4=10.244.0.201 ipv6="fd00:10:244::a5fc" k8sPodName=/ subsys=endpoint
2024-11-21T18:06:53.410656086Z time="2024-11-21T18:06:53.410591976Z" level=debug msg="Controller func execution time: 12.198196ms" name=resolve-identity-2265 subsys=controller uuid=6073640d-aa4b-48de-ab25-f19b6247dd9b
2024-11-21T18:06:53.410831913Z time="2024-11-21T18:06:53.39843317Z" level=debug msg="Wait time for proxy updates: 61.796µs" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2265 identity=8 ipv4=10.244.0.201 ipv6="fd00:10:244::a5fc" k8sPodName=/ subsys=endpoint
2024-11-21T18:06:53.411104010Z time="2024-11-21T18:06:53.411019793Z" level=debug msg="Controller func execution time: 112.76µs" name=daemon-validate-config subsys=controller uuid=095db3fd-78a9-4c2f-b6af-e249d4c9f5a0
2024-11-21T18:06:53.411316797Z time=2024-11-21T18:06:53Z level=debug msg="upserting health status" module=health lastLevel=none reporter-id=agent.controlplane.daemon. status="agent.controlplane.daemon.: [OK] daemon-validate-config"
2024-11-21T18:06:53.411635451Z time="2024-11-21T18:06:53.411550353Z" level=info msg="Processing 0 queued deletion requests" subsys=daemon
2024-11-21T18:06:53.411815867Z time="2024-11-21T18:06:53.411718365Z" level=info msg="Envoy: Waiting for endpoint restoration before serving xDS resources..." subsys=envoy-manager
2024-11-21T18:06:53.411994650Z time="2024-11-21T18:06:53.411916084Z" level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc008c90c80 Labels:[]}" subsys=daemon
2024-11-21T18:06:53.412162093Z time="2024-11-21T18:06:53.412061695Z" level=debug msg="Processing API request with rate limiter" name=endpoint-list parallelRequests=2 subsys=rate uuid=33c56f53-fb44-4c2f-9590-ba0c9d70a83b
2024-11-21T18:06:53.412327190Z time="2024-11-21T18:06:53.41225211Z" level=debug msg="API request released by rate limiter" burst=4 limit=1.00/s maxWaitDurationLimiter="-216.354µs" name=endpoint-list parallelRequests=2 subsys=rate uuid=33c56f53-fb44-4c2f-9590-ba0c9d70a83b waitDurationLimiter=0s waitDurationTotal="227.114µs"
2024-11-21T18:06:53.417757042Z time="2024-11-21T18:06:53.413851782Z" level=warning msg="Cilium API handler panicked" client=@ method=GET panic_message="write unix /var/run/cilium/cilium.sock->@: write: broken pipe" subsys=api url=/v1/healthz
2024-11-21T18:06:53.418379763Z time="2024-11-21T18:06:53.398417784Z" level=info msg="Cleaning up Cilium health endpoint" subsys=daemon
2024-11-21T18:06:53.418389030Z time="2024-11-21T18:06:53.418303668Z" level=debug msg="Didn't find existing cilium-health endpoint to delete" subsys=daemon
2024-11-21T18:06:53.418393919Z time="2024-11-21T18:06:53.418315841Z" level=debug msg="Killing old health endpoint process" pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-11-21T18:06:53.422639624Z time=2024-11-21T18:06:53Z level=debug msg="upserting health status" module=health lastLevel=none reporter-id=agent.controlplane.node-manager.neighbor-link-updater.kind-worker2 status="agent.controlplane.node-manager.neighbor-link-updater.kind-worker2: [OK] Node neighbor link update successful"
2024-11-21T18:06:53.422871636Z time="2024-11-21T18:06:53.422759146Z" level=debug msg="Controller func execution time: 26.320346ms" name=node-neighbor-link-updater subsys=controller uuid=4fd12eb2-854a-4272-a633-6b0c3f2adbd7
2024-11-21T18:06:53.423176986Z time="2024-11-21T18:06:53.4230831Z" level=debug msg="Didn't find existing device" error="Link not found" interface=cilium_health subsys=cilium-health-launcher
2024-11-21T18:06:53.423440637Z time="2024-11-21T18:06:53.423370947Z" level=debug msg="Didn't find existing device" error="Link not found" interface=lxc_health subsys=cilium-health-launcher
2024-11-21T18:06:53.430001828Z goroutine 1800 [running]:
2024-11-21T18:06:53.430014952Z runtime/debug.Stack()
2024-11-21T18:06:53.430058122Z  /usr/local/go/src/runtime/debug/stack.go:26 +0x5e
2024-11-21T18:06:53.430064604Z github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP.func1()
2024-11-21T18:06:53.430069263Z  /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:34 +0x2aa
2024-11-21T18:06:53.430074633Z panic({0x3fa3f80?, 0xc013b6e190?})
2024-11-21T18:06:53.430079061Z  /usr/local/go/src/runtime/panic.go:785 +0x132
2024-11-21T18:06:53.430083700Z github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthzOK).WriteResponse(0xc0128b0b60, {0x4d7d0a0, 0xc0042f23f0}, {0x4d33dc0, 0x48edcd0})
2024-11-21T18:06:53.430089190Z  /go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz_responses.go:59 +0x99
2024-11-21T18:06:53.430094370Z github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc000bbea00, {0x4d7d0a0, 0xc0042f23f0}, 0xc008752280, {0xc000cb2a00, 0x1, 0x1}, 0xc004081100, {0x3ed7220, 0xc0128b0b60})
2024-11-21T18:06:53.430111001Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/context.go:559 +0x6e3
2024-11-21T18:06:53.430116621Z github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetHealthz).ServeHTTP(0xc000bf64e0, {0x4d7d0a0, 0xc0042f23f0}, 0xc008752280)
2024-11-21T18:06:53.430121791Z  /go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_healthz.go:61 +0x1d9
2024-11-21T18:06:53.430126930Z github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1({0x4d7d0a0, 0xc0042f23f0}, 0xc008752280)
2024-11-21T18:06:53.430132300Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x53
2024-11-21T18:06:53.430137350Z net/http.HandlerFunc.ServeHTTP(0xc000bbea00?, {0x4d7d0a0?, 0xc0042f23f0?}, 0xc004b807d0?)
2024-11-21T18:06:53.430143080Z  /usr/local/go/src/net/http/server.go:2220 +0x29
2024-11-21T18:06:53.430148140Z github.com/go-openapi/runtime/middleware.NewRouter.func1({0x4d7d0a0, 0xc0042f23f0}, 0xc003285a40)
2024-11-21T18:06:53.430153159Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:80 +0x257
2024-11-21T18:06:53.430158188Z net/http.HandlerFunc.ServeHTTP(0xc00764ccc4?, {0x4d7d0a0?, 0xc0042f23f0?}, 0x2?)
2024-11-21T18:06:53.430163248Z  /usr/local/go/src/net/http/server.go:2220 +0x29
2024-11-21T18:06:53.430167646Z github.com/go-openapi/runtime/middleware.Redoc.serveUI.func1({0x4d7d0a0, 0xc0042f23f0}, 0xc003285a40)
2024-11-21T18:06:53.430172655Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/ui_options.go:164 +0xda
2024-11-21T18:06:53.430177424Z net/http.HandlerFunc.ServeHTTP(0xc00764ccc4?, {0x4d7d0a0?, 0xc0042f23f0?}, 0x0?)
2024-11-21T18:06:53.430182394Z  /usr/local/go/src/net/http/server.go:2220 +0x29
2024-11-21T18:06:53.430187654Z github.com/go-openapi/runtime/middleware.Spec.func1({0x4d7d0a0, 0xc0042f23f0}, 0xc003285a40)
2024-11-21T18:06:53.430193034Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:72 +0x1a8
2024-11-21T18:06:53.430197713Z net/http.HandlerFunc.ServeHTTP(0xc0040f1bc0?, {0x4d7d0a0?, 0xc0042f23f0?}, 0x3?)
2024-11-21T18:06:53.430202882Z  /usr/local/go/src/net/http/server.go:2220 +0x29
2024-11-21T18:06:53.430208242Z github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc0007025a0, {0x4d7cf80, 0xc002356e00}, 0xc003285a40)
2024-11-21T18:06:53.430213502Z  /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:63 +0x1d0
2024-11-21T18:06:53.430218391Z github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0xc0015b17a0?, {0x4d7cf80?, 0xc002356e00?}, 0x738096?)
2024-11-21T18:06:53.430223641Z  /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 +0x5b
2024-11-21T18:06:53.430228700Z net/http.(*ServeMux).ServeHTTP(0x46f519?, {0x4d7cf80, 0xc002356e00}, 0xc003285a40)
2024-11-21T18:06:53.430234050Z  /usr/local/go/src/net/http/server.go:2747 +0x1ca
2024-11-21T18:06:53.430239120Z net/http.serverHandler.ServeHTTP({0xc0050a6780?}, {0x4d7cf80?, 0xc002356e00?}, 0x6?)
2024-11-21T18:06:53.430244369Z  /usr/local/go/src/net/http/server.go:3210 +0x8e
2024-11-21T18:06:53.430248958Z net/http.(*conn).serve(0xc0040db440, {0x4d95ef8, 0xc009bc02a0})
2024-11-21T18:06:53.430253747Z  /usr/local/go/src/net/http/server.go:2092 +0x5d0
2024-11-21T18:06:53.430258426Z created by net/http.(*Server).Serve in goroutine 1436
2024-11-21T18:06:53.430263184Z  /usr/local/go/src/net/http/server.go:3360 +0x485
2024-11-21T18:06:53.430423343Z 2024/11/21 18:06:53 http: superfluous response.WriteHeader call from github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP.func1 (apipanic.go:36)
2024-11-21T18:06:53.430572311Z time="2024-11-21T18:06:53.430453079Z" level=debug msg="Failed to write API response" error="write unix /var/run/cilium/cilium.sock->@: write: broken pipe" subsys=api
```

**Comment by rectified95** [comment]
Another hit here: https://github.com/cilium/cilium/actions/runs/12057724243/job/33623000401

**Comment by tommyp1ckles** [comment]
Hit this here: https://github.com/cilium/cilium/actions/runs/12058381039/job/33625170135

**Comment by tommyp1ckles** [comment]
https://github.com/cilium/cilium/actions/runs/12058364499/job/33625083620 Couple more here.
