### ISSUE TITLE
CI: Workflow Telemetry - Integration Tests (ci-integration) / Integration Test (ubuntu-latest)

### ISSUE THREAD

**Issue by sypakine** [cilium/cilium#36244]
## CI failure

[Integration Test (ubuntu-latest)](https://github.com/cilium/cilium/actions/runs/12074224513/job/33671828479#logs)

https://github.com/cilium/cilium/actions/runs/12074224513/job/33671828479

```
logger.go:257: time=2024-11-28T19:02:08.186Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:342 msg=Started duration=77.865µs
fatal error: concurrent map read and map write

goroutine 18 [running]:
github.com/cilium/cilium/pkg/hive/health.Test_Metrics(0xc00021cea0)
	/home/runner/work/cilium/cilium/pkg/hive/health/metrics_test.go:110 +0xb4e
testing.tRunner(0xc00021cea0, 0xd86fa0)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1743 +0x390

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00021cd00, {0xd2aab0?, 0x0?}, 0xd86fa0)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1751 +0x3ab
testing.runTests.func1(0xc00021cd00)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:2168 +0x37
testing.tRunner(0xc00021cd00, 0xc0003efc70)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0xf4
testing.runTests(0xc000220558, {0x1383480, 0x2, 0x2}, {0x470ab0?, 0x47071a?, 0x1398800?})
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:2166 +0x43d
testing.(*M).Run(0xc00025f180)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:2034 +0x64a
main.main()
	_testmain.go:57 +0x9b

goroutine 22 [select]:
github.com/cilium/cilium/pkg/rate.NewLimiter.func1()
	/home/runner/work/cilium/cilium/pkg/rate/limiter.go:47 +0x93
created by github.com/cilium/cilium/pkg/rate.NewLimiter in goroutine 21
	/home/runner/work/cilium/cilium/pkg/rate/limiter.go:45 +0x[127](https://github.com/cilium/cilium/actions/runs/12074224513/job/33671828479#step:13:128)

goroutine 20 [select]:
github.com/cilium/statedb.graveyardWorker(0xc000220c30, {0xe57b08, 0xc000256d70}, 0x3b9aca00?)
	/home/runner/work/cilium/cilium/vendor/github.com/cilium/statedb/graveyard.go:25 +0x179
created by github.com/cilium/statedb.(*DB).Start in goroutine 18
	/home/runner/work/cilium/cilium/vendor/github.com/cilium/statedb/db.go:281 +0x165

goroutine 21 [select]:
github.com/cilium/cilium/pkg/hive/health.publishJob({0xe57ad0, 0xc0004e3b30}, {{{}}, 0xc000220c30, {0xe69db0, 0xc00025cc00}, {0xe57e18, 0xc000252cf0}, 0xc00023dc00}, 0xc000220ed0)
	/home/runner/work/cilium/cilium/pkg/hive/health/metrics.go:120 +0x37b
github.com/cilium/cilium/pkg/hive/health.Test_Metrics.func2.2({0xe57ad0?, 0xc0004e3b30?}, {0x7?, 0xfffffffffffffffc?})
	/home/runner/work/cilium/cilium/pkg/hive/health/metrics_test.go:59 +0x39
github.com/cilium/hive/job.(*jobOneShot).start(0xc0002019e0, {0xe57ad0, 0xc0004e3b30}, 0x0?, {0xe59be0, 0xc0002018c0}, {{{0x0, 0x0, 0x0}}, 0xc0004d3ad0, ...})
	/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/job/oneshot.go:[138](https://github.com/cilium/cilium/actions/runs/12074224513/job/33671828479#step:13:139) +0x503
created by github.com/cilium/hive/job.(*group).Start.func1 in goroutine 18
	/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:161 +0x174
```

[logs_31454747485.zip](https://github.com/user-attachments/files/17951802/logs_31454747485.zip)

**Comment by sypakine** [comment]
@ovidiutirla

**Comment by ovidiutirla** [comment]
hmm, nice catch, we'll have a look into it

**Comment by joestringer** [comment]
We should triage this before 1.17 in case this fatal error may occur in live environments.
