### ISSUE TITLE
CI: PANIC  package: github.com/cilium/cilium/operator/pkg/bgpv2 • Test_NodeLabels

### ISSUE THREAD

**Issue by bimmlerd** [cilium/cilium#36354]
## CI failure

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                        
┃   PANIC  package: github.com/cilium/cilium/operator/pkg/bgpv2 • Test_NodeLabels   ┃                        
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                        
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]                               
	panic: sync: WaitGroup is reused before previous Wait has returned                                           
                                                                                                             
goroutine 110 [running]:                                                                                     
testing.tRunner.func1.2({0x2e408e0, 0x3a45a70})                                                              
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1632 +0x230                                        
testing.tRunner.func1()                                                                                      
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1635 +0x35e                                        
panic({0x2e408e0?, 0x3a45a70?})                                                                              
	/opt/hostedtoolcache/go/1.23.3/x64/src/runtime/panic.go:785 +0x132                                           
sync.(*WaitGroup).Wait(0x3623747?)                                                                           
	/opt/hostedtoolcache/go/1.23.3/x64/src/sync/waitgroup.go:120 +0x74                                           
github.com/cilium/cilium/pkg/k8s/resource.(*resource[...]).Stop(0x0, {0xc00024bc08?, 0x4ec12f?})             
	/home/runner/work/cilium/cilium/pkg/k8s/resource/resource.go:404 +0xb0                                       
github.com/cilium/hive/cell.(*DefaultLifecycle).Stop(0xc000aebd40, 0xc0005d40f0, {0x3a8d550?, 0xc00060d5e0?})
	/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:166 +0x2e6                   
github.com/cilium/hive.(*Hive).Stop(0xc000a2b2c0, 0xc0005d40f0, {0x3a8d550, 0xc00060d5e0})                   
	/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:355 +0xd9                              
github.com/cilium/cilium/operator/pkg/bgpv2.Test_NodeLabels.func1(0xc00017c1a0)                              
	/home/runner/work/cilium/cilium/operator/pkg/bgpv2/cluster_test.go:300 +0x278                                
testing.tRunner(0xc00017c1a0, 0xc000ad45c0)                                                                  
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0xf4                                         
created by testing.(*T).Run in goroutine 19                                                                  
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1743 +0x390                                        
FAIL	github.com/cilium/cilium/operator/pkg/bgpv2	0.294s 
```

Reproduced locally:

```
$ stress -p 50 ./bgpv2.test -test.timeout=1m -test.run="NodeLabels"
4m45s: 19383 runs so far, 3 failures (0.02%)
```

I think this race is not specific to the test, I think it's a bug the releaseable resources. I think calling `resource.release` concurrently with `resource.Stop` has a chance of racing, since the release call can unblock a `startWhenNeeded` goroutine which then calls `r.wg.Add(1)` while the `Stop` is still in `r.wg.Wait()`.

**Comment by tklauser** [comment]
Reopening as this still occurs in CI, e.g. on #38126, see https://github.com/cilium/cilium/actions/runs/13857097921/job/38776261063
