### ISSUE TITLE
CI: nightly test failed in K8s1.8 upgrading from Cilium stable to master

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3657]
Relevant output: 

```
12:43:15 K8sValidatedUpdates 
12:43:15   Updating Cilium stable to master
12:43:15   /home/jenkins/workspace/Cilium-Master-Nightly-Tests-All/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:270
12:43:15 time="2018-04-11T12:43:10Z" level=info msg=Starting testName=K8sValidatedUpdates
12:43:15 time="2018-04-11T12:43:10Z" level=info msg="Vagrant: running command 'vagrant ssh-config k8s1-1.8'"
12:43:15 time="2018-04-11T12:43:11Z" level=debug msg="generated SSHConfig for node k8s1-1.8"
12:43:15 time="2018-04-11T12:43:11Z" level=debug msg="done importing ssh config"
12:43:15 time="2018-04-11T12:43:11Z" level=debug msg="running command: ls /tmp/"
12:43:15 time="2018-04-11T12:43:11Z" level=debug msg="running command: cat ${HOME}/.kube/config"
12:43:15 time="2018-04-11T12:43:11Z" level=debug msg="deleting /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.yaml" testName=K8sValidatedUpdates
12:43:15 time="2018-04-11T12:43:11Z" level=debug msg="running command: kubectl delete -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.yaml"
12:43:26 time="2018-04-11T12:43:25Z" level=debug msg="running command: kubectl delete --all pods,svc,cnp -n default"
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="running command: kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'"
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="running command: sudo docker rmi cilium/cilium"
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="deleting resource ds with name -n kube-system cilium" testName=K8sValidatedUpdates
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="running command: kubectl delete ds -n kube-system cilium"
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="applying /home/vagrant/go/src/github.com/cilium/cilium/test/cilium_ds_9acb0442.json" testName=K8sValidatedUpdates
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="running command: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/cilium_ds_9acb0442.json"
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="running command: kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=21.136256565s --previous"
12:43:32 time="2018-04-11T12:43:31Z" level=debug msg="running command: kubectl get pods -o wide"
12:43:32 time="2018-04-11T12:43:32Z" level=debug msg="running command: kubectl get cnp --all-namespaces -o json"
12:43:32 time="2018-04-11T12:43:32Z" level=debug msg="running command: kubectl describe pods --all-namespaces -o json"
12:43:32 time="2018-04-11T12:43:32Z" level=debug msg="running command: kubectl get replicationcontroller --all-namespaces -o json"
12:43:32 time="2018-04-11T12:43:32Z" level=debug msg="running command: kubectl get deployment --all-namespaces -o json"
12:43:32 time="2018-04-11T12:43:32Z" level=debug msg="running command: kubectl -n kube-system logs -l k8s-app=cilium --timestamps"
12:43:33 time="2018-04-11T12:43:32Z" level=debug msg="running command: kubectl get pods --all-namespaces -o json"
12:43:33 time="2018-04-11T12:43:33Z" level=debug msg="running command: kubectl get ds --all-namespaces -o json"
12:43:33 time="2018-04-11T12:43:33Z" level=debug msg="running command: kubectl get services --all-namespaces -o json"
12:43:33 time="2018-04-11T12:43:33Z" level=debug msg="running command: kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium | grep -qi -B 5 -A 5 deadlock"
12:43:33 time="2018-04-11T12:43:33Z" level=debug msg="running command: kubectl -n kube-system logs --timestamps=true --previous -l k8s-app=cilium | grep -qi -B 5 -A 5 deadlock"
12:43:33 time="2018-04-11T12:43:33Z" level=debug msg="deleting /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/l7_policy.yaml" testName=K8sValidatedUpdates
12:43:33 time="2018-04-11T12:43:33Z" level=debug msg="running command: kubectl delete -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/l7_policy.yaml"
12:43:34 time="2018-04-11T12:43:33Z" level=debug msg="deleting /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/l3_l4_policy.yaml" testName=K8sValidatedUpdates
12:43:34 time="2018-04-11T12:43:33Z" level=debug msg="running command: kubectl delete -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/l3_l4_policy.yaml"
12:43:34 time="2018-04-11T12:43:34Z" level=debug msg="deleting /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/demo.yaml" testName=K8sValidatedUpdates
12:43:34 time="2018-04-11T12:43:34Z" level=debug msg="running command: kubectl delete -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/demo.yaml"
12:43:34 time="2018-04-11T12:43:34Z" level=debug msg="deleting resource ds with name -n kube-system cilium" testName=K8sValidatedUpdates
12:43:34 time="2018-04-11T12:43:34Z" level=debug msg="running command: kubectl delete ds -n kube-system cilium"
12:43:43 time="2018-04-11T12:43:42Z" level=debug msg="running command: kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'"
12:43:43 
12:43:43 • Failure in Spec Setup (BeforeEach) [32.005 seconds]
12:43:43 K8sValidatedUpdates
12:43:43 /home/jenkins/workspace/Cilium-Master-Nightly-Tests-All/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:238
12:43:43   Updating Cilium stable to master [BeforeEach]
12:43:43   /home/jenkins/workspace/Cilium-Master-Nightly-Tests-All/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:270
12:43:43 
12:43:43   cannot apply cilium example daemonset
12:43:43   Expected
12:43:43       <bool>: false
12:43:43   to be true
12:43:43 
12:43:43   /home/jenkins/workspace/Cilium-Master-Nightly-Tests-All/src/github.com/cilium/cilium/test/helpers/utils.go:192
```

Build link: https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/173/execution/node/51/log/?consoleFull

**Comment by eloycoto** [comment]
Looks like that the `yaml` created didn't like to `kubectl`. Due #3656 I can't see the logs. Waiting for the PR to get merged and wait until fails again to check what happens. 

Trigger a new PR  https://github.com/cilium/cilium/pull/3685 with k8s-1.8 to know if it fails.

Regards

**Comment by nebril** [comment]
Another build: https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/173

**Comment by eloycoto** [comment]
@nebril is the same build

**Comment by rlenglet** [comment]
Saw this with K8s 1.7 as well: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2399/execution/node/59/log/

`kubectl apply` is terminating with a panic:
```
time="2018-04-14T08:52:00Z" level=debug msg="running command: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/cilium_ds_9acb0442.json"
cmd: "kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/cilium_ds_9acb0442.json" exitCode: 2 
 configmap "cilium-config" created
secret "cilium-etcd-secrets" created
daemonset "cilium" created
clusterrolebinding "cilium" created
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml.(*YAMLOrJSONDecoder).Decode(0xc421053610, 0x1f623a0, 0xc420d3aea0, 0x0, 0x0)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go:243 +0x373
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc42039fb80, 0xc4206b6f60, 0x2e5cfe0, 0xc4206b6fc0)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:531 +0x12e
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc4206b6da0, 0xc4206b6f60, 0x0, 0x0)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:501 +0x1a6
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc420373c40, 0x1, 0x1, 0xc420668270, 0x1, 0xc420668270)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:211 +0x100
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc4206b6e40, 0xc420668270, 0x7f95aed204b0, 0x0)
	<autogenerated>:115 +0x69
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2e59060, 0xc4206b6e40, 0xc42039fb40, 0xc42039fd00, 0xc4206b6f01, 0xc42039fd00)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:417 +0xa3
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc4206b6e60, 0xc42039fd00, 0x18, 0x18)
	<autogenerated>:130 +0x69
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2e590e0, 0xc4206b6e60, 0xc4206b6ea0, 0x3, 0x4, 0xc4206b6f20, 0x1, 0xc4206b6f20)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:325 +0xd8
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc4206681b0, 0xc4206b6f20, 0x40cce8, 0x1e72a60)
	<autogenerated>:151 +0x73
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x2e58fe0, 0xc4206681b0, 0xc420670a50, 0x7f95aed204b0, 0x0)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:352 +0xf1
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc420373c60, 0xc420670a50, 0x40f468, 0xb0)
	<autogenerated>:144 +0x60
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc420263880, 0xc420670a50, 0x0, 0xc420668240)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:96 +0x62
k8s.io/kubernetes/pkg/kubectl/cmd.RunApply(0x2e7e620, 0xc4207035f0, 0xc420486000, 0x2e58160, 0xc420066008, 0x2e58160, 0xc420066010, 0xc420250ae0, 0x208ca61, 0x4)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:339 +0x699
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdApply.func1(0xc420486000, 0xc4208bff20, 0x0, 0x2)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:108 +0x188
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420486000, 0xc4208bfdc0, 0x2, 0x2, 0xc420486000, 0xc4208bfdc0)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203a5680, 0x8000103, 0x0, 0xffffffffffffffff)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203a5680, 0xc4207035f0, 0x2e58120)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
	/workspace/anago-v1.7.15-beta.0.16+8c7c1c8b0ce086/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
```

**Comment by ianvernon** [comment]
@eloycoto any update on this? Been seeing this issue frequently in CI.

**Comment by ianvernon** [comment]
@eloycoto anything?

**Comment by eloycoto** [comment]
Close this one, related to https://github.com/cilium/cilium/issues/4329
