### ISSUE TITLE
Fatal Error in Cilium Agent due to Unexpected Return PC

### ISSUE THREAD

**Issue by warnerchen** [cilium/cilium#36741]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.14.17 and lower than v1.15.0

### What happened?

The Cilium Agent encountered a fatal error leading to a segmentation fault (SIGSEGV). The issue appears to be related to a stack corruption or an unexpected program counter (PC) return while executing the function prometheus.checkMetricConsistency. This occurred during garbage collection (GC) in the Go runtime. The error resulted in the following stack trace:
```log
runtime: g 9920: unexpected return pc for github.com/prometheus/client_golang/prometheus.checkMetricConsistency called from 0x7
fatal error: unknown caller pc
SIGSEGV: segmentation violation
```

### How can we reproduce the issue?

Still attempting to reproduce.

### Cilium Version

v1.15.5

### Kernel Version

5.15.0-118-generic

### Kubernetes Version

v1.24

### Relevant log output

```shell
runtime: g 9920: unexpected return pc for github.com/prometheus/client_golang/prometheus.checkMetricConsistency called from 0x7
stack: frame={sp:0xc0023f6fd0, fp:0xc0023f71e0} stack=[0xc0023f6000,0xc0023f8000)
0x000000c0023f6ed0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f6ee0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f6ef0:  0x0000000003214a20  0x0000000000000007 
0x000000c0023f6f00:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f6f10:  0x00000000039473cc  0x000000c001a244e0 
0x000000c0023f6f20:  0x0000000006068e20  0x0000000000000000 
0x000000c0023f6f30:  0x0000000003214a20  0x0000000006068e20 
0x000000c0023f6f40:  0x0000000000000000  0x0000000000000000 
0x000000c0023f6f50:  0x0000000000000000  0x0000000000000000 
0x000000c0023f6f60:  0x000000c0023f6fc0  0x00000000004533f8 <runtime.sigpanic+0x0000000000000378> 
0x000000c0023f6f70:  0x0000000003214a20  0x0000000006068e20 
0x000000c0023f6f80:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f6f90:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f6fa0:  0x000000c001a244e0  0x000000000000000a 
0x000000c0023f6fb0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f6fc0:  0x000000c0023f71d0  0x0000000000c1f714 <github.com/prometheus/client_golang/prometheus.checkMetricConsistency+0x0000000000000554> 
0x000000c0023f6fd0: <0x00000000039473cc  0x0000000000000007 
0x000000c0023f6fe0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f6ff0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7000:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7010:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7020:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7030:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7040:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7050:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7060:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7070:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7080:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7090:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f70a0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f70b0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f70c0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f70d0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f70e0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f70f0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7100:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7110:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7120:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7130:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7140:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7150:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7160:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7170:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7180:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7190:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f71a0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f71b0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f71c0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f71d0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f71e0: >0x0000000003952ba2  0x000000000000000a 
0x000000c0023f71f0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7200:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7210:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7220:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7230:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7240:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7250:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7260:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7270:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f7280:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f7290:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f72a0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f72b0:  0x00000000039473cc  0x0000000000000007 
0x000000c0023f72c0:  0x0000000003952ba2  0x000000000000000a 
0x000000c0023f72d0:  0x00000000039473cc  0x0000000000000007 
fatal error: unknown caller pc
SIGSEGV: segmentation violation
PC=0x4238bf m=21 sigcode=1

goroutine 0 [idle]:
runtime.gcDrain(0x0, 0xc000c848c0)
	/usr/local/go/src/runtime/mgcmark.go:1108 +0x1bf fp=0xc002345f78 sp=0xc002345f18 pc=0x4238bf

goroutine 12 [GC worker (active), 1 minutes]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc000617f50 sp=0xc000617f40 pc=0x470a88
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1355 +0x1f2 fp=0xc000617fe0 sp=0xc000617f50 pc=0x41fe72
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000617fe8 sp=0xc000617fe0 pc=0x4728e1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1219 +0x1c

goroutine 49944928 [???, locked to thread]:
runtime: g 49944928: unknown pc 0x3
stack: frame={sp:0x358e100, fp:0x0} stack=[0x70,0x60)

runtime: g 49944928: unknown pc 0x3
stack: frame={sp:0x358e100, fp:0x0} stack=[0x70,0x60)
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by warnerchen** [comment]
The issue has not reappeared for now, and we are unable to reproduce it. Close this issue, thx.
