### ISSUE TITLE
If an L4 policy is applied to an endpoint, then L7 policy is applied on top, then the L7 policy never becomes realized

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4181]
To replicate follow the instructions in http://cilium.readthedocs.io/en/latest/gettingstarted/minikube/

On http://cilium.readthedocs.io/en/latest/gettingstarted/minikube/#step-4-apply-an-l3-l4-policy the L7 policy is not enforced.

The L7 policy enforcement works if the l3_l4_l7 policy is deleted and then created.

Reported-by: @JrCs

**Comment by aanm** [comment]
Since the PR https://github.com/cilium/cilium/pull/4152 was merged, the e2e test needs to be revisited

**Comment by joestringer** [comment]
I attempted this using Cilium v1.0.3 and did not observe the issue:

```
$ k8s-cilium-exec.sh cilium version
Unable to use a TTY - input is not a terminal or the right kind of file
Client: 1.0.3 a2ebe00a5 2018-05-16T19:13:52+00:00 go version go1.9 linux/amd64
Daemon: 1.0.3 a2ebe00a5 2018-05-16T19:13:52+00:00 go version go1.9 linux/amd64
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl get pods                        
kubNAME                          READY     STATUS    RESTARTS   AGE                     
deathstar-76995f4687-6bgtw    1/1       Running   0          1m                                                                           
deathstar-76995f4687-xzsw9    1/1       Running   0          1m                                                       
etcd-cilium-0                 1/1       Running   2          3d                                                               
tiefighter-68c6cb4b4b-zz8mx   1/1       Running   0          1m                                                 
xwing-cc65988f5-bn8cj         1/1       Running   0          1m
```
```
$ kubectl exec xwing-cc65988f5-bn8cj -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing                              
^C
```
```
$ k8s-cilium-exec cilium policy get
Unable to use a TTY - input is not a terminal or the right kind of file
[                                       
  {                                         
    "endpointSelector": {                 
      "matchLabels": {                               
        "any:class": "deathstar",                  
        "any:org": "empire",                     
        "k8s:io.kubernetes.pod.namespace": "default"
      }                                                
    },                                                        
    "ingress": [                                       
      {                                                                        
        "fromEndpoints": [                                             
          {                                                                                                                                                                        
            "matchLabels": {                                                                                                                                                                
              "any:org": "empire",              
              "k8s:io.kubernetes.pod.namespace": "default"
            }                                                                                                             
          }                                                                                                                        
        ],                                                                                                                       
        "toPorts": [                                                                                                                            
          {                                              
            "ports": [                                       
              {                                                 
                "port": "80",                
                "protocol": "TCP"  
              }                                         
            ]                           
          }                                                                           
        ]                                
      }                                          
    ],                                                         
    "labels": [                               
      {                                        
        "key": "io.cilium.k8s.policy.name",      
        "value": "rule1",                                   
        "source": "unspec"                                                                                                                                                                                                      
      },                                                                           
      {                                               
        "key": "io.cilium.k8s.policy.namespace",                                                                 
        "value": "default",                              
        "source": "unspec"                                                                       
      }                                                                                                                                                                                                  
    ]                                                                                                                                                            
  }                                                                                                                                              
]                                                                                                  
Revision: 7
```
```
$ kubectl get cnp rule1 -o yaml                                                                                                                                                     
apiVersion: cilium.io/v2                                                            
kind: CiliumNetworkPolicy                   
metadata:                                                                                                         
  clusterName: ""                                                                            
  creationTimestamp: 2018-05-18T17:24:12Z                                                                                                                                                                
  generation: 0                                                                                                                                                  
  name: rule1                                                                                                
  namespace: default                                                       
  resourceVersion: "16584"                                                                                                 
  selfLink: /apis/cilium.io/v2/namespaces/default/ciliumnetworkpolicies/rule1
  uid: 48349465-5ac0-11e8-9206-080027a0bf67     
spec:                                                                
  endpointSelector:                                       
    matchLabels:                                                            
      any:class: deathstar                                                                                                                          
      any:org: empire                                                                                                                               
  ingress:                                                                                                                                          
  - fromEndpoints:                                                                                                                                  
    - matchLabels:                                                                                                                                  
        any:org: empire                                                                                                                             
    toPorts:                                                                                                                                        
    - ports:                                                                                                                                        
      - port: "80"                                                                                                                                  
        protocol: TCP                                                                                                                               
status:                                                                                                                                             
  nodes:                                                                                                                                            
    minikube:                                                                                                                                       
      enforcing: true                                                                                                                               
      lastUpdated: 2018-05-18T17:32:24.899495028Z                                                                                                   
      localPolicyRevision: 2
      ok: true
```
```
$ TIEFIGHTER=$(kubectl get pod | grep tie | sed 's/^\([^ ]*\).*/\1/g')
$ kubectl exec $TIEFIGHTER -- curl -s -XPUT deathstar.default.svc.cluster.local/v1/exhaust-port
Panic: deathstar exploded

goroutine 1 [running]:
main.HandleGarbage(0x2080c3f50, 0x2, 0x4, 0x425c0, 0x5, 0xa)
        /code/src/github.com/empire/deathstar/
        temp/main.go:9 +0x64
main.main()
        /code/src/github.com/empire/deathstar/
        temp/main.go:5 +0x85
```
```
$ kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/sw_l3_l4_l7_policy.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
ciliumnetworkpolicy.cilium.io "rule1" configured
```
```

kind: CiliumNetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cilium.io/v2","description":"L7 policy to restrict access to specific HTTP call","kind":"CiliumNetworkPolicy","metadata":{"annotations":{},"name":"rule1","namespace":"default"},"spec":{"endpointSelector":{"matchLabels":{"class":"deathstar","org":"empire"}},"ingress":[{"fromEndpoints":[{"matchLabels":{"org":"empire"}}],"toPorts":[{"ports":[{"port":"80","protocol":"TCP"}],"rules":{"http":[{"method":"POST","path":"/v1/request-landing"}]}}]}]}}
  clusterName: ""
  creationTimestamp: 2018-05-18T17:24:12Z
  generation: 0
  name: rule1
  namespace: default
  resourceVersion: "17233"
  selfLink: /apis/cilium.io/v2/namespaces/default/ciliumnetworkpolicies/rule1
  uid: 48349465-5ac0-11e8-9206-080027a0bf67
spec:
  endpointSelector:
    matchLabels:
      any:class: deathstar
      any:org: empire
  ingress:
  - fromEndpoints:
    - matchLabels:
        any:org: empire
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: POST
          path: /v1/request-landing
status:
  nodes:
    minikube:
      enforcing: true
      lastUpdated: 2018-05-18T17:41:46.513668378Z
      localPolicyRevision: 9
      ok: true
```
```
$ k8s-cilium-exec cilium policy get
Unable to use a TTY - input is not a terminal or the right kind of file
[
  {
    "endpointSelector": {
      "matchLabels": {
        "any:class": "deathstar",
        "any:org": "empire",
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:org": "empire",
              "k8s:io.kubernetes.pod.namespace": "default"
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "80",
                "protocol": "TCP"
              }
            ],
            "rules": {
              "http": [
                {
                  "path": "/v1/request-landing",
                  "method": "POST"
                }
              ]
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "rule1",
        "source": "unspec"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "default",
        "source": "unspec"
      }
    ]
  }
]
Revision: 9
```
```
$ kubectl exec $TIEFIGHTER -- curl -s -XPUT deathstar.default.svc.cluster.local/v1/exhaust-port
Access denied
```
```
$ kubectl exec $TIEFIGHTER -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing
Ship landed
```

**Comment by joestringer** [comment]
Reproduced with `latest` tag.

**Comment by joestringer** [comment]
From one of the deathstar endpoints, the `spec` for policy is different from the `realized`:

```
        "realized": {
          "allowed-egress-identities": [
            41845,
            49774,
            31638,
            2,
            1,
            3,
            4,
            34384
          ],
          "allowed-ingress-identities": [
            1
          ],
          "build": 12,
          "cidr-policy": {
            "egress": [],
            "ingress": []
          },
          "id": 41845,
          "l4": {
            "egress": [],
            "ingress": [
              {
                "derived-from-rules": [
                  [
                    "unspec:io.cilium.k8s.policy.name=rule1",
                    "unspec:io.cilium.k8s.policy.namespace=default"
                  ]
                ],
                "rule": {
                  "port": 80,
                  "protocol": "TCP"
                }
              }
            ]
          },
          "policy-enabled": "ingress",
          "policy-revision": 12
        },
        "spec": {
          "allowed-egress-identities": [
            49774,
            41845,
            1,
            2,
            4,
            3,
            34384,
            31638
          ],
          "allowed-ingress-identities": [
            1
          ],
          "build": 12,
          "cidr-policy": {
            "egress": [],
            "ingress": []
          },
          "id": 41845,
          "l4": {
            "egress": [],
            "ingress": [
              {
                "derived-from-rules": [
                  [
                    "unspec:io.cilium.k8s.policy.name=rule1",
                    "unspec:io.cilium.k8s.policy.namespace=default"
                  ]
                ],
                "rule": {
                  "l7-rules": [
                    {
                      "any.org=empire,k8s.io.kubernetes.pod.namespace=default": {
                        "http": [
                          {
                            "method": "POST",
                            "path": "/v1/request-landing"
                          }
                        ]
                      }
                    }
                  ],
                  "port": 80,
                  "protocol": "TCP"
                }
              }
            ]
          },
          "policy-enabled": "ingress",
          "policy-revision": 12
        }
```

However the endpoint log suggests that it thinks policy doesn't need to be regenerated:

```
$ k8s-cilium-exec cilium endpoint log 13949
Unable to use a TTY - input is not a terminal or the right kind of file
Timestamp              Status    State                   Message
2018-05-18T18:06:49Z   OK        ready                   Endpoint policy update skipped because no changes were needed
2018-05-18T18:01:49Z   OK        ready                   Endpoint policy update skipped because no changes were needed
2018-05-18T17:56:49Z   OK        ready                   Endpoint policy update skipped because no changes were needed
2018-05-18T17:54:48Z   OK        ready                   Endpoint policy update skipped because no changes were needed
2018-05-18T17:54:48Z   OK        ready                   Endpoint policy update skipped because no changes were needed
2018-05-18T17:53:09Z   OK        ready                   Successfully regenerated endpoint program due to endpoint policy updated & changes were needed
2018-05-18T17:53:09Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2018-05-18T17:53:08Z   OK        regenerating            Regenerating Endpoint BPF: endpoint policy updated & changes were needed
2018-05-18T17:53:08Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to policy updates
2018-05-18T17:52:50Z   OK        ready                   Successfully regenerated endpoint program due to endpoint policy updated & changes were needed
2018-05-18T17:52:50Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2018-05-18T17:52:49Z   OK        regenerating            Regenerating Endpoint BPF: endpoint policy updated & changes were needed
2018-05-18T17:52:49Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to policy updates
2018-05-18T17:51:49Z   OK        ready                   Endpoint policy update skipped because no changes were needed
2018-05-18T17:51:45Z   OK        ready                   Successfully regenerated endpoint program due to endpoint policy updated & changes were needed
2018-05-18T17:51:45Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2018-05-18T17:51:44Z   OK        regenerating            Regenerating Endpoint BPF: endpoint policy updated & changes were needed
2018-05-18T17:51:44Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to policy updates
2018-05-18T17:51:42Z   OK        ready                   Successfully regenerated endpoint program due to syncing state to host
2018-05-18T17:51:42Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2018-05-18T17:51:40Z   OK        regenerating            Regenerating Endpoint BPF: syncing state to host
2018-05-18T17:51:40Z   OK        waiting-to-regenerate   Triggering synchronous endpoint regeneration while syncing state to host
2018-05-18T17:51:40Z   OK        restoring               Synchronizing endpoint labels with KVStore
2018-05-18T17:51:40Z   OK        restoring               Restoring endpoint from previous cilium instance
```

For reference, the L7 policy was applied at `May 18 10:54:39 PDT`, which would be `17:54:39` UTC (log TZ)

**Comment by joestringer** [comment]
This is the entirety of the Cilium logs for the period when the `kubectl apply` put the L7 policy in place:
```
2018-05-18T17:54:48.58355308Z level=info msg="Deleted CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 k8sApiVersion= k8sNamespace=default
2018-05-18T17:54:48.583604414Z level=info msg="Policy imported via API, recalculating..." policyRevision=10
2018-05-18T17:54:48.583613554Z level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 k8sApiVersion= k8sNamespace=default
```
