### ISSUE TITLE
nil pointer dereference in cilium 1.0.4 after running master

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4899]
One of my PRs got a test failure, the PR itself is not changing any fundamental things. https://github.com/cilium/cilium/pull/4877

Unfortunately it got a panic on the cilium to master upgrade test.

```
2018-07-19T00:00:47.763062707Z panic: runtime error: invalid memory address or nil pointer dereference

2018-07-19T00:00:47.763095759Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8781eb]
2018-07-19T00:00:47.763100173Z 
2018-07-19T00:00:47.763103458Z goroutine 126 [running]:
2018-07-19T00:00:47.763107129Z github.com/cilium/cilium/pkg/option.(*BoolOptions).IsEnabled(0x0, 0x1dd2cc6, 0x5, 0x0)
2018-07-19T00:00:47.763109916Z 	/go/src/github.com/cilium/cilium/pkg/option/option.go:172 +0x2b
2018-07-19T00:00:47.763114334Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).updateLogger(0xc421731900)
2018-07-19T00:00:47.763118656Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/log.go:56 +0x752
2018-07-19T00:00:47.763123166Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).getLogger(0xc421731900, 0xc42162b400)
2018-07-19T00:00:47.763127455Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/log.go:30 +0x2b
2018-07-19T00:00:47.763131664Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).logStatusLocked(0xc421731900, 0x0, 0x0, 0x1dee783, 0x10)
2018-07-19T00:00:47.763136104Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1543 +0x1b8
2018-07-19T00:00:47.763139429Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).SetStateLocked(0xc421731900, 0x1de5043, 0xc, 0x1dee783, 0x10, 0xc4214ed0e0)
2018-07-19T00:00:47.763142624Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1989 +0x134
2018-07-19T00:00:47.763145327Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).LeaveLocked(0xc421731900, 0x2e11980, 0xc420461c00, 0x2e05940, 0xc4201b1c80, 0xc4214ed070)
2018-07-19T00:00:47.763168508Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1763 +0x16d
2018-07-19T00:00:47.763173399Z main.(*Daemon).deleteEndpointQuiet(0xc420461c00, 0xc421731900, 0x45, 0xc4214abf80, 0x1)
2018-07-19T00:00:47.76317751Z 	/go/src/github.com/cilium/cilium/daemon/endpoint.go:433 +0x33b
2018-07-19T00:00:47.763180687Z main.(*Daemon).SyncState.func1(0xc421615101, 0xc420461c00, 0xc421731900, 0xc421615110, 0xc421615180)
2018-07-19T00:00:47.763183568Z 	/go/src/github.com/cilium/cilium/daemon/state.go:79 +0xa4e
2018-07-19T00:00:47.763186577Z created by main.(*Daemon).SyncState
2018-07-19T00:00:47.763190022Z 	/go/src/github.com/cilium/cilium/daemon/state.go:67 +0x1e4
```

Cilium revision 228c4e597d0e75f447c593bd2098501b8128ff23

This might have been introduced by recent changes in https://github.com/cilium/cilium/pull/4828

[test_results_Cilium-PR-Ginkgo-Tests-Validated_5084_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/2210039/test_results_Cilium-PR-Ginkgo-Tests-Validated_5084_BDD-Test-PR.zip)

**Comment by tgraf** [comment]
@aanm The title says 1.0.4, #4828 is only in 1.2/master. Can you confirm version?

**Comment by aanm** [comment]
@tgraf that is the problem, `1.0.4` was unable to start because of changes made in master, by #4828. When starting `1.0.4` the health endpoint from `latest` was still in place and `1.0.4` tried to restore it, since there isn't a container for the health endpoint, the restore functionality deletes the endpoint and while doing it cilium crashed.

**Comment by joestringer** [comment]
OK, I guess we need to do the thing where we serialize as many options as we can to the old `Opts` field in the JSON so that these older versions can read a config that makes sense, rather than just leaving that field out. I'll work on it.
