### ISSUE TITLE
Failed to start container: Invalid IPv4 Address

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4939]
Running #4936 PR (almost exclusively datapath changes), I've observed in local testing that Cilium IPAM gets into a bad state and hands out garbage IP addresses to the CNI plugin:

```
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012e1
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012ac
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?126200001322
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012b2
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012c3
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?12620000127e
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?126200001301
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012ce
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?126200001313
```

Running the k8s tests locally:
```
• [SLOW TEST:114.726 seconds]
K8sValidatedPolicyTest
/home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
  Namespaces policies
  /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
    Tests the same Policy in different namespaces
    /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
------------------------------
K8sValidatedPolicyTest Namespaces policies
  Kubernetes Network Policy by namespace selector
  /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
STEP: Testing connectivity across Namespaces without policy
STEP: Applying Policy in "second" namespace
STEP: Delete Kubernetes Network Policies in "second" namespace
=== Test Finished at 2018-07-20T18:01:21-07:00====
<Checks>
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0

</Checks>


• [SLOW TEST:102.548 seconds]
K8sValidatedPolicyTest
/home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
  Namespaces policies
  /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
    Kubernetes Network Policy by namespace selector
    /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
------------------------------
K8sValidatedPolicyTest Namespaces policies
  Cilium Network policy using namespace label and L7
  /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376

---
K8sValidatedPolicyTest Namespaces policies Cilium Network policy using namespace label and L7
at /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376

Microscope cannot be started
Expected
    <*errors.errorString | 0xc4201ef850>: {
        s: "Timeout reached: could not get Pods",
    }
to be nil
```

```
vagrant@k8s1:~$ kubectl describe po -n kube-system microscope
Name:         microscope
Namespace:    kube-system
Node:         k8s2/192.168.36.12
Start Time:   Sat, 21 Jul 2018 01:02:11 +0000
Labels:       k8s-app=microscope
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"k8s-app":"microscope"},"name":"microscope","namespace":"kube-system"},"spec":{"...
Status:       Pending
IP:                                   
Containers:           
  microscope:         
    Container ID:     
    Image:         docker.io/cilium/microscope:1.0.1
    Image ID:                                                 
    Port:          <none>                               
    Host Port:     <none>
    Args:                 
      sleep
      100000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from microscope-token-h7pjz (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  microscope-token-h7pjz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  microscope-token-h7pjz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Normal   SuccessfulMountVolume   11m                 kubelet, k8s2      MountVolume.SetUp succeeded for volume "microscope-token-h7pjz"
  Normal   Scheduled               11m                 default-scheduler  Successfully assigned microscope to k8s2
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012e1
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012ac
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?126200001322
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012b2
  Warning  FailedCreatePodSandBox  11m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012c3
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?12620000127e
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?126200001301
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?1262000012ce
  Warning  FailedCreatePodSandBox  10m                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?126200001313
  Warning  FailedCreatePodSandBox  10m (x3 over 10m)   kubelet, k8s2      (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "microscope_kube-system" network: Invalid IPv4 address: ?12620000135e
  Normal   SandboxChanged          1m (x280 over 11m)  kubelet, k8s2      Pod sandbox changed, it will be killed and re-created.
```

**Comment by joestringer** [comment]
Seen also in Cilium logs:
```
2018-07-21T01:12:03.668929759Z panic: runtime error: invalid memory address or nil pointer dereference
2018-07-21T01:12:03.668957319Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15998f5]
2018-07-21T01:12:03.66896198Z 
2018-07-21T01:12:03.668965304Z goroutine 234511 [running]:
2018-07-21T01:12:03.668968102Z github.com/cilium/cilium/pkg/labels.Labels.DeleteMarked(0xc421a8a570, 0x279ce4d)
2018-07-21T01:12:03.668971088Z  /go/src/github.com/cilium/cilium/pkg/labels/labels.go:232 +0xe5
2018-07-21T01:12:03.668974123Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).replaceInformationLabels(0xc420503680, 0xc4255fe180)
2018-07-21T01:12:03.668977164Z  /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1686 +0x3ce
2018-07-21T01:12:03.668980094Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).UpdateLabels(0xc420503680, 0x29be940, 0xc4222b9e60, 0xc4255fe150, 0xc4255fe180)
2018-07-21T01:12:03.66898313Z   /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2269 +0x3ef
2018-07-21T01:12:03.668998005Z github.com/cilium/cilium/pkg/workloads.(*dockerClient).handleCreateWorkload(0xc42000e988, 0xc4247d32c0, 0x40, 0xc423561700)
2018-07-21T01:12:03.669001718Z  /go/src/github.com/cilium/cilium/pkg/workloads/docker.go:477 +0x8b2
2018-07-21T01:12:03.669736397Z created by github.com/cilium/cilium/pkg/workloads.(*watcherState).syncWithRuntime.func1
2018-07-21T01:12:03.669753793Z  /go/src/github.com/cilium/cilium/pkg/workloads/watcher_state.go:133 +0xb5
2018-07-21T01:12:03.694090351Z level=fatal msg="Agent pipe unexpectedly closed, shutting down"
```

**Comment by joestringer** [comment]
Duplicate of #4886, see that issue for resolution.
