### ISSUE TITLE
CI failure: Allows traffic with k8s default-allow egress policy failed

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4971]
Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1279/testReport/junit/k8s-1/11/K8sValidatedPolicyTest_Basic_Test_Allows_traffic_with_k8s_default_allow_egress_policy/

Output:
```
Stacktrace

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Egress connectivity should be allowed for pod "app2-56fbc4b964-bh9qc"
Expected command: kubectl exec -n default app2-56fbc4b964-bh9qc -- curl -s --output /dev/stderr -w '%{http_code}' --connect-timeout 3 http://www.google.com/ 
To succeed, but it failed:
Exitcode: 7 
Stdout:
 	 000
Stderr:
 	 command terminated with exit code 7
	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Policies.go:593
Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: [cilium-8vm7m cilium-pc77n]
Netpols loaded: default::allow-all-egress 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     app1-5d79fbc474-cdb2r              =>   egress
     app1-5d79fbc474-mftbp              =>   egress
     cilium-health-k8s1                 =>   none
     prometheus-core-6546477dc8-csbnq   =>   none
     app2-56fbc4b964-bh9qc              =>   egress
     app3-5d9895d6ff-pww2k              =>   egress
     cilium-health-k8s2                 =>   none
     coredns-b9476b976-5g8hp            =>   none
     coredns-b9476b976-vzdpn            =>   none
Cilium agent "cilium-8vm7m": Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 31 Failed 0
Cilium agent "cilium-pc77n": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 44 Failed 0

Standard Error

STEP: Installing egress default-allow
STEP: Checking that all endpoints have egress enforcement enabled
STEP: Checking connectivity between pods and external services after installing egress policy
=== Test Finished at 2018-07-24T07:43:25Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE       IP              NODE
default       app1-5d79fbc474-cdb2r              1/1       Running   0          16m       10.10.0.237     k8s1
default       app1-5d79fbc474-mftbp              1/1       Running   0          16m       10.10.0.249     k8s1
default       app2-56fbc4b964-bh9qc              1/1       Running   0          16m       10.10.0.1       k8s1
default       app3-5d9895d6ff-pww2k              1/1       Running   0          16m       10.10.0.31      k8s1
kube-system   cilium-8vm7m                       1/1       Running   0          19m       192.168.36.12   k8s2
kube-system   cilium-pc77n                       1/1       Running   0          19m       192.168.36.11   k8s1
kube-system   coredns-b9476b976-5g8hp            1/1       Running   0          22m       10.10.1.32      k8s2
kube-system   coredns-b9476b976-vzdpn            1/1       Running   0          22m       10.10.0.193     k8s1
kube-system   etcd-k8s1                          1/1       Running   0          55m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                1/1       Running   0          55m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1       1/1       Running   0          55m       192.168.36.11   k8s1
kube-system   kube-proxy-9zfbp                   1/1       Running   0          49m       192.168.36.12   k8s2
kube-system   kube-proxy-src29                   1/1       Running   0          56m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                1/1       Running   0          55m       192.168.36.11   k8s1
prometheus    prometheus-core-6546477dc8-csbnq   1/1       Running   0          49m       10.10.1.93      k8s2

cmd: kubectl exec -n kube-system cilium-8vm7m -- cilium service list
ID   Frontend             Backend                   
1    10.110.86.208:9090   1 => 10.10.1.93:9090      
2    10.96.0.1:443        1 => 192.168.36.11:6443   
3    10.96.0.10:53        1 => 10.10.0.193:53       
                          2 => 10.10.1.32:53        
5    10.100.67.213:80     1 => 10.10.0.237:80       
                          2 => 10.10.0.249:80       

cmd: kubectl exec -n kube-system cilium-8vm7m -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                   IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                               
13949      Disabled           Disabled          45254      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:100:0:367d   10.10.1.32   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                          
                                                           k8s:k8s-app=kube-dns                                                                                 
16106      Disabled           Disabled          4          reserved:health                                          f00d::a0a:100:0:3eea   10.10.1.90   ready   
32937      Disabled           Disabled          53167      k8s:app=prometheus                                       f00d::a0a:100:0:80a9   10.10.1.93   ready   
                                                           k8s:component=core                                                                                   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                               
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                           

cmd: kubectl exec -n kube-system cilium-pc77n -- cilium service list
ID   Frontend             Backend                   
1    10.110.86.208:9090   1 => 10.10.1.93:9090      
2    10.96.0.1:443        1 => 192.168.36.11:6443   
3    10.96.0.10:53        1 => 10.10.0.193:53       
                          2 => 10.10.1.32:53        
5    10.100.67.213:80     1 => 10.10.0.237:80       
                          2 => 10.10.0.249:80       

cmd: kubectl exec -n kube-system cilium-pc77n -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                            
6099       Disabled           Enabled           42967      k8s:id=app1                                            f00d::a0a:0:0:17d3   10.10.0.249   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:zgroup=testapp                                                                                
29111      Disabled           Disabled          4          reserved:health                                        f00d::a0a:0:0:71b7   10.10.0.182   ready   
30230      Disabled           Enabled           3073       k8s:id=app3                                            f00d::a0a:0:0:7616   10.10.0.31    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:zgroup=testapp                                                                                
39712      Disabled           Enabled           18538      k8s:appSecond=true                                     f00d::a0a:0:0:9b20   10.10.0.1     ready   
                                                           k8s:id=app2                                                                                       
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:zgroup=testapp                                                                                
54779      Disabled           Enabled           42967      k8s:id=app1                                            f00d::a0a:0:0:d5fb   10.10.0.237   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                           
                                                           k8s:zgroup=testapp                                                                                
60670      Disabled           Disabled          45254      k8s:io.cilium.k8s.policy.serviceaccount=coredns        f00d::a0a:0:0:ecfe   10.10.0.193   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                       
                                                           k8s:k8s-app=kube-dns 
```

Logs: 
[aa209b8e_K8sValidatedPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip](https://github.com/cilium/cilium/files/2224793/aa209b8e_K8sValidatedPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip)

**Comment by ianvernon** [comment]
Another failure occurred.

Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1281/testReport/junit/k8s-1/11/K8sValidatedPolicyTest_Basic_Test_Allows_traffic_with_k8s_default_allow_egress_policy/

Output: 
```
Stacktrace

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Egress connectivity should be allowed for pod "app2-56fbc4b964-qkkfj"
Expected command: kubectl exec -n default app2-56fbc4b964-qkkfj -- curl -s --output /dev/stderr -w '%{http_code}' --connect-timeout 3 http://www.google.com/ 
To succeed, but it failed:
Exitcode: 7 
Stdout:
 	 000��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
Stderr:
 	 command terminated with exit code 7
	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Policies.go:593
Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: [cilium-8kvt7 cilium-bs2xj]
Netpols loaded: default::allow-all-egress 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     app2-56fbc4b964-qkkfj              =>   egress
     app3-5d9895d6ff-665m5              =>   egress
     cilium-health-k8s2                 =>   
     coredns-b9476b976-nltkl            =>   none
     coredns-b9476b976-z9v88            =>   none
     prometheus-core-6546477dc8-b7gx4   =>   none
     app1-5d79fbc474-78w98              =>   egress
     app1-5d79fbc474-jqr8v              =>   egress
Cilium agent "cilium-8kvt7": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 49 Failed 0
Cilium agent "cilium-bs2xj": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 26 Failed 0

Standard Error

STEP: Installing egress default-allow
STEP: Checking that all endpoints have egress enforcement enabled
STEP: Checking connectivity between pods and external services after installing egress policy
=== Test Finished at 2018-07-24T17:37:47Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE       IP              NODE
default       app1-5d79fbc474-78w98              1/1       Running   0          15m       10.10.0.139     k8s1
default       app1-5d79fbc474-jqr8v              1/1       Running   0          15m       10.10.0.226     k8s1
default       app2-56fbc4b964-qkkfj              1/1       Running   0          15m       10.10.0.1       k8s1
default       app3-5d9895d6ff-665m5              1/1       Running   0          15m       10.10.0.99      k8s1
kube-system   cilium-8kvt7                       1/1       Running   0          16m       192.168.36.11   k8s1
kube-system   cilium-bs2xj                       1/1       Running   0          16m       192.168.36.12   k8s2
kube-system   coredns-b9476b976-nltkl            1/1       Running   0          19m       10.10.1.32      k8s2
kube-system   coredns-b9476b976-z9v88            1/1       Running   0          19m       10.10.0.193     k8s1
kube-system   etcd-k8s1                          1/1       Running   0          1h        192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                1/1       Running   0          1h        192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1       1/1       Running   0          1h        192.168.36.11   k8s1
kube-system   kube-proxy-pxqq9                   1/1       Running   0          1h        192.168.36.11   k8s1
kube-system   kube-proxy-qztqn                   1/1       Running   0          55m       192.168.36.12   k8s2
kube-system   kube-scheduler-k8s1                1/1       Running   0          1h        192.168.36.11   k8s1
prometheus    prometheus-core-6546477dc8-b7gx4   1/1       Running   0          55m       10.10.0.216     k8s1

cmd: kubectl exec -n kube-system cilium-8kvt7 -- cilium service list
ID   Frontend             Backend                   
1    10.102.206.37:9090   1 => 10.10.0.216:9090     
2    10.96.0.1:443        1 => 192.168.36.11:6443   
3    10.96.0.10:53        1 => 10.10.0.193:53       
                          2 => 10.10.1.32:53        
4    10.98.236.209:80     1 => 10.10.0.139:80       
                          2 => 10.10.0.226:80       

cmd: kubectl exec -n kube-system cilium-8kvt7 -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                              
30392      Disabled           Enabled           56785      k8s:id=app1                                              f00d::a0a:0:0:76b8   10.10.0.139   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
35645      Disabled           Disabled          64751      k8s:app=prometheus                                       f00d::a0a:0:0:8b3d   10.10.0.216   ready   
                                                           k8s:component=core                                                                                  
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                              
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                          
49245      Disabled           Enabled           45047      k8s:id=app3                                              f00d::a0a:0:0:c05d   10.10.0.99    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                     
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
52676      Disabled           Enabled           34776      k8s:appSecond=true                                       f00d::a0a:0:0:cdc4   10.10.0.1     ready   
                                                           k8s:id=app2                                                                                         
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
60558      Disabled           Enabled           56785      k8s:id=app1                                              f00d::a0a:0:0:ec8e   10.10.0.226   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
60670      Disabled           Disabled          11977      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:0:0:ecfe   10.10.0.193   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                         
                                                           k8s:k8s-app=kube-dns                                                                                
61011      Disabled           Disabled          4          reserved:health                                          f00d::a0a:0:0:ee53   10.10.0.161   ready   

cmd: kubectl exec -n kube-system cilium-bs2xj -- cilium service list
ID   Frontend             Backend                   
1    10.102.206.37:9090   1 => 10.10.0.216:9090     
2    10.96.0.1:443        1 => 192.168.36.11:6443   
3    10.96.0.10:53        1 => 10.10.0.193:53       
                          2 => 10.10.1.32:53        
4    10.98.236.209:80     1 => 10.10.0.139:80       
                          2 => 10.10.0.226:80       

cmd: kubectl exec -n kube-system cilium-bs2xj -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                         
13949      Disabled           Disabled          11977      k8s:io.cilium.k8s.policy.serviceaccount=coredns   f00d::a0a:100:0:367d   10.10.1.32    ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                    
                                                           k8s:k8s-app=kube-dns                                                                           
34829      Disabled           Disabled          4          reserved:health                                   f00d::a0a:100:0:880d   10.10.1.222   ready   

```

Logs: 
[700e0976_K8sValidatedPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip](https://github.com/cilium/cilium/files/2224813/700e0976_K8sValidatedPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip)

**Comment by ianvernon** [comment]
Triaging:
https://github.com/cilium/cilium/issues/4971#issue-344144775

app2 has endpoint ID 52676 in pod `cilium-8kvt7`.


#### BPF Policy Get 39712

```
DIRECTION   LABELS (source:key[=value])                              PORT/PROTO   PROXY PORT   BYTES   PACKETS   
...                                                                                                                                                                
Egress      reserved:world                                           ANY          NONE         336     4
...
```

The PolicyMap entry shows that packets are indeed going out to the world on egress, so the plumbed policy is OK.

This means that there could be an issue with the datapath itself. Unfortunately, because of #4879 , we have no visibility into the datapath; the contents of `monitor.log` are the following:

```
[2018-07-24 07:43:04] 
[2018-07-24 07:43:04] closing
[2018-07-24 07:43:04] Traceback (most recent call last):
[2018-07-24 07:43:04]   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[2018-07-24 07:43:04]     "__main__", mod_spec)
[2018-07-24 07:43:04]   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
[2018-07-24 07:43:04]     exec(code, run_globals)
[2018-07-24 07:43:04]   File "/bin/microscope/__main__.py", line 153, in <module>
[2018-07-24 07:43:04]   File "/bin/microscope/__main__.py", line 138, in main
[2018-07-24 07:43:04]   File "/bin/microscope/microscope/monitor/runner.py", line 98, in run
[2018-07-24 07:43:04]   File "/bin/microscope/microscope/monitor/runner.py", line 205, in retrieve_endpoint_data
[2018-07-24 07:43:04]   File "/bin/microscope/microscope/monitor/runner.py", line 205, in <listcomp>
[2018-07-24 07:43:04] KeyError: 'status'
command terminated with exit code 1
```

**Comment by ianvernon** [comment]
Another similar failure occurred in a recent build.

Link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3449/testReport/k8s-1/11/K8sPolicyTest_Basic_Test_Allows_traffic_with_k8s_default_allow_egress_policy/

Output:
```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Egress connectivity should be allowed for pod "app2-56fbc4b964-f2ncg"
Expected command: kubectl exec -n default app2-56fbc4b964-f2ncg -- curl -s --output /dev/stderr -w '%{http_code}' --connect-timeout 3 http://www.google.com/ 
To succeed, but it failed:
Exitcode: 7 
Stdout:
 	 000
Stderr:
 	 command terminated with exit code 7
	 

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/Policies.go:590
Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: [cilium-64lwq cilium-wmn4q]
Netpols loaded: default::knp-default-allow-egress 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     coredns-b9476b976-9c76j            =>   none
     prometheus-core-6546477dc8-5pgb6   =>   none
     app1-5d79fbc474-2fxqx              =>   egress
     app1-5d79fbc474-47p8n              =>   egress
     app2-56fbc4b964-f2ncg              =>   egress
     app3-5d9895d6ff-nx44c              =>   egress
     cilium-health-k8s1                 =>   none
     cilium-health-k8s2                 =>   none
⚠️  Cilium agent "cilium-64lwq": Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 44 Failed 44
Failed controllers:
 controller sync-IPv4-identity-mapping (25068) failure ""
controller sync-identity-to-k8s-pod (32642) failure ""
controller lxcmap-bpf-host-sync failure ""
controller sync-policymap-31235 failure ""
controller sync-to-k8s-ciliumendpoint (7455) failure ""
controller dns-poller failure ""
controller metricsmap-bpf-prom-sync failure ""
controller sync-to-k8s-ciliumendpoint (49514) failure ""
controller etcd-lease-keepalive-0xc4200dbd90 failure ""
controller sync-IPv6-identity-mapping (49514) failure ""
controller sync-to-k8s-ciliumendpoint (25068) failure ""
controller sync-IPv6-identity-mapping (28843) failure ""
controller sync-IPv4-identity-mapping (31235) failure ""
controller sync-to-k8s-ciliumendpoint (32642) failure ""
controller sync-IPv6-identity-mapping (32642) failure ""
controller resolve-identity-32642 failure ""
controller resolve-identity-28843 failure ""
controller sync-to-k8s-ciliumendpoint (28843) failure ""
controller sync-identity-to-k8s-pod (49514) failure ""
controller sync-policymap-25068 failure ""
controller sync-policymap-7455 failure ""
controller sync-policymap-49514 failure ""
controller kvstore-sync-store-cilium/state/nodes/v1 failure ""
controller sync-identity-to-k8s-pod (25068) failure ""
controller kvstore-etcd-session-renew failure ""
controller cilium-health-ep failure ""
controller sync-to-k8s-ciliumendpoint-gc (k8s1) failure ""
controller sync-identity-to-k8s-pod (28843) failure ""
controller sync-identity-to-k8s-pod (7455) failure ""
controller sync-IPv6-identity-mapping (7455) failure ""
controller sync-IPv4-identity-mapping (49514) failure ""
controller resolve-identity-49514 failure ""
controller sync-IPv6-identity-mapping (25068) failure ""
controller resolve-identity-7455 failure ""
controller ipcache-bpf-garbage-collection failure ""
controller sync-identity-to-k8s-pod (31235) failure ""
controller sync-policymap-28843 failure ""
controller sync-policymap-32642 failure ""
controller resolve-identity-31235 failure ""
controller sync-IPv4-identity-mapping (7455) failure ""
controller sync-IPv4-identity-mapping (32642) failure ""
controller sync-IPv6-identity-mapping (31235) failure ""
controller sync-IPv4-identity-mapping (28843) failure ""
controller sync-to-k8s-ciliumendpoint (31235) failure ""
⚠️  Cilium agent "cilium-wmn4q": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 20 Failed 20
Failed controllers:
 controller sync-IPv4-identity-mapping (25068) failure ""
controller sync-identity-to-k8s-pod (32642) failure ""
controller lxcmap-bpf-host-sync failure ""
controller sync-policymap-31235 failure ""
controller sync-to-k8s-ciliumendpoint (7455) failure ""
controller dns-poller failure ""
controller metricsmap-bpf-prom-sync failure ""
controller sync-to-k8s-ciliumendpoint (49514) failure ""
controller etcd-lease-keepalive-0xc4200dbd90 failure ""
controller sync-IPv6-identity-mapping (49514) failure ""
controller sync-to-k8s-ciliumendpoint (25068) failure ""
controller sync-IPv6-identity-mapping (28843) failure ""
controller sync-IPv4-identity-mapping (31235) failure ""
controller sync-to-k8s-ciliumendpoint (32642) failure ""
controller sync-IPv6-identity-mapping (32642) failure ""
controller resolve-identity-32642 failure ""
controller resolve-identity-28843 failure ""
controller sync-to-k8s-ciliumendpoint (28843) failure ""
controller sync-identity-to-k8s-pod (49514) failure ""
controller sync-policymap-25068 failure ""
controller sync-policymap-7455 failure ""
controller sync-policymap-49514 failure ""
controller kvstore-sync-store-cilium/state/nodes/v1 failure ""
controller sync-identity-to-k8s-pod (25068) failure ""
controller kvstore-etcd-session-renew failure ""
controller cilium-health-ep failure ""
controller sync-to-k8s-ciliumendpoint-gc (k8s1) failure ""
controller sync-identity-to-k8s-pod (28843) failure ""
controller sync-identity-to-k8s-pod (7455) failure ""
controller sync-IPv6-identity-mapping (7455) failure ""
controller sync-IPv4-identity-mapping (49514) failure ""
controller resolve-identity-49514 failure ""
controller sync-IPv6-identity-mapping (25068) failure ""
controller resolve-identity-7455 failure ""
controller ipcache-bpf-garbage-collection failure ""
controller sync-identity-to-k8s-pod (31235) failure ""
controller sync-policymap-28843 failure ""
controller sync-policymap-32642 failure ""
controller resolve-identity-31235 failure ""
controller sync-IPv4-identity-mapping (7455) failure ""
controller sync-IPv4-identity-mapping (32642) failure ""
controller sync-IPv6-identity-mapping (31235) failure ""
controller sync-IPv4-identity-mapping (28843) failure ""
controller sync-to-k8s-ciliumendpoint (31235) failure ""
controller sync-identity-to-k8s-pod (46694) failure ""
controller sync-IPv6-identity-mapping (25238) failure ""
controller etcd-lease-keepalive-0xc4200dbd90 failure ""
controller sync-IPv4-identity-mapping (25238) failure ""
controller ipcache-bpf-garbage-collection failure ""
controller sync-to-k8s-ciliumendpoint-gc (k8s2) failure ""
controller sync-to-k8s-ciliumendpoint (25238) failure ""
controller metricsmap-bpf-prom-sync failure ""
controller kvstore-sync-store-cilium/state/nodes/v1 failure ""
controller lxcmap-bpf-host-sync failure ""
controller cilium-health-ep failure ""
controller dns-poller failure ""
controller sync-to-k8s-ciliumendpoint (46694) failure ""
controller resolve-identity-25238 failure ""
controller sync-identity-to-k8s-pod (25238) failure ""
controller kvstore-etcd-session-renew failure ""
controller sync-IPv6-identity-mapping (46694) failure ""
controller sync-IPv4-identity-mapping (46694) failure ""
controller sync-policymap-25238 failure ""
controller sync-policymap-46694 failure ""

Standard Error

STEP: Installing egress default-allow
STEP: Checking that all endpoints have egress enforcement enabled
STEP: Checking connectivity between pods and external services after installing egress policy
=== Test Finished at 2018-07-27T17:40:19Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE       IP              NODE
default       app1-5d79fbc474-2fxqx              1/1       Running   0          16m       10.10.0.2       k8s1
default       app1-5d79fbc474-47p8n              1/1       Running   0          16m       10.10.0.235     k8s1
default       app2-56fbc4b964-f2ncg              1/1       Running   0          16m       10.10.0.148     k8s1
default       app3-5d9895d6ff-nx44c              1/1       Running   0          16m       10.10.0.41      k8s1
kube-system   cilium-64lwq                       1/1       Running   0          17m       192.168.36.11   k8s1
kube-system   cilium-wmn4q                       1/1       Running   0          17m       192.168.36.12   k8s2
kube-system   coredns-b9476b976-9c76j            1/1       Running   0          24m       10.10.1.156     k8s2
kube-system   etcd-k8s1                          1/1       Running   0          54m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                1/1       Running   2          54m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1       1/1       Running   0          55m       192.168.36.11   k8s1
kube-system   kube-proxy-psvsl                   1/1       Running   0          47m       192.168.36.12   k8s2
kube-system   kube-proxy-qgxtv                   1/1       Running   0          55m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                1/1       Running   0          54m       192.168.36.11   k8s1
prometheus    prometheus-core-6546477dc8-5pgb6   1/1       Running   0          47m       10.10.0.190     k8s1

cmd: kubectl exec -n kube-system cilium-64lwq -- cilium service list
ID   Frontend             Backend                   
1    10.103.196.15:9090   1 => 10.10.0.190:9090     
2    10.96.0.1:443        1 => 192.168.36.11:6443   
3    10.96.0.10:53        1 => 10.10.1.156:53       
4    10.104.106.103:80    1 => 10.10.0.2:80         
                          2 => 10.10.0.235:80       

cmd: kubectl exec -n kube-system cilium-64lwq -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                              
7455       Disabled           Disabled          4          reserved:health                                          f00d::a0a:0:0:1d1f   10.10.0.54    ready   
25068      Disabled           Disabled          8710       k8s:app=prometheus                                       f00d::a0a:0:0:61ec   10.10.0.190   ready   
                                                           k8s:component=core                                                                                  
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                              
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                          
28843      Disabled           Enabled           8060       k8s:appSecond=true                                       f00d::a0a:0:0:70ab   10.10.0.148   ready   
                                                           k8s:id=app2                                                                                         
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
31235      Disabled           Enabled           26488      k8s:id=app1                                              f00d::a0a:0:0:7a03   10.10.0.2     ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
32642      Disabled           Enabled           46148      k8s:id=app3                                              f00d::a0a:0:0:7f82   10.10.0.41    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                     
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  
49514      Disabled           Enabled           26488      k8s:id=app1                                              f00d::a0a:0:0:c16a   10.10.0.235   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=testapp                                                                                  

cmd: kubectl exec -n kube-system cilium-wmn4q -- cilium service list
ID   Frontend             Backend                   
1    10.103.196.15:9090   1 => 10.10.0.190:9090     
2    10.96.0.1:443        1 => 192.168.36.11:6443   
3    10.96.0.10:53        1 => 10.10.1.156:53       
4    10.104.106.103:80    1 => 10.10.0.2:80         
                          2 => 10.10.0.235:80       

cmd: kubectl exec -n kube-system cilium-wmn4q -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                         
25238      Disabled           Disabled          4          reserved:health                                   f00d::a0a:100:0:6296   10.10.1.77    ready   
46694      Disabled           Disabled          16032      k8s:io.cilium.k8s.policy.serviceaccount=coredns   f00d::a0a:100:0:b666   10.10.1.156   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                    
                                                           k8s:k8s-app=kube-dns             
```

Logs:
[ab051ea7_K8sPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip](https://github.com/cilium/cilium/files/2237061/ab051ea7_K8sPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip)

**Comment by ianvernon** [comment]
I'm closing this; it hasn't reproduced in some time.
