### ISSUE TITLE
CI failure: KafkaPolicies failed due to kafka-broker going into CrashLoopBackOff because service names aren't plumbed down to kube-dns for 5 minutes in K8s 1.7 environments

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5025]
Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3446/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Output:
```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:333
Kafka Pods are not ready after timeout
Expected
    <*errors.errorString | 0xc425a8b630>: {
        s: "Timeout reached: timed out waiting for pods with filter -l zgroup=kafkaTestApp to be ready",
    }
to be nil
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:133
Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: [cilium-cx4bm cilium-sc5qb]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     empire-outpost-9999-4143713519-q2sv1   =>   none
     kafka-broker-2873197211-qh6kt          =>   none
     prometheus-core-3506541099-jwhst       =>   none
     empire-backup-2986355077-7lh6d         =>   none
     empire-hq-2917507631-n4d1c             =>   none
     empire-outpost-8888-3627733903-8xdrk   =>   none
     zookeeper-1032194181-mt667             =>   none
     cilium-health-k8s2                     =>   none
     kube-dns-2552250787-1xc0z              =>   none
Cilium agent "cilium-cx4bm": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 50 Failed 0
Cilium agent "cilium-sc5qb": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 26 Failed 0

Standard Error

===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                                   READY     STATUS             RESTARTS   AGE       IP              NODE
default       empire-backup-2986355077-7lh6d         1/1       Running            0          5m        10.10.1.190     k8s2
default       empire-hq-2917507631-n4d1c             1/1       Running            0          5m        10.10.0.251     k8s1
default       empire-outpost-8888-3627733903-8xdrk   1/1       Running            0          5m        10.10.1.192     k8s2
default       empire-outpost-9999-4143713519-q2sv1   1/1       Running            0          5m        10.10.1.222     k8s2
default       kafka-broker-2873197211-qh6kt          0/1       CrashLoopBackOff   5          5m        10.10.1.98      k8s2
default       zookeeper-1032194181-mt667             1/1       Running            0          5m        10.10.1.165     k8s2
kube-system   cilium-cx4bm                           1/1       Running            0          5m        192.168.36.12   k8s2
kube-system   cilium-sc5qb                           1/1       Running            0          5m        192.168.36.11   k8s1
kube-system   etcd-k8s1                              1/1       Running            0          46m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running            0          46m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running            0          46m       192.168.36.11   k8s1
kube-system   kube-dns-2552250787-1xc0z              3/3       Running            0          6m        10.10.1.243     k8s2
kube-system   kube-proxy-vps9k                       1/1       Running            0          47m       192.168.36.11   k8s1
kube-system   kube-proxy-vxchz                       1/1       Running            0          40m       192.168.36.12   k8s2
kube-system   kube-scheduler-k8s1                    1/1       Running            0          46m       192.168.36.11   k8s1
prometheus    prometheus-core-3506541099-jwhst       1/1       Running            0          40m       10.10.0.75      k8s1

cmd: kubectl exec -n kube-system cilium-cx4bm -- cilium service list
ID   Frontend             Backend                   
1    10.96.0.1:443        1 => 192.168.36.11:6443   
2    10.96.0.10:53        1 => 10.10.1.243:53       
3    10.101.3.243:9090    1 => 10.10.0.75:9090      
4    10.105.192.11:2181   1 => 10.10.1.165:2181     

cmd: kubectl exec -n kube-system cilium-cx4bm -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                        IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                          
3650       Disabled           Disabled          22035      k8s:app=empire-outpost                             f00d::a0a:100:0:e42    10.10.1.222   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                 
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:outpostid=9999                                                                              
                                                           k8s:zgroup=kafkaTestApp                                                                         
6117       Disabled           Disabled          35842      k8s:app=empire-outpost                             f00d::a0a:100:0:17e5   10.10.1.192   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                 
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:outpostid=8888                                                                              
                                                           k8s:zgroup=kafkaTestApp                                                                         
6523       Disabled           Disabled          4          reserved:health                                    f00d::a0a:100:0:197b   10.10.1.247   ready   
8208       Disabled           Disabled          50075      k8s:app=kafka                                      f00d::a0a:100:0:2010   10.10.1.98    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                 
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:zgroup=kafkaTestApp                                                                         
22152      Disabled           Disabled          47341      k8s:io.cilium.k8s.policy.serviceaccount=kube-dns   f00d::a0a:100:0:5688   10.10.1.243   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                     
                                                           k8s:k8s-app=kube-dns                                                                            
32564      Disabled           Disabled          59494      k8s:app=zook                                       f00d::a0a:100:0:7f34   10.10.1.165   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                 
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:zgroup=kafkaTestApp                                                                         
45365      Disabled           Disabled          43645      k8s:app=empire-backup                              f00d::a0a:100:0:b135   10.10.1.190   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                 
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:zgroup=kafkaTestApp                                                                         

cmd: kubectl exec -n kube-system cilium-sc5qb -- cilium service list
ID   Frontend             Backend                   
1    10.96.0.1:443        1 => 192.168.36.11:6443   
2    10.96.0.10:53        1 => 10.10.1.243:53       
3    10.101.3.243:9090    1 => 10.10.0.75:9090      
4    10.105.192.11:2181   1 => 10.10.1.165:2181     

cmd: kubectl exec -n kube-system cilium-sc5qb -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                              
8417       Disabled           Disabled          48563      k8s:app=prometheus                                       f00d::a0a:0:0:20e1   10.10.0.75    ready   
                                                           k8s:component=core                                                                                  
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                              
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                          
38477      Disabled           Disabled          4          reserved:health                                          f00d::a0a:0:0:964d   10.10.0.190   ready   
41052      Disabled           Disabled          32829      k8s:app=empire-hq                                        f00d::a0a:0:0:a05c   10.10.0.251   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                     
                                                           k8s:io.kubernetes.pod.namespace=default                                                             
                                                           k8s:zgroup=kafkaTestApp    
```

Logs:
[4bc18599_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2236538/4bc18599_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by ianvernon** [comment]
Zookeeper DNS failed to resolve within the Kafka broker. From the pod's logs:

```
2018-07-27T10:54:27.516143862Z [2018-07-27 10:54:27,513] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
2018-07-27T10:54:27.516163091Z java.net.UnknownHostException: zook: Name does not resolve
2018-07-27T10:54:27.516165504Z 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2018-07-27T10:54:27.516167476Z 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
2018-07-27T10:54:27.516169246Z 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
2018-07-27T10:54:27.516170967Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
2018-07-27T10:54:27.516172698Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
2018-07-27T10:54:27.516182839Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
2018-07-27T10:54:27.516184829Z 	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
2018-07-27T10:54:27.516186695Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
2018-07-27T10:54:27.51618839Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
2018-07-27T10:54:27.516190161Z 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:86)
2018-07-27T10:54:27.516191885Z 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1539)
2018-07-27T10:54:27.516193563Z 	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:345)
2018-07-27T10:54:27.516195258Z 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:369)
2018-07-27T10:54:27.516196974Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
2018-07-27T10:54:27.516198656Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-07-27T10:54:27.516200337Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-07-27T10:54:27.516201953Z 	at kafka.Kafka.main(Kafka.scala)
2018-07-27T10:54:27.516698901Z [2018-07-27 10:54:27,516] INFO shutting down (kafka.server.KafkaServer)
2018-07-27T10:54:27.518095563Z [2018-07-27 10:54:27,517] WARN  (kafka.utils.CoreUtils$)
2018-07-27T10:54:27.518104494Z java.lang.NullPointerException
2018-07-27T10:54:27.518106742Z 	at kafka.server.KafkaServer.$anonfun$shutdown$6(KafkaServer.scala:569)
2018-07-27T10:54:27.518108745Z 	at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
2018-07-27T10:54:27.518110549Z 	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:569)
2018-07-27T10:54:27.518112267Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:326)
2018-07-27T10:54:27.518113958Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-07-27T10:54:27.518115724Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-07-27T10:54:27.518117359Z 	at kafka.Kafka.main(Kafka.scala)
2018-07-27T10:54:27.52276573Z [2018-07-27 10:54:27,522] INFO shut down completed (kafka.server.KafkaServer)
2018-07-27T10:54:27.52325169Z [2018-07-27 10:54:27,523] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
2018-07-27T10:54:27.5244127Z [2018-07-27 10:54:27,524] INFO shutting down (kafka.server.KafkaServer)
``

**Comment by ianvernon** [comment]
Perhaps we should split up how we deploy the Kafka app. I hypothesize that the issue here is that we deploy everything at once in one YAML (`kafka-sw-app.yaml`): 

https://github.com/cilium/cilium/blob/295c5cb9b7811d205fba69f165c450d56a73540c/test/k8sT/KafkaPolicies.go#L131-L133

The issue with this, is that the pods and the services are deployed at the same time; is it at all likely that the services are not ready / their DNS entries are not set up before the pods start, which results in the pods crashing? What if we install the services, wait for DNS to resolve, then install the deployment and then wait for the pods?

**Comment by eloycoto** [comment]
@ianvernon I don't think that is needed TBH. If kafka can't  connect to zookeeper it'll retry because we have a `livenessProbe` in there, and kafka will restart until can connect to zook.

**Comment by ianvernon** [comment]
From the console output from the test, the test lasted from 10:51:00 until 10:56:26:

```
10:51:00 K8sKafkaPolicyTest Kafka Policy Tests 
10:51:00   KafkaPolicies
10:51:00   /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
10:56:26 ===================== TEST FAILED =====================
```

Kafka app was deployed shortly after:
```
time="2018-07-27T10:51:14Z" level=debug msg="applying /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/kafka-sw-app.yaml"
time="2018-07-27T10:51:14Z" level=debug msg="running command: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/kafka-sw-app.yaml"
cmd: "kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/kafka-sw-app.yaml" exitCode: 0 stdout:
deployment "kafka-broker" created
deployment "zookeeper" created
service "zook" created
service "kafka-service" created
deployment "empire-hq" created
deployment "empire-outpost-8888" created
deployment "empire-outpost-9999" created
deployment "empire-backup" created
```

DNS lookups for the `zook` service in K8s failed shortly after:
```
2018-07-27T10:51:24.208715284Z I0727 10:51:24.208647       5 dns.go:637] Query for "zook.default.svc.cluster.local.", exact: false
2018-07-27T10:51:24.208782861Z I0727 10:51:24.208754       5 dns.go:866] Not a federation query: len(["zook" "default" "svc" "cluster" "local"]) != 4+len(["local" "cluster"])
2018-07-27T10:51:24.208816735Z I0727 10:51:24.208800       5 dns.go:757] Found 0 records for [local cluster svc default zook] in the cache
2018-07-27T10:51:24.208841373Z I0727 10:51:24.208828       5 dns.go:764] getRecordsForPath retval=[], path=[local cluster svc default zook]
2018-07-27T10:51:24.208863728Z I0727 10:51:24.208852       5 dns.go:670] No record found for zook.default.svc.cluster.local.
2018-07-27T10:51:24.208954813Z I0727 10:51:24.208647       5 dns.go:637] Query for "zook.default.svc.cluster.local.", exact: false
```

kube-apiserver logs from around the time show issues - I'm not sure what port 10250 is, though:
```
2018-07-27T10:51:11.233955848Z E0727 10:51:11.232818       7 proxy.go:199] Error proxying data from client to backend: write tcp 192.168.36.11:49886->192.168.36.11:10250: write: broken pipe
2018-07-27T10:51:12.559522201Z E0727 10:51:12.559268       7 proxy.go:213] Error proxying data from backend to client: write tcp 192.168.36.11:6443->192.168.36.11:53858: write: broken pipe
2018-07-27T10:51:12.560087119Z E0727 10:51:12.559993       7 proxy.go:199] Error proxying data from client to backend: write tcp 192.168.36.11:39636->192.168.36.12:10250: write: broken pipe
2018-07-27T10:53:43.654025706Z I0727 10:53:43.653587       7 compact.go:159] etcd: compacted rev (7746), endpoints ([http://127.0.0.1:2379])
2018-07-27T10:55:54.951893458Z E0727 10:55:54.951792       7 watcher.go:210] watch chan error: etcdserver: mvcc: required revision has been compacted
2018-07-27T10:55:54.95208521Z W0727 10:55:54.952047       7 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: watch of *extensions.ThirdPartyResource ended with: etcdserver: mvcc: required revision has been compacted
```

DNS lookups failed for some time:
```
2018-07-27T10:55:25.087410593Z I0727 10:55:25.080795       5 dns.go:482] No service for endpoint "zook" in namespace "default"
2018-07-27T10:55:25.087413665Z I0727 10:55:25.080820       5 dns.go:482] No service for endpoint "zook" in namespace "default"
2018-07-27T10:55:25.08741666Z I0727 10:55:25.080844       5 dns.go:482] No service for endpoint "zook" in namespace "default"
```

The services added by the test finally got imported at 10:55:25:

```
2018-07-27T10:55:25.09028353Z I0727 10:55:25.086717       5 dns.go:304] New service: zook
2018-07-27T10:55:25.090286411Z I0727 10:55:25.086732       5 dns.go:305] Service details: &Service{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:zook,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/services/zook,UID:fb62dc42-918a-11e8-8845-08002707f0ef,ResourceVersion:8497,Generation:0,CreationTimestamp:2018-07-27 10:51:14.387461849 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: zook,},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"zook"},"name":"zook","namespace":"default"},"spec":{"ports":[{"name":"zookeeper-port","port":2181,"protocol":"TCP","targetPort":2181}],"selector":{"app":"zook"}}}
2018-07-27T10:55:25.090310008Z ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:ServiceSpec{Ports:[{zookeeper-port TCP 2181 {0 2181 } 0}],Selector:map[string]string{app: zook,},ClusterIP:10.105.192.11,Type:ClusterIP,ExternalIPs:[],DeprecatedPublicIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[],},},}
2018-07-27T10:55:25.090313692Z I0727 10:55:25.086835       5 util.go:68] Constructed new DNS record: &{10.105.192.11 0 10 10  false 30 0  }, hash:51d38844
2018-07-27T10:55:25.090316692Z I0727 10:55:25.086864       5 util.go:68] Constructed new DNS record: &{zook.default.svc.cluster.local. 2181 10 10  false 30 0  }, hash:1c890718
2018-07-27T10:55:25.09032379Z I0727 10:55:25.086880       5 dns.go:511] Added SRV record &{Host:zook.default.svc.cluster.local. Port:2181 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
2018-07-27T10:55:25.090327191Z I0727 10:55:25.086918       5 util.go:68] Constructed new DNS record: &{zook.default.svc.cluster.local. 0 10 10  false 30 0  }, hash:7f5469b8
2018-07-27T10:55:25.090330235Z I0727 10:55:25.086937       5 dns.go:304] New service: kafka-service
2018-07-27T10:55:25.090333044Z I0727 10:55:25.086952       5 dns.go:305] Service details: &Service{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:kafka-service,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/services/kafka-service,UID:fb6ac376-918a-11e8-8845-08002707f0ef,ResourceVersion:8505,Generation:0,CreationTimestamp:2018-07-27 10:51:14.439256308 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: kafka,},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kafka"},"name":"kafka-service","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"name":"kafka-port","port":9092,"protocol":"TCP","targetPort":9092}],"selector":{"app":"kafka"}}}
2018-07-27T10:55:25.090339809Z ,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:ServiceSpec{Ports:[{kafka-port TCP 9092 {0 9092 } 0}],Selector:map[string]string{app: kafka,},ClusterIP:None,Type:ClusterIP,ExternalIPs:[],DeprecatedPublicIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[],},},}
2018-07-27T10:55:25.090343234Z I0727 10:55:25.087044       5 dns.go:529] Endpoints Annotations: map[]
```

But the kafka-broker pod was in a bad state for some time before that, and it last finished at 10:54:27:
```
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2018-07-27T10:51:14Z",
                        "status": "True",
                        "type": "Initialized"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2018-07-27T10:51:14Z",
                        "message": "containers with unready status: [kafka]",
                        "reason": "ContainersNotReady",
                        "status": "False",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2018-07-27T10:51:14Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
                ],
                "containerStatuses": [
                    {
                        "containerID": "docker://cdf9c49053325938da8df8b4ba31aa9c2d96935c271ab2c127c7475f3cc17548",
                        "image": "wurstmeister/kafka:1.1.0",
                        "imageID": "docker-pullable://wurstmeister/kafka@sha256:3a63b48894bce633fb2f0d2579e162163367113d79ea12ca296120e90952b463",
                        "lastState": {
                            "terminated": {
                                "containerID": "docker://cdf9c49053325938da8df8b4ba31aa9c2d96935c271ab2c127c7475f3cc17548",
                                "exitCode": 1,
                                "finishedAt": "2018-07-27T10:54:27Z",
                                "reason": "Error",
                                "startedAt": "2018-07-27T10:54:26Z"
                            }
                        },
                        "name": "kafka",
                        "ready": false,
                        "restartCount": 5,
                        "state": {
                            "waiting": {
                                "message": "Back-off 2m40s restarting failed container=kafka pod=kafka-broker-2873197211-qh6kt_default(fb59a6a4-918a-11e8-8845-08002707f0ef)",
                                "reason": "CrashLoopBackOff"
                            }
                        }
                    }
                ],
                "hostIP": "192.168.36.12",
                "phase": "Running",
                "podIP": "10.10.1.98",
                "qosClass": "BestEffort",
                "startTime": "2018-07-27T10:51:14Z"
            }
```

```
"finishedAt": "2018-07-27T10:54:27Z"
```

It makes sense that it went into CrashLoopBackOff at this time, and didn't restart sooner since it had already restarted 5 times. So, I guess this isn't a test issue, moreso that kube-dns took way too long to get the information about the added services.

**Comment by ianvernon** [comment]
Port 10250 is what serves kubelet, c.f. https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ . 

So this means the kube-apiserver wasn't able to communicate with kubelet?

**Comment by ianvernon** [comment]
Discussed with @tgraf - we should see if we can apply resource limits to the Kafka pods. There may be an inordinate amount of load on the system.

**Comment by ianvernon** [comment]
The amount of load doesn't seem to be too unreasonable(?). From the bugtool for pod `cilium-cx4bm`:

# uptime

```
 10:56:21 up 50 min,  0 users,  load average: 0.09, 0.92, 1.65

```

**Comment by ianvernon** [comment]
Unassigning myself; I've done triage, but am unsure about how to proceed further on this.

**Comment by ianvernon** [comment]
Failure occurred again:

Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3461/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: 
[b838c55d_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242207/b838c55d_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by ianvernon** [comment]
And again:

Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3463/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: 
[c8c814df_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242214/c8c814df_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

Note: upgrade test ran right before this test.

**Comment by ianvernon** [comment]
And again:

Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3469/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: 
[d70856d4_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242220/d70856d4_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

Note: upgrade test ran right before this test

**Comment by ianvernon** [comment]
And again! 

Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3472/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: 
[4d087366_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242225/4d087366_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

Note: upgrade test ran right before this test

**Comment by ianvernon** [comment]
Note that these failures are only occurring with K8s 1.7.

**Comment by ianvernon** [comment]
Again!

Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3473/testReport/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: 
[ccf33869_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242228/ccf33869_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by ianvernon** [comment]
Again:

Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1336/

Logs: [2b66e783_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242239/2b66e783_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by ianvernon** [comment]
Again:

Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1335/testReport/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: [25a217d9_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242248/25a217d9_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by ianvernon** [comment]
Again:

Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1334/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

Logs: 
[94a19373_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2242249/94a19373_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by eloycoto** [comment]
I've just noticed that this is use to happens when Cilium Upgrade happens just before Kafka, maybe any miss update?

Builds ID: 1335 and 1336
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1335/execution/node/97/log/?consoleFull
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1336/execution/node/97/log/?consoleFull

Seed: 1532949306

**Comment by ianvernon** [comment]
@eloycoto nice find! If that's the case, this should be reproducible. I'll spin up a setup locally and work on reproducing (running upgrade test then running the Kafka test).

**Comment by ianvernon** [comment]
Was able to reproduce locally - had a bunch of issues with my setup, but right before it kernel panicked, was able to see that the `kafka-broker` went into CrashLoopBackOff after running the Upgrade Test --> Kafka Test in the K8s 1.7 setup.

**Comment by ianvernon** [comment]
Reproducing steps:

1. Launch the multinode K8s tests from the `test` directory from latest master:

```
cd test; 
K8S_VERSION=1.7 vagrant up k8s1-1.7; K8S_VERSION=1.7 vagrant up k8s2-1.7
```

2. Run the upgrade test:
```
K8S_VERSION=1.7 ginkgo --focus="K8sUpdates" -v -- -cilium.provision=false -cilium.holdEnvironment=true
```

3. Run the Kafka test:
```
K8S_VERSION=1.7 ginkgo --focus="K8sKafkaPolicyTest" -v -- -cilium.provision=false -cilium.holdEnvironment=true
```

4. The Kafka test will fail because the kafka-broker pod goes into `CrashLoopBackOff`.

**Comment by ianvernon** [comment]
Reducing priority on this due to #5054 being merged. If this is not observed for a few days, I will close.

**Comment by ianvernon** [comment]
This hasn't reproduced after #5054 , closing.
