### ISSUE TITLE
Panic in RunK8sCiliumEndpointSyn

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5084]
Cilium master/1.2-rc1

```
level=info msg="New endpoint" containerID=cilium-loc endpointID=7249 ipv4=10.2.1.227 ipv6="f00d::a02:100:0:1c51" k8sPodName=/ policyRevision=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1562491]

goroutine 49512 [running]:
github.com/cilium/cilium/vendor/github.com/hashicorp/go-version.(*Version).String(0x0, 0xc423689200, 0xc422fddb58)
        /go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/go-version/version.go:307 +0x51
github.com/cilium/cilium/vendor/github.com/hashicorp/go-version.(*Version).Compare(0x0, 0xc42009c800, 0xc422fddc08)
        /go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/go-version/version.go:88 +0x40
github.com/cilium/cilium/vendor/github.com/hashicorp/go-version.constraintGreaterThanEqual(0x0, 0xc42009c800, 0x1235)
        /go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/go-version/constraint.go:137 +0x35
github.com/cilium/cilium/vendor/github.com/hashicorp/go-version.(*Constraint).Check(0xc4213922a0, 0x0, 0x293e840)
        /go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/go-version/constraint.go:91 +0x3c
github.com/cilium/cilium/vendor/github.com/hashicorp/go-version.Constraints.Check(0xc4200d2070, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/vendor/github.com/hashicorp/go-version/constraint.go:71 +0x55
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RunK8sCiliumEndpointSync.func1(0xc422fddf10, 0x2)
        /go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:606 +0x46c
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc424d801a0)
        /go/src/github.com/cilium/cilium/pkg/controller/controller.go:182 +0x457
created by github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController
        /go/src/github.com/cilium/cilium/pkg/controller/manager.go:100 +0x49b
```

Just before that:
```
level=error msg="unable to retrieve kubernetes serverversion" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (7249)" endpointID=7249 error="Get https://172.18.0.1:443/version?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)" ipv4=10.2.1.227 ipv6="f00d::a02:100:0:1c51" k8sPodName=/ policyRevision=0
```

**Comment by raybejjani** [comment]
@tgraf do you remember which cilium version and k8s version this was with? I'm guessing k8s 1.11

**Comment by tgraf** [comment]
> cilium version

master as of 4 days ago



> k8s

1.9

**Comment by raybejjani** [comment]
@tgraf #5113 "fixes" the actual crash here, but I couldn't reproduce this case. The nil was the go-version.Constraint object, and for that to happen the string `"> 1.6"`  needed to cause an error... but we haven't changed that specific one in a while. So, I'm not convinced #5113 fixes the root issue, as much as makes it more likely to catch it.

**Comment by tgraf** [comment]
@raybejjani It fixes the runtime panic at arbitrary times which is the most serious aspect of this
