### ISSUE TITLE
kube-dns does not receive new service names for a long time after Cilium is deleted and re-installed

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5121]
#5025 was an issue that was blocking the CI for some time. In it, it was found that kube-dns became unresponsive for some time, and tests which relied upon hostnames that ran soon after Cilium was deleted / reinstalled were failing because the hostnames for services were not plumbed to kube-dns for some time. 

I also hit this in #5115 :
https://github.com/cilium/cilium/pull/5115#issuecomment-411098306

I tried reproducing it locally with K8s 1.7. The tests pass, but the `kafka-broker` pod goes into `CrashLoopBackoff`.

Reproducing steps:

1. Boot the K8s VMs with version 1.7:

```
K8S_VERSION=1.7 vagrant up k8s1-1.7; K8S_VERSION=1.7 vagrant up k8s2-1.7
```

2. Run the following commands to run the `K8sChaosTest`, which deletes Cilium and reinstalls it:

```
K8S_VERSION=1.7 ginkgo --focus="K8sChaosTest" -v -- -cilium.provision=false -cilium.holdEnvironment=true; K8S_VERSION=1.7 ginkgo --focus="K8sKafkaPolicyTest" -v -- -cilium.provision=false -cilium.holdEnvironment=true
```

3. Check for `kafka-broker` pod crashing.  The tests may very well pass. *However*, when the Kafka test starts, the kafka-broker will go into `CrashLoopBackoff` because the `zook` hostname will not be resolved (similar to the issue seen in #5115 / #5025) : 

```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY     STATUS             RESTARTS   AGE
...
default       kafka-broker-2873197211-x97p5          0/1       CrashLoopBackOff   4          2m
...
```

The logs will reveal that the `kafka-broker` pod cannot resolve the `zook` hostname for an extremely long time after the service is plumbed:

```
$ kubectl logs kafka-broker-2873197211-dqcfw 
[2018-08-07 17:06:03,432] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.net.UnknownHostException: zook: Name does not resolve
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:86)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1539)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:345)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:369)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:92)
	at kafka.Kafka.main(Kafka.scala)
```

Locally, at least for me, the test still passes, probably because the amount of time we wait for pods to be ready is liberal enough that kube-dns eventually gets into a good state, and receives the service name, albeit far too long after it is added to Kubernetes. I checked this:

```
I0807 17:07:39.307047       6 dns.go:304] New service: zook
I0807 17:07:39.307098       6 dns.go:305] Service details: &Service{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:zook,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/services/zook,UID:fcc40d2c-9a63-11e8-8ab2-0800278b5835,ResourceVersion:12838,Generation:0,CreationTimestamp:2018-08-07 17:04:46.794678303 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: zook,},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-configuration: {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"zook"},"name":"zook","namespace":"default"},"spec":{"ports":[{"name":"zookeeper-port","port":2181,"protocol":"TCP","targetPort":2181}],"selector":{"app":"zook"}}}
,},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:ServiceSpec{Ports:[{zookeeper-port TCP 2181 {0 2181 } 0}],Selector:map[string]string{app: zook,},ClusterIP:10.108.164.158,Type:ClusterIP,ExternalIPs:[],DeprecatedPublicIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[],},},}
I0807 17:07:39.307359       6 util.go:68] Constructed new DNS record: &{zook.default.svc.cluster.local. 2181 10 10  false 30 0  }, hash:1c890718
```

Note the time difference between the logs from the Kafka Pod (`17:06:03`) vs. the time the service was received by `kube-dns` (`17:07:39`). I suspect that if we reduced the timeout for pods to be ready in the CI, that we would hit this issue consistently. 

We can do what was done in #5054 to remove these spurious failures, as this use case (installing Cilium, installing kube-dns, uninstalling Cilium, reinstalling Cilium) should (ideally) be rare. But, it is still concerning that we appear to put something as critical as DNS in a bad state. It would be interesting to figure out why this happened beyond stabilizing the CI.

**Comment by ianvernon** [comment]
Next steps: what causes kube-dns to go into a good state? Is the program for `kube-dns` regenerated? Is something synced to the daemon via the Kubernetes watcher which was missing after restart?

**Comment by ianvernon** [comment]
There are two angles to this:

* Unblocking the CI (restarting kube-dns whenever Cilium is deleted / reinstalled ?)
* Debugging why kube-dns doesn't receive updates from kube-apiserver for some time about the services

**Comment by ianvernon** [comment]
This was only being hit in K8s 1.7. We are only supporting K8s >= 1.10 now. Closing.
