### ISSUE TITLE
Long lock: Map.OpenOrCreate()

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5353]
```
2018-08-24T22:42:47.764369859Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1" seconds=0.100117453 subsys=lock-lib
2018-08-24T22:42:47.764390567Z goroutine 1 [running]:
2018-08-24T22:42:47.764405096Z goroutine 1 runtime/debug.Stack(0xbed84059e70eeb6b, 0x3bbb4c22a, 0x38ff320)
2018-08-24T22:42:47.764418915Z goroutine 1      /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-08-24T22:42:47.764433842Z goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc420510238)
2018-08-24T22:42:47.764446791Z goroutine 1      /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:68 +0xc6
2018-08-24T22:42:47.764488832Z goroutine 1 github.com/cilium/cilium/pkg/bpf.(*Map).OpenOrCreate(0xc4205101e0, 0x1, 0x0, 0x0)
2018-08-24T22:42:47.764503892Z goroutine 1      /go/src/github.com/cilium/cilium/pkg/bpf/map.go:413 +0x266
2018-08-24T22:42:47.764517583Z goroutine 1 github.com/cilium/cilium/pkg/bpf.checkOrMountFS(0x0, 0x0, 0x39011a0, 0x2)
2018-08-24T22:42:47.764530583Z goroutine 1      /go/src/github.com/cilium/cilium/pkg/bpf/bpffs.go:320 +0xda
2018-08-24T22:42:47.764543796Z goroutine 1 github.com/cilium/cilium/pkg/bpf.CheckOrMountFS.func1()
2018-08-24T22:42:47.764556677Z goroutine 1      /go/src/github.com/cilium/cilium/pkg/bpf/bpffs.go:337 +0x37
2018-08-24T22:42:47.764573233Z goroutine 1 sync.(*Once).Do(0x3e49390, 0xc422067570)
2018-08-24T22:42:47.764588961Z goroutine 1      /usr/local/go/src/sync/once.go:44 +0xbe
2018-08-24T22:42:47.764605117Z goroutine 1 github.com/cilium/cilium/pkg/bpf.CheckOrMountFS(0x0, 0x0)
2018-08-24T22:42:47.76462061Z goroutine 1       /go/src/github.com/cilium/cilium/pkg/bpf/bpffs.go:336 +0x60
2018-08-24T22:42:47.764633452Z goroutine 1 main.initEnv(0x386ac00)
2018-08-24T22:42:47.764647045Z goroutine 1      /go/src/github.com/cilium/cilium/daemon/main.go:671 +0xcac
2018-08-24T22:42:47.764660609Z goroutine 1 main.glob..func2(0x386ac00, 0xc420488d00, 0x0, 0x8)
2018-08-24T22:42:47.764673418Z goroutine 1      /go/src/github.com/cilium/cilium/daemon/main.go:159 +0x2b
2018-08-24T22:42:47.764686448Z goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x386ac00, 0xc4200e0010, 0x8, 0x8, 0x386ac00, 0xc4200e0010)
2018-08-24T22:42:47.764700195Z goroutine 1      /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x234
2018-08-24T22:42:47.764713914Z goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x386ac00, 0xc421695120, 0x2451ec0, 0xc4215ff878)
2018-08-24T22:42:47.764727306Z goroutine 1      /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x2d4
2018-08-24T22:42:47.764746632Z goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x386ac00, 0x0, 0xc4204c0900)
2018-08-24T22:42:47.764761179Z goroutine 1      /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
2018-08-24T22:42:47.764775079Z goroutine 1 main.main()
2018-08-24T22:42:47.764788135Z goroutine 1      /go/src/github.com/cilium/cilium/daemon/main.go:174 +0x11c
```

**Comment by jomenxiao** [comment]
https://github.com/cilium/cilium/blob/master/pkg/bpf/map.go#L413

become a deadlock?

**Comment by joestringer** [comment]
@jomenxiao the map type is updated on line 412, so line 406 will not enter more than once:

https://github.com/cilium/cilium/blob/3b6e8a9aa377121d6ff1dfc864f18757ef91b4cb/pkg/bpf/map.go#L404-L413

**Comment by jomenxiao** [comment]
why long lock?
