### ISSUE TITLE
Long Lock: endpoint.regenerate()

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5356]
```
2018-08-24T22:45:40.819425165Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 29716" seconds=15.442981912 subsys=lock-lib
2018-08-24T22:45:40.819523863Z goroutine 29716 [running]:
2018-08-24T22:45:40.819540598Z goroutine 29716 runtime/debug.Stack(0xbed84081566c9eca, 0x28749b2181, 0x38ff320)
2018-08-24T22:45:40.819549979Z goroutine 29716  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-08-24T22:45:40.819559337Z goroutine 29716 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc42403ca50)
2018-08-24T22:45:40.819567787Z goroutine 29716  /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:105 +0xc6
2018-08-24T22:45:40.819576572Z goroutine 29716 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc42403c840, 0x2a064e0, 0xc421edb080, 0x280ee81, 0x17, 0x0, 0x0)
2018-08-24T22:45:40.819585724Z goroutine 29716  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:796 +0x8fd
2018-08-24T22:45:40.819594332Z goroutine 29716 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0x280ee81, 0x17, 0x2a064e0, 0xc421edb080, 0xc4239ae6e0, 0xc42403c840)
2018-08-24T22:45:40.819603462Z goroutine 29716  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:832 +0x20c
2018-08-24T22:45:40.819611872Z goroutine 29716 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-08-24T22:45:40.819620292Z goroutine 29716  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:810 +0x137
```

**Comment by ianvernon** [comment]
Related-to #5365

**Comment by ianvernon** [comment]
This should be less-likely to occur now:

* We now only do one compilation of BPF at agent boostrap, instead of one compilation per-endpoint due to BPF templating
* We are working on removing policy regeneration entirely out of 'regeneration' of an endpoint - regeneration of an endpoint is orthogonal to policy calculation

I'd be interested in seeing the load on the system during this time as well. 

@tgraf are you good to close this? This is related to https://github.com/cilium/cilium/issues/5365

**Comment by tgraf** [comment]
@ianvernon Agreed. Closing.
