### ISSUE TITLE
Upgrade test fail from 1.2 to master due proxy context timeout

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5532]
```
2018-09-12T05:38:01.615395888Z level=debug msg="Queueing container event" containerID=2235c7a429 event=exec_die subsys=workload-watcher
2018-09-12T05:38:02.182627101Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1663" seconds=53.927578637 subsys=lock-lib
2018-09-12T05:38:02.182647138Z goroutine 1663 [running]:
2018-09-12T05:38:02.182649689Z goroutine 1663 runtime/debug.Stack(0xbede47610f11d570, 0x21fe16a0d, 0x393c3c0)
2018-09-12T05:38:02.182651699Z goroutine 1663 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-09-12T05:38:02.182653863Z goroutine 1663 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc42398cba0)
2018-09-12T05:38:02.182655834Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:105 +0xc6
2018-09-12T05:38:02.182657831Z goroutine 1663 github.com/cilium/cilium/pkg/completion.(*WaitGroup).Wait(0xc42398cb90, 0x29ecd80, 0x3e85a20)
2018-09-12T05:38:02.182659876Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/completion/completion.go:89 +0x25d
2018-09-12T05:38:02.182661928Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).WaitForProxyCompletions(0xc421763080, 0xc42398cb90, 0x1, 0x1)
2018-09-12T05:38:02.182663937Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:531 +0x16e
2018-09-12T05:38:02.182665937Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc424951ac0, 0xa, 0xc423d58840, 0x0, 0x0, 0x0, 0x0)
2018-09-12T05:38:02.182667985Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:573 +0xc1e
2018-09-12T05:38:02.182670003Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc423d58840, 0x0, 0x0)
2018-09-12T05:38:02.182672468Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:771 +0x6d1
2018-09-12T05:38:02.182674527Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc423d58840, 0x2a382a0, 0xc4214eb800, 0xc423f47340, 0xc421763080)
2018-09-12T05:38:02.182676547Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:845 +0x1fc
2018-09-12T05:38:02.182678504Z goroutine 1663 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-12T05:38:02.182680447Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:823 +0x123
2018-09-12T05:38:02.182682398Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1663" seconds=55.074056503 subsys=lock-lib
2018-09-12T05:38:02.182684615Z goroutine 1663 [running]:
2018-09-12T05:38:02.182686537Z goroutine 1663 runtime/debug.Stack(0xbede4760c6580345, 0x1db8ccde1, 0x393c3c0)
2018-09-12T05:38:02.182696504Z goroutine 1663 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-09-12T05:38:02.182699146Z goroutine 1663 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).RUnlock(0xc421d74e40)
2018-09-12T05:38:02.182700928Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:84 +0xc6
2018-09-12T05:38:02.182702897Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc424951ac0, 0xa, 0xc423d58840, 0x0, 0x1, 0x29e74e0, 0xc4245c68d0)
2018-09-12T05:38:02.182704741Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:575 +0xcbd
2018-09-12T05:38:02.1827065Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc423d58840, 0x0, 0x0)
2018-09-12T05:38:02.182708329Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:771 +0x6d1
2018-09-12T05:38:02.182710112Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc423d58840, 0x2a382a0, 0xc4214eb800, 0xc423f47340, 0xc421763080)
2018-09-12T05:38:02.182711878Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:845 +0x1fc
2018-09-12T05:38:02.18271357Z goroutine 1663 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-12T05:38:02.182717624Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:823 +0x123
2018-09-12T05:38:02.182719512Z level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 file-path=54070_next_fail ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774
2018-09-12T05:38:02.182721821Z level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 endpointState=ready ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774 policyRevision=0 type=0
2018-09-12T05:38:02.182724018Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1663" seconds=56.211521531 subsys=lock-lib
2018-09-12T05:38:02.182725893Z goroutine 1663 [running]:
2018-09-12T05:38:02.182727589Z goroutine 1663 runtime/debug.Stack(0xbede476079c31fa9, 0x197c25651, 0x393c3c0)
2018-09-12T05:38:02.18272931Z goroutine 1663 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-09-12T05:38:02.182731803Z goroutine 1663 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc421763280)
2018-09-12T05:38:02.182733837Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:105 +0xc6
2018-09-12T05:38:02.182735641Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc423d58840, 0x29e74e0, 0xc4245c68d0)
2018-09-12T05:38:02.182737459Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:778 +0x901
2018-09-12T05:38:02.182739363Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc423d58840, 0x2a382a0, 0xc4214eb800, 0xc423f47340, 0xc421763080)
2018-09-12T05:38:02.182743486Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:845 +0x1fc
2018-09-12T05:38:02.182745343Z goroutine 1663 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-12T05:38:02.182747056Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:823 +0x123
2018-09-12T05:38:02.182748898Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=1.058972167s buildDuration=56.215753051s containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774 mapSync="48.935µs" policyCalculation="883.416µs" prepareBuild=1.630066ms proxyConfiguration=7.609811ms proxyPolicyCalculation=3.255198ms proxyWaitForAck=0s reason="syncing state to host" waitingForCTClean=0s waitingForLock=1.137175844s
2018-09-12T05:38:02.182752312Z level=debug msg="Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" code=Failure containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 endpointState=ready ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774 policyRevision=0 type=200
2018-09-12T05:38:02.182754569Z level=warning msg="Failed while regenerating endpoint" endpointID=54070 subsys=daemon
```

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1580/testReport/junit/k8s-1/11/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/
[a31fe822_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/2373884/a31fe822_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

**Comment by rlenglet** [comment]
There's a single regeneration happening for this endpoint:
```
$ grep endpointID=54070 pod-kube-system-cilium-4nww6-cilium-agent.log | grep 'Regenerating endpoint'
2018-09-12T05:37:05.969012287Z level=info msg="Regenerating endpoint" containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=54070 ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=/ reason="syncing state to host" startTime="2018-09-12 05:37:05.964876216 +0000 UTC m=+6.836850258"
2018-09-12T05:37:05.969214942Z level=debug msg="Regenerating endpoint: syncing state to host" code=OK containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=54070 endpointState=regenerating ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=/ policyRevision=0 type=0
```
This fails because of a port conflict:
```
$ grep -v level=debug pod-kube-system-cilium-4nww6-cilium-agent.log  | grep subsys=envoy | grep -v level=info
2018-09-12T05:37:07.205093108Z level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 54070:ingress:TCP:80:10250: cannot bind '[::]:10250': Address already in use" subsys=envoy-upstream threadID=328
2018-09-12T05:37:07.205110617Z level=warning msg="[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 54070:ingress:TCP:80:10250: cannot bind '[::]:10250': Address already in use" subsys=envoy-config threadID=328
```

Port 10250 is opened by Kubelet, cf. https://github.com/kubernetes/kubernetes/issues/7965.
We may now have conflicts with other services on the node because we removed the open port check, which was causing other issues.

We had discussed with @jrajahalme a fix that wouldn't need to open ports (which has been causing problems), but rather by doing a "netstat" and checking whether another process on the node has opened the port. Parsing the contents of `/proc/net/tcp` and `/proc/net/tcp6` should be sufficient:
```
cat /proc/net/tcp | awk '{print$2}' | sed 's/^[^:]*:\(.*\)$/0x\1/' | grep -v local_address | sort | uniq

cat /proc/net/tcp6 | awk '{print$2}' | sed 's/^[^:]*:\(.*\)$/0x\1/' | grep -v local_address | sort | uniq
```
That is not too hard to do in Golang.
