### ISSUE TITLE
PR 5736 CI: cilium-agent SIGSEGV during endpoint restoration

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#5757]
Cilium-agent crashed during CI run https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6869/

Excerpt from `RuntimeKVStoreTest_Consul_KVStore/test-output.log`

```
level=info msg="Restoring endpoints from former life..." subsys=daemon
level=debug msg="Reading directory" endpointID=9391 file-path=/var/run/cilium/state/9391/lxc_config.h subsys=daemon
level=debug msg="Found endpoint C header file" endpointID=9391 file-path=/var/run/cilium/state/9391/lxc_config.h subsys=daemon
level=debug msg="Endpoint restoring" code=OK containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=9391 endpointState=restoring ipv4=10.15.154.91 ipv6="f00d::a0f:0:0:24af" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fa3ca6]

goroutine 1 [running]:
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).UnconditionalRLock(0xc421941b80)
	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:60 +0x26
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).HasLabels(0xc421941b80, 0xc4205c8b10, 0x0)
	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1716 +0x34
main.(*Daemon).restoreOldEndpoints(0xc4204ded80, 0xc4218ed0e0, 0x15, 0x1, 0x0, 0x0, 0xc420576100)
	/home/vagrant/go/src/github.com/cilium/cilium/daemon/state.go:92 +0x2e6
main.NewDaemon(0x2710da0, 0xc42234c840, 0x1, 0x1)
	/home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:1212 +0x7fc
main.runDaemon()
	/home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:826 +0xac
main.glob..func2(0x3b057c0, 0xc4204b85f0, 0x0, 0x5)
	/home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:164 +0x30
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x3b057c0, 0xc42004c0d0, 0x5, 0x5, 0x3b057c0, 0xc42004c0d0)
	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x234
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3b057c0, 0xc42191d580, 0x2612100, 0xc42187dd28)
	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x2d4
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x3b057c0, 0x0, 0xc420540d00)
	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:182 +0x11c

time="2018-10-01T21:36:42Z" level=debug msg="running command: sudo cilium status"
cmd: "sudo cilium status" exitCode: 1 duration: 180.340091ms stdout:

stderr:
Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

**Comment by ianvernon** [comment]
I suspect this is definitely related to the PR which had the failures occur. It changes the mutex of the endpoint to be a pointer. When we restore the endpoint, the lock value is not restored, because it is not marshaled into the JSON. As such, it is nil. If the PR in question wants to have the lock changed to a pointer to a mutex, all restored endpoints should have a new lock created upon restoration, otherwise it will be the zero value for a pointer, which is nil.

**Comment by jrajahalme** [comment]
So I wonder why `go vet` would require such a change in #5736?

**Comment by tgraf** [comment]
Closing this as it is related to the PR itself
