### ISSUE TITLE
CI: Kafka Policy Tests: Kafka Pods are not ready after timeout

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5867]
On a v1.1 backport PR (#5864), I observed this:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7191/testReport/junit/k8s-1/11/K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

```
Stacktrace
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:330
Kafka Pods are not ready after timeout
Expected
    <*errors.errorString | 0xc420424bb0>: {
        s: "Timeout reached: could not get Pods",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:130
Standard Output
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                                   READY     STATUS             RESTARTS   AGE       IP              NODE
default       empire-backup-76dd5cbf7b-bcrkv         1/1       Running            0          5m        10.10.0.19      k8s1
default       empire-hq-749db985fb-l5qfq             1/1       Running            0          5m        10.10.0.9       k8s1
default       empire-outpost-8888-84469c7b8b-qzvpw   1/1       Running            0          5m        10.10.1.115     k8s2
default       empire-outpost-9999-845f585bcd-6c59w   1/1       Running            0          5m        10.10.1.203     k8s2
default       kafka-broker-6f5f474db-5qmmc           0/1       CrashLoopBackOff   5          5m        10.10.0.84      k8s1
default       zookeeper-ddbc5c98d-ds7zs              1/1       Running            0          5m        10.10.1.173     k8s2
kube-system   cilium-m8gtg                           1/1       Running            0          5m        192.168.36.11   k8s1
kube-system   cilium-s2mtv                           1/1       Running            0          5m        192.168.36.12   k8s2
kube-system   coredns-78fcdf6894-dg7hh               1/1       Running            0          32m       10.10.1.48      k8s2
kube-system   coredns-78fcdf6894-k4tx2               1/1       Running            0          32m       10.10.1.114     k8s2
kube-system   etcd-k8s1                              1/1       Running            0          31m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running            0          31m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running            0          31m       192.168.36.11   k8s1
kube-system   kube-proxy-nlmmg                       1/1       Running            0          24m       192.168.36.12   k8s2
kube-system   kube-proxy-sl5w4                       1/1       Running            0          32m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                    1/1       Running            0          31m       192.168.36.11   k8s1
prometheus    prometheus-core-6546477dc8-dbvv2       1/1       Running            0          24m       10.10.1.232     k8s2

cmd: kubectl exec -n kube-system cilium-m8gtg -- cilium service list
ID   Frontend              Backend                   
1    10.105.120.204:9090   1 => 10.10.1.232:9090     
2    10.96.0.1:443         1 => 192.168.36.11:6443   
3    10.96.0.10:53         1 => 10.10.1.114:53       
                           2 => 10.10.1.48:53        
20   10.97.52.11:2181      1 => 10.10.1.173:2181     

cmd: kubectl exec -n kube-system cilium-m8gtg -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                       
6283       Disabled           Disabled          4          reserved:health                                   f00d::a0a:0:0:188b   10.10.0.164   ready   
16434      Disabled           Disabled          34868      k8s:app=empire-backup                             f00d::a0a:0:0:4032   10.10.0.19    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                      
                                                           k8s:zgroup=kafkaTestApp                                                                      
31063      Disabled           Disabled          46405      k8s:app=kafka                                     f00d::a0a:0:0:7957   10.10.0.84    ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                      
                                                           k8s:zgroup=kafkaTestApp                                                                      
64841      Disabled           Disabled          6040       k8s:app=empire-hq                                 f00d::a0a:0:0:fd49   10.10.0.9     ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                              
                                                           k8s:io.kubernetes.pod.namespace=default                                                      
                                                           k8s:zgroup=kafkaTestApp                                                                      

cmd: kubectl exec -n kube-system cilium-s2mtv -- cilium service list
ID   Frontend              Backend                   
1    10.105.120.204:9090   1 => 10.10.1.232:9090     
2    10.96.0.1:443         1 => 192.168.36.11:6443   
3    10.96.0.10:53         1 => 10.10.1.114:53       
                           2 => 10.10.1.48:53        
20   10.97.52.11:2181      1 => 10.10.1.173:2181     

cmd: kubectl exec -n kube-system cilium-s2mtv -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                
185        Disabled           Disabled          57002      k8s:app=empire-outpost                                   f00d::a0a:100:0:b9     10.10.1.203   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:outpostid=9999                                                                                    
                                                           k8s:zgroup=kafkaTestApp                                                                               
19049      Disabled           Disabled          53454      k8s:app=zook                                             f00d::a0a:100:0:4a69   10.10.1.173   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:zgroup=kafkaTestApp                                                                               
21466      Disabled           Disabled          10059      k8s:app=prometheus                                       f00d::a0a:100:0:53da   10.10.1.232   ready   
                                                           k8s:component=core                                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                
                                                           k8s:io.kubernetes.pod.namespace=prometheus                                                            
26435      Disabled           Disabled          53906      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:100:0:6743   10.10.1.48    ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                           
                                                           k8s:k8s-app=kube-dns                                                                                  
32450      Disabled           Disabled          53906      k8s:io.cilium.k8s.policy.serviceaccount=coredns          f00d::a0a:100:0:7ec2   10.10.1.114   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                           
                                                           k8s:k8s-app=kube-dns                                                                                  
41791      Disabled           Disabled          8084       k8s:app=empire-outpost                                   f00d::a0a:100:0:a33f   10.10.1.115   ready   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                       
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:outpostid=8888                                                                                    
                                                           k8s:zgroup=kafkaTestApp                                                                               
44182      Disabled           Disabled          4          reserved:health                                          f00d::a0a:100:0:ac96   10.10.1.71    ready   

===================== EXITING REPORT GENERATION =====================
```

[9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies (6).zip](https://github.com/cilium/cilium/files/2470257/9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.6.zip)

**Comment by joestringer** [comment]
From `pod-default-kafka-broker-6f5f474db-5qmmc-kafka-previous.log`:

```
2018-10-11T18:03:55.240368904Z [2018-10-11 18:03:55,238] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
2018-10-11T18:03:55.240385776Z java.net.UnknownHostException: zook: Name does not resolve
2018-10-11T18:03:55.240388174Z 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2018-10-11T18:03:55.240390163Z 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
2018-10-11T18:03:55.240391993Z 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
2018-10-11T18:03:55.240408787Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
2018-10-11T18:03:55.240410646Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
2018-10-11T18:03:55.240432331Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
2018-10-11T18:03:55.240434432Z 	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
2018-10-11T18:03:55.240436449Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
2018-10-11T18:03:55.240438597Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
2018-10-11T18:03:55.240440449Z 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:86)
2018-10-11T18:03:55.240442294Z 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1539)
2018-10-11T18:03:55.240444114Z 	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:345)
2018-10-11T18:03:55.240445968Z 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:369)
2018-10-11T18:03:55.240447803Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
2018-10-11T18:03:55.240449602Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-10-11T18:03:55.240451459Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-10-11T18:03:55.240453189Z 	at kafka.Kafka.main(Kafka.scala)
2018-10-11T18:03:55.244409245Z [2018-10-11 18:03:55,244] INFO shutting down (kafka.server.KafkaServer)
2018-10-11T18:03:55.248451362Z [2018-10-11 18:03:55,248] WARN  (kafka.utils.CoreUtils$)
2018-10-11T18:03:55.248467701Z java.lang.NullPointerException
2018-10-11T18:03:55.248470085Z 	at kafka.server.KafkaServer.$anonfun$shutdown$6(KafkaServer.scala:569)
2018-10-11T18:03:55.248472233Z 	at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
2018-10-11T18:03:55.248474073Z 	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:569)
2018-10-11T18:03:55.24847583Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:326)
2018-10-11T18:03:55.248477689Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-10-11T18:03:55.248479522Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-10-11T18:03:55.248481199Z 	at kafka.Kafka.main(Kafka.scala)
```

**Comment by joestringer** [comment]
Seems similar to https://github.com/cilium/cilium/issues/5025, might be affected/fixed by https://github.com/cilium/cilium/pull/5054

**Comment by ianvernon** [comment]
@joestringer definitely the same problem. I believe this was fixed by 01096d866c8deee85f519b437fe0c7e4a1297a41 in master, where we switched to different containers for use in the Kafka test.

**Comment by raybejjani** [comment]
I'm afraid this happened again, on master:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1789/testReport/junit/k8s-1/12/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

[329ae4d9_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2495879/329ae4d9_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

**Comment by jrajahalme** [comment]
Happened again on a PR build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8179/execution/node/96/log/?consoleFull

**Comment by aanm** [comment]
v1.1 is EOL closing

**Comment by brb** [comment]
Happened again: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5940/testReport/junit/k8s-1/13/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

[8f26a217_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2879352/8f26a217_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)

```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:366
Kafka Pods are not ready after timeout
Expected
    <*errors.errorString | 0xc428bc7d70>: {
        s: "Timeout reached: timed out waiting for pods with filter -l zgroup=kafkaTestApp to be ready",
    }
to be nil
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:129
```

From `pod-default-kafka-broker-55f8f488d-bbgzf-kafka.log`:

```
<..>
2019-02-18T20:55:29.740316264Z 2019-02-18 20:55:29,740 INFO exited: kafka_proxy (exit status 2; not expected)
2019-02-18T20:55:30.871412329Z 2019-02-18 20:55:30,871 INFO success: zookeeper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-18T20:55:30.872384152Z 2019-02-18 20:55:30,872 INFO spawned: 'kafka_proxy' with pid 271
2019-02-18T20:55:30.873123009Z 2019-02-18 20:55:30,873 INFO success: kafka entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-18T20:55:30.876408906Z 2019-02-18 20:55:30,876 INFO exited: kafka_proxy (exit status 2; not expected)
2019-02-18T20:55:33.12264204Z 2019-02-18 20:55:33,121 INFO spawned: 'kafka_proxy' with pid 302
2019-02-18T20:55:33.125442481Z 2019-02-18 20:55:33,125 INFO exited: kafka_proxy (exit status 2; not expected)
2019-02-18T20:55:36.134642167Z 2019-02-18 20:55:36,133 INFO spawned: 'kafka_proxy' with pid 304
2019-02-18T20:55:36.137946583Z 2019-02-18 20:55:36,137 INFO exited: kafka_proxy (exit status 2; not expected)
2019-02-18T20:55:37.140965773Z 2019-02-18 20:55:37,140 INFO gave up: kafka_proxy entered FATAL state, too many start retries too quickly
```
