### ISSUE TITLE
Duration is negative on End" duration="-23.063µs" subsys=spanstat

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6076]
```
level=warning msg="Duration is negative on End" duration="-23.063µs" subsys=spanstat
goroutine 334250 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/cilium/cilium/pkg/spanstat.(*SpanStat).End(0xc4263fc518, 0x1)
        /go/src/github.com/cilium/cilium/pkg/spanstat/spanstat.go:57 +0x1c5
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc4203cdb00, 0x2c0a8a0, 0xc4202c2280, 0xc4263fc380, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:737 +0x6ef
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc4263fc380, 0x2c0a8a0, 0xc4202c2280, 0xc4283b0b20, 0xc4203cdb00)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:842 +0x1fc
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:820 +0x123
```

**Comment by tgraf** [comment]
Fixed in master
