### ISSUE TITLE
http: panic serving due to broken pipe

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#649]
Hit twice so far during testing, unclear what could trigger it at this point:
```
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: INFO Regenerated program of endpoint 13628
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: INFO Regenerated program of endpoint 38593
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: 2017/05/05 01:23:25 http: panic serving @: write unix /var/run/cilium/cilium.sock->@: write: broken pipe
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: goroutine 23108 [running]:
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.(*conn).serve.func1(0xc422a8c600)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:1491 +0x12a
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: panic(0x19d9080, 0xc42290be50)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/runtime/panic.go:458 +0x243
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*GetEndpointOK).WriteResponse(0xc422ab3dc0, 0x29ae580, 0xc42299cf70, 0x299c700, 0x1cd9c28)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/get_endpoint_responses.go:55 +0x158
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc42249e880, 0x29ae580, 0xc42299cf70, 0xc422afc000, 0xc4214cc5c0, 0x1, 0x1, 0xc421b37500, 0x19cfe00, 0xc422ab3dc0)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/context.go:439 +0x424
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*GetEndpoint).ServeHTTP(0xc422485d80, 0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/get_endpoint.go:54 +0x1f9
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.HandlerFunc.ServeHTTP(0xc420ae42a0, 0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:75 +0xe2
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.HandlerFunc.ServeHTTP(0xc4220a8600, 0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xac
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.HandlerFunc.ServeHTTP(0xc42246b380, 0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x8b
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.HandlerFunc.ServeHTTP(0xc42246b3c0, 0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:1726 +0x44
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.serverHandler.ServeHTTP(0xc4223be280, 0x29ae580, 0xc42299cf70, 0xc422afc000)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:2202 +0x7d
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: net/http.(*conn).serve(0xc422a8c600, 0x29afa40, 0xc422ace280)
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:1579 +0x4b7
May 05 01:23:25 linux-3-1.home cilium-agent[8830]: created by net/http.(*Server).Serve
May 05 01:23:25 linux-3-1.home cilium-agent[8830]:         /usr/lib/golang/src/net/http/server.go:2293 +0x44d
May 05 01:23:29 linux-3-1.home cilium-agent[8830]: WARN Update of policy map failed: Unable to delete element: no such file or directory
May 05 01:23:29 linux-3-1.home cilium-agent[8830]: WARN Update of policy map failed: Unable to delete element: no such file or directory
May 05 01:24:23 linux-3-1.home cilium-agent[8830]: INFO Recycling Service ID 1
May 05 01:24:26 linux-3-1.home cilium-agent[8830]: INFO Regenerated program of endpoint 17471
May 05 01:24:28 linux-3-1.home cilium-agent[8830]: INFO Regenerated program of endpoint 17471
May 05 01:24:28 linux-3-1.home cilium-agent[8830]: INFO Regenerated program of endpoint 34700

```

**Comment by tgraf** [comment]
We never saw this again, closing for now.
