### ISSUE TITLE
Crash in lbmap

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6537]
Observed in Cilium 1.2.5

```
level=info msg="ipv4 Conntrack garbage collection statistics" completed=true duration=610.039924ms maxEntries=1000000 numDeleted=2598 numKeyFallbacks=0 numLookups=205206 numLookupsFailed=0 startTime="2019-01-03 09:45:49.140678969 +0000 UTC m=+83016.450345020" subsys=map-ct
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1fd097e]

goroutine 308 [running]:
github.com/cilium/cilium/pkg/maps/lbmap.(*bpfService).getBackends(0xc425d6cdc0, 0x2a371a0, 0xc4264ba0e8, 0xc4238bdc80)
    /go/src/github.com/cilium/cilium/pkg/maps/lbmap/bpfservice.go:125 +0xce
github.com/cilium/cilium/pkg/maps/lbmap.UpdateService(0x2a371a0, 0xc4264ba0e8, 0xc4238bdc80, 0x8, 0x8, 0xc421d4ae01, 0x11, 0x0, 0x0)
    /go/src/github.com/cilium/cilium/pkg/maps/lbmap/lbmap.go:347 +0x9c
main.(*Daemon).addSVC2BPFMap(0xc42022c280, 0xc4232faee0, 0x10, 0x10, 0xc4232af59d, 0x3, 0x1f90, 0x11, 0x2a371a0, 0xc4264ba0e8, ...)
    /go/src/github.com/cilium/cilium/daemon/loadbalancer.go:39 +0x167
main.(*Daemon).svcAdd(0xc42022c280, 0xc4232faee0, 0x10, 0x10, 0xc4232af59d, 0x3, 0x1f90, 0x11, 0xc420394540, 0x8, ...)
    /go/src/github.com/cilium/cilium/daemon/loadbalancer.go:124 +0x6ea
main.(*Daemon).addK8sSVCs(0xc42022c280, 0xc42474dae0, 0x9, 0xc42474daec, 0x4, 0xc42454b800, 0xc423bd5e50, 0x110, 0xc423f1fd40)
    /go/src/github.com/cilium/cilium/daemon/k8s_watcher.go:1184 +0x7f5
main.(*Daemon).syncLB.func2(0xc42474dae0, 0x9, 0xc42474daec, 0x4)
    /go/src/github.com/cilium/cilium/daemon/k8s_watcher.go:1228 +0x194
main.(*Daemon).syncLB(0xc42022c280, 0xc424777a40, 0x0, 0x0)
    /go/src/github.com/cilium/cilium/daemon/k8s_watcher.go:1246 +0x9e
main.(*Daemon).addK8sEndpointV1(0xc42022c280, 0xc423f1fb00)
    /go/src/github.com/cilium/cilium/daemon/k8s_watcher.go:936 +0x77a
main.(*Daemon).updateK8sEndpointV1(0xc42022c280, 0xc423f1f8c0, 0xc423f1fb00)
    /go/src/github.com/cilium/cilium/daemon/k8s_watcher.go:968 +0x35
main.(*Daemon).EnableK8sWatcher.func8.1(0x0, 0xc421f03440)
    /go/src/github.com/cilium/cilium/daemon/k8s_watcher.go:442 +0x3c
github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run(0xc42239c4e0)
    /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:65 +0x70
created by github.com/cilium/cilium/pkg/serializer.NewFunctionQueue
    /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:45 +0xbe
level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
```

**Comment by ianvernon** [comment]
Crash occurred in this code: https://github.com/cilium/cilium/blob/5c69b1c611c401c274f359cdd7b1a4d0b99600a5/pkg/maps/lbmap/bpfservice.go#L126-L132

I suspect it is because `backendsByMapIndex` has a pointer for the values: https://github.com/cilium/cilium/blob/5c69b1c611c401c274f359cdd7b1a4d0b99600a5/pkg/maps/lbmap/bpfservice.go#L36-L41

and `bpfBackend` value in the map is nil, and we try to dereference it.

Or, the underlying `bpfService` itself is `nil`.

**Comment by brb** [comment]
I think `backends[i-1] = b.backendsByMapIndex[i].bpfValue` is the culprit when `i == len(b.backendsByMapIndex)` - out of bound access.

**Comment by brb** [comment]
> Or, the underlying bpfService itself is nil.

I think it's not possible, as `backends := make([]ServiceValue, len(b.backendsByMapIndex))` would have panicked otherwise. So, probably there is a hole in `backendsByMapIndex`.

**Comment by Globegitter** [comment]
Thanks for opening up the ticket - just to add we are still affected by this in production today. I am happy to be available for any debugging purposes if it helps to resolve this issue.

**Comment by tgraf** [comment]
@Globegitter Working on a fix

**Comment by tgraf** [comment]
@ianvernon @brb The code currently relies on the caller to lock properly which I think may not work correctly. I'm adding locking to bpfService itself.
