### ISSUE TITLE
index out of range in idpool

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6632]
```
level=info msg="Conntrack garbage collection statistics" completed=true duration="443.628µs" family=ipv6 maxEntries=262144 numDeleted=0 numKeyFallbacks=0 numLookups=1 numLookupsFailed=0 protocol=non-TCP startTime="2019-01-14 06:00:56.760577245 +0000 UTC m=+244126.543738330" subsys=map-ct
panic: runtime error: index out of range

goroutine 206 [running]:
github.com/cilium/cilium/pkg/idpool.(*idCache).doRemove(0xc421e5c090, 0x8135, 0xc42055ac98)
    /go/src/github.com/cilium/cilium/pkg/idpool/idpool.go:293 +0x151
github.com/cilium/cilium/pkg/idpool.(*idCache).remove(0xc421e5c090, 0x8135, 0xc42180f170)
    /go/src/github.com/cilium/cilium/pkg/idpool/idpool.go:272 +0x35
github.com/cilium/cilium/pkg/idpool.(*IDPool).Remove(0xc42180f170, 0x8135, 0xc42335de00)
    /go/src/github.com/cilium/cilium/pkg/idpool/idpool.go:170 +0x78
github.com/cilium/cilium/pkg/kvstore/allocator.(*cache).start.func1(0xc42182c3c0, 0xc42182c300, 0xc421e27e00, 0xc421d0b450)
    /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/cache.go:186 +0x909
created by github.com/cilium/cilium/pkg/kvstore/allocator.(*cache).start
    /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/cache.go:139 +0x180
```

**Comment by tgraf** [comment]
Looked into this, can't see how it can happen. An if would protect from the panic but would likely cause inconsistency.

**Comment by UnwashedMeme** [comment]
I've seen this a couple times, most recently a few minutes ago.  Running cilium 1.3.2 on kubernetes 1.13.3.  I can't think of anything more to add that might help clarify.

**Comment by joestringer** [comment]
@UnwashedMeme are you in a position to upgrade to a v1.4.x release? It appears that this was fixed there.

**Comment by UnwashedMeme** [comment]
I will try it soon.
