### ISSUE TITLE
CI: level=warning msg="/var/lib/cilium/bpf/run_probes.sh: line 29:  9383 Terminated

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6643]
```
Jan 15 01:37:49 runtime cilium-agent[9075]: level=warning msg="/var/lib/cilium/bpf/run_probes.sh: line 29:  9383 Terminated              clang $PROBE_OPTS \"$PROBE_BASE/raw_main.c\" -o \"$OUT/$OUT_BIN\"" subsys=daemon
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 [running]:
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 runtime/debug.Stack(0xbf076c3b12a4fd43, 0x1c0dfc877, 0x4510f80)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc000ab1ec0)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:68 +0xc3
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.(*Daemon).compileBase(0xc000366600, 0x2edb160, 0xc000313240)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:512 +0x96b
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.(*Daemon).init(0xc000366600, 0x0, 0x0)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:571 +0x1d2
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.NewDaemon(0x2edf3c0, 0xc000ab0cc0, 0x1, 0x1, 0x0, 0x0)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:1115 +0x107d
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.runDaemon()
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:939 +0x1f2
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.glob..func1(0x446a8e0, 0xc0007cc880, 0x0, 0x4)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:102 +0x30
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x446a8e0, 0xc0000d0010, 0x4, 0x4, 0x446a8e0, 0xc0000d0010)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x446a8e0, 0x2ec3178, 0x2ee9c40, 0x2ec31a0)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x446a8e0, 0x0, 0x0)
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:800 +0x2b
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.daemonMain()
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:120 +0x14c
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1 main.main()
Jan 15 01:37:49 runtime cilium-agent[9075]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:30 +0xc9
```

**Comment by tgraf** [comment]
[230542b6_RuntimeCassandra_Tests_policy_allowing_all_actions.zip](https://github.com/cilium/cilium/files/2758931/230542b6_RuntimeCassandra_Tests_policy_allowing_all_actions.zip)
