### ISSUE TITLE
CI: org.jenkinsci.plugins.workflow.steps.FlowInterruptedException

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#6720]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9231/console
```
22:44:26 + ./post_build_agent.sh
22:44:26 output of following commands are ran on the Jenkins agent itself
22:44:26 output of: "ps -ef | grep -i vbox" 
22:44:26 root     22175     2  0 21:14 ?        00:00:00 [iprt-VBoxWQueue]
22:44:26 root     22179     2  0 21:14 ?        00:00:00 [iprt-VBoxTscThr]
22:44:26 root     32308 32305  0 22:44 ?        00:00:00 grep -i vbox
22:44:26 output of: "ps -ef | grep -i vagrant" 
22:44:26 root     32310 32305  0 22:44 ?        00:00:00 grep -i vagrant
22:44:26 output of: "VBoxManage list runningvms" 
22:44:26 output of: "VBoxManage list intnets" 
22:44:26 Name:        cilium-k8s9231-Cilium-PR-Ginkgo-Tests-Validated-1.13
22:44:26 Name:        intnet
[Pipeline] sh
22:44:27 + cd test/
22:44:27 + ./archive_test_results.sh
22:45:23 Body did not finish within grace period; terminating with extreme prejudice
Error when executing always post condition:
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.cancel(TimeoutStepExecution.java:160)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.access$100(TimeoutStepExecution.java:38)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution$1.run(TimeoutStepExecution.java:134)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] sh
22:45:23 + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium//test/
22:45:23 + K8S_VERSION=1.8 vagrant destroy -f
22:45:24 ==> k8s2-1.8: VM not created. Moving on...
22:45:24 ==> k8s1-1.8: VM not created. Moving on...
22:45:24 ==> runtime: VM not created. Moving on...
22:45:24 + true
[Pipeline] sh
```

**Comment by tgraf** [comment]
We can't do much about this, they happen. Closing
