### ISSUE TITLE
CI: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#6753]
https://travis-ci.org/cilium/cilium/builds/484070155?utm_source=github_status&utm_medium=notification
```
builder238: queued build, 1 now queued
builder44: dequeued 1 builds cancelled=false, 0 now queued
builder72: dequeued 1 builds cancelled=false, 0 now queued
builder160: queued build, 1 now queued
builder68: queued build, 1 now queued
builder173: queued build, 1 now queued
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8ee9ec]
goroutine 27 [running]:
github.com/cilium/cilium/pkg/buildqueue.(*build).createAndAddNotificationChannel(...)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue.go:231
github.com/cilium/cilium/pkg/buildqueue.(*BuildQueue).enqueueBuild(0xc000144850, 0xadb680, 0xc00001e280, 0xc00005ff90, 0xc00005ff98)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue.go:292 +0xbc
github.com/cilium/cilium/pkg/buildqueue.(*BuildQueue).Enqueue(0xc000144850, 0xadb680, 0xc00001e280, 0xc00042e020)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue.go:361 +0x49
github.com/cilium/cilium/pkg/buildqueue.(*BuildQueueTestSuite).TestBuildGuarantees.func2(0xc00042e020, 0xc000144850, 0xc00001e280)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue_test.go:419 +0x68
created by github.com/cilium/cilium/pkg/buildqueue.(*BuildQueueTestSuite).TestBuildGuarantees
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue_test.go:416 +0x3a3
FAIL	github.com/cilium/cilium/pkg/buildqueue	0.078s
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

**Comment by aanm** [comment]
[log.txt](https://github.com/cilium/cilium/files/2793707/log.txt)

**Comment by jrajahalme** [comment]
Hit this too:
```
builder1: starting build...
builder231: queued build, 3 now queued
builder157: queued build, 3 now queued
builder233: queued build, 3 now queued
builder234: queued build, 3 now queued
builder66: queued build, 3 now queued
builder210: queued build, 3 now queued
builder214: queued build, 3 now queued
builder2: build finished after 12ms
builder79: queued build, 2 now queued
builder1: queued build, 1 now queued
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa27bae]
goroutine 73 [running]:
github.com/cilium/cilium/pkg/buildqueue.(*build).createAndAddNotificationChannel(...)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue.go:231
github.com/cilium/cilium/pkg/buildqueue.(*BuildQueue).enqueueBuild(0xc000118d20, 0xcaeca0, 0xc0000bf0e0, 0xc000061f90, 0xc000061f98)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue.go:292 +0xbe
github.com/cilium/cilium/pkg/buildqueue.(*BuildQueue).Enqueue(0xc000118d20, 0xcaeca0, 0xc0000bf0e0, 0xc000424080)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue.go:361 +0x49
github.com/cilium/cilium/pkg/buildqueue.(*BuildQueueTestSuite).TestBuildGuarantees.func2(0xc000424080, 0xc000118d20, 0xc0000bf0e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue_test.go:419 +0x68
created by github.com/cilium/cilium/pkg/buildqueue.(*BuildQueueTestSuite).TestBuildGuarantees
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/buildqueue/buildqueue_test.go:416 +0x39b
FAIL	github.com/cilium/cilium/pkg/buildqueue	0.056s
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```
(https://travis-ci.org/cilium/cilium/builds/503398002?utm_source=github_status&utm_medium=notification)

**Comment by jrajahalme** [comment]
Here too: https://travis-ci.com/cilium/cilium/builds/108270039

**Comment by ianvernon** [comment]
Package was removed, closing.
