### ISSUE TITLE
CI: K8sDatapathConfig: Unable to create endpoint: Cilium API client timeout exceeded

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#6947]
### k8s-1.13.K8sDatapathConfig DirectRouting Check connectivity with automatic direct nodes routes

So far only observed in PR #6681, however I fail to see what specifically in that PR could cause the CNI plugin to disappear. Only observed once in one k8s run out of at least 2 or 3 CI runs.

### Base failure
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
Pods are not ready after timeout
Expected
    <*errors.errorString | 0xc433810650>: {
        s: "Timeout reached: timed out waiting for pods with filter  to be ready",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:148
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9642/testReport/junit/k8s-1/13/K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes/

### Further details

From pods_status.txt in the attached zip:

```
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Normal   Scheduled               6m24s               default-scheduler  Successfully assigned default/testclient-kt6c4 to k8s2
  Warning  FailedCreatePodSandBox  6m23s               kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "9d889eb118513e7369e4c8138ddd7b8ca0e75ae578bfc8d6fbbfe7ab2716393c" network for pod "testclient-kt6c4": NetworkPlugin cni failed to set up pod "testclient-kt6c4_default" network: failed to find plugin "cilium-cni" in path [/opt/cni/bin], failed to clean up sandbox container "9d889eb118513e7369e4c8138ddd7b8ca0e75ae578bfc8d6fbbfe7ab2716393c" network for pod "testclient-kt6c4": NetworkPlugin cni failed to teardown pod "testclient-kt6c4_default" network: failed to find plugin "cilium-cni" in path [/opt/cni/bin]]
  Warning  FailedCreatePodSandBox  4m40s               kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "6a63fcf7c195aebe0430336f082315abe252e7b7007fc0fdd7554ac703686e94" network for pod "testclient-kt6c4": NetworkPlugin cni failed to set up pod "testclient-kt6c4_default" network: Unable to create endpoint: Cilium API client timeout exceeded
  Warning  FailedCreatePodSandBox  3m8s                kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "1b96efa10b2a19ed6d1ea8217b529251f364a4f5ae756c5c4f1d4e227b17c150" network for pod "testclient-kt6c4": NetworkPlugin cni failed to set up pod "testclient-kt6c4_default" network: Unable to create endpoint: Cilium API client timeout exceeded
  Warning  FailedCreatePodSandBox  96s                 kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "fd9b4f942f85863297e15de247ec54e6836b88599a642ddf63421daa11d36549" network for pod "testclient-kt6c4": NetworkPlugin cni failed to set up pod "testclient-kt6c4_default" network: Unable to create endpoint: Cilium API client timeout exceeded
  Warning  FailedCreatePodSandBox  4s                  kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f9b520c77335572a03a4abd455af2c190235d12b8b6c80e08fe8c54843e08a73" network for pod "testclient-kt6c4": NetworkPlugin cni failed to set up pod "testclient-kt6c4_default" network: Unable to create endpoint: Cilium API client timeout exceeded
  Normal   SandboxChanged          3s (x6 over 6m22s)  kubelet, k8s2      Pod sandbox changed, it will be killed and re-created.
```

This was after applying the DS for auto node routes:
 https://github.com/cilium/cilium/blob/d96d205a58fc1329b23915bfa588ebab1efeb84c/test/k8sT/DatapathConfiguration.go#L148

Weirdly, other pods and Cilium seem fine?

```
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE     NAME                                   READY   STATUS              RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 default       testclient-5tqpr                       1/1     Running             0          5m57s   10.10.0.250     k8s1   <none>           <none>
	 default       testclient-kt6c4                       0/1     ContainerCreating   0          5m57s   <none>          k8s2   <none>           <none>
	 default       testds-bsrdw                           1/1     Running             0          5m57s   10.10.0.212     k8s1   <none>           <none>
	 default       testds-dsrbq                           1/1     Running             0          5m57s   10.10.1.206     k8s2   <none>           <none>
	 kube-system   cilium-etcd-operator-d6cb86868-6n62z   1/1     Running             0          9m21s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   cilium-etcd-pw9zmgtctz                 1/1     Running             0          7m26s   10.10.1.3       k8s2   <none>           <none>
	 kube-system   cilium-etcd-qbl94llvq7                 1/1     Running             0          8m6s    10.10.0.244     k8s1   <none>           <none>
	 kube-system   cilium-etcd-ws4nkqtqsx                 1/1     Running             0          8m54s   10.10.1.121     k8s2   <none>           <none>
	 kube-system   cilium-mxn87                           1/1     Running             0          5m54s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   cilium-tj7c2                           1/1     Running             0          5m54s   192.168.36.11   k8s1   <none>           <none>
	 kube-system   coredns-fff89c9b9-xw665                1/1     Running             0          13m     10.10.1.38      k8s2   <none>           <none>
	 kube-system   etcd-k8s1                              1/1     Running             0          13m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   etcd-operator-5cf67779fd-qxzrs         1/1     Running             0          9m17s   10.10.1.211     k8s2   <none>           <none>
	 kube-system   kube-apiserver-k8s1                    1/1     Running             0          12m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-controller-manager-k8s1           1/1     Running             0          12m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-proxy-wbxhr                       1/1     Running             0          13m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-proxy-zr9fn                       1/1     Running             0          9m48s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   kube-scheduler-k8s1                    1/1     Running             0          13m     192.168.36.11   k8s1   <none>           <none>
```

### Test results archive

[9a8ecf47_K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes.zip](https://github.com/cilium/cilium/files/2834857/9a8ecf47_K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes.zip)

**Comment by joestringer** [comment]
This hasn't been observed in more than 20 of the most recent master builds, so the simplest explanation is there's something wrong in my PR. Not sure what yet though since my PR changes mostly BPF code.

**Comment by joestringer** [comment]
The original title is present, but that may just be reporting the failure when attempting to deploy the container during the Cilium restart/upgrade. I've modified the title to the one that recurs, which appears to be a Cilium timeout. This seems more likely to be caused by some locking situation inside Cilium.

**Comment by joestringer** [comment]
From endpoint list in `cilium-mxn87` (`k8s2` instance), pod is apparently waiting for identity?

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])                              IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                     
535        Disabled           Disabled          33274           k8s:io.cilium.k8s.policy.cluster=default                 f00d::a0a:100:0:4e5    10.10.1.206   ready                  
                                                                k8s:io.cilium.k8s.policy.serviceaccount=default                                                                      
                                                                k8s:io.kubernetes.pod.namespace=default                                                                              
                                                                k8s:zgroup=testDS                                                                                                    
692        Disabled           Disabled          101             k8s:app=etcd                                             f00d::a0a:100:0:d590   10.10.1.121   ready                  
                                                                k8s:etcd_cluster=cilium-etcd                                                                                         
                                                                k8s:io.cilium.k8s.policy.cluster=default                                                                             
                                                                k8s:io.cilium.k8s.policy.serviceaccount=default                                                                      
                                                                k8s:io.cilium/app=etcd-operator                                                                                      
                                                                k8s:io.kubernetes.pod.namespace=kube-system                                                                          
1236       Unknown            Unknown           <no label id>   k8s:io.cilium.k8s.policy.cluster=default                 f00d::a0a:100:0:fe40   10.10.1.6     waiting-for-identity   
                                                                k8s:io.cilium.k8s.policy.serviceaccount=default                                                                      
                                                                k8s:io.kubernetes.pod.namespace=default                                                                              
                                                                k8s:zgroup=testDSClient  
```

**Comment by joestringer** [comment]
Similar report on the general channel in Cilium slack with Cilium v1.4.0-rc7.

**Comment by joestringer** [comment]
Seen in the cilium log, 1.5s bpf compilation times:

```
2019-02-06T02:23:20.154023259Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 44642" seconds=1.568429665 subsys=lock-lib
2019-02-06T02:23:20.154153804Z goroutine 44642 [running]:
2019-02-06T02:23:20.154159332Z goroutine 44642 runtime/debug.Stack(0xbf0eaf25a2e6d243, 0x118a0f76a, 0x45fa520)
2019-02-06T02:23:20.154161701Z goroutine 44642  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2019-02-06T02:23:20.154164906Z goroutine 44642 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc000cd2980)
2019-02-06T02:23:20.154167879Z goroutine 44642  /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:105 +0xc3
2019-02-06T02:23:20.154171025Z goroutine 44642 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc000cd2780, 0x2fd4e60, 0xc000560240, 0xc001253a40, 0x0, 0x0)
2019-02-06T02:23:20.154174115Z goroutine 44642  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:321 +0xa30
2019-02-06T02:23:20.154177242Z goroutine 44642 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc000975160, 0xc000142540, 0xc000cd2780, 0x2fd4e60, 0xc000560240)
2019-02-06T02:23:20.154180878Z goroutine 44642  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:433 +0x230
2019-02-06T02:23:20.154184155Z goroutine 44642 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2019-02-06T02:23:20.154187241Z goroutine 44642  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:408 +0x89
2019-02-06T02:23:20.154291405Z level=info msg="Completed endpoint regeneration" bpfCompilation=1.56516588s buildDuration=1.568692555s containerID=f557c1685f datapathPolicyRevision=4 des
iredPolicyRevision=4 endpointID=692 identity=101 ipv4=10.10.1.121 ipv6="f00d::a0a:100:0:d590" k8sPodName=kube-system/cilium-etcd-ws4nkqtqsx mapSync="590.66µs" policyCalculation="112.523
µs" prepareBuild="635.665µs" proxyConfiguration="5.62µs" proxyPolicyCalculation="122.969µs" proxyWaitForAck="148.057µs" reason="syncing state to host" subsys=endpoint waitingForCTClean=
341ns waitingForLock="71.977µs"
```

**Comment by joestringer** [comment]
Lots of 0.15s lock holds for endpoint delete during restore, too:

```
2019-02-06T02:23:18.760188627Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 44537" seconds=0.156143039 subsys=lock-lib
2019-02-06T02:23:18.760191492Z goroutine 44537 [running]:
2019-02-06T02:23:18.760194028Z goroutine 44537 runtime/debug.Stack(0xbf0eaf25a3fc11a9, 0x119b636c9, 0x45fa520)
2019-02-06T02:23:18.760196396Z goroutine 44537  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2019-02-06T02:23:18.760199014Z goroutine 44537 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc000217688)
2019-02-06T02:23:18.760201964Z goroutine 44537  /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:68 +0xc3
2019-02-06T02:23:18.760204712Z goroutine 44537 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Unlock(0xc000217680)
2019-02-06T02:23:18.760207536Z goroutine 44537  /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:31 +0x31
2019-02-06T02:23:18.760210482Z goroutine 44537 main.(*Daemon).deleteEndpointQuiet(0xc000560240, 0xc000217680, 0xc000b06701, 0x1, 0x1000000010000, 0xc0006128a0)
2019-02-06T02:23:18.760213505Z goroutine 44537  /go/src/github.com/cilium/cilium/daemon/endpoint.go:618 +0x347
2019-02-06T02:23:18.760216275Z goroutine 44537 created by main.(*Daemon).regenerateRestoredEndpoints
2019-02-06T02:23:18.760219055Z goroutine 44537  /go/src/github.com/cilium/cilium/daemon/state.go:330 +0x447
```

**Comment by tgraf** [comment]
@joestringer Are these logs from the user report or from the CI test?

**Comment by joestringer** [comment]
@tgraf All logs I've posted here are from the CI test.

**Comment by joestringer** [comment]
Community report was a different issue, removed tag. Still need to triage and determine severity wrt release.

**Comment by aanm** [comment]
@tgraf looking at the sysdump, the problem was due the fact that the endpoint `1236` tried to allocate an identity with the kvstore but got stuck in there.

```
$ grep -i 'endpointID=1236' pod-kube-system-cilium-mxn87-cilium-agent.log | grep -i 'Resolv.*identity'
2019-02-06T02:27:59.315074459Z level=debug msg="Resolving identity for labels" containerID=f9b520c773 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1236 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDSClient" ipv4=10.10.1.6 ipv6="f00d::a0a:100:0:fe40" k8sPodName=default/testclient-kt6c4 subsys=endpoint
```

https://github.com/cilium/cilium/blob/51a8ed056ad195b2818a720d8a6d6f376570ac91/pkg/endpoint/endpoint.go#L2066-L2073

Which stuck all the identity allocations as the only one that was able to resolve an identity was 33274
```
$ cat pod-kube-system-cilium-mxn87-cilium-agent.log | grep -i 'Resolved identity'
2019-02-06T02:23:51.169341025Z level=debug msg="Resolved identity" identity=33274 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDS" isNew=false subsys=identity-cache
```

**Comment by tgraf** [comment]
@aanm I don't understand how one identity allocation getting stuck blocks all other identity allocations? The allocation is stuck because etcd connectivity is not there or because etcd does not have quorum. We should not need to allocate any identity via kvstore to reach that point.

**Comment by ianvernon** [comment]
Is this still a release blocker?

**Comment by tgraf** [comment]
No progress on this, removing release-blocker label

**Comment by joestringer** [comment]
Seems duplicate with a lot of recent DatapathConfig issues, eg https://github.com/cilium/cilium/issues/7373
