### ISSUE TITLE
assignment to entry in nil map when using workload options

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6963]
Running the agent with the options: `--container-runtime=docker --container-runtime-endpoint=unix:///var/run/docker.sock`, seeing the following panic in master. Likely related to the workload option changes done recently.

```
Feb 06 02:01:26 k8s1 cilium-agent[2949]: panic: assignment to entry in nil map
Feb 06 02:01:26 k8s1 cilium-agent[2949]: goroutine 1 [running]:
Feb 06 02:01:26 k8s1 cilium-agent[2949]: main.NewDaemon(0x2f5ade0, 0xc000a13020, 0x1, 0x1, 0xc0007cf928, 0x11412e2)
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:1155 +0xeea
Feb 06 02:01:26 k8s1 cilium-agent[2949]: main.runDaemon()
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:1049 +0x214
Feb 06 02:01:26 k8s1 cilium-agent[2949]: main.glob..func1(0x450f320, 0xc0002fe2a0, 0x0, 0xe)
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:108 +0x30
Feb 06 02:01:26 k8s1 cilium-agent[2949]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x450f320, 0xc00004c100, 0xe, 0xe, 0x450f320, 0xc00004c100)
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
Feb 06 02:01:26 k8s1 cilium-agent[2949]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x450f320, 0x2f3dd00, 0x2f65620, 0x2f3dd20)
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
Feb 06 02:01:26 k8s1 cilium-agent[2949]: github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x450f320, 0x0, 0x0)
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:800 +0x2b
Feb 06 02:01:26 k8s1 cilium-agent[2949]: main.daemonMain()
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:126 +0x14c
Feb 06 02:01:26 k8s1 cilium-agent[2949]: main.main()
Feb 06 02:01:26 k8s1 cilium-agent[2949]:         /home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:30 +0xc9
```

Could be related to #6920

**Comment by aanm** [comment]
I already had a fix locally but I thought it was only affecting non-docker environments.
