### ISSUE TITLE
Istio GSG fails in final step with Kafka SchemaException

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7169]
Running [the Istio GSG for Cilium v1.3.3](https://docs.cilium.io/en/v1.3/gettingstarted/istio/) succeeds up until the very last step, specifically:

> Check that Cilium prevents the authaudit-logger service from fetching messages from this topic:

Expected behavior:
```
$ export POD_LOGGER_V1=`kubectl get pods -n default -l app=authaudit-logger,version=v1 -o jsonpath='{.items[0].metadata.name}'`
$ kubectl exec ${POD_LOGGER_V1} -c authaudit-logger -ti -- /opt/kafka_2.11-0.10.1.0/bin/kafka-console-consumer.sh --bootstrap-server=kafka:9092 --topic=credit-card-payments
[2017-12-07 03:08:54,513] WARN Not authorized to read from topic credit-card-payments. (org.apache.kafka.clients.consumer.internals.Fetcher)
[2017-12-07 03:08:54,517] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [credit-card-payments]
Processed a total of 0 messages
```

Output: 
```
$ kubectl exec ${POD_LOGGER_V1} -c authaudit-logger -ti -- /opt/kafka_2.11-0.10.1.0/bin/kafka-console-consumer.sh --bootstrap-server=kafka:9092 --topic=credit-card-payments
[2019-02-20 21:46:27,367] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'responses': Error reading field 'partition_responses': Error reading field 'record_set': Bytes size -1 cannot be negative
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73)
	at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1031)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
	at kafka.consumer.NewShinyConsumer.receive(BaseConsumer.scala:100)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:120)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:75)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:50)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Processed a total of 0 messages
```

**Comment by ianvernon** [comment]
Same issue occurs using Istio GSG with v1.4.1 of Cilium.

**Comment by ianvernon** [comment]
Removing backport labels for the following release branches / reasons:
* v1.3 is going to be EOL'd with the release of v1.6
* v1.4 is moving to a security-fix-only backport model

I am going to nominate this for v1.6 backport so we can track this to see if it still is a problem. I will not nominate this for v1.5 backport because I'd like to reduce the churn in release branches before the most recent release (e.g., 1.6 is the most recent branch, do not backport such fixes to v1.5).

**Comment by jrajahalme** [comment]
This still occurs in master, 1.6, 1.5, and 1.4.

**Comment by joestringer** [comment]
Closing due to age. Post a comment to request re-opening the investigation of this issue.
