### ISSUE TITLE
CI: potential deadlock from cilium health

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#7760]
Timing fits with `Command execution failed` from llc. Seen in #7749. Jenkins: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11667/

```
[...]
2018-09-29T12:21:39.678287863Z level=debug msg="Found unwatched container" containerID=4a52c173b7 subsys=workload-watcher
2018-09-29T12:21:39.67828963Z level=debug msg="Found unwatched container" containerID=0a966ea402 subsys=workload-watcher
2018-09-29T12:21:39.678291376Z level=debug msg="Found unwatched container" containerID=801dc99550 subsys=workload-watcher
2018-09-29T12:21:39.68728444Z level=debug msg="Controller func execution time: 10.397539ms" name="sync-IPv4-identity-mapping (64975)" subsys=controller uuid=3784d978-c3e2-11e8-9cdb-080027b66966
2018-09-29T12:21:39.698593109Z level=debug msg="Didn't find existing cilium-health endpoint to delete" endpointID=58609 subsys=daemon
2018-09-29T12:21:39.704640986Z level=debug msg="Didn't find existing device" error="Link not found" subsys=cilium-health-launcher veth=cilium_health
2018-09-29T12:21:39.706589917Z level=error msg="Command execution failed" cmd="[llc -march=bpf -mcpu=probe -filetype=obj -o 30591_next/bpf_lxc.o]" error="signal: killed" subsys=datapath-loader
2018-09-29T12:21:39.70665344Z level=debug msg="Received event from etcd: {Header:{ClusterId:3373127551666285087 MemberId:13506963981489885289 Revision:562 RaftTerm:3} Events:[0xc4240f4500] CompactRevision:0 Canceled:false Created:false closeErr:<nil> cancelReason:}" prefix=cilium/state/ip/v1 revision=562 subsys=kvstore watcher=endpointIPWatcher
2018-09-29T12:21:39.706709316Z level=info msg="Conntrack garbage collection statistics" completed=true duration=70.889075ms family=ipv4 maxEntries=524288 numDeleted=23 numKeyFallbacks=0 numLookups=31 numLookupsFailed=0 protocol=TCP startTime="2018-09-29 12:21:39.617646692 +0000 UTC m=+6.299733232" subsys=map-ct
[...]


[...]
2018-09-29T12:26:49.613821712Z level=debug msg="Load 1-min: 0.28 5-min: 1.76 15min: 2.73" endpointID=30591 subsys=endpoint
2018-09-29T12:26:49.613958462Z level=debug msg="Memory: Total: 3949 Used: 1446 (36.62%) Free: 1174 Buffers: 102 Cached: 1226" endpointID=30591 subsys=endpoint
2018-09-29T12:26:49.614907669Z level=debug msg="Swap: Total: 0 Used: 0 (0.00%) Free: 0" endpointID=30591 subsys=endpoint
2018-09-29T12:26:49.614917549Z level=debug msg="NAME cilium-agent STATUS S PID 1 CPU: 1.10% MEM: 3.41% CMDLINE: cilium-agent --debug=true -t=vxlan --kvstore=etcd --kvstore-opt=etcd.config=/var/lib/etcd-config/etcd.config --disable-ipv4=false --k8s-require-ipv4-pod-cidr --pprof=true --log-system-load MEM-EXT: RSS: 134 VMS: 1049 Data: 0 Stack: 0 Locked: 0 Swap: 0" endpointID=30591 subsys=endpoint
2018-09-29T12:26:49.677029092Z POTENTIAL DEADLOCK:
2018-09-29T12:26:49.677131002Z Previous place where the lock was grabbed
2018-09-29T12:26:49.677151711Z goroutine 1142 lock 0xc42232f8f0
2018-09-29T12:26:49.677329105Z /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:78 lock.(*internalRWMutex).RLock ??? <<<<<
2018-09-29T12:26:49.677442241Z /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:373 endpoint.(*Endpoint).regenerateBPF ???
2018-09-29T12:26:49.677493754Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:786 endpoint.(*Endpoint).regenerate ???
2018-09-29T12:26:49.677498313Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:864 endpoint.(*Endpoint).Regenerate.func1 ???
2018-09-29T12:26:49.677500281Z 
2018-09-29T12:26:49.677527769Z Have been trying to lock it again for more than 5m10s
2018-09-29T12:26:49.677564661Z goroutine 1405 lock 0xc42232f8f0
2018-09-29T12:26:49.677594988Z /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:78 lock.(*internalRWMutex).RLock ??? <<<<<
2018-09-29T12:26:49.67763573Z /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:373 endpoint.(*Endpoint).regenerateBPF ???
2018-09-29T12:26:49.677668939Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:786 endpoint.(*Endpoint).regenerate ???
2018-09-29T12:26:49.677673621Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:864 endpoint.(*Endpoint).Regenerate.func1 ???
2018-09-29T12:26:49.677678078Z 
2018-09-29T12:26:49.677684356Z 
2018-09-29T12:26:49.687679843Z Here is what goroutine 1142 doing now
2018-09-29T12:26:49.687699623Z goroutine 1142 [IO wait, 5 minutes]:
2018-09-29T12:26:49.687701988Z internal/poll.runtime_pollWait(0x7ffff7f3d610, 0x72, 0xc421fcec28)
2018-09-29T12:26:49.687703915Z 	/usr/local/go/src/runtime/netpoll.go:173 +0x57
2018-09-29T12:26:49.687705891Z internal/poll.(*pollDesc).wait(0xc423b590f8, 0x72, 0xffffffffffffff01, 0x2bb42e0, 0x3b06590)
2018-09-29T12:26:49.687707776Z 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
2018-09-29T12:26:49.68770956Z internal/poll.(*pollDesc).waitRead(0xc423b590f8, 0xc42417b401, 0x200, 0x200)
2018-09-29T12:26:49.687711407Z 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
2018-09-29T12:26:49.687713248Z internal/poll.(*FD).Read(0xc423b590e0, 0xc42417b400, 0x200, 0x200, 0x0, 0x0, 0x0)
2018-09-29T12:26:49.687715038Z 	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
2018-09-29T12:26:49.68771679Z os.(*File).read(0xc4219d5488, 0xc42417b400, 0x200, 0x200, 0xfe88f1, 0x261c280, 0x200)
2018-09-29T12:26:49.687718711Z 	/usr/local/go/src/os/file_unix.go:226 +0x4e
2018-09-29T12:26:49.687720503Z os.(*File).Read(0xc4219d5488, 0xc42417b400, 0x200, 0x200, 0x200, 0x200, 0xc42417b400)
2018-09-29T12:26:49.68772229Z 	/usr/local/go/src/os/file.go:107 +0x6a
2018-09-29T12:26:49.687724068Z bytes.(*Buffer).ReadFrom(0xc421753ab0, 0x2bb23c0, 0xc4219d5488, 0x0, 0x0, 0xc4200d5db0)
2018-09-29T12:26:49.687725843Z 	/usr/local/go/src/bytes/buffer.go:205 +0xa0
2018-09-29T12:26:49.687735641Z io/ioutil.readAll(0x2bb23c0, 0xc4219d5488, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-09-29T12:26:49.687737601Z 	/usr/local/go/src/io/ioutil/ioutil.go:36 +0xb5
2018-09-29T12:26:49.687740897Z io/ioutil.ReadAll(0x2bb23c0, 0xc4219d5488, 0xc4219d5488, 0x2bb23c0, 0xc4219d5488, 0x200, 0x2bb2480)
2018-09-29T12:26:49.687742704Z 	/usr/local/go/src/io/ioutil/ioutil.go:45 +0x3e
2018-09-29T12:26:49.687744491Z github.com/cilium/cilium/pkg/datapath/loader.compileAndLink(0x2be9520, 0xc423b63080, 0x3af2640, 0xc421fcf6c0, 0xc423a5b980, 0x0, 0x10, 0xc423a5b980)
2018-09-29T12:26:49.687746383Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/compile.go:147 +0x39c
2018-09-29T12:26:49.687748195Z github.com/cilium/cilium/pkg/datapath/loader.compile(0x2be9520, 0xc423b63080, 0x3af2640, 0xc421fcf6c0, 0x261a400, 0xc423b980c0, 0xc423b980c0)
2018-09-29T12:26:49.68775008Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/compile.go:218 +0x5d0
2018-09-29T12:26:49.687751878Z github.com/cilium/cilium/pkg/datapath/loader.compileDatapath(0x2be9520, 0xc423b63080, 0x2bcfbe0, 0xc423b63020, 0xc421fcf6c0, 0x0, 0x2be94e0, 0xc4200ce010)
2018-09-29T12:26:49.68775375Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:72 +0x3c2
2018-09-29T12:26:49.687756022Z github.com/cilium/cilium/pkg/datapath/loader.compileAndLoad(0x2be9520, 0xc423b63080, 0x2bcfbe0, 0xc423b63020, 0xc421fcf6c0, 0x5baf6e53, 0xc42325fa0b)
2018-09-29T12:26:49.687757943Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:101 +0x79
2018-09-29T12:26:49.687759727Z github.com/cilium/cilium/pkg/datapath/loader.CompileAndLoad(0x2be9520, 0xc423b63080, 0x2bcfbe0, 0xc423b63020, 0xc423b63080, 0xc423b98090)
2018-09-29T12:26:49.687761582Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:122 +0xe0
2018-09-29T12:26:49.687763397Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc421ef62c0, 0x2c00f80, 0xc4217a8c00, 0xc423a8d9e0, 0x1b, 0xc423a85ba0, 0xa, 0xc421bf7680, 0x0, 0x0, ...)
2018-09-29T12:26:49.687765319Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:562 +0x9e8
2018-09-29T12:26:49.687767141Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421ef62c0, 0x2c00f80, 0xc4217a8c00, 0xc421bf7680, 0x0, 0x0)
2018-09-29T12:26:49.687769088Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:786 +0x73a
2018-09-29T12:26:49.687770842Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc421bf7680, 0x2c00f80, 0xc4217a8c00, 0xc423ab8980, 0xc421ef62c0)
2018-09-29T12:26:49.687772645Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:864 +0x1fc
2018-09-29T12:26:49.687774381Z created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-29T12:26:49.687776147Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:842 +0x123
2018-09-29T12:26:49.687777911Z 
2018-09-29T12:26:49.687779613Z Other goroutines holding locks:
2018-09-29T12:26:49.687781274Z goroutine 1142 lock 0xc421ef64c0
2018-09-29T12:26:49.687782964Z /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:99 lock.(*internalMutex).Lock ??? <<<<<
2018-09-29T12:26:49.687787259Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:717 endpoint.(*Endpoint).regenerate ???
2018-09-29T12:26:49.68778921Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:864 endpoint.(*Endpoint).Regenerate.func1 ???
2018-09-29T12:26:49.687791382Z 
2018-09-29T12:26:49.687793196Z goroutine 1405 lock 0xc421ef6780
2018-09-29T12:26:49.687795921Z /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:99 lock.(*internalMutex).Lock ??? <<<<<
2018-09-29T12:26:49.687821949Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:717 endpoint.(*Endpoint).regenerate ???
2018-09-29T12:26:49.687883659Z /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:864 endpoint.(*Endpoint).Regenerate.func1 ???
2018-09-29T12:26:49.6878883Z 
2018-09-29T12:26:49.687890071Z 
[...]
```

**Comment by ianvernon** [comment]
Such an ordering of lock acquisition does not usually mean a deadlock, but that the endpoint got stuck regenerating. Here, it looks like the compilation got stuck?

```
018-09-29T12:26:49.687744491Z github.com/cilium/cilium/pkg/datapath/loader.compileAndLink(0x2be9520, 0xc423b63080, 0x3af2640, 0xc421fcf6c0, 0xc423a5b980, 0x0, 0x10, 0xc423a5b980)
2018-09-29T12:26:49.687746383Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/compile.go:147 +0x39c
2018-09-29T12:26:49.687748195Z github.com/cilium/cilium/pkg/datapath/loader.compile(0x2be9520, 0xc423b63080, 0x3af2640, 0xc421fcf6c0, 0x261a400, 0xc423b980c0, 0xc423b980c0)
2018-09-29T12:26:49.68775008Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/compile.go:218 +0x5d0
2018-09-29T12:26:49.687751878Z github.com/cilium/cilium/pkg/datapath/loader.compileDatapath(0x2be9520, 0xc423b63080, 0x2bcfbe0, 0xc423b63020, 0xc421fcf6c0, 0x0, 0x2be94e0, 0xc4200ce010)
2018-09-29T12:26:49.68775375Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:72 +0x3c2
2018-09-29T12:26:49.687756022Z github.com/cilium/cilium/pkg/datapath/loader.compileAndLoad(0x2be9520, 0xc423b63080, 0x2bcfbe0, 0xc423b63020, 0xc421fcf6c0, 0x5baf6e53, 0xc42325fa0b)
2018-09-29T12:26:49.687757943Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:101 +0x79
2018-09-29T12:26:49.687759727Z github.com/cilium/cilium/pkg/datapath/loader.CompileAndLoad(0x2be9520, 0xc423b63080, 0x2bcfbe0, 0xc423b63020, 0xc423b63080, 0xc423b98090)
2018-09-29T12:26:49.687761582Z 	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:122 +0xe0
```

cc: @joestringer

**Comment by joestringer** [comment]
I'm not sure where you got those logs from, but looking at one of the failures below, there seems to be something seriously wrong on the node affecting any command execution.

[6f1a7c4b_RuntimeConnectivityInVethModeTest_Basic_Connectivity_test_Test_connectivity_between_containers_with_policy_imported.zip](https://github.com/cilium/cilium/files/3091577/6f1a7c4b_RuntimeConnectivityInVethModeTest_Basic_Connectivity_test_Test_connectivity_between_containers_with_policy_imported.zip)

#### test-output.log
```
===================== TEST FAILED =====================
time="2019-04-17T12:54:18Z" level=debug msg="running command: sudo cilium endpoint list"
time="2019-04-17T12:54:18Z" level=error msg="Error executing command 'sudo cilium endpoint list'" error="failed to create session: unexpected EOF"
time="2019-04-17T12:54:18Z" level=error msg="Error executing command 'sudo cilium endpoint list'" error="failed to create session: unexpected EOF"
```

@borkmann how did you get those logs? Most of the bugtools from this build are borked due to the above.

**Comment by borkmann** [comment]
> I'm not sure where you got those logs from, but looking at one of the failures below, there seems to be something seriously wrong on the node affecting any command execution.
> 
[6f1a7c4b_RuntimeConnectivityInVethModeTest_Basic_Connectivity_test_Test_connectivity_between_containers_with_policy_imported.zip](https://github.com/cilium/cilium/files/3091577/6f1a7c4b_RuntimeConnectivityInVethModeTest_Basic_Connectivity_test_Test_connectivity_between_containers_with_policy_imported.zip)
> 
> #### test-output.log
> ```
> ===================== TEST FAILED =====================
> time="2019-04-17T12:54:18Z" level=debug msg="running command: sudo cilium endpoint list"
> time="2019-04-17T12:54:18Z" level=error msg="Error executing command 'sudo cilium endpoint list'" error="failed to create session: unexpected EOF"
> time="2019-04-17T12:54:18Z" level=error msg="Error executing command 'sudo cilium endpoint list'" error="failed to create session: unexpected EOF"
> ```
> @borkmann how did you get those logs? Most of the bugtools from this build are borked due to the above.

Appeared to be a flake seen in  #7749.

**Comment by joestringer** [comment]
Seems likely that the above errors come from here, where the test code attempts to SSH into the runtime VM to gather bugtool data, but it gets `EOF`s:

https://github.com/cilium/cilium/blob/5b17c993e57963a86bfa4887b58018e055624086/test/helpers/ssh_command.go#L300-L320

Specifically:

https://github.com/cilium/cilium/blob/5b17c993e57963a86bfa4887b58018e055624086/test/helpers/ssh_command.go#L320

**Comment by joestringer** [comment]
> > @borkmann how did you get those logs? Most of the bugtools from this build are borked due to the above.
> 
> Appeared to be a flake seen in #7749.

Are you able to find & attach the relevant zip files? I am having trouble finding good logs from either the PR #7749 or the jenkins link in the description.

**Comment by joestringer** [comment]
I've filed https://github.com/cilium/cilium/pull/7771 which may help with bounding the context of this execution, but it seems to me like something is seriously interfering with Cilium's ability to run commands on this node so the underlying issue is still not known. Maybe with that PR Cilium will just get a bit further and then have other weird complaints.
