### ISSUE TITLE
CI: potential deadlock / slow endpoint delete

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#7781]
This may be the same issue as https://github.com/cilium/cilium/issues/7760 but I'm not sure. It may simply be a slow delete.
I haven't triaged it too deeply, but eloycoto and I spent some time isolating the issue. The fail is in a nightly build, and those have many creates and deletes of endpoints. Another interesting thing to note is that multiple tests failed and cnp status update controllers failed on all cilium agents. This may be a slow/broken api-server (but the logs there seemed ok).
https://jenkins.cilium.io/job/cilium-master-Nightly/158/testReport/junit/Suite-k8s-1/12/NightlyPolicies_PolicyEnforcement_default_L3_Ingress_Label_L4_Ingress_Port_80_TCP_L7_Egress_policy_to__private__Destination_Direct/

Unfortunately, the test data is larger than github allows me to upload, so ping me if you would like it. The file name is [`ccc7f3cd_NightlyPolicies_PolicyEnforcement_default_L3_Ingress_Label_L4_Ingress_Port_80_TCP_L7_Egress_policy_to_-private-_Destination_Direct.zip`](https://jenkins.cilium.io/job/cilium-master-Nightly/158/testReport/junit/Suite-k8s-1/12/NightlyPolicies_PolicyEnforcement_default_L3_Ingress_Label_L4_Ingress_Port_80_TCP_L7_Egress_policy_to__private__Destination_Direct/attachments/ccc7f3cd_NightlyPolicies_PolicyEnforcement_default_L3%3AIngress_Label_L4%3AIngress_Port_80_TCP_L7%3AEgress_policy_to_-private-_Destination%3ADirect.zip)

In pod-kube-system-cilium-4lk8p-cilium-agent-previous.log from the attached zip:
```
2019-04-18T00:13:35.324308404Z POTENTIAL DEADLOCK:
2019-04-18T00:13:35.324433505Z Previous place where the lock was grabbed
2019-04-18T00:13:35.324475016Z goroutine 60727 lock 0xc00100f348
2019-04-18T00:13:35.324650912Z /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:62 lock.(*internalRWMutex).Lock ??? <<<<<
2019-04-18T00:13:35.324823611Z /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:55 main.(*Daemon).deleteEndpointQuiet ???
2019-04-18T00:13:35.324834577Z /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:55 endpoint.(*Endpoint).UnconditionalLock ???
2019-04-18T00:13:35.324852146Z /go/src/github.com/cilium/cilium/daemon/endpoint.go:509 main.(*Daemon).deleteEndpoint ???
2019-04-18T00:13:35.32493185Z /go/src/github.com/cilium/cilium/daemon/endpoint.go:621 main.(*Daemon).DeleteEndpoint ???
2019-04-18T00:13:35.324989518Z /go/src/github.com/cilium/cilium/daemon/endpoint.go:637 main.(*deleteEndpointID).Handle ???
2019-04-18T00:13:35.325187969Z /go/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/delete_endpoint_id.go:65 endpoint.(*DeleteEndpointID).ServeHTTP ???
2019-04-18T00:13:35.32519764Z /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 middleware.NewOperationExecutor.func1 ???
2019-04-18T00:13:35.326739971Z /usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP ???
2019-04-18T00:13:35.326749527Z /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:76 middleware.NewRouter.func1 ???
2019-04-18T00:13:35.326752278Z /usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP ???
2019-04-18T00:13:35.326758225Z /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 middleware.Redoc.func1 ???
2019-04-18T00:13:35.326867368Z /usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP ???
2019-04-18T00:13:35.326876155Z /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 middleware.Spec.func1 ???
2019-04-18T00:13:35.326878789Z /usr/local/go/src/net/http/server.go:1995 http.HandlerFunc.ServeHTTP ???
2019-04-18T00:13:35.326892988Z /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:69 metrics.(*APIEventTSHelper).ServeHTTP ???
2019-04-18T00:13:35.327009707Z /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:53 api.(*APIPanicHandler).ServeHTTP ???
2019-04-18T00:13:35.32701841Z /usr/local/go/src/net/http/server.go:2774 http.serverHandler.ServeHTTP ???
2019-04-18T00:13:35.327021079Z /usr/local/go/src/net/http/server.go:1878 http.(*conn).serve ???
2019-04-18T00:13:35.327023254Z
2019-04-18T00:13:35.327025325Z Have been trying to lock it again for more than 5m10s
2019-04-18T00:13:35.327051828Z goroutine 61888 lock 0xc00100f348
2019-04-18T00:13:35.327124387Z /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:78 lock.(*internalRWMutex).RLock ??? <<<<<
2019-04-18T00:13:35.327178753Z /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:60 endpoint.(*Endpoint).HasLabels ???
2019-04-18T00:13:35.327185284Z /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:60 endpoint.(*Endpoint).UnconditionalRLock ???
2019-04-18T00:13:35.327235565Z /go/src/github.com/cilium/cilium/daemon/endpoint.go:78 main.getEndpointList.func1 ???
2019-04-18T00:13:35.327280464Z
2019-04-18T00:13:35.34637834Z Here is what goroutine 60727 doing now
2019-04-18T00:13:35.346453425Z goroutine 60727 [semacquire, 5 minutes]:
2019-04-18T00:13:35.346460096Z sync.runtime_Semacquire(0xc0015d26c8)
2019-04-18T00:13:35.346462345Z  /usr/local/go/src/runtime/sema.go:56 +0x39
2019-04-18T00:13:35.34646454Z sync.(*WaitGroup).Wait(0xc0015d26c0)
2019-04-18T00:13:35.346466558Z  /usr/local/go/src/sync/waitgroup.go:130 +0x65
2019-04-18T00:13:35.346468568Z github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Stop.func1()
2019-04-18T00:13:35.346481332Z  /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:272 +0x18a
2019-04-18T00:13:35.346483516Z sync.(*Once).Do(0xc0015d26b4, 0xc002d511d8)
2019-04-18T00:13:35.346485486Z  /usr/local/go/src/sync/once.go:44 +0xb3
2019-04-18T00:13:35.346487461Z github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Stop(0xc0015d2690)
2019-04-18T00:13:35.346489803Z  /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:262 +0x81
2019-04-18T00:13:35.34649182Z main.(*Daemon).deleteEndpointQuiet(0xc000988000, 0xc00100f340, 0xc001650000, 0xa, 0xc001d3d608, 0xc000cd6a00)
2019-04-18T00:13:35.346493874Z  /go/src/github.com/cilium/cilium/daemon/endpoint.go:561 +0x1b6
2019-04-18T00:13:35.346495853Z main.(*Daemon).deleteEndpoint(0xc000988000, 0xc00100f340, 0x0)
2019-04-18T00:13:35.346497787Z  /go/src/github.com/cilium/cilium/daemon/endpoint.go:509 +0x157
2019-04-18T00:13:35.346499752Z main.(*Daemon).DeleteEndpoint(0xc000988000, 0xc001dd4554, 0x4d, 0x1, 0x1, 0xc001dd4620)
2019-04-18T00:13:35.346501783Z  /go/src/github.com/cilium/cilium/daemon/endpoint.go:621 +0xbe
2019-04-18T00:13:35.346503764Z main.(*deleteEndpointID).Handle(0xc00166c090, 0xc00330ce00, 0xc001dd4554, 0x4d, 0xc001155140, 0x0)
2019-04-18T00:13:35.346505779Z  /go/src/github.com/cilium/cilium/daemon/endpoint.go:637 +0x243
2019-04-18T00:13:35.346507847Z github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*DeleteEndpointID).ServeHTTP(0xc001d074a0, 0x340e140, 0xc0011550a0, 0xc00330ce00)
2019-04-18T00:13:35.346509981Z  /go/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/delete_endpoint_id.go:65 +0x177
2019-04-18T00:13:35.346512039Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x340e140, 0xc0011550a0, 0xc00330ce00)
2019-04-18T00:13:35.34651416Z   /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x75
2019-04-18T00:13:35.346516196Z net/http.HandlerFunc.ServeHTTP(0xc002448fd0, 0x340e140, 0xc0011550a0, 0xc00330ce00)
2019-04-18T00:13:35.346518207Z  /usr/local/go/src/net/http/server.go:1995 +0x44
2019-04-18T00:13:35.346520115Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x340e140, 0xc0011550a0, 0xc00330cc00)
2019-04-18T00:13:35.346522142Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:76 +0x358
2019-04-18T00:13:35.34652459Z net/http.HandlerFunc.ServeHTTP(0xc0022c5ca0, 0x340e140, 0xc0011550a0, 0xc00330cc00)
2019-04-18T00:13:35.346526661Z  /usr/local/go/src/net/http/server.go:1995 +0x44
2019-04-18T00:13:35.346528558Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x340e140, 0xc0011550a0, 0xc00330cc00)
2019-04-18T00:13:35.346530581Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x2a5
2019-04-18T00:13:35.346532616Z net/http.HandlerFunc.ServeHTTP(0xc001802fc0, 0x340e140, 0xc0011550a0, 0xc00330cc00)
2019-04-18T00:13:35.346536814Z  /usr/local/go/src/net/http/server.go:1995 +0x44
2019-04-18T00:13:35.346538865Z github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x340e140, 0xc0011550a0, 0xc00330cc00)
2019-04-18T00:13:35.346540999Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x1ad
2019-04-18T00:13:35.34654314Z net/http.HandlerFunc.ServeHTTP(0xc001803000, 0x340e140, 0xc0011550a0, 0xc00330cc00)
2019-04-18T00:13:35.346545135Z  /usr/local/go/src/net/http/server.go:1995 +0x44
2019-04-18T00:13:35.346547045Z github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc001e4d7a0, 0x34275c0, 0xc000665180, 0xc00330cc00)
2019-04-18T00:13:35.346549094Z  /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:69 +0x111
2019-04-18T00:13:35.346551098Z github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0xc001bbcae0, 0x34275c0, 0xc000665180, 0xc00330cc00)
2019-04-18T00:13:35.346553165Z  /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:53 +0x8f
2019-04-18T00:13:35.346555138Z net/http.serverHandler.ServeHTTP(0xc0020f7c70, 0x34275c0, 0xc000665180, 0xc00330cc00)
2019-04-18T00:13:35.346557161Z  /usr/local/go/src/net/http/server.go:2774 +0xa8
2019-04-18T00:13:35.346559101Z net/http.(*conn).serve(0xc001a137c0, 0x3438540, 0xc0034c5c80)
2019-04-18T00:13:35.346561081Z  /usr/local/go/src/net/http/server.go:1878 +0x851
2019-04-18T00:13:35.346563014Z created by net/http.(*Server).Serve
2019-04-18T00:13:35.34664899Z   /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by ianvernon** [comment]
Looks like slow deletion indeed for the endpoint. Are there any additional logs for this endpoint specifically that are present while it is being deleted? We could inspect those logs to possibly see what option is hanging. Perhaps we should add context to endpoint deletion as well?
