### ISSUE TITLE
Segfault when handling rule changes

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#8131]
A panic happened during nightly tests yesterday: https://jenkins.cilium.io/job/cilium-master-Nightly/190/testReport/junit/Suite-k8s-1/12/NightlyPolicies_PolicyEnforcement_default_L3_Ingress_Label_Invalid_L4_No_Policy_L7_No_Policy_Destination_Direct/

My only guess is that this is a race with an uninitialised, or deleting, endpoint but I have no proof (I lost the trail at the policy queue). The order of events would be something like:
- an endpoint ends up in a selector cache somewhere
- updates come in, we roll up the endpoint IDs into epsToRegen
- When we finally handle this event in endpointmanager, a particular endpoint ID isn't present anymore. We don't guard against it not being present so we then break.

I've implemented the obvious solution in https://github.com/cilium/cilium/pull/8132 but I'm not sure that is the actual behaviour we want.

@ianvernon I assigned you only because you might be able to triage this. If not, unassign :)

```
2019-05-28T00:45:59.631681198Z panic: runtime error: invalid memory address or nil pointer dereference
2019-05-28T00:45:59.631700733Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25befb6]
2019-05-28T00:45:59.631703503Z 
2019-05-28T00:45:59.63170562Z goroutine 3144988 [running]:
2019-05-28T00:45:59.631707723Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).LockAlive(0x0, 0xc00188d608, 0xc002290fa8)
2019-05-28T00:45:59.631709798Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:21 +0x26
2019-05-28T00:45:59.631711954Z github.com/cilium/cilium/pkg/endpointmanager.regenerateEndpointNonBlocking(0x369b200, 0xc0003d4900, 0x0, 0xc00284d3b0)
2019-05-28T00:45:59.631714064Z 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:436 +0x43
2019-05-28T00:45:59.631716103Z github.com/cilium/cilium/pkg/endpointmanager.RegenerateEndpointSetSignalWhenEnqueued.func1(0x369b200, 0xc0003d4900, 0x0, 0xc00284d3b0, 0xc001316de0)
2019-05-28T00:45:59.631718164Z 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:458 +0x49
2019-05-28T00:45:59.631720125Z created by github.com/cilium/cilium/pkg/endpointmanager.RegenerateEndpointSetSignalWhenEnqueued
2019-05-28T00:45:59.631722537Z 	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:457 +0x12b
2019-05-28T00:45:59.652524953Z level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
```

I have the whole test run but it is too large, so I've attached only the logs for the cilium instance.
[pod-kube-system-cilium-g4hx8-cilium-agent-previous.log.tar.gz](https://github.com/cilium/cilium/files/3226975/pod-kube-system-cilium-g4hx8-cilium-agent-previous.log.tar.gz)
[pod-kube-system-cilium-g4hx8-cilium-agent.log](https://github.com/cilium/cilium/files/3226963/pod-kube-system-cilium-g4hx8-cilium-agent.log)

**Comment by ianvernon** [comment]
I think the endpoint we are putting into the endpointmanager is nil - which is strange, since I would expect that we'd never actually set endpoints to be nil, and would leave them to be GC'd.

**Comment by ianvernon** [comment]
@raybejjani I've assigned this to you since you have opened #8132 .
