### ISSUE TITLE
cilium: panic: interface conversion: *nat.NatKey4 is not tuple.TupleKey: missing method ToHost

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#8399]
On latest master /cc @aanm :
```
# ./cilium/cilium bpf nat list
panic: interface conversion: *nat.NatKey4 is not tuple.TupleKey: missing method ToHost

goroutine 1 [running]:
github.com/cilium/cilium/pkg/maps/nat.(*Map).DumpEntries.func1(0x1bca5e0, 0xc000525170, 0x1bb8420, 0xc0000b46f0)
	/root/go/src/github.com/cilium/cilium/pkg/maps/nat/nat.go:121 +0x57
github.com/cilium/cilium/pkg/bpf.(*Map).DumpWithCallback(0xc00020ee00, 0xc000567b40, 0x0, 0x0)
	/root/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:586 +0x500
github.com/cilium/cilium/pkg/maps/nat.(*Map).DumpEntries(0xc00020ee00, 0x1a61b10, 0xc00020ee00, 0x0, 0x0)
	/root/go/src/github.com/cilium/cilium/pkg/maps/nat/nat.go:128 +0x8a
github.com/cilium/cilium/cilium/cmd.dumpNat()
	/root/go/src/github.com/cilium/cilium/cilium/cmd/bpf_nat_list.go:65 +0x221
github.com/cilium/cilium/cilium/cmd.glob..func12(0x2d49620, 0x3307fa0, 0x0, 0x0)
	/root/go/src/github.com/cilium/cilium/cilium/cmd/bpf_nat_list.go:35 +0x3b
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x2d49620, 0x3307fa0, 0x0, 0x0, 0x2d49620, 0x3307fa0)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2d53540, 0x1, 0x1, 0x2d532e0)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:850 +0x2f8
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x2d53540, 0x407850, 0xc00009c058)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cilium/cilium/cilium/cmd.Execute()
	/root/go/src/github.com/cilium/cilium/cilium/cmd/root.go:47 +0x2d
main.main()
	/root/go/src/github.com/cilium/cilium/cilium/main.go:22 +0x20
```

**Comment by borkmann** [comment]
And flush panic is slightly different:
```
# ./cilium/cilium bpf nat flush
panic: interface conversion: bpf.MapKey is *nat.NatKey4, not *tuple.TupleKey4Global

goroutine 1 [running]:
github.com/cilium/cilium/pkg/maps/nat.doFlush4.func1(0x1bca5e0, 0xc000538fb0, 0x1bb8420, 0xc000232e70)
	/root/go/src/github.com/cilium/cilium/pkg/maps/nat/nat.go:151 +0x185
github.com/cilium/cilium/pkg/bpf.(*Map).DumpReliablyWithCallback(0xc0001f6f00, 0xc000559b30, 0xc000427f90, 0x0, 0x0)
	/root/go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:697 +0x833
github.com/cilium/cilium/pkg/maps/nat.doFlush4(0xc0001f6f00, 0xc0000ec530, 0xc000559bc0, 0x18, 0xc000559bb8)
	/root/go/src/github.com/cilium/cilium/pkg/maps/nat/nat.go:159 +0xa3
github.com/cilium/cilium/pkg/maps/nat.(*Map).Flush(0xc0001f6f00, 0x1a61b10)
	/root/go/src/github.com/cilium/cilium/pkg/maps/nat/nat.go:181 +0x39
github.com/cilium/cilium/cilium/cmd.flushNat()
	/root/go/src/github.com/cilium/cilium/cilium/cmd/bpf_nat_flush.go:54 +0x1d4
github.com/cilium/cilium/cilium/cmd.glob..func11(0x2d493c0, 0x3307fa0, 0x0, 0x0)
	/root/go/src/github.com/cilium/cilium/cilium/cmd/bpf_nat_flush.go:33 +0x3b
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x2d493c0, 0x3307fa0, 0x0, 0x0, 0x2d493c0, 0x3307fa0)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2d53540, 0x1, 0x1, 0x2d532e0)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:850 +0x2f8
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x2d53540, 0x407850, 0xc00009c058)
	/root/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/cilium/cilium/cilium/cmd.Execute()
	/root/go/src/github.com/cilium/cilium/cilium/cmd/root.go:47 +0x2d
main.main()
	/root/go/src/github.com/cilium/cilium/cilium/main.go:22 +0x20
```
