### ISSUE TITLE
CI: panic in CI code

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8492]
Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7620/execution/node/160/log/

```
21:25:12  ===================== TEST FAILED =====================
21:25:12  panic: runtime error: invalid memory address or nil pointer dereference
21:25:12  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137e249]
21:25:12  
21:25:12  goroutine 116 [running]:
21:25:12  github.com/cilium/cilium/test/helpers.(*Kubectl).GetPodNamesContext(0x0, 0x1a61820, 0xc000770480, 0x17bdc15, 0xb, 0x17c26ad, 0xe, 0x0, 0x0, 0x0, ...)
21:25:12  	/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:330 +0x219
21:25:12  github.com/cilium/cilium/test/helpers.(*Kubectl).GetCiliumPodsContext(...)
21:25:12  	/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:1060
21:25:12  github.com/cilium/cilium/test/helpers.(*Kubectl).DumpCiliumCommandOutput(0x0, 0x1a61820, 0xc000770480, 0x17bdc15, 0xb)
21:25:12  	/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:1758 +0xdf
21:25:12  github.com/cilium/cilium/test/helpers.(*Kubectl).CiliumReport.func1(0xc000352660, 0x0, 0x1a61820, 0xc000770480, 0x17bdc15, 0xb)
21:25:12  	/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:1485 +0x7d
21:25:12  created by github.com/cilium/cilium/test/helpers.(*Kubectl).CiliumReport
21:25:12  	/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/helpers/kubectl.go:1483 +0x138
21:25:12  
```

**Comment by ianvernon** [comment]
Not observed for some time, closing.
