### ISSUE TITLE
Cilium agent panics at https://github.com/cilium/cilium/blob/master/pkg/endpointmanager/manager.go#L407 with nil pointer exception

### ISSUE THREAD

**Issue by bsiravara** [cilium/cilium#8816]
Code inspection does not point to an obvious reason for panic.
Both callsites to the function in Cilium (RegenerateAllEndpoints) populate the value in question with a non-nil string

Filed https://github.com/sirupsen/logrus/issues/1003 with logrus

**Comment by ianvernon** [comment]
PR which moved the dereference out of the `WithFields` call: https://github.com/cilium/cilium/pull/8810

This was made to make debugging this issue easier if it is hit again. The upstream issue is the main focus to RCA what happened.

**Comment by tgraf** [comment]
Workaround merged via #8810. User has not seen this again.

**Comment by aanm** [comment]
This issue is not fixed

**Comment by sebfaerber** [comment]
I think we hit the same issue today running:
Cilium 1.6.5 88642ed70 2019-12-16T07:21:37-08:00 go version go1.12.14 linux/amd64" subsys=daemon
```
/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x130
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:210 +0x2d7
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0008ad400)
/go/src/github.com/cilium/cilium/daemon/policy.go:74 +0xe3
main.(*Daemon).policyUpdateTrigger(0xc00000c3c0, 0xc000690000, 0x1, 0x1)
/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:466 +0x1c1
github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints(0xc002336090, 0xc002336090)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:285
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Info(...)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:268 +0xed
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc000ff0000, 0xc000000004, 0xc001b47ce0, 0x1, 0x1)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:231 +0x193
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000f2480, 0xc0023360c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:255 +0x81
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).write(0xc000ff0070)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:202 +0xa52
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).Format(0xc00010c730, 0xc000ff0070, 0xc0000f24b0, 0xc001b47b18, 0x381e718, 0x0, 0xc001b47b18)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:285 +0x90
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendKeyValue(0xc00010c730, 0xc0023360f0, 0x342880c, 0x6, 0x2fca580, 0xc000690020)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:294 +0x6d
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendValue(0xc00010c730, 0xc0023360f0, 0x2fca580, 0xc000690020)
/go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:268 +0x4e
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).needsQuoting(0xc00010c730, 0x2, 0x8c, 0x1c)
goroutine 49 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x144ca1e]
panic: runtime error: invalid memory address or nil pointer dereference
level=info msg="Waiting for endpoint to be generated" containerID=2148d83e4a datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2936 ipv4=172.16.4.160 ipv6= k8sPodName=test/test-0-7685c7fbf5-t7v6w subsys=daemon
```

**Comment by aanm** [comment]
@sebfaerber thanks for the comment.

We are still tracking this bug. If possible please deploy the following cilium docker image:

`docker.io/cilium/cilium-dev:v1.6.5-with-panic-recover`

It is exactly as the v1.6.5 and the only difference is that it contains more log statements when that bug is hit. You can check the diff here: https://github.com/cilium/cilium/commit/e07ce6f6c6b24f0c33661776722da1df5ef8c6fe

Thank you!

**Comment by sebfaerber** [comment]
> We are still tracking this bug. If possible please deploy the following cilium docker image (it might take ~20 minutes for the tag to be built as I just have triggered the build now):
> 
> `docker.io/cilium/cilium-dev:v1.6.5-with-panic-recover`

Thanks @aanm, running this docker image now and will report back once we hit the bug again.
Hasn't happend again yet, but we noticed another panic (no segfault) - maybe it's related?

```
/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0xaa
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
/usr/local/go/src/sync/once.go:44 +0xb3
sync.(*Once).Do(0xc000bfe858, 0xc000689190)
/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:256 +0x150
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1()
/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x466
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0000a1550, 0xc00271c780)
/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:348 +0xdcd
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0004fac80, 0xc002dc7400, 0x0, 0x0)
/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:370 +0x116
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).updateRealizedState(0xc0004fac80, 0xc002dc7410, 0xc002e6ea20, 0x19, 0x1, 0x0, 0x0, 0x0)
/go/src/github.com/cilium/cilium/pkg/endpoint/directory.go:120 +0x9be
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).synchronizeDirectories(0xc0004fac80, 0xc002e6ea20, 0x19, 0xc002dc7500, 0x0, 0x0)
/go/src/github.com/cilium/cilium/common/utils.go:94 +0x4d
github.com/cilium/cilium/common.MoveNewFilesTo(0xc0030076b0, 0x9, 0xc002e6ea20, 0x19, 0x1, 0x0)
/usr/local/go/src/io/ioutil/ioutil.go:106 +0x161
io/ioutil.ReadDir(0xc0030076b0, 0x9, 0x108, 0xffffffffffffff9c, 0xc003007700, 0xffffffffffffff9c, 0xc002bdd920)
/usr/local/go/src/sort/slice.go:21 +0x129
sort.Slice(0x2f793c0, 0xc0012221c0, 0xc00209ef98)
/usr/local/go/src/sort/zfuncversion.go:143 +0x9a
sort.quickSort_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x406eb188ec4, 0x56)
/usr/local/go/src/sort/zfuncversion.go:76 +0x4f9
sort.doPivot_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x406eb188ec4, 0x3078f20, 0x8)
/usr/local/go/src/sort/zfuncversion.go:53 +0x3e
sort.medianOfThree_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x80dd6311d8, 0x101bac623b0)
/usr/local/go/src/io/ioutil/ioutil.go:106 +0xd5
io/ioutil.ReadDir.func1(0x0, 0x80dd6311d8, 0x31ac880)
goroutine 702 [running]:
panic: runtime error: index out of range
level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager```

**Comment by aanm** [comment]
> > We are still tracking this bug. If possible please deploy the following cilium docker image (it might take ~20 minutes for the tag to be built as I just have triggered the build now):
> > `docker.io/cilium/cilium-dev:v1.6.5-with-panic-recover`
> 
> Thanks @aanm, running this docker image now and will report back once we hit the bug again.
> Hasn't happend again yet, but we noticed another panic (no segfault) - maybe it's related?
> 
> ```
> /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0xaa
> created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
> /usr/local/go/src/sync/once.go:44 +0xb3
> sync.(*Once).Do(0xc000bfe858, 0xc000689190)
> /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:256 +0x150
> github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1()
> /go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x466
> github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0000a1550, 0xc00271c780)
> /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:348 +0xdcd
> github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0004fac80, 0xc002dc7400, 0x0, 0x0)
> /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:370 +0x116
> github.com/cilium/cilium/pkg/endpoint.(*Endpoint).updateRealizedState(0xc0004fac80, 0xc002dc7410, 0xc002e6ea20, 0x19, 0x1, 0x0, 0x0, 0x0)
> /go/src/github.com/cilium/cilium/pkg/endpoint/directory.go:120 +0x9be
> github.com/cilium/cilium/pkg/endpoint.(*Endpoint).synchronizeDirectories(0xc0004fac80, 0xc002e6ea20, 0x19, 0xc002dc7500, 0x0, 0x0)
> /go/src/github.com/cilium/cilium/common/utils.go:94 +0x4d
> github.com/cilium/cilium/common.MoveNewFilesTo(0xc0030076b0, 0x9, 0xc002e6ea20, 0x19, 0x1, 0x0)
> /usr/local/go/src/io/ioutil/ioutil.go:106 +0x161
> io/ioutil.ReadDir(0xc0030076b0, 0x9, 0x108, 0xffffffffffffff9c, 0xc003007700, 0xffffffffffffff9c, 0xc002bdd920)
> /usr/local/go/src/sort/slice.go:21 +0x129
> sort.Slice(0x2f793c0, 0xc0012221c0, 0xc00209ef98)
> /usr/local/go/src/sort/zfuncversion.go:143 +0x9a
> sort.quickSort_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x406eb188ec4, 0x56)
> /usr/local/go/src/sort/zfuncversion.go:76 +0x4f9
> sort.doPivot_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x406eb188ec4, 0x3078f20, 0x8)
> /usr/local/go/src/sort/zfuncversion.go:53 +0x3e
> sort.medianOfThree_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x80dd6311d8, 0x101bac623b0)
> /usr/local/go/src/io/ioutil/ioutil.go:106 +0xd5
> io/ioutil.ReadDir.func1(0x0, 0x80dd6311d8, 0x31ac880)
> goroutine 702 [running]:
> panic: runtime error: index out of range
> level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
> level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager```
> ```

@sebfaerber that is a new bug. Do you have any logs from that run?

**Comment by sebfaerber** [comment]
@aanm Yes, here are the full logs for the "index out of range" panic:

```

2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0xaa
2020-02-10 12:37:01	created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
2020-02-10 12:37:01	/usr/local/go/src/sync/once.go:44 +0xb3
2020-02-10 12:37:01	sync.(*Once).Do(0xc000bfe858, 0xc000689190)
2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:256 +0x150
2020-02-10 12:37:01	github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1()
2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x466
2020-02-10 12:37:01	github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0000a1550, 0xc00271c780)
2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:348 +0xdcd
2020-02-10 12:37:01	github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0004fac80, 0xc002dc7400, 0x0, 0x0)
2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:370 +0x116
2020-02-10 12:37:01	github.com/cilium/cilium/pkg/endpoint.(*Endpoint).updateRealizedState(0xc0004fac80, 0xc002dc7410, 0xc002e6ea20, 0x19, 0x1, 0x0, 0x0, 0x0)
2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/pkg/endpoint/directory.go:120 +0x9be
2020-02-10 12:37:01	github.com/cilium/cilium/pkg/endpoint.(*Endpoint).synchronizeDirectories(0xc0004fac80, 0xc002e6ea20, 0x19, 0xc002dc7500, 0x0, 0x0)
2020-02-10 12:37:01	/go/src/github.com/cilium/cilium/common/utils.go:94 +0x4d
2020-02-10 12:37:01	github.com/cilium/cilium/common.MoveNewFilesTo(0xc0030076b0, 0x9, 0xc002e6ea20, 0x19, 0x1, 0x0)
2020-02-10 12:37:01	/usr/local/go/src/io/ioutil/ioutil.go:106 +0x161
2020-02-10 12:37:01	io/ioutil.ReadDir(0xc0030076b0, 0x9, 0x108, 0xffffffffffffff9c, 0xc003007700, 0xffffffffffffff9c, 0xc002bdd920)
2020-02-10 12:37:01	/usr/local/go/src/sort/slice.go:21 +0x129
2020-02-10 12:37:01	sort.Slice(0x2f793c0, 0xc0012221c0, 0xc00209ef98)
2020-02-10 12:37:01	/usr/local/go/src/sort/zfuncversion.go:143 +0x9a
2020-02-10 12:37:01	sort.quickSort_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x406eb188ec4, 0x56)
2020-02-10 12:37:01	/usr/local/go/src/sort/zfuncversion.go:76 +0x4f9
2020-02-10 12:37:01	sort.doPivot_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x406eb188ec4, 0x3078f20, 0x8)
2020-02-10 12:37:01	/usr/local/go/src/sort/zfuncversion.go:53 +0x3e
2020-02-10 12:37:01	sort.medianOfThree_func(0xc00209ef98, 0xc00213a5d0, 0x0, 0x80dd6311d8, 0x101bac623b0)
2020-02-10 12:37:01	/usr/local/go/src/io/ioutil/ioutil.go:106 +0xd5
2020-02-10 12:37:01	io/ioutil.ReadDir.func1(0x0, 0x80dd6311d8, 0x31ac880)
2020-02-10 12:37:01	goroutine 702 [running]:
2020-02-10 12:37:01	
2020-02-10 12:37:01	panic: runtime error: index out of range
2020-02-10 12:37:01	level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
2020-02-10 12:37:00	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-02-10 12:37:00	level=info msg="Waiting for endpoint to be generated" containerID=e46026671d datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3716 ipv4=172.16.8.164 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-2074dn6 subsys=daemon
2020-02-10 12:37:00	level=info msg="Identity of endpoint changed" containerID=e46026671d datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3716 identity=24079 identityLabels="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=gitlab,k8s:pod=runner-cscw8mci-project-203-concurrent-20" ipv4=172.16.8.164 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-2074dn6 oldIdentity="no identity" subsys=endpoint
2020-02-10 12:37:00	level=info msg="Reusing existing global key" key="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=gitlab;k8s:pod=runner-cscw8mci-project-203-concurrent-20;" subsys=allocator
2020-02-10 12:37:00	level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=gitlab;k8s:pod=runner-cscw8mci-project-203-concurrent-20;': identity does not exist" key="[k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=gitlab k8s:pod=runner-cscw8mci-project-203-concurrent-20]" subsys=allocator
2020-02-10 12:37:00	level=info msg="Skipped non-kubernetes labels when labelling ciliumidentity. All labels will still be used in identity determination" labels="map[]" subsys=crd-allocator
2020-02-10 12:37:00	level=info msg="Resolving identity labels (blocking)" containerID=e46026671d datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3716 identityLabels="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=gitlab,k8s:pod=runner-cscw8mci-project-203-concurrent-20" ipv4=172.16.8.164 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-2074dn6 subsys=endpoint
2020-02-10 12:37:00	level=info msg="New endpoint" containerID=e46026671d datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3716 ipv4=172.16.8.164 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-2074dn6 subsys=endpoint
2020-02-10 12:36:59	level=info msg="Successful endpoint creation" containerID=21de0d5deb datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=207 identity=57507 ipv4=172.16.8.151 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-1126b6f subsys=daemon
2020-02-10 12:36:59	level=info msg="Rewrote endpoint BPF program" containerID=21de0d5deb datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=207 identity=57507 ipv4=172.16.8.151 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-1126b6f subsys=endpoint
2020-02-10 12:36:59	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-02-10 12:36:58	level=info msg="Waiting for endpoint to be generated" containerID=21de0d5deb datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=207 ipv4=172.16.8.151 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-1126b6f subsys=daemon
2020-02-10 12:36:58	level=info msg="Identity of endpoint changed" containerID=21de0d5deb datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=207 identity=57507 identityLabels="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=gitlab,k8s:pod=runner-cscw8mci-project-203-concurrent-11" ipv4=172.16.8.151 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-1126b6f oldIdentity="no identity" subsys=endpoint
2020-02-10 12:36:58	level=info msg="Reusing existing global key" key="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=gitlab;k8s:pod=runner-cscw8mci-project-203-concurrent-11;" subsys=allocator
2020-02-10 12:36:58	level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=gitlab;k8s:pod=runner-cscw8mci-project-203-concurrent-11;': identity does not exist" key="[k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=gitlab k8s:pod=runner-cscw8mci-project-203-concurrent-11]" subsys=allocator
2020-02-10 12:36:58	level=info msg="Skipped non-kubernetes labels when labelling ciliumidentity. All labels will still be used in identity determination" labels="map[]" subsys=crd-allocator
2020-02-10 12:36:58	level=info msg="Resolving identity labels (blocking)" containerID=21de0d5deb datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=207 identityLabels="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=gitlab,k8s:pod=runner-cscw8mci-project-203-concurrent-11" ipv4=172.16.8.151 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-1126b6f subsys=endpoint
2020-02-10 12:36:58	level=info msg="New endpoint" containerID=21de0d5deb datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=207 ipv4=172.16.8.151 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-1126b6f subsys=endpoint
2020-02-10 12:36:58	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-02-10 12:36:57	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-02-10 12:36:56	level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
2020-02-10 12:36:56	level=info msg="Successful endpoint creation" containerID=b52bb48880 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1845 identity=32588 ipv4=172.16.8.108 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-3nf7kh subsys=daemon
2020-02-10 12:36:56	level=info msg="Rewrote endpoint BPF program" containerID=b52bb48880 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1845 identity=32588 ipv4=172.16.8.108 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-3nf7kh subsys=endpoint
2020-02-10 12:36:55	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-02-10 12:36:55	level=info msg="Waiting for endpoint to be generated" containerID=b52bb48880 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1845 ipv4=172.16.8.108 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-3nf7kh subsys=daemon
2020-02-10 12:36:55	level=info msg="Identity of endpoint changed" containerID=b52bb48880 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1845 identity=32588 identityLabels="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=gitlab,k8s:pod=runner-cscw8mci-project-203-concurrent-3" ipv4=172.16.8.108 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-3nf7kh oldIdentity="no identity" subsys=endpoint
2020-02-10 12:36:55	level=info msg="Reusing existing global key" key="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=gitlab;k8s:pod=runner-cscw8mci-project-203-concurrent-3;" subsys=allocator
2020-02-10 12:36:55	level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=gitlab;k8s:pod=runner-cscw8mci-project-203-concurrent-3;': identity does not exist" key="[k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=gitlab k8s:pod=runner-cscw8mci-project-203-concurrent-3]" subsys=allocator
2020-02-10 12:36:55	level=info msg="Skipped non-kubernetes labels when labelling ciliumidentity. All labels will still be used in identity determination" labels="map[]" subsys=crd-allocator
2020-02-10 12:36:55	level=info msg="Resolving identity labels (blocking)" containerID=b52bb48880 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1845 identityLabels="k8s:io.cilium.k8s.namespace.labels.fluxcd.io/sync-gc-mark=sha256.lVd9JDBre0iT-r25DP5tpo9XAOHDt30GhKamogPLCCo,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=gitlab,k8s:pod=runner-cscw8mci-project-203-concurrent-3" ipv4=172.16.8.108 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-3nf7kh subsys=endpoint
2020-02-10 12:36:55	level=info msg="New endpoint" containerID=b52bb48880 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1845 ipv4=172.16.8.108 ipv6= k8sPodName=gitlab/runner-cscw8mci-project-203-concurrent-3nf7kh subsys=endpoint
2020-02-10 12:36:54	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-02-10 12:24:59	level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager```

**Comment by aanm** [comment]
@sebfaerber sorry, I meant the logs before the panic, not after.

**Comment by sebfaerber** [comment]
> @sebfaerber sorry, I meant the logs before the panic, not after.
The logs are from right before the panic. My logging stack displays them from oldest to newest (see timestamps).

**Comment by aanm** [comment]
@sebfaerber that's another occurrence of the same bug. Do you have any way to replicate this or it just happens occasionally?
