### ISSUE TITLE
panic when running cnitool with Cilium

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#923]
```core@ip-10-3-0-12 /opt/cni/bin $ sudo -E ./cnitool add cilium /proc/21409/ns/net
DEBU[0000] ADD &{cni /proc/21409/ns/net eth0  /opt/cni/bin {
    "name": "cilium",
    "type": "cilium-cni",
    "mtu": 1450
}
} 
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
github.com/cilium/cilium/common/plugins.SetupVeth(0xc42000c190, 0x3, 0x5aa, 0xc420078ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/common/plugins/add_endpoint.go:45 +0xf29
main.cmdAdd(0xc42015bb90, 0x0, 0x0)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/plugins/cilium-cni/cilium-cni.go:297 +0x650
github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc4203dc140, 0xc42015bb90, 0x1693500, 0xc420315050, 0xf9f9f0, 0x0, 0x40)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:162 +0x19f
github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc4203dc140, 0xf9f9f0, 0xf9f9f8, 0x1693500, 0xc420315050, 0x73d95d1e)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:173 +0x2f8
github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0xf9f9f0, 0xf9f9f8, 0x1693500, 0xc420315050, 0xc420058058)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0xed
github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0xf9f9f0, 0xf9f9f8, 0x1693500, 0xc420315050)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:222 +0x56
main.main()
	/tmp/cilium-net-build/src/github.com/cilium/cilium/plugins/cilium-cni/cilium-cni.go:66 +0x51
netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input```

**Comment by aanm** [comment]
What was the container's ID?

**Comment by tgraf** [comment]
A random one
