### ISSUE TITLE
deadlock can occur if AllocatorEventChan buffer is full and attempts to allocate local CIDR identities are in flight

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9292]
A user reported that `cilium endpoint list` fails with a context deadline exceeded.

When looking into the agent logs, there are a few instances of:

```
cilium.io/agent: "endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1037 error="context canceled" identity=4 ipv4=10.0.124.181 ipv6= k8sPodName=/ subsys=endpoint
```

From the gops stack traces:

```
 goroutine 658 [chan receive, 15 minutes]:
main.(*Daemon).regenerateRestoredEndpoints.func1(0xc00000c3c0, 0xc000176780, 0xc002d0dce0)
    /go/src/github.com/cilium/cilium/daemon/state.go:365 +0x5b9
created by main.(*Daemon).regenerateRestoredEndpoints
    /go/src/github.com/cilium/cilium/daemon/state.go:261 +0x61f

[...]

goroutine 843 [semacquire, 15 minutes]:
sync.runtime_SemacquireMutex(0xc0001e5198, 0x7ffff80000000000)
    /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001e5194)
    /usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc0001e5194)
    /usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).LockAlive(0xc0001e5180, 0x0, 0x0)
    /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:21 +0x3a
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RegenerateIfAlive(0xc0001e5180, 0xc0021b0c60, 0xc002b3bc20)
    /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:419 +0x43
github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints.func1(0xc0021b0c60, 0xc002b24630, 0xc0001e5180)
    /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:434 +0x35
created by github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints
    /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:433 +0x207
```

From the cilium-agent logs I can see that the user has imported a few network policies (with FQDN) which could have triggered the latter regeneration.

Worth noting that a previous instance of the cilium-agent has been killed by OOM killer most likely due to the FQDN cache size increase.

Cilium: v1.6.1 + some custom patches.

**Comment by ianvernon** [comment]
The root cause is that there is a deadlock due to a mutex being acquired in one goroutine, with that same goroutine trying to send to a buffered channel which is full, while another goroutine, which receives off of that buffered channel, also has logic to try to acquire the same lock which the goroutine which is trying to send on the buffered channel has already acquired. As a result, the buffered channel is never drained, and the goroutine trying to send on the channel will never release the lock which the goroutine that is trying to acquire the lock would subsequently drain.

Registration of FQDNSelector in SelectorCache tries to allocate IPs for CIDRs upon bootstrap. The goroutine is blocking on sending to the `events` channel:
```
1 occurences. Sample stack trace:
github.com/cilium/cilium/pkg/identity/cache.(*localIdentityCache).lookupOrCreate(0xc00005d040, 0xc001710fc0, 0x0, 0xc002910c00, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/identity/cache/local.go:106 +0x340
github.com/cilium/cilium/pkg/identity/cache.AllocateIdentity(0x35eadc0, 0xc000e854a0, 0x0, 0x0, 0xc001710fc0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/identity/cache/allocator.go:292 +0xa36
github.com/cilium/cilium/pkg/ipcache.allocateCIDRs(0xc00037d200, 0x4a8, 0x4a8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:71 +0x21a
github.com/cilium/cilium/pkg/ipcache.AllocateCIDRsForIPs(0xc00241c000, 0x4a8, 0x1d55, 0x1, 0x1, 0xc00296e360, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:49 +0x65
github.com/cilium/cilium/pkg/fqdn.(*NameManager).RegisterForIdentityUpdates(0xc000f27ce0, 0x0, 0x0, 0xc00087c1c0, 0x14, 0xc002c9d100, 0x2f, 0x7fd7a03eed98)
        /go/src/github.com/cilium/cilium/pkg/fqdn/name_manager.go:102 +0xa5d
github.com/cilium/cilium/pkg/policy.(*SelectorCache).AddFQDNSelector(0xc000226bc0, 0x357a360, 0xc001732a80, 0x0, 0x0, 0xc00087c1c0, 0x14, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:554 +0x2fd
```

the `watch` function in the `identityWatcher` is responsible for draining the `events` channel to which the above goroutine is trying to send. However, the `watch` function also calls into `UpdateIdentities` synchronously, which tries to acquire the lock for the `SelectorCache`, of which the above stack trace has possession:
```
1 occurences. Sample stack trace:
sync.runtime_SemacquireMutex(0xc000226bc4, 0xc0011f3500)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc000226bc0)
        /usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc000226bc0)
        /usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cilium/cilium/pkg/policy.(*SelectorCache).UpdateIdentities(0xc000226bc0, 0xc002f32ae0, 0xc002f32b10)
        /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:690 +0x45
main.(*Daemon).UpdateIdentities(0xc00000c3c0, 0xc002f32ae0, 0xc002f32b10)
        /go/src/github.com/cilium/cilium/daemon/policy.go:96 +0x48
github.com/cilium/cilium/pkg/identity/cache.(*identityWatcher).watch.func1(0xc0008fa300, 0x4ebcbf0, 0x35a8840, 0xc00000c3c0)
        /go/src/github.com/cilium/cilium/pkg/identity/cache/cache.go:194 +0x213
created by github.com/cilium/cilium/pkg/identity/cache.(*identityWatcher).watch
        /go/src/github.com/cilium/cilium/pkg/identity/cache/cache.go:143 +0x8d
```

As such, the buffered channel is never drained, and we have a deadlock.
