### ISSUE TITLE
CI: Suite-runtime.RuntimeKVStoreTest Consul KVStore: Found a JoinEP: Failed to load tc filter: signal: terminated

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#9301]
Seen on master from time to time: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/3577/
```
Stacktrace

/home/jenkins/workspace/cilium-ginkgo_cilium_master/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:347
Found a "JoinEP: " in Cilium Logs
/home/jenkins/workspace/cilium-ginkgo_cilium_master/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:536

Standard Output

⚠️  Found a "JoinEP: " in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 5
⚠️  Number of "level=warning" in logs: 6
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 3
Top 5 errors/warnings:
Error while rewriting endpoint BPF program
endpoint regeneration failed
JoinEP: Failed to load program
generating BPF for endpoint failed, keeping stale directory.
Regeneration of endpoint failed

Standard Error

STEP: Starting Cilium with consul as kvstore
STEP: Restarting cilium-docker service
=== Test Finished at 2019-09-27T20:33:42Z====
===================== TEST FAILED =====================
cmd: sudo cilium endpoint list
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error: cannot get endpoint list: Get http:///var/run/cilium/cilium.sock/v1/endpoint: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
	 Is the agent running?
	 
	 

cmd: sudo cilium status
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
	 Is the agent running?
```

**Comment by joestringer** [comment]
New report: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15236/

[test_results_Cilium-PR-Ginkgo-Tests-Validated_15236_BDD-Test-PR-runtime.zip](https://github.com/cilium/cilium/files/3683316/test_results_Cilium-PR-Ginkgo-Tests-Validated_15236_BDD-Test-PR-runtime.zip)

**Comment by joestringer** [comment]
From the Cilium logs pointed to from the issue description (tail, grepped to remove info and debug level):

```
Sep 27 20:33:27 runtime systemd[1]: Stopping cilium...
Sep 27 20:33:27 runtime cilium-agent[14488]: level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3540_next/bpf_lxc.o sec from-container]" error="signal: terminated" subsys=datapath-loader
Sep 27 20:33:27 runtime cilium-agent[14488]: level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to load tc filter: signal: terminated" file-path=3540_next/bpf_lxc.o identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=datapath-loader veth=lxc_health
Sep 27 20:33:27 runtime cilium-agent[14488]: level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to load tc filter: signal: terminated" identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=endpoint
Sep 27 20:33:27 runtime cilium-agent[14488]: level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 file-path=3540_next_fail identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=endpoint
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 [running]:
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 runtime/debug.Stack(0xbf5bba659727133c, 0x1e1925b60, 0x53777a0)
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc000413820)
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:97 +0xc4
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc000413600, 0xc0012c6000, 0x382f9e0, 0xc0001a7520)
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:335 +0xd64
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0001a79f0, 0xc000795320)
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x467
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1()
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:260 +0x17e
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 sync.(*Once).Do(0xc0010a5318, 0xc0001a6e90)
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/usr/local/go/src/sync/once.go:44 +0xb3
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
Sep 27 20:33:27 runtime cilium-agent[14488]: goroutine 1135 	/home/vagrant/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:248 +0xaa
Sep 27 20:33:27 runtime cilium-agent[14488]: level=warning msg="Regeneration of endpoint failed" bpfCompilation=1.220906445s bpfLoadProg=177.631448ms bpfWaitForELF=1.221097906s bpfWriteELF="242.317µs" buildDuration=1.404778814s containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to load tc filter: signal: terminated" identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ mapSync="75.148µs" policyCalculation="128.849µs" prepareBuild="348.88µs" proxyConfiguration="2.646µs" proxyPolicyCalculation="151.086µs" proxyWaitForAck=0s reason="updated security labels" subsys=endpoint waitingForCTClean="8.615µs" waitingForLock="20.13µs"
Sep 27 20:33:27 runtime cilium-agent[14488]: level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to load tc filter: signal: terminated" identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=endpoint
Sep 27 20:33:27 runtime cilium-agent[14488]: level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to replace Qdisc for lxc_health: Link not found" file-path=3540_next/bpf_lxc.o identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=datapath-loader veth=lxc_health
Sep 27 20:33:27 runtime cilium-agent[14488]: level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to replace Qdisc for lxc_health: Link not found" identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=endpoint
Sep 27 20:33:27 runtime cilium-agent[14488]: level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 file-path=3540_next_fail identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=endpoint
Sep 27 20:33:27 runtime cilium-agent[14488]: level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg="133.107µs" bpfWaitForELF="20.35µs" bpfWriteELF="308.229µs" buildDuration=18.91606ms containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to replace Qdisc for lxc_health: Link not found" identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ mapSync="25.721µs" policyCalculation="317.826µs" prepareBuild="747.637µs" proxyConfiguration="1.954µs" proxyPolicyCalculation="969.749µs" proxyWaitForAck=0s reason="retrying regeneration" subsys=endpoint waitingForCTClean=5.433036ms waitingForLock="48.473µs"
Sep 27 20:33:27 runtime cilium-agent[14488]: level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3540 error="Failed to replace Qdisc for lxc_health: Link not found" identity=4 ipv4=10.15.194.172 ipv6="f00d::a0f:0:0:9941" k8sPodName=/ subsys=endpoint
```

**Comment by joestringer** [comment]
This can also occur in `Suite-runtime.RuntimePolicies L3/L4 Checks`:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15243/testReport/junit/(root)/Suite-runtime/RuntimePolicies_L3_L4_Checks/
[test_results_Cilium-PR-Ginkgo-Tests-Validated_15243_BDD-Test-PR-runtime.zip](https://github.com/cilium/cilium/files/3684109/test_results_Cilium-PR-Ginkgo-Tests-Validated_15243_BDD-Test-PR-runtime.zip)

**Comment by jrajahalme** [comment]
@joestringer Another instance on L3/L4 Checks: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15278/testReport/junit/(root)/Suite-runtime/RuntimePolicies_L3_L4_Checks/

**Comment by ianvernon** [comment]
Could we add logic to our sig handler which waits for regenerations that are in flight to complete, or time out after some time?

**Comment by joestringer** [comment]
Or the signal handler could cancel the contexts for ongoing regenerations..?

**Comment by aanm** [comment]
> Or the signal handler could cancel the contexts for ongoing regenerations..?

@joestringer I think that can easily be achieve, IIRC @ianvernon recently added a `aliveContext` in the endpoint structure that we could safely cancel before shutting down?

**Comment by ianvernon** [comment]
@ianvernon - double check between how we handled canceled contexts vs. timed out contexts (from Cilium Community Meeting)

**Comment by ianvernon** [comment]
The fix for this is to create a single context on the daemon side, from which we can create child contexts that are propagated down to Endpoints / controllers / things which should be 'stopped' upon agent termination. This was fixed in the following PRs:

* https://github.com/cilium/cilium/pull/9437
* https://github.com/cilium/cilium/pull/9489
