### ISSUE TITLE
CI: Travis: fatal error: concurrent map iteration and map write in pkg/aws/eni

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9779]
Travis failure on master (v1.7 dev cycle):

https://travis-ci.com/cilium/cilium/builds/141416864?utm_medium=notification&utm_source=email

Consolidated stack traces using `contrib/scripts/consolidate_go_stacktrace.py`:

```
9 unique stack traces
225 occurences. Sample stack trace:
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc00083dd60)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:218 +0x157
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
2 occurences. Sample stack trace:
runtime.goparkunlock(...)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/proc.go:310
time.Sleep(0x976473)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/time.go:105 +0x157
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc0000e9f40)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:197 +0x3f0
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
1 occurences. Sample stack trace:

1 occurences. Sample stack trace:
gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc00061e990)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:470 +0xc4
created by gopkg.in/check%2ev1.(*resultTracker).start
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:450 +0x3f
1 occurences. Sample stack trace:
testing.(*T).Run(0xc000578500, 0x1d86ea0, 0x4, 0x1e495b8, 0x48bcb6)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc000578400)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc000578400, 0xc000599d88)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:909 +0xc9
testing.runTests(0xc00000e620, 0x319f8c0, 0x1, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc00054c000, 0x0)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:962 +0x1d4
1 occurences. Sample stack trace:
k8s.io/klog.(*loggingT).flushDaemon(0x31c6aa0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:411 +0xd6
1 occurences. Sample stack trace:
gopkg.in/check%2ev1.(*suiteRunner).runTest(...)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:819
gopkg.in/check%2ev1.(*suiteRunner).run(0xc00054c080, 0x31e45c8)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:624 +0x11d
gopkg.in/check%2ev1.Run(0x1cf2220, 0x31e45c8, 0xc00006b708, 0xd0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x4d
gopkg.in/check%2ev1.RunAll(0xc00007ff08, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x96
gopkg.in/check%2ev1.TestingT(0xc000578500)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x395
github.com/cilium/cilium/pkg/aws/eni.Test(0xc000578500)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/eni_test.go:26 +0x2b
testing.tRunner(0xc000578500, 0x1e495b8)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/testing/testing.go:960 +0x350
1 occurences. Sample stack trace:
runtime.throw(0x1dbb307, 0x26)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0xc000a715c8 sp=0xc000a71598 pc=0x431a22
runtime.mapiternext(0xc000a716d8)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/map.go:858 +0x579 fp=0xc000a71650 sp=0xc000a715c8 pc=0x411779
runtime.mapiterinit(0x1a72aa0, 0xc000abe960, 0xc000a716d8)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/map.go:848 +0x1c3 fp=0xc000a71670 sp=0xc000a71650 pc=0x411113
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*IPAMSpec).DeepCopyInto(0xc000437f28, 0xc0004293e8)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:644 +0x11c fp=0xc000a71748 sp=0xc000a71670 pc=0x14c5f4c
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*NodeSpec).DeepCopyInto(0xc000437e58, 0xc000429318)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:739 +0xda fp=0xc000a717a0 sp=0xc000a71748 pc=0x14c697a
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopyInto(0xc000437d40, 0xc000429200)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:406 +0xc6 fp=0xc000a717c8 sp=0xc000a717a0 pc=0x14c4396
github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopy(0xc000437d40, 0xc000189ab0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:417 +0x5b fp=0xc000a717f0 sp=0xc000a717c8 pc=0x14c447b
github.com/cilium/cilium/pkg/aws/eni.(*Node).ResourceCopy(0xc000986f00, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:290 +0x83 fp=0xc000a71850 sp=0xc000a717f0 pc=0x1895a43
github.com/cilium/cilium/pkg/aws/eni.(*Node).SyncToAPIServer(0xc000986f00, 0x2ab530b2, 0x61ddb107a3)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:774 +0xc0 fp=0xc000a71ea0 sp=0xc000a71850 pc=0x189b7c0
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Update.func2(0xc000442d70, 0x1, 0x1)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:168 +0x30 fp=0xc000a71ec8 sp=0xc000a71ea0 pc=0x18b1c20
github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter(0xc000d39900)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:210 +0x319 fp=0xc000a71fd8 sp=0xc000a71ec8 pc=0x1850549
runtime.goexit()
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000a71fe0 sp=0xc000a71fd8 pc=0x460ce1
created by github.com/cilium/cilium/pkg/trigger.NewTrigger
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:133 +0x14d
1 occurences. Sample stack trace:
sync.runtime_SemacquireMutex(0xc000986f08, 0xd19700, 0x0)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).Lock(0xc000986f00)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/sync/rwmutex.go:103 +0x88
github.com/cilium/cilium/pkg/aws/eni.(*Node).updatedResource(0xc000986f00, 0xc000437d40, 0x1d87bbe)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node.go:196 +0x37
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Update(0xc000447000, 0xc000437d40, 0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:185 +0xd2
github.com/cilium/cilium/pkg/aws/eni.(*ENISuite).TestNodeManagerReleaseAddress(0x31e45c8, 0xc0005281e0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/aws/eni/node_manager_test.go:445 +0x948
reflect.Value.call(0x1cf2220, 0x31e45c8, 0x6213, 0x1d86cf8, 0x4, 0xc000d60f30, 0x1, 0x1, 0x31e66c0, 0xc00002f5d0, ...)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1cf2220, 0x31e45c8, 0x6213, 0xc00002f730, 0x1, 0x1, 0x0, 0xc000c35980, 0xc00002f658)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/reflect/value.go:321 +0xb4
gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc0005281e0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0x5e4
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc00054c080, 0xc0005281e0, 0xc0004e15c0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xa2
created by gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:672 +0x1fb
```

Possibly related to #9770 (/cc @ungureanuvladvictor)

**Comment by ungureanuvladvictor** [comment]
@joestringer took a look but I don't think it's related to my changes -- the change I introduce runs before the node manager starts and does not operate at all on that codepath.

I suspect this bug was always in the codebase.

**Comment by joestringer** [comment]
@ungureanuvladvictor thanks for taking a look. I guess we'll just have to figure this one out the old fashioned way.

**Comment by aanm** [comment]
probably related with https://github.com/cilium/cilium/issues/9604

**Comment by jrajahalme** [comment]
Happaned again in https://travis-ci.com/cilium/cilium/builds/144796599

**Comment by jrajahalme** [comment]
Had a brief look, seems the panicing iteration is the deep copy of the eni node "resource", while the contending write access is nicely waiting on a mutex, so seemingly no conflict? The contending resource is the `IPAMSpec`, I wonder if the map within is originally *not* deep copied, and is accessed concurrently somewhere else?

**Comment by jrajahalme** [comment]
`updatedResource(resource *v2.CiliumNode)`  does NOT deep copy `resource`, thereby relying on the caller(s) to not access it afterwards. I'll try to repro with the instructions in #9604 and see if a deepcopy will remove the panic.

**Comment by jrajahalme** [comment]
Saw this when testing in a loop without any changes:
```
level=info msg="Attached ENI to instance" addresses=9 attachmentID= eniID=f34bed7d-38a6-11ea-9705-080027fcd8ce index=1 instanceID=i-testNodeManagerManyNodes-0 name=node0 securityGroupIDs="[sg1 sg2]" subnetID=s-1 subsys=eni
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x18a5275]

goroutine 558 [running]:
github.com/cilium/cilium/pkg/aws/eni.(*Node).recalculateLocked(0xc000435440)
        /home/vagrant/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:232 +0x95
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).resyncNode(0xc000500280, 0x2130620, 0xc000044078, 0xc000435440, 0xc0004b4100, 0xbf80532b2288bcef, 0x132d93a59, 0x31a24e0)
        /home/vagrant/go/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:260 +0xb2
github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Resync.func1(0xc000500280, 0x2130620, 0xc000044078, 0xbf80532b2288bcef, 0x132d93a59, 0x31a24e0, 0xc00128e460, 0xc000435440, 0xc0004b4100)
        /home/vagrant/go/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:308 +0x7b
created by github.com/cilium/cilium/pkg/aws/eni.(*NodeManager).Resync
        /home/vagrant/go/src/github.com/cilium/cilium/pkg/aws/eni/node_manager.go:307 +0x198
exit status 2
FAIL    github.com/cilium/cilium/pkg/aws/eni    5.157s
```

**Comment by jrajahalme** [comment]
Testing with this to only stop for panics, ignoring other kind of test failures:
`go test -count=1 > /tmp/eni-test.result || true && ! grep "panic" /tmp/eni-test.result; do echo "." && sleep 1;done`

**Comment by jrajahalme** [comment]
`operator/cilium_node.go` deep copies the resource before calling `ciliumNodeUpdated()` so this may only be a testing issue.
